import { SerializedError }                from '@reduxjs/toolkit'
import { FetchBaseQueryError, SkipToken } from '@reduxjs/toolkit/query/react'

// NOTE:
// Taken from https://redux-toolkit.js.org/rtk-query/api/created-api/hooks#usequery
// Uses to help bridge the gap when we need to prepare helpers that wrap around
// query helpers exposed by RTK Query, i.e. those useXyzQuery

// eslint-disable-next-line @typescript-eslint/no-explicit-any
export type UseQuery <ResultType, Payload = any> = (
  arg: Payload | SkipToken,
  options?: UseQueryOptions
) => UseQueryResult<ResultType>

export type UseQueryOptions = {
  pollingInterval?: number
  refetchOnReconnect?: boolean
  refetchOnFocus?: boolean
  skip?: boolean
  refetchOnMountOrArgChange?: boolean | number
  // selectFromResult?: (result: UseQueryStateDefaultResult) => any // omitted
}

export type UseQueryResult<ResultType> = {
  // Base query state
  originalArgs?: unknown // Arguments passed to the query
  data?: ResultType // The latest returned result regardless of hook arg, if present
  currentData?: ResultType // The latest returned result for the current hook arg, if present
  error?: FetchBaseQueryError | SerializedError // Error result if present
  requestId?: string // A string generated by RTK Query
  endpointName?: string // The name of the given endpoint for the query
  startedTimeStamp?: number // Timestamp for when the query was initiated
  fulfilledTimeStamp?: number // Timestamp for when the query was completed

  // Derived request status booleans
  isUninitialized: boolean // Query has not started yet.
  isLoading: boolean // Query is currently loading for the first time. No data yet.
  isFetching: boolean // Query is currently fetching, but might have data from an earlier request.
  isSuccess: boolean // Query has data from a successful load.
  isError: boolean // Query is currently in an "error" state.

  refetch: () => void // A function to force refetch the query
}
