ARG GAR_DOCKER_ROOT_URL
FROM ${GAR_DOCKER_ROOT_URL}/acx-service/acx-ui-cache/nx-cache:latest as nx-cache
FROM ${GAR_DOCKER_ROOT_URL}/acx-service/baseimage/node:master--latest as build-base

WORKDIR /app
 
RUN apk add curl
 
ARG ENV_FILE
COPY ${ENV_FILE} .
RUN source ${ENV_FILE} \
  && npm config set registry "http://artifactory.cicd.rks-cloud.com/artifactory/api/npm/npm/" \
  && curl -u "${ARTI_USER}:${ARTI_PASSWORD}" "http://artifactory.cicd.rks-cloud.com/artifactory/api/npm/auth" >> ~/.npmrc
 
# Install dependencies
COPY package.json package-lock.json ./
COPY patches ./patches
COPY tools/dev/eslint-custom-rule ./tools/dev/eslint-custom-rule
RUN npm install
 
COPY .eslintignore \
  .eslintrc.json \
  babel.config.json \
  jest.config.ts \
  jest.preset.ts \
  jest.setup.js \
  jest.build.setup.js \
  nx.json \
  webpack.config.base.js \
  tsconfig.base.json \
  workspace.json \
  ./

COPY .storybook ./.storybook
COPY apps ./apps
COPY libs ./libs
 
COPY --from=nx-cache /app/node_modules/.cache/nx /app/node_modules/.cache/nx
 
COPY tools/tests ./tools/tests


COPY cicd_tools ./cicd_tools
COPY test_cases.table ./test_cases.table
RUN chmod a+x ./cicd_tools/run_test_cases_tool.sh

ARG PRECOMMIT=true
ARG GIT_COMMIT_BRANCH=master
RUN if [ "${PRECOMMIT}" == "true" ] || [ "${GIT_COMMIT_BRANCH}" == "master" ]; then \
       ./cicd_tools/run_test_cases_tool.sh; \
    else mkdir -p /app/coverage; fi
