FROM node:14.19.1-alpine

WORKDIR /app

#COPY .eslintignore .
#COPY .eslintrc.js .
#COPY .npmrc .
#COPY yarn.lock .

#COPY tsconfig.base.json .
#COPY craco.config.js .

#COPY package.json .
#COPY package-lock.json .

#RUN npm i

#COPY public/ public/
#COPY src/ src/
#COPY storybook/ storybook/

#Quick fix for build failed
COPY . .

CMD ["npm", "start"]

EXPOSE 3000
