FROM node:14.19.1-alpine

WORKDIR /app

COPY .eslintignore .
COPY .eslintrc.json .
COPY .npmrc .
COPY yarn.lock .

COPY tsconfig.json .
COPY craco.config.js .

COPY package.json .
COPY package-lock.json .

RUN npm i

COPY public/ public/
COPY src/ src/
COPY storybook/ storybook/

CMD ["npm", "start"]

EXPOSE 3000
