export const WIFI_COUNTRY_CODE = [
  { code: 'AL',name: 'Albania' },
  { code: 'DZ',name: 'Algeria' },
  { code: 'AO',name: 'Angola' },
  { code: 'AR',name: 'Argentina' },
  { code: 'AM',name: 'Armenia' },
  { code: 'AU',name: 'Australia' },
  { code: 'AT',name: 'Austria' },
  { code: 'AZ',name: 'Azerbaijan' },
  { code: 'BH',name: 'Bahrain' },
  { code: 'BD',name: 'Bangladesh' },
  { code: 'BY',name: 'Belarus' },
  { code: 'BE',name: 'Belgium' },
  { code: 'BZ',name: 'Belize' },
  { code: 'BO',name: 'Bolivia' },
  { code: 'BA',name: 'Bosnia And Herzegovina' },
  { code: 'BW',name: 'Botswana' },
  { code: 'BR',name: 'Brazil' },
  { code: 'BN',name: 'Brunei Darussalam' },
  { code: 'BG',name: 'Bulgaria' },
  { code: 'CA',name: 'Canada' },
  { code: 'CL',name: 'Chile' },
  { code: 'CN',name: 'China' },
  { code: 'CO',name: 'Colombia' },
  { code: 'CR',name: 'Costa Rica' },
  { code: 'HR',name: 'Croatia' },
  { code: 'CY',name: 'Cyprus' },
  { code: 'CZ',name: 'Czech Republic' },
  { code: 'DK',name: 'Denmark' },
  { code: 'DO',name: 'Dominican Republic' },
  { code: 'EC',name: 'Ecuador' },
  { code: 'EG',name: 'Egypt' },
  { code: 'SV',name: 'El Salvador' },
  { code: 'EE',name: 'Estonia' },
  { code: 'ET',name: 'Ethiopia' },
  { code: 'FI',name: 'Finland' },
  { code: 'FR',name: 'France' },
  { code: 'GE',name: 'Georgia' },
  { code: 'DE',name: 'Germany' },
  { code: 'GH',name: 'Ghana' },
  { code: 'GR',name: 'Greece' },
  { code: 'GT',name: 'Guatemala' },
  { code: 'HN',name: 'Honduras' },
  { code: 'HK',name: 'Hong Kong' },
  { code: 'HU',name: 'Hungary' },
  { code: 'IS',name: 'Iceland' },
  { code: 'IN',name: 'India' },
  { code: 'ID',name: 'Indonesia' },
  { code: 'IQ',name: 'Iraq' },
  { code: 'IE',name: 'Ireland' },
  { code: 'IL',name: 'Israel' },
  { code: 'IT',name: 'Italy' },
  { code: 'JM',name: 'Jamaica' },
  { code: 'JP',name: 'Japan' },
  { code: 'JO',name: 'Jordan' },
  { code: 'KZ',name: 'Kazakhstan' },
  { code: 'KE',name: 'Kenya' },
  { code: 'KR',name: 'Korea' },
  { code: 'KW',name: 'Kuwait' },
  { code: 'LV',name: 'Latvia' },
  { code: 'LB',name: 'Lebanon' },
  { code: 'LY',name: 'Libyan Arab Jamahiriya' },
  { code: 'LI',name: 'Liechtenstein' },
  { code: 'LT',name: 'Lithuania' },
  { code: 'LU',name: 'Luxembourg' },
  { code: 'MO',name: 'Macao' },
  { code: 'MK',name: 'Macedonia' },
  { code: 'MY',name: 'Malaysia' },
  { code: 'MT',name: 'Malta' },
  { code: 'MU',name: 'Mauritius' },
  { code: 'MX',name: 'Mexico' },
  { code: 'MC',name: 'Monaco' },
  { code: 'MN',name: 'Mongolia' },
  { code: 'ME',name: 'Montenegro' },
  { code: 'MA',name: 'Morocco' },
  { code: 'NA',name: 'Namibia' },
  { code: 'NP',name: 'Nepal' },
  { code: 'NL',name: 'Netherlands' },
  { code: 'AN',name: 'Netherlands Antilles' },
  { code: 'NZ',name: 'New Zealand' },
  { code: 'NG',name: 'Nigeria' },
  { code: 'NO',name: 'Norway' },
  { code: 'OM',name: 'Oman' },
  { code: 'PK',name: 'Pakistan' },
  { code: 'PA',name: 'Panama' },
  { code: 'PG',name: 'Papua New Guinea' },
  { code: 'PY',name: 'Paraguay' },
  { code: 'PE',name: 'Peru' },
  { code: 'PH',name: 'Philippines' },
  { code: 'PL',name: 'Poland' },
  { code: 'PT',name: 'Portugal' },
  { code: 'PR',name: 'Puerto Rico' },
  { code: 'QA',name: 'Qatar' },
  { code: 'RE',name: 'Reunion' },
  { code: 'RO',name: 'Romania' },
  { code: 'RU',name: 'Russian Federation' },
  { code: 'RW',name: 'Rwanda' },
  { code: 'SM',name: 'San Marino' },
  { code: 'SA',name: 'Saudi Arabia' },
  { code: 'RS',name: 'Serbia' },
  { code: 'SC',name: 'Seychelles' },
  { code: 'SG',name: 'Singapore' },
  { code: 'SK',name: 'Slovakia' },
  { code: 'SI',name: 'Slovenia' },
  { code: 'ZA',name: 'South Africa' },
  { code: 'ES',name: 'Spain' },
  { code: 'LK',name: 'Sri Lanka' },
  { code: 'SZ',name: 'Swaziland' },
  { code: 'SE',name: 'Sweden' },
  { code: 'CH',name: 'Switzerland' },
  { code: 'SY',name: 'Syrian Arab Republic' },
  { code: 'TW',name: 'Taiwan' },
  { code: 'TZ',name: 'Tanzania' },
  { code: 'TH',name: 'Thailand' },
  { code: 'TT',name: 'Trinidad And Tobago' },
  { code: 'TN',name: 'Tunisia' },
  { code: 'TR',name: 'Turkey' },
  { code: 'UG',name: 'Uganda' },
  { code: 'UA',name: 'Ukraine' },
  { code: 'AE',name: 'United Arab Emirates' },
  { code: 'GB',name: 'United Kingdom' },
  { code: 'US',name: 'United States' },
  { code: 'UY',name: 'Uruguay' },
  { code: 'UZ',name: 'Uzbekistan' },
  { code: 'VE',name: 'Venezuela' },
  { code: 'VN',name: 'Vietnam' },
  { code: 'EH',name: 'Western Sahara' },
  { code: 'YE',name: 'Yemen' },
  { code: 'ZM',name: 'Zambia' },
  { code: 'ZW',name: 'Zimbabwe' },
  { code: 'F2',name: 'France_Res' },
  { code: 'I1',name: 'India2' },
  { code: 'I2',name: 'Indonesia2' },
  { code: 'I5',name: 'Indonesia5' },
  { code: 'R1',name: 'Reserved_1' },
  { code: 'Z2',name: 'Zone2' }
]
