import { SwitchViewModel, SWITCH_TYPE, SwitchStatusEnum } from '@acx-ui/rc/utils'

export const lagList = [
  {
    id: 'b343a5a0f88d4a878a070aadc5363538',
    lagId: 1,
    name: 'test-lag',
    ports: [
      '1/1/5'
    ],
    realRemove: true,
    switchId: 'c0:c5:20:aa:32:79',
    taggedVlans: [
      '2',
      '3'
    ],
    type: 'static',
    untaggedVlan: '1'
  }
]


export const switchDetailData: SwitchViewModel = {
  type: 'device',
  isStack: true,
  rearModule: 'none',
  switchMac: 'c0:c5:20:aa:32:79',
  switchName: 'ICX7150-C12 Router',
  model: 'ICX7150-C12P',
  id: 'c0:c5:20:aa:32:79',
  syncDataEndTime: '2023-01-16T06:07:09Z',
  firmwareVersion: 'SPR09010e',
  clientCount: 1,
  serialNumber: 'FEK3216Q05B',
  ipAddress: '10.206.33.13',
  cliApplied: false,
  subnetMask: '255.255.254.0',
  venueName: 'My-Venue',
  name: 'ICX7150-C12 Router',
  suspendingDeployTime: '',
  switchType: SWITCH_TYPE.ROUTER,
  configReady: true,
  deviceStatus: SwitchStatusEnum.OPERATIONAL,
  venueId: 'c675aa2d39b74c22b93b96d5dc297d5c',
  syncedSwitchConfig: true,
  defaultGateway: '10.206.33.254',
  stackMembers: [
    { model: 'ICX7150-C12P', id: 'FEK3216Q02P' },
    { model: 'ICX7150-C12P', id: 'FEK3216Q05B' }
  ],
  uptime: '7 days, 7:36:21.00',
  formStacking: false
}

export const selectedPorts = [{
  adminStatus: 'Down',
  broadcastIn: '0',
  broadcastOut: '0',
  cloudPort: false,
  crcErr: '0',
  deviceStatus: 'ONLINE',
  egressAclName: 'test acl',
  id: 'c0-c5-20-aa-32-7d_1-1-5',
  inDiscard: '0',
  inErr: '0',
  inactiveRow: false,
  inactiveTooltip: '',
  lagId: '0',
  lagName: '',
  multicastIn: '0',
  multicastOut: '0',
  name: 'GigabitEthernet1/1/5',
  neighborName: '',
  opticsType: '1 Gbits per second copper',
  outErr: '0',
  poeEnabled: true,
  poeTotal: 0,
  poeType: 'n/a',
  poeUsed: 0,
  portId: 'c0-c5-20-aa-32-7d_1-1-5',
  portIdentifier: '5',
  portSpeed: 'link down or no traffic',
  signalIn: 0,
  signalOut: 0,
  stack: false,
  status: 'Down',
  switchMac: 'c0:c5:20:aa:32:79',
  switchModel: 'ICX7150-C12P',
  switchName: 'FEK3224R0AG',
  switchSerial: 'c0:c5:20:aa:32:79',
  switchUnitId: 'FEK3224R0AG',
  syncedSwitchConfig: true,
  unTaggedVlan: '1',
  unitState: 'ONLINE',
  unitStatus: 'Standalone',
  usedInFormingStack: false,
  vlanIds: '2 1'
}, {
  adminStatus: 'Up',
  cloudPort: false,
  deviceStatus: 'ONLINE',
  hierarchy: ['58-fb-96-0e-82-8e_1-1-5'],
  id: '58-fb-96-0e-82-8e_1-1-5',
  isFirstLevel: true,
  lagId: '0',
  name: 'GigabitEthernet1/1/5',
  neighborName: '',
  poeEnabled: false,
  poeTotal: 0,
  poeUsed: 0,
  portId: '58-fb-96-0e-82-8e_1-1-5',
  portIdentifier: '1/1/5',
  portSpeed: 'link down or no traffic',
  signalIn: 0,
  signalOut: 0,
  stack: true,
  status: 'Down',
  switchMac: 'c0:c5:20:aa:32:79',
  switchModel: 'ICX7150-C12P',
  switchName: '7150stack',
  switchSerial: 'c0:c5:20:aa:32:79',
  switchUnitId: 'FEK3230S0A0',
  syncedSwitchConfig: true,
  unTaggedVlan: '2',
  unitState: 'ONLINE',
  unitStatus: 'Active',
  usedInFormingStack: false,
  vlanIds: '1'
}, {
  adminStatus: 'Up',
  broadcastIn: '0',
  broadcastOut: '0',
  cloudPort: false,
  crcErr: '0',
  deviceStatus: 'ONLINE',
  id: 'c0-c5-20-aa-32-7e_1-1-6',
  inDiscard: '0',
  inErr: '0',
  inactiveRow: false,
  inactiveTooltip: '',
  lagId: '0',
  lagName: '',
  multicastIn: '0',
  multicastOut: '0',
  name: 'GigabitEthernet1/1/6',
  neighborName: '',
  opticsType: '1 Gbits per second copper',
  outErr: '0',
  poeEnabled: true,
  poeTotal: 0,
  poeType: 'n/a',
  poeUsed: 0,
  portId: 'c0-c5-20-aa-32-7e_1-1-6',
  portIdentifier: '1/1/6',
  portSpeed: 'link down or no traffic',
  signalIn: 0,
  signalOut: 0,
  stack: false,
  status: 'Down',
  switchMac: 'c0:c5:20:aa:32:79',
  switchModel: 'ICX7150-C12P',
  switchName: 'FEK3224R0AG',
  switchSerial: 'c0:c5:20:aa:32:79',
  switchUnitId: 'FEK3224R0AG',
  syncedSwitchConfig: true,
  unTaggedVlan: '1',
  unitState: 'ONLINE',
  unitStatus: 'Standalone',
  usedInFormingStack: false,
  vlanIds: '1'
}]

export const switchDetailHeader = {
  activeSerial: 'FEK3224R0AG',
  cliApplied: false,
  clientCount: 1,
  cloudPort: 'INVALID',
  configReady: true,
  cpu: 32,
  defaultGateway: '10.206.11.254',
  deviceStatus: 'ONLINE',
  deviceType: 'DVCNWTYPE_SWITCH',
  dns: '10.10.10.106',
  family: 'ICX7150-C12P',
  firmware: 'SPR09010e',
  firmwareVersion: 'SPR09010e',
  floorplanId: '',
  formStacking: false,
  freeMemory: 262000640,
  id: 'c0:c5:20:aa:32:79',
  ipAddress: '10.206.10.27',
  isIpFullContentParsed: true,
  isStack: false,
  memory: 74,
  model: 'ICX7150-C12P',
  modules: 'switch',
  name: 'FEK3224R0AG',
  numOfPorts: 16,
  numOfUnits: 1,
  poeUsage: { poeFree: 124000, poeTotal: 124000, poeUtilization: 0 },
  portModuleIds: 'FEK3224R0AG',
  portsStatus: { Down: 14, Up: 2 },
  rearModule: 'none',
  sendedHostname: true,
  serialNumber: 'FEK3224R0AG',
  stackMember: false,
  stackMemberOrder: '',
  stackMembers: [],
  staticOrDynamic: 'dynamic',
  subnetMask: '255.255.254.0',
  suspendingDeployTime: '',
  switchMac: 'c0:c5:20:aa:32:79',
  switchName: 'FEK3224R0AG',
  switchType: 'router',
  syncDataEndTime: 1672685019090,
  syncedSwitchConfig: true,
  // eslint-disable-next-line max-len
  temperatureGroups: '[{"serialNumber":"FEK3224R0AG","stackId":"C0 C5 20 AA 32 79","temperatureSlotList":[{"slotNumber":3,"temperatureValue":48},{"slotNumber":4,"temperatureValue":49},{"slotNumber":1,"temperatureValue":64},{"slotNumber":2,"temperatureValue":10}]}]',
  tenantId: 'f2e4a77d49914dc7b1bcb0dfc21b9a74',
  timestamp: 1672685019073,
  totalMemory: 1019744256,
  type: 'device',
  unitSerialNumbers: 'FEK3224R0AG',
  uptime: '10 days, 11:5:24.00',
  venueId: 'a98653366d2240b9ae370e48fab3a9a1',
  venueName: 'My-Venue',
  xPercent: 0,
  yPercent: 0
}

export const defaultVlan = [
  { switchId: 'c0:c5:20:aa:32:79', defaultVlanId: 1 }]

export const switchVlans = []

export const vlansByVenue = []

export const successResponse = {
  requestId: 'request-id'
}

export const portlist = {
  data: [
    {
      cloudPort: false,
      id: 'c0-c5-20-aa-33-3f_1-1-1',
      lagId: '0',
      opticsType: '1 Gbits per second copper',
      poeEnabled: false,
      poeTotal: 0,
      poeUsed: 0,
      portIdentifier: '1/1/1',
      signalIn: 0,
      signalOut: 0,
      stack: false,
      syncedSwitchConfig: false,
      usedInFormingStack: false
    },
    {
      cloudPort: false,
      id: 'c0-c5-20-aa-33-48_1-1-10',
      lagId: '0',
      opticsType: '1 Gbits per second copper',
      poeEnabled: false,
      poeTotal: 0,
      poeUsed: 0,
      portIdentifier: '1/1/10',
      signalIn: 0,
      signalOut: 0,
      stack: false,
      syncedSwitchConfig: false,
      usedInFormingStack: false
    },
    {
      cloudPort: false,
      id: 'c0-c5-20-aa-33-49_1-1-11',
      lagId: '0',
      opticsType: '1 Gbits per second copper',
      poeEnabled: false,
      poeTotal: 0,
      poeUsed: 0,
      portIdentifier: '1/1/11',
      signalIn: 0,
      signalOut: 0,
      stack: false,
      syncedSwitchConfig: false,
      usedInFormingStack: false
    },
    {
      cloudPort: false,
      id: 'c0-c5-20-aa-33-4a_1-1-12',
      lagId: '0',
      opticsType: '1 Gbits per second copper',
      poeEnabled: false,
      poeTotal: 0,
      poeUsed: 0,
      portIdentifier: '1/1/12',
      signalIn: 0,
      signalOut: 0,
      stack: false,
      syncedSwitchConfig: false,
      usedInFormingStack: false
    },
    {
      cloudPort: false,
      id: 'c0-c5-20-aa-33-40_1-1-2',
      lagId: '0',
      opticsType: '1 Gbits per second copper',
      poeEnabled: false,
      poeTotal: 0,
      poeUsed: 0,
      portIdentifier: '1/1/2',
      signalIn: 0,
      signalOut: 0,
      stack: false,
      syncedSwitchConfig: false,
      usedInFormingStack: false
    },
    {
      cloudPort: false,
      id: 'c0-c5-20-aa-33-41_1-1-3',
      lagId: '0',
      opticsType: '1 Gbits per second copper',
      poeEnabled: false,
      poeTotal: 0,
      poeUsed: 0,
      portIdentifier: '1/1/3',
      signalIn: 0,
      signalOut: 0,
      stack: false,
      syncedSwitchConfig: false,
      usedInFormingStack: false
    },
    {
      cloudPort: false,
      id: 'c0-c5-20-aa-33-42_1-1-4',
      lagId: '0',
      opticsType: '1 Gbits per second copper',
      poeEnabled: false,
      poeTotal: 0,
      poeUsed: 0,
      portIdentifier: '1/1/4',
      signalIn: 0,
      signalOut: 0,
      stack: false,
      syncedSwitchConfig: false,
      usedInFormingStack: false
    },
    {
      cloudPort: false,
      id: 'c0-c5-20-aa-33-43_1-1-5',
      lagId: '0',
      opticsType: '1 Gbits per second copper',
      poeEnabled: false,
      poeTotal: 0,
      poeUsed: 0,
      portIdentifier: '1/1/5',
      signalIn: 0,
      signalOut: 0,
      stack: false,
      syncedSwitchConfig: false,
      usedInFormingStack: false
    },
    {
      cloudPort: false,
      id: 'c0-c5-20-aa-33-44_1-1-6',
      lagId: '0',
      opticsType: '1 Gbits per second copper',
      poeEnabled: false,
      poeTotal: 0,
      poeUsed: 0,
      portIdentifier: '1/1/6',
      signalIn: 0,
      signalOut: 0,
      stack: false,
      syncedSwitchConfig: false,
      usedInFormingStack: false
    },
    {
      cloudPort: false,
      id: 'c0-c5-20-aa-33-45_1-1-7',
      lagId: '0',
      opticsType: '1 Gbits per second copper',
      poeEnabled: false,
      poeTotal: 0,
      poeUsed: 0,
      portIdentifier: '1/1/7',
      signalIn: 0,
      signalOut: 0,
      stack: false,
      syncedSwitchConfig: false,
      usedInFormingStack: false
    },
    {
      cloudPort: false,
      id: 'c0-c5-20-aa-33-46_1-1-8',
      lagId: '0',
      opticsType: '1 Gbits per second copper',
      poeEnabled: false,
      poeTotal: 0,
      poeUsed: 0,
      portIdentifier: '1/1/8',
      signalIn: 0,
      signalOut: 0,
      stack: false,
      syncedSwitchConfig: false,
      usedInFormingStack: false
    },
    {
      cloudPort: false,
      id: 'c0-c5-20-aa-33-47_1-1-9',
      lagId: '0',
      opticsType: '1 Gbits per second copper',
      poeEnabled: false,
      poeTotal: 0,
      poeUsed: 0,
      portIdentifier: '1/1/9',
      signalIn: 0,
      signalOut: 0,
      stack: false,
      syncedSwitchConfig: false,
      usedInFormingStack: false
    },
    {
      cloudPort: false,
      id: 'c0-c5-20-aa-33-4c_1-2-1',
      lagId: '0',
      opticsType: '1 Gbits per second copper',
      poeEnabled: false,
      poeTotal: 0,
      poeUsed: 0,
      portIdentifier: '1/2/1',
      signalIn: 0,
      signalOut: 0,
      stack: false,
      syncedSwitchConfig: false,
      usedInFormingStack: false
    },
    {
      cloudPort: false,
      id: 'c0-c5-20-aa-33-4d_1-2-2',
      lagId: '0',
      opticsType: '1 Gbits per second copper',
      poeEnabled: false,
      poeTotal: 0,
      poeUsed: 0,
      portIdentifier: '1/2/2',
      signalIn: 0,
      signalOut: 0,
      stack: false,
      syncedSwitchConfig: false,
      usedInFormingStack: false
    },
    {
      cloudPort: false,
      id: 'c0-c5-20-aa-33-4e_1-3-1',
      lagId: '0',
      opticsType: '10 Gbits per second fiber',
      poeEnabled: false,
      poeTotal: 0,
      poeUsed: 0,
      portIdentifier: '1/3/1',
      signalIn: 0,
      signalOut: 0,
      stack: true,
      syncedSwitchConfig: false,
      usedInFormingStack: true
    },
    {
      cloudPort: false,
      id: 'c0-c5-20-aa-33-4f_1-3-2',
      lagId: '0',
      opticsType: '10 Gbits per second fiber',
      poeEnabled: false,
      poeTotal: 0,
      poeUsed: 0,
      portIdentifier: '1/3/2',
      signalIn: 0,
      signalOut: 0,
      stack: true,
      syncedSwitchConfig: false,
      usedInFormingStack: true
    }
  ],
  fields: [
    'portIdentifier',
    'id',
    'opticsType',
    'usedInFormingStack'
  ],
  page: 1,
  totalCount: 16
}

export const switchVlanUnion = {
  switchDefaultVlan: [
    {
      switchId: 'c0:c5:20:aa:32:79',
      vlanConfigName: 'DEFAULT-VLAN',
      profileLevel: false,
      defaultVlan: true,
      vlanId: 1
    }
  ],
  switchVlan: [
    {
      switchId: 'c0:c5:20:aa:32:79',
      profileLevel: false,
      defaultVlan: false,
      vlanId: 2
    },
    {
      switchId: 'c0:c5:20:aa:32:79',
      profileLevel: false,
      defaultVlan: false,
      vlanId: 3
    },
    {
      switchId: 'c0:c5:20:aa:32:79',
      profileLevel: false,
      defaultVlan: false,
      vlanId: 4
    }
  ]
}
