FROM node:18.20.8-alpine3.21

RUN apk update && apk upgrade --no-cache && \
    npm install -g npm@10.9.0 && \
    npm uninstall -g cross-spawn && \
    npm cache clean --force && \
    find /usr/local/lib/node_modules -name "cross-spawn" -type d -exec rm -rf {} + && \
    npm install -g cross-spawn@7.0.5 --force && \
    npm config set save-exact=true && \
    npm config set legacy-peer-deps=true
