import { configureStore, createDynamicMiddleware }        from '@reduxjs/toolkit'
import { TypedUseSelectorHook, useDispatch, useSelector } from 'react-redux'

import {
  baseAdministrationApi as administrationApi,
  baseApApi as apApi,
  baseConfigTemplateApi,
  baseClientApi as clientApi,
  baseCommonApi as commonApi,
  baseConnectionMeteringApi as connectionMeteringApi,
  dataApi,
  dataApiSearch,
  baseDhcpApi as dhcpApi,
  baseEdgeApi as edgeApi,
  baseEdgeDhcpApi as edgeDhcpApi,
  baseEdgeFirewallApi as edgeFirewallApi,
  baseEdgeHqosProfilesApi as edgeHqosProfilesApi,
  baseEdgeSdLanApi,
  baseEdgeMdnsProxyApi,
  baseEdgeTnmServiceApi,
  baseEventAlarmApi as eventAlarmApi,
  baseFirmwareApi as firmwareApi,
  intentAIApi,
  baseLicenseApi as licenseApi,
  baseMigrationApi as migrationApi,
  baseMsgTemplateApi as msgTemplateApi,
  baseMspApi as mspApi,
  baseNetworkApi as networkApi,
  notificationApi,
  basePinApi as pinApi,
  basePersonaApi as personaApi,
  basePolicyApi as policyApi,
  rbacApi,
  recommendationApi,
  reportsApi,
  baseResidentPortalApi as residentPortalApi,
  baseRWGApi as rwgApi,
  baseServiceApi as serviceApi,
  serviceGuardApi,
  baseSigPackApi as sigPackApi,
  smartZoneApi,
  baseSoftGreApi as softGreApi,
  baseSwitchApi as switchApi,
  baseTimelineApi as timelineApi,
  baseTunnelProfileApi as tunnelProfileApi,
  userApi,
  baseEthernetPortProfileApi as ethernetPortProfileApi,
  baseVenueApi as venueApi,
  baseWorkflowApi,
  videoCallQoeApi,
  baseRuckusAssistantApi as ruckusAssistantApi,
  baseDirectoryServerApi as directoryServerApi,
  baseRuckusAiChatApi as ruckusAiChatApi,
  baseClientIsolationApi as clientIsolationApi,
  baseSamlIdpProfileApi as samlIdpProfileApi
} from './baseApi'
import { cancelMiddleware } from './cancelMiddleware'

const isDev = process.env['NODE_ENV'] === 'development'

export const dynamicMiddleware = createDynamicMiddleware()

export const store = configureStore({
  reducer: {
    [commonApi.reducerPath]: commonApi.reducer,
    [networkApi.reducerPath]: networkApi.reducer,
    [venueApi.reducerPath]: venueApi.reducer,
    [eventAlarmApi.reducerPath]: eventAlarmApi.reducer,
    [timelineApi.reducerPath]: timelineApi.reducer,
    [dataApi.reducerPath]: dataApi.reducer,
    [dataApiSearch.reducerPath]: dataApiSearch.reducer,
    [reportsApi.reducerPath]: reportsApi.reducer,
    [rbacApi.reducerPath]: rbacApi.reducer,
    [recommendationApi.reducerPath]: recommendationApi.reducer,
    [intentAIApi.reducerPath]: intentAIApi.reducer,
    [apApi.reducerPath]: apApi.reducer,
    [userApi.reducerPath]: userApi.reducer,
    [dhcpApi.reducerPath]: dhcpApi.reducer,
    [serviceApi.reducerPath]: serviceApi.reducer,
    [mspApi.reducerPath]: mspApi.reducer,
    [licenseApi.reducerPath]: licenseApi.reducer,
    [edgeApi.reducerPath]: edgeApi.reducer,
    [policyApi.reducerPath]: policyApi.reducer,
    [clientApi.reducerPath]: clientApi.reducer,
    [switchApi.reducerPath]: switchApi.reducer,
    [administrationApi.reducerPath]: administrationApi.reducer,
    [firmwareApi.reducerPath]: firmwareApi.reducer,
    [migrationApi.reducerPath]: migrationApi.reducer,
    [edgeDhcpApi.reducerPath]: edgeDhcpApi.reducer,
    [personaApi.reducerPath]: personaApi.reducer,
    [serviceGuardApi.reducerPath]: serviceGuardApi.reducer,
    [pinApi.reducerPath]: pinApi.reducer,
    [tunnelProfileApi.reducerPath]: tunnelProfileApi.reducer,
    [softGreApi.reducerPath]: softGreApi.reducer,
    [msgTemplateApi.reducerPath]: msgTemplateApi.reducer,
    [connectionMeteringApi.reducerPath]: connectionMeteringApi.reducer,
    [videoCallQoeApi.reducerPath]: videoCallQoeApi.reducer,
    [edgeFirewallApi.reducerPath]: edgeFirewallApi.reducer,
    [sigPackApi.reducerPath]: sigPackApi.reducer,
    [residentPortalApi.reducerPath]: residentPortalApi.reducer,
    [rwgApi.reducerPath]: rwgApi.reducer,
    [notificationApi.reducerPath]: notificationApi.reducer,
    [baseEdgeSdLanApi.reducerPath]: baseEdgeSdLanApi.reducer,
    [baseEdgeMdnsProxyApi.reducerPath]: baseEdgeMdnsProxyApi.reducer,
    [baseEdgeTnmServiceApi.reducerPath]: baseEdgeTnmServiceApi.reducer,
    [baseConfigTemplateApi.reducerPath]: baseConfigTemplateApi.reducer,
    [baseWorkflowApi.reducerPath]: baseWorkflowApi.reducer,
    [smartZoneApi.reducerPath]: smartZoneApi.reducer,
    [ethernetPortProfileApi.reducerPath]: ethernetPortProfileApi.reducer,
    [edgeHqosProfilesApi.reducerPath]: edgeHqosProfilesApi.reducer,
    [ruckusAssistantApi.reducerPath]: ruckusAssistantApi.reducer,
    [directoryServerApi.reducerPath]: directoryServerApi.reducer,
    [ruckusAiChatApi.reducerPath]: ruckusAiChatApi.reducer,
    [clientIsolationApi.reducerPath]: clientIsolationApi.reducer,
    [samlIdpProfileApi.reducerPath]: samlIdpProfileApi.reducer
  },

  middleware: (getDefaultMiddleware) => {
    return getDefaultMiddleware({
      serializableCheck: isDev ? undefined : false,
      immutableCheck: isDev ? undefined : false
    }).concat([
      cancelMiddleware,
      dynamicMiddleware.middleware,
      commonApi.middleware,
      networkApi.middleware,
      venueApi.middleware,
      eventAlarmApi.middleware,
      timelineApi.middleware,
      dataApi.middleware,
      recommendationApi.middleware,
      intentAIApi.middleware,
      dataApiSearch.middleware,
      apApi.middleware,
      rbacApi.middleware,
      reportsApi.middleware,
      userApi.middleware,
      dhcpApi.middleware,
      serviceApi.middleware,
      mspApi.middleware,
      licenseApi.middleware,
      edgeApi.middleware,
      policyApi.middleware,
      clientApi.middleware,
      switchApi.middleware,
      administrationApi.middleware,
      firmwareApi.middleware,
      migrationApi.middleware,
      edgeDhcpApi.middleware,
      personaApi.middleware,
      serviceGuardApi.middleware,
      pinApi.middleware,
      tunnelProfileApi.middleware,
      softGreApi.middleware,
      msgTemplateApi.middleware,
      connectionMeteringApi.middleware,
      videoCallQoeApi.middleware,
      edgeFirewallApi.middleware,
      sigPackApi.middleware,
      residentPortalApi.middleware,
      rwgApi.middleware,
      notificationApi.middleware,
      baseEdgeSdLanApi.middleware,
      baseEdgeMdnsProxyApi.middleware,
      baseEdgeTnmServiceApi.middleware,
      baseConfigTemplateApi.middleware,
      baseWorkflowApi.middleware,
      smartZoneApi.middleware,
      ethernetPortProfileApi.middleware,
      edgeHqosProfilesApi.middleware,
      ruckusAssistantApi.middleware,
      directoryServerApi.middleware,
      ruckusAiChatApi.middleware,
      clientIsolationApi.middleware,
      samlIdpProfileApi.middleware
    ])
  },

  devTools: isDev
})

export type AppState = ReturnType<typeof store.getState>
export type AppDispatch = typeof store.dispatch

export function baseSelector (state: AppState) {
  return state
}

export const useAppDispatch = () => useDispatch<AppDispatch>()
export const useAppSelector: TypedUseSelectorHook<AppState> = useSelector
