export enum QosPriorityEnum {
  WIFICALLING_PRI_VOICE = 'WIFICALLING_PRI_VOICE',
  WIFICALLING_PRI_VIDEO = 'WIFICALLING_PRI_VIDEO',
  WIFICALLING_PRI_BE = 'WIFICALLING_PRI_BE',
  WIFICALLING_PRI_BG = 'WIFICALLING_PRI_BG',
}