export enum WifiEntityEnum {
  apNetworkList = 'apNetworkList',
  apList = 'aplist',
  apsTree = 'aps',
  apsMesh = 'apsMesh',
  apGroupslist = 'apGroupslist',
  apGroupApList = 'apGroupApList',
  apGroupNetworkList = 'apGroupNetworkList',
  dpskList = 'dpskList',
  accessControlProfileList = 'accessControlProfileList',
  devicePolicyList = 'devicePolicyList',
  trafficControlPolicyList = 'trafficControlPolicyList',
  deviceConnectionPolicyList = 'deviceConnectionPolicyList',
  applicationPolicyList = 'applicationPolicyList',
  urlFilteringPolicyList = 'urlFilteringPolicyList',
  clientIsolationAllowlist = 'clientIsolationAllowlist',
  clientlist = 'clientlist',
  vlanPoolList = 'vlanPoolList',
  rogueApList = 'rogueApList',
  roguePolicyList = 'roguePolicyList'
}
