import { STACK_MEMBERSHIP, SwitchStatusEnum, SWITCH_TYPE, SwitchPortStatus } from '@acx-ui/rc/utils'

export const stackMemberStandalone = [
  {
    serialNumber: 'FEK3230S0DA',
    unitName: 'ICX7150-C12 Router',
    poeFree: 108600,
    uptime: '41 days, 0 hours',
    deviceStatus: SwitchStatusEnum.OPERATIONAL,
    unitStatus: STACK_MEMBERSHIP.ACTIVE,
    venueName: 'My-Venue',
    switchMac: '58:fb:96:0e:c0:c4',
    unitId: 1,
    model: 'ICX7150-C12P',
    activeSerial: 'FEK3230S0DA',
    poeTotal: 124000,
    id: 'FEK3230S0DA',
    poeUtilization: 15400,
    order: '1'
  }
]

const ports =[
  {
    vlanIds: '1',
    isInWarningState: false,
    tx: 956495589,
    portIdentifier: '1/1/1',
    rx: 1626140140,
    neighborMacAddress: 'C0:C5:20:AA:33:3F',
    unTaggedVlan: '1',
    neighborName: '11F_LAB_R3_UP_10.206.11.2',
    portnumber: '1',
    switchUnitId: 'FEK3230S0DA',
    portSpeed: '1 Gb/sec',
    adminStatus: 'Up',
    poeEnabled: true,
    name: 'GigabitEthernet1/1/1',
    poeUsed: 0,
    poeTotal: 0,
    poeType: 'n/a',
    usedInFormingStack: false,
    status: 'Up'
  },
  {
    vlanIds: '1',
    isInWarningState: false,
    tx: 0,
    portIdentifier: '1/1/2',
    rx: 0,
    unTaggedVlan: '1',
    neighborName: '',
    portnumber: '2',
    switchUnitId: 'FEK3230S0DA',
    portSpeed: 'link down or no traffic',
    adminStatus: 'Up',
    poeEnabled: true,
    name: 'GigabitEthernet1/1/2',
    poeUsed: 0,
    poeTotal: 0,
    poeType: 'n/a',
    usedInFormingStack: false,
    status: 'Down',
    lagId: '1'
  },
  {
    vlanIds: '1 3 4',
    isInWarningState: false,
    tx: 0,
    portIdentifier: '1/1/3',
    rx: 0,
    unTaggedVlan: '1',
    neighborName: '',
    portnumber: '3',
    switchUnitId: 'FEK3230S0DA',
    portSpeed: 'link down or no traffic',
    adminStatus: 'Up',
    poeEnabled: true,
    name: 'GigabitEthernet1/1/3',
    poeUsed: 0,
    poeTotal: 0,
    poeType: 'n/a',
    usedInFormingStack: false,
    status: 'Down'
  },
  {
    vlanIds: '1',
    isInWarningState: false,
    tx: 0,
    portIdentifier: '1/1/4',
    rx: 0,
    unTaggedVlan: '1',
    neighborName: '',
    portnumber: '4',
    switchUnitId: 'FEK3230S0DA',
    portSpeed: 'link down or no traffic',
    adminStatus: 'Up',
    poeEnabled: true,
    name: 'GigabitEthernet1/1/4',
    poeUsed: 0,
    poeTotal: 0,
    poeType: 'n/a',
    usedInFormingStack: false,
    status: 'Down'
  },
  {
    vlanIds: '1',
    isInWarningState: false,
    tx: 0,
    portIdentifier: '1/1/5',
    rx: 0,
    unTaggedVlan: '1',
    neighborName: '',
    portnumber: '5',
    switchUnitId: 'FEK3230S0DA',
    portSpeed: 'link down or no traffic',
    adminStatus: 'Up',
    poeEnabled: true,
    name: 'GigabitEthernet1/1/5',
    poeUsed: 0,
    poeTotal: 0,
    poeType: 'n/a',
    usedInFormingStack: false,
    status: 'Down'
  },
  {
    vlanIds: '1',
    isInWarningState: false,
    tx: 0,
    portIdentifier: '1/1/6',
    rx: 0,
    unTaggedVlan: '1',
    neighborName: '',
    portnumber: '6',
    switchUnitId: 'FEK3230S0DA',
    portSpeed: 'link down or no traffic',
    adminStatus: 'Up',
    poeEnabled: true,
    name: 'GigabitEthernet1/1/6',
    poeUsed: 0,
    poeTotal: 0,
    poeType: 'n/a',
    usedInFormingStack: false,
    status: 'Down'
  },
  {
    vlanIds: '1',
    isInWarningState: false,
    tx: 1487118221,
    portIdentifier: '1/1/7',
    rx: 512926581,
    neighborMacAddress: '34:20:E3:2C:B5:B0',
    unTaggedVlan: '1',
    neighborName: 'RuckusAP',
    portnumber: '7',
    switchUnitId: 'FEK3230S0DA',
    portSpeed: '1 Gb/sec',
    adminStatus: 'Up',
    poeEnabled: true,
    name: 'GigabitEthernet1/1/7',
    poeUsed: 3300,
    poeTotal: 15400,
    poePercent: 21.428571428571427,
    poeType: '2P-IEEE',
    usedInFormingStack: false,
    status: 'Up'
  },
  {
    vlanIds: '1',
    isInWarningState: false,
    tx: 0,
    portIdentifier: '1/1/8',
    rx: 0,
    unTaggedVlan: '1',
    neighborName: '',
    portnumber: '8',
    switchUnitId: 'FEK3230S0DA',
    portSpeed: 'link down or no traffic',
    adminStatus: 'Up',
    poeEnabled: true,
    name: 'GigabitEthernet1/1/8',
    poeUsed: 0,
    poeTotal: 0,
    poeType: 'n/a',
    usedInFormingStack: false,
    status: 'Down'
  },
  {
    vlanIds: '1',
    isInWarningState: false,
    tx: 0,
    portIdentifier: '1/1/9',
    rx: 0,
    unTaggedVlan: '1',
    neighborName: '',
    portnumber: '9',
    switchUnitId: 'FEK3230S0DA',
    portSpeed: 'link down or no traffic',
    adminStatus: 'Up',
    poeEnabled: true,
    name: 'GigabitEthernet1/1/9',
    poeUsed: 0,
    poeTotal: 0,
    poeType: 'n/a',
    usedInFormingStack: false,
    status: 'Down'
  },
  {
    vlanIds: '1',
    isInWarningState: false,
    tx: 0,
    portIdentifier: '1/1/10',
    rx: 0,
    unTaggedVlan: '1',
    neighborName: '',
    portnumber: '10',
    switchUnitId: 'FEK3230S0DA',
    portSpeed: 'link down or no traffic',
    adminStatus: 'Up',
    poeEnabled: true,
    name: 'GigabitEthernet1/1/10',
    poeUsed: 0,
    poeTotal: 0,
    poeType: 'n/a',
    usedInFormingStack: false,
    status: 'Down'
  },
  {
    vlanIds: '1',
    isInWarningState: false,
    tx: 0,
    portIdentifier: '1/1/11',
    rx: 0,
    unTaggedVlan: '1',
    neighborName: '',
    portnumber: '11',
    switchUnitId: 'FEK3230S0DA',
    portSpeed: 'link down or no traffic',
    adminStatus: 'Up',
    poeEnabled: true,
    name: 'GigabitEthernet1/1/11',
    poeUsed: 0,
    poeTotal: 0,
    poeType: 'n/a',
    usedInFormingStack: false,
    status: 'Down'
  },
  {
    vlanIds: '1',
    isInWarningState: false,
    tx: 0,
    portIdentifier: '1/1/12',
    rx: 0,
    unTaggedVlan: '1',
    neighborName: '',
    portnumber: '12',
    switchUnitId: 'FEK3230S0DA',
    portSpeed: 'link down or no traffic',
    adminStatus: 'Up',
    poeEnabled: true,
    name: 'GigabitEthernet1/1/12',
    poeUsed: 0,
    poeTotal: 0,
    poeType: 'n/a',
    usedInFormingStack: false,
    status: 'Down'
  },
  {
    vlanIds: '1',
    isInWarningState: false,
    tx: 0,
    portIdentifier: '1/2/1',
    rx: 0,
    unTaggedVlan: '1',
    neighborName: '',
    portnumber: '1',
    switchUnitId: 'FEK3230S0DA',
    portSpeed: 'link down or no traffic',
    adminStatus: 'Up',
    poeEnabled: false,
    name: 'GigabitEthernet1/2/1',
    poeUsed: 0,
    poeTotal: 0,
    poeType: '',
    usedInFormingStack: false,
    status: 'Down'
  },
  {
    vlanIds: '1',
    isInWarningState: false,
    tx: 0,
    portIdentifier: '1/2/2',
    rx: 0,
    unTaggedVlan: '1',
    neighborName: '',
    portnumber: '2',
    switchUnitId: 'FEK3230S0DA',
    portSpeed: 'link down or no traffic',
    adminStatus: 'Up',
    poeEnabled: false,
    name: 'GigabitEthernet1/2/2',
    poeUsed: 0,
    poeTotal: 0,
    poeType: '',
    usedInFormingStack: false,
    status: 'Down'
  },
  {
    vlanIds: '1',
    isInWarningState: false,
    tx: 162041230,
    portIdentifier: '1/3/1',
    rx: 2112,
    neighborMacAddress: 'C0:C5:20:AA:32:88',
    unTaggedVlan: '1',
    neighborName: '',
    portnumber: '1',
    switchUnitId: 'FEK3230S0DA',
    portSpeed: '10 Gb/sec',
    adminStatus: 'Up',
    poeEnabled: false,
    name: '10GigabitEthernet1/3/1',
    poeUsed: 0,
    poeTotal: 0,
    poeType: '',
    usedInFormingStack: true,
    status: 'Up'
  },
  {
    vlanIds: '1',
    isInWarningState: false,
    tx: 0,
    portIdentifier: '1/3/2',
    rx: 0,
    unTaggedVlan: '1',
    neighborName: '',
    portnumber: '2',
    switchUnitId: 'FEK3230S0DA',
    portSpeed: 'link down or no traffic',
    adminStatus: 'Up',
    poeEnabled: false,
    name: '10GigabitEthernet1/3/2',
    poeUsed: 0,
    poeTotal: 0,
    poeType: '',
    usedInFormingStack: true,
    status: 'Down'
  }
]

export const standaloneFront = {
  data: ports
}

export const standaloneRear = {
  powerStatus: [
    {
      unit: 1,
      slotNumber: 1,
      type: 'AC',
      status: 'OK'
    }
  ]
}

export const switchDetailSatckOnline = {
  type: 'device',
  isStack: true,
  rearModule: 'none',
  switchMac: '58:fb:96:0e:c0:c4',
  switchName: 'ICX7150-C12 Router',
  model: 'ICX7150-C12P',
  id: '58:fb:96:0e:c0:c4',
  firmwareVersion: 'SPR09010e',
  freeMemory: 274526208,
  clientCount: 2,
  floorplanId: '',
  deviceType: 'DVCNWTYPE_SWITCH',
  serialNumber: 'FEK3230S0DA',
  yPercent: 0,
  portsStatus: {
    Down: 27,
    Up: 5
  },
  staticOrDynamic: 'dynamic',
  ipAddress: '10.206.10.28',
  dns: '10.10.10.106',
  cpu: 29,
  stackMember: false,
  cliApplied: true,
  subnetMask: '255.255.254.0',
  unitSerialNumbers: 'FEK3230S0DA',
  modules: 'switch',
  venueName: 'My-Venue',
  isIpFullContentParsed: true,
  name: 'ICX7150-C12 Router',
  activeSerial: 'FEK3230S0DA',
  suspendingDeployTime: '',
  cloudPort: 'INVALID',
  stackMemberOrder: 'FEK3230S0DA',
  numOfUnits: 1,
  memory: 73,
  switchType: SWITCH_TYPE.ROUTER,
  crtTime: '1676287992033',
  portModuleIds: 'FEK3230S0DA',
  configReady: true,
  deviceStatus: SwitchStatusEnum.OPERATIONAL,
  sendedHostname: true,
  venueId: 'a98653366d2240b9ae370e48fab3a9a1',
  firmware: 'SPR09010e',
  timestamp: 1677143094679,
  xPercent: 0,
  syncedSwitchConfig: true,
  defaultGateway: '10.206.11.254',
  stackMembers: [
    {
      model: 'ICX7150-C12P',
      id: 'FEK3230S0DA'
    }
  ],
  uptime: '41 days, 1:6:54.00',
  poeUsage: {
    poeFree: 108600,
    poeTotal: 124000,
    poeUtilization: 15400
  },
  totalMemory: 1019744256,
  tenantId: 'f2e4a77d49914dc7b1bcb0dfc21b9a74',
  family: 'ICX7150-C12P',
  numOfPorts: 16
}

export const switchDetailSwitchOffline = {
  deviceType: 'DVCNWTYPE_SWITCH',
  suspendingDeployTime: '',
  stackMemberOrder: '',
  serialNumber: 'FEK3224R07X',
  xPercent: 0,
  yPercent: 0,
  portsStatus: {},
  stackMember: false,
  cliApplied: false,
  isStack: false,
  rearModule: 'none',
  deviceStatus: SwitchStatusEnum.NEVER_CONTACTED_CLOUD,
  poeUsage: {},
  venueName: 'test9',
  isIpFullContentParsed: false,
  sendedHostname: true,
  switchMac: '',
  venueId: '9417693931ab409ca41ecf9b36f516be',
  name: '',
  tenantId: 'f2e4a77d49914dc7b1bcb0dfc21b9a74',
  activeSerial: 'FEK3224R07X',
  model: 'ICX7150-C12P',
  id: 'FEK3224R07X',
  floorplanId: '',
  configReady: false,
  syncedSwitchConfig: false,
  stackMembers: []
}

export const breakoutPorts = [
  {
    vlanIds: '1',
    isInWarningState: false,
    tx: 0,
    portIdentifier: '1/2/1:1',
    rx: 0,
    unTaggedVlan: '1',
    neighborName: '',
    portnumber: '1:1',
    switchUnitId: 'FLX3333R011',
    portSpeed: 'link down or no traffic',
    adminStatus: 'Up',
    poeEnabled: false,
    name: '100GigabitEthernet1/2/1:1',
    poeUsed: 0,
    poeTotal: 0,
    poeType: '',
    usedInFormingStack: true,
    usedInUplink: true,
    status: 'Down'
  },
  {
    vlanIds: '1',
    isInWarningState: false,
    tx: 0,
    portIdentifier: '1/2/1:2',
    rx: 0,
    unTaggedVlan: '1',
    neighborName: '',
    portnumber: '1:2',
    switchUnitId: 'FLX3333R011',
    portSpeed: 'link down or no traffic',
    adminStatus: 'Up',
    poeEnabled: false,
    name: '100GigabitEthernet1/2/1:2',
    poeUsed: 0,
    poeTotal: 0,
    poeType: '',
    usedInFormingStack: false,
    status: 'Down'
  },
  {
    vlanIds: '1',
    isInWarningState: false,
    tx: 0,
    portIdentifier: '1/2/1:3',
    rx: 0,
    unTaggedVlan: '1',
    neighborName: '',
    portnumber: '1:3',
    switchUnitId: 'FLX3333R011',
    portSpeed: 'link down or no traffic',
    adminStatus: 'Up',
    poeEnabled: false,
    name: '100GigabitEthernet1/2/1:3',
    poeUsed: 0,
    poeTotal: 0,
    poeType: '',
    usedInFormingStack: false,
    status: 'Down'
  },
  {
    vlanIds: '1',
    isInWarningState: false,
    tx: 0,
    portIdentifier: '1/2/1:4',
    rx: 0,
    unTaggedVlan: '1',
    neighborName: '',
    portnumber: '1:4',
    switchUnitId: 'FLX3333R011',
    portSpeed: 'link down or no traffic',
    adminStatus: 'Up',
    poeEnabled: true,
    name: '100GigabitEthernet1/2/1:4',
    poeUsed: 30,
    poeTotal: 3000,
    poeType: '',
    usedInFormingStack: false,
    status: 'Down'
  },
  {
    vlanIds: '1',
    isInWarningState: false,
    tx: 0,
    portIdentifier: '1/2/2',
    rx: 0,
    unTaggedVlan: '1',
    neighborName: '',
    portnumber: '8',
    switchUnitId: 'FLX3333R011',
    portSpeed: 'link down or no traffic',
    adminStatus: 'Up',
    poeEnabled: false,
    name: '100GigabitEthernet1/2/8',
    poeUsed: 0,
    poeTotal: 0,
    poeType: '',
    usedInFormingStack: false,
    status: 'Down'
  }
] as SwitchPortStatus[]
