/* eslint-disable max-len */
export const mockNetwork1Data = {
  id: '27a213f3908b45aba754bf1f096ac783',
  name: 'network2',
  type: 'OPEN',
  content: '{"type":"open","isCloudpathEnabled":false,"venues":[],"enableAccountingProxy":false,"enableAuthProxy":false,"enableAccountingService":false,"wlan":{"advancedCustomization":{"clientIsolation":true,"devicePolicyId":null,"l2AclPolicyId":null,"l3AclPolicyId":null,"applicationPolicyId":null,"accessControlProfileId":null,"userUplinkRateLimiting":0,"userDownlinkRateLimiting":0,"maxClientsOnWlanPerRadio":100,"enableBandBalancing":true,"clientIsolationOptions":{"autoVrrp":false},"hideSsid":false,"forceMobileDeviceDhcp":false,"clientLoadBalancingEnable":true,"directedThreshold":5,"enableNeighborReport":true,"radioCustomization":{"rfBandUsage":"BOTH","phyTypeConstraint":"NONE"},"enableSyslog":false,"clientInactivityTimeout":120,"accessControlEnable":false,"respectiveAccessControl":true,"vlanPool":null,"applicationPolicyEnable":false,"l2AclEnable":false,"l3AclEnable":false,"wifiCallingEnabled":false,"wifiCallingIds":[],"proxyARP":false,"enableAirtimeDecongestion":false,"enableJoinRSSIThreshold":false,"joinRSSIThreshold":-85,"enableTransientClientManagement":false,"joinWaitTime":30,"joinExpireTime":300,"joinWaitThreshold":10,"enableOptimizedConnectivityExperience":false,"broadcastProbeResponseDelay":15,"rssiAssociationRejectionThreshold":-75,"enableAntiSpoofing":false,"enableArpRequestRateLimit":true,"arpRequestRateLimit":15,"enableDhcpRequestRateLimit":true,"dhcpRequestRateLimit":15,"dnsProxyEnabled":false,"dnsProxy":{"dnsProxyRules":[]},"bssPriority":"HIGH","dhcpOption82Enabled":false,"dhcpOption82SubOption1Enabled":false,"dhcpOption82SubOption1Format":null,"dhcpOption82SubOption2Enabled":false,"dhcpOption82SubOption2Format":null,"dhcpOption82SubOption150Enabled":false,"dhcpOption82SubOption151Enabled":false,"dhcpOption82SubOption151Format":null,"dhcpOption82MacFormat":null,"enableMulticastUplinkRateLimiting":false,"enableMulticastDownlinkRateLimiting":false,"enableMulticastUplinkRateLimiting6G":false,"enableMulticastDownlinkRateLimiting6G":false,"enableAdditionalRegulatoryDomains":true,"wifi6Enabled":true,"wifi7Enabled":true,"multiLinkOperationEnabled":false,"multiLinkOperationOptions":{"enable24G":true,"enable50G":true,"enable6G":false},"qosMirroringEnabled":true,"qosMapSetEnabled":false,"qosMapSetOptions":{"rules":[]},"fastRoamingOptions":{"statisticsOverDistributedSystemEnabled":false,"reassociationTimeout":20}},"enable":true,"vlanId":1},"hotspot20Settings":{}}',
  sessionId: '59af7b003a5545b2bc8e0f11647f5767',
  requiredFields: [
    'type'
  ]
}