/* eslint-disable max-len */
export const vlans = [{
  arpInspection: false,
  id: '545d08c0e7894501846455233ad60cc5',
  igmpSnooping: 'none',
  ipv4DhcpSnooping: false,
  spanningTreePriority: 32768,
  spanningTreeProtocol: 'none',
  vlanId: 2,
  vlanName: 'vlan-01'
}, {
  arpInspection: false,
  id: '1af3d29b5dcc46a5a20a651fda55e2df',
  igmpSnooping: 'none',
  ipv4DhcpSnooping: false,
  spanningTreePriority: 32768,
  spanningTreeProtocol: 'none',
  switchFamilyModels: [{
    id: '9874453239bc479fac68bc050d0cf729',
    model: 'ICX7550-24P',
    slots: [
      { slotNumber: 1, enable: true },
      { slotNumber: 3, enable: true, option: '2X40G' },
      { slotNumber: 2, enable: true, option: '2X40G' }
    ],
    taggedPorts: '1/2/2',
    untaggedPorts: '1/1/20,1/3/2'
  }, {
    id: '9874453239bc479fac68bc050d0cf730',
    model: 'ICX7850-48F',
    slots: [
      { slotNumber: 1, enable: true, option: '' },
      { slotNumber: 2, enable: true, option: '12X40/100G' },
      { slotNumber: 3, enable: true, option: '8X40/100G' }
    ]
  }],
  vlanId: 3,
  vlanName: 'vlan-02'
}]

export const records = [{
  id: '9874453239bc479fac68bc050d0cf729',
  model: 'ICX7550-24P',
  slots: [
    { slotNumber: 1, enable: true, option: '' },
    { slotNumber: 3, enable: true, option: '2X40G' },
    { slotNumber: 2, enable: true, option: '2X40G' }
  ],
  taggedPorts: ['1/1/48'],
  title: '',
  untaggedPorts: ['1/1/44'],
  vlanConfigName: ''
}]

export const vlanSettingValues = {
  enableSlot2: true,
  enableSlot3: true,
  enableSlot4: false,
  family: 'ICX7150',
  model: '48',
  selectedOptionOfSlot2: '2X1G',
  selectedOptionOfSlot3: '4X1/10G',
  selectedOptionOfSlot4: '',
  switchFamilyModels: {
    id: '',
    model: 'ICX7150-48',
    slots: [
      { slotNumber: 1, enable: true, option: '', slotPortInfo: '48X1G', portStatus: Array(48) },
      { slotNumber: 2, enable: true, option: '2X1G', slotPortInfo: '2X1G', portStatus: Array(2) },
      { slotNumber: 3, enable: true, option: '4X1/10G', slotPortInfo: '4X1/10G', portStatus: Array(4) }
    ],
    taggedPorts: ['1/1/28'],
    untaggedPorts: ['1/1/21', '1/1/40']
  }
}

export const portList = [{
  cloudPort: true,
  stack: false,
  name: '1114',
  portId: 'c0-c5-20-b2-0e-e9_1-1-1',
  status: 'Up',
  adminStatus: 'Up',
  vlanIds: '1',
  portSpeed: '1 Gb/sec',
  poeUsed: 0,
  poeTotal: 0,
  signalIn: 0,
  signalOut: 0,
  crcErr: '0',
  inErr: '0',
  outErr: '0',
  opticsType: '1 Gbits per second copper',
  switchUnitId: 'FMF3250Q06R',
  poeEnabled: true,
  usedInFormingStack: false,
  portIdentifier: '1/1/1',
  portNumber: '1',
  portnumber: '1',
  unTaggedVlan: '1',
  inDiscard: '0',
  broadcastIn: '623822',
  broadcastOut: '4',
  multicastIn: '655248',
  multicastOut: '8931',
  poeType: 'n/a',
  switchMac: 'c0:c5:20:b2:0e:e9',
  id: 'c0-c5-20-b2-0e-e9_1-1-1',
  neighborName: '[11F_LAB_R2_DOWN_10.206.11.5',
  venueId: '81e0fac39cee430992e9f770fce3645b',
  ingressAclName: '',
  egressAclName: '',
  vsixIngressAclName: '',
  vsixEgressAclName: '',
  lagName: 'LAG3',
  switchName: 'ICX7150-C08P Switch - test',
  switchSerial: 'c0:c5:20:b2:0e:e9',
  lagId: '4',
  deviceStatus: 'ONLINE',
  unitStatus: 'Standalone',
  unitState: 'ONLINE',
  switchModel: 'ICX7150-C08P',
  neighborMacAddress: '5C:8A:38:9F:5F:12',
  syncedSwitchConfig: true,
  mediaType: 'MEDIA_TYPE_EMPTY',
  poeUsage: '0/0W (0%)'
}, {
  cloudPort: false,
  stack: false,
  name: 'GigabitEthernet1/1/2',
  portId: 'c0-c5-20-b2-0e-ea_1-1-2',
  status: 'Down',
  adminStatus: 'Up',
  vlanIds: '101 100 32 8',
  portSpeed: 'link down or no traffic',
  poeUsed: 0,
  poeTotal: 0,
  signalIn: 0,
  signalOut: 0,
  crcErr: '0',
  inErr: '0',
  outErr: '0',
  opticsType: '1 Gbits per second copper',
  switchUnitId: 'FMF3250Q06R',
  poeEnabled: true,
  usedInFormingStack: false,
  portIdentifier: '1/1/2',
  portNumber: '2',
  portnumber: '2',
  unTaggedVlan: '32',
  inDiscard: '0',
  broadcastIn: '0',
  broadcastOut: '0',
  multicastIn: '0',
  multicastOut: '0',
  poeType: 'n/a',
  switchMac: 'c0:c5:20:b2:0e:e9',
  id: 'c0-c5-20-b2-0e-ea_1-1-2',
  neighborName: '',
  venueId: '81e0fac39cee430992e9f770fce3645b',
  ingressAclName: '',
  egressAclName: '',
  vsixIngressAclName: '',
  vsixEgressAclName: '',
  lagName: 'LAG2',
  switchName: 'ICX7150-C08P Switch - test',
  switchSerial: 'c0:c5:20:b2:0e:e9',
  lagId: '2',
  deviceStatus: 'ONLINE',
  unitStatus: 'Standalone',
  unitState: 'ONLINE',
  switchModel: 'ICX7150-C08P',
  neighborMacAddress: '',
  syncedSwitchConfig: true,
  mediaType: 'MEDIA_TYPE_EMPTY',
  poeUsage: '0/0W (0%)'
}, {
  cloudPort: false,
  stack: false,
  name: 'testtttt${var}<><aaabb>',
  portId: 'c0-c5-20-b2-0e-eb_1-1-3',
  status: 'Down',
  adminStatus: 'Up',
  vlanIds: '1',
  portSpeed: 'link down or no traffic',
  poeUsed: 0,
  poeTotal: 0,
  signalIn: 0,
  signalOut: 0,
  crcErr: '0',
  inErr: '0',
  outErr: '0',
  opticsType: '1 Gbits per second copper',
  switchUnitId: 'FMF3250Q06R',
  poeEnabled: true,
  usedInFormingStack: false,
  portIdentifier: '1/1/3',
  portNumber: '3',
  portnumber: '3',
  unTaggedVlan: '1',
  inDiscard: '0',
  broadcastIn: '0',
  broadcastOut: '0',
  multicastIn: '0',
  multicastOut: '0',
  poeType: 'n/a',
  switchMac: 'c0:c5:20:b2:0e:e9',
  id: 'c0-c5-20-b2-0e-eb_1-1-3',
  neighborName: '',
  venueId: '81e0fac39cee430992e9f770fce3645b',
  ingressAclName: '',
  egressAclName: '',
  vsixIngressAclName: '',
  vsixEgressAclName: '',
  lagName: '',
  switchName: 'ICX7150-C08P Switch - test',
  switchSerial: 'c0:c5:20:b2:0e:e9',
  lagId: '0',
  deviceStatus: 'ONLINE',
  unitStatus: 'Standalone',
  unitState: 'ONLINE',
  switchModel: 'ICX7150-C08P',
  neighborMacAddress: '',
  syncedSwitchConfig: true,
  mediaType: 'MEDIA_TYPE_EMPTY',
  poeUsage: '0/0W (0%)'
}, {
  cloudPort: false,
  stack: false,
  name: 'GigabitEthernet1/1/4',
  portId: 'c0-c5-20-b2-0e-ec_1-1-4',
  status: 'Down',
  adminStatus: 'Up',
  vlanIds: '101 100 32 8',
  portSpeed: 'link down or no traffic',
  poeUsed: 0,
  poeTotal: 0,
  signalIn: 0,
  signalOut: 0,
  crcErr: '0',
  inErr: '0',
  outErr: '0',
  opticsType: '1 Gbits per second copper',
  switchUnitId: 'FMF3250Q06R',
  poeEnabled: true,
  usedInFormingStack: false,
  portIdentifier: '1/1/4',
  portNumber: '4',
  portnumber: '4',
  unTaggedVlan: '32',
  inDiscard: '0',
  broadcastIn: '0',
  broadcastOut: '0',
  multicastIn: '0',
  multicastOut: '0',
  poeType: 'n/a',
  switchMac: 'c0:c5:20:b2:0e:e9',
  id: 'c0-c5-20-b2-0e-ec_1-1-4',
  neighborName: '',
  venueId: '81e0fac39cee430992e9f770fce3645b',
  ingressAclName: '',
  egressAclName: '',
  vsixIngressAclName: '',
  vsixEgressAclName: '',
  lagName: 'LAG2',
  switchName: 'ICX7150-C08P Switch - test',
  switchSerial: 'c0:c5:20:b2:0e:e9',
  lagId: '2',
  deviceStatus: 'ONLINE',
  unitStatus: 'Standalone',
  unitState: 'ONLINE',
  switchModel: 'ICX7150-C08P',
  neighborMacAddress: '',
  syncedSwitchConfig: true,
  mediaType: 'MEDIA_TYPE_EMPTY',
  poeUsage: '0/0W (0%)'
}, {
  cloudPort: false,
  stack: false,
  name: 'GigabitEthernet1/1/5',
  portId: 'c0-c5-20-b2-0e-ed_1-1-5',
  status: 'Down',
  adminStatus: 'Up',
  vlanIds: '7',
  portSpeed: 'link down or no traffic',
  poeUsed: 0,
  poeTotal: 0,
  signalIn: 0,
  signalOut: 0,
  crcErr: '0',
  inErr: '0',
  outErr: '0',
  opticsType: '1 Gbits per second copper',
  switchUnitId: 'FMF3250Q06R',
  poeEnabled: true,
  usedInFormingStack: false,
  portIdentifier: '1/1/5',
  portNumber: '5',
  portnumber: '5',
  unTaggedVlan: '7',
  inDiscard: '0',
  broadcastIn: '0',
  broadcastOut: '0',
  multicastIn: '0',
  multicastOut: '0',
  poeType: 'n/a',
  switchMac: 'c0:c5:20:b2:0e:e9',
  id: 'c0-c5-20-b2-0e-ed_1-1-5',
  neighborName: '',
  venueId: '81e0fac39cee430992e9f770fce3645b',
  ingressAclName: '11',
  egressAclName: 'ext1',
  vsixIngressAclName: '',
  vsixEgressAclName: '',
  lagName: '',
  switchName: 'ICX7150-C08P Switch - test',
  switchSerial: 'c0:c5:20:b2:0e:e9',
  lagId: '0',
  deviceStatus: 'ONLINE',
  unitStatus: 'Standalone',
  unitState: 'ONLINE',
  switchModel: 'ICX7150-C08P',
  neighborMacAddress: '',
  syncedSwitchConfig: true,
  mediaType: 'MEDIA_TYPE_EMPTY',
  poeUsage: '0/0W (0%)'
}, {
  cloudPort: false,
  stack: false,
  name: 'GigabitEthernet1/1/6',
  portId: 'c0-c5-20-b2-0e-ee_1-1-6',
  status: 'Down',
  adminStatus: 'Up',
  vlanIds: '1',
  portSpeed: 'link down or no traffic',
  poeUsed: 0,
  poeTotal: 0,
  signalIn: 0,
  signalOut: 0,
  crcErr: '0',
  inErr: '0',
  outErr: '0',
  opticsType: '1 Gbits per second copper',
  switchUnitId: 'FMF3250Q06R',
  poeEnabled: true,
  usedInFormingStack: false,
  portIdentifier: '1/1/6',
  portNumber: '6',
  portnumber: '6',
  unTaggedVlan: '1',
  inDiscard: '0',
  broadcastIn: '0',
  broadcastOut: '0',
  multicastIn: '0',
  multicastOut: '0',
  poeType: 'n/a',
  switchMac: 'c0:c5:20:b2:0e:e9',
  id: 'c0-c5-20-b2-0e-ee_1-1-6',
  neighborName: '',
  venueId: '81e0fac39cee430992e9f770fce3645b',
  ingressAclName: '',
  egressAclName: '',
  vsixIngressAclName: '',
  vsixEgressAclName: '',
  lagName: '',
  switchName: 'ICX7150-C08P Switch - test',
  switchSerial: 'c0:c5:20:b2:0e:e9',
  lagId: '0',
  deviceStatus: 'ONLINE',
  unitStatus: 'Standalone',
  unitState: 'ONLINE',
  switchModel: 'ICX7150-C08P',
  neighborMacAddress: '',
  syncedSwitchConfig: true,
  mediaType: 'MEDIA_TYPE_EMPTY',
  poeUsage: '0/0W (0%)'
}, {
  cloudPort: false,
  stack: false,
  name: '${testString}<aaabbbccc>',
  portId: 'c0-c5-20-b2-0e-ef_1-1-7',
  status: 'Down',
  adminStatus: 'Up',
  vlanIds: '1',
  portSpeed: 'link down or no traffic',
  poeUsed: 0,
  poeTotal: 0,
  signalIn: 0,
  signalOut: 0,
  crcErr: '0',
  inErr: '0',
  outErr: '0',
  opticsType: '1 Gbits per second copper',
  switchUnitId: 'FMF3250Q06R',
  poeEnabled: true,
  usedInFormingStack: false,
  portIdentifier: '1/1/7',
  portNumber: '7',
  portnumber: '7',
  unTaggedVlan: '1',
  inDiscard: '0',
  broadcastIn: '0',
  broadcastOut: '0',
  multicastIn: '0',
  multicastOut: '0',
  poeType: 'n/a',
  switchMac: 'c0:c5:20:b2:0e:e9',
  id: 'c0-c5-20-b2-0e-ef_1-1-7',
  neighborName: '',
  venueId: '81e0fac39cee430992e9f770fce3645b',
  ingressAclName: '',
  egressAclName: '',
  vsixIngressAclName: '',
  vsixEgressAclName: '',
  lagName: '',
  switchName: 'ICX7150-C08P Switch - test',
  switchSerial: 'c0:c5:20:b2:0e:e9',
  lagId: '0',
  deviceStatus: 'ONLINE',
  unitStatus: 'Standalone',
  unitState: 'ONLINE',
  switchModel: 'ICX7150-C08P',
  neighborMacAddress: '',
  syncedSwitchConfig: true,
  mediaType: 'MEDIA_TYPE_EMPTY',
  poeUsage: '0/0W (0%)'
}, {
  cloudPort: false,
  stack: false,
  name: '${testString}',
  portId: 'c0-c5-20-b2-0e-f0_1-1-8',
  status: 'Down',
  adminStatus: 'Up',
  vlanIds: '4',
  portSpeed: 'link down or no traffic',
  poeUsed: 0,
  poeTotal: 0,
  signalIn: 0,
  signalOut: 0,
  crcErr: '0',
  inErr: '0',
  outErr: '0',
  opticsType: '1 Gbits per second copper',
  switchUnitId: 'FMF3250Q06R',
  poeEnabled: true,
  usedInFormingStack: false,
  portIdentifier: '1/1/8',
  portNumber: '8',
  portnumber: '8',
  unTaggedVlan: '4',
  inDiscard: '0',
  broadcastIn: '0',
  broadcastOut: '0',
  multicastIn: '0',
  multicastOut: '0',
  poeType: 'n/a',
  switchMac: 'c0:c5:20:b2:0e:e9',
  id: 'c0-c5-20-b2-0e-f0_1-1-8',
  neighborName: '',
  venueId: '81e0fac39cee430992e9f770fce3645b',
  ingressAclName: '',
  egressAclName: '',
  vsixIngressAclName: '',
  vsixEgressAclName: '',
  lagName: '',
  switchName: 'ICX7150-C08P Switch - test',
  switchSerial: 'c0:c5:20:b2:0e:e9',
  lagId: '0',
  deviceStatus: 'ONLINE',
  unitStatus: 'Standalone',
  unitState: 'ONLINE',
  switchModel: 'ICX7150-C08P',
  neighborMacAddress: '',
  syncedSwitchConfig: true,
  mediaType: 'MEDIA_TYPE_EMPTY',
  poeUsage: '0/0W (0%)'
}, {
  cloudPort: false,
  stack: false,
  name: 'GigabitEthernet1/2/1',
  portId: 'c0-c5-20-b2-0e-f1_1-2-1',
  status: 'Down',
  adminStatus: 'Up',
  vlanIds: '3',
  portSpeed: 'link down or no traffic',
  poeUsed: 0,
  poeTotal: 0,
  signalIn: 0,
  signalOut: 0,
  crcErr: '0',
  inErr: '0',
  outErr: '0',
  opticsType: '1 Gbits per second fiber',
  switchUnitId: 'FMF3250Q06R',
  poeEnabled: false,
  usedInFormingStack: false,
  portIdentifier: '1/2/1',
  portNumber: '1',
  portnumber: '1',
  unTaggedVlan: '3',
  inDiscard: '0',
  broadcastIn: '0',
  broadcastOut: '0',
  multicastIn: '0',
  multicastOut: '0',
  poeType: '',
  switchMac: 'c0:c5:20:b2:0e:e9',
  id: 'c0-c5-20-b2-0e-f1_1-2-1',
  neighborName: '',
  venueId: '81e0fac39cee430992e9f770fce3645b',
  ingressAclName: '',
  egressAclName: '',
  vsixIngressAclName: '',
  vsixEgressAclName: '',
  lagName: '',
  switchName: 'ICX7150-C08P Switch - test',
  switchSerial: 'c0:c5:20:b2:0e:e9',
  lagId: '0',
  deviceStatus: 'ONLINE',
  unitStatus: 'Standalone',
  unitState: 'ONLINE',
  switchModel: 'ICX7150-C08P',
  neighborMacAddress: '',
  syncedSwitchConfig: true,
  mediaType: 'MEDIA_TYPE_EMPTY',
  poeUsage: 'off'
}, {
  cloudPort: false,
  stack: false,
  name: 'GigabitEthernet1/2/2',
  portId: 'c0-c5-20-b2-0e-f2_1-2-2',
  status: 'Down',
  adminStatus: 'Up',
  vlanIds: '1 7',
  portSpeed: 'link down or no traffic',
  poeUsed: 0,
  poeTotal: 0,
  signalIn: 0,
  signalOut: 0,
  crcErr: '0',
  inErr: '0',
  outErr: '0',
  opticsType: '1 Gbits per second fiber',
  switchUnitId: 'FMF3250Q06R',
  poeEnabled: false,
  usedInFormingStack: false,
  portIdentifier: '1/2/2',
  portNumber: '2',
  portnumber: '2',
  unTaggedVlan: '1',
  inDiscard: '0',
  broadcastIn: '0',
  broadcastOut: '0',
  multicastIn: '0',
  multicastOut: '0',
  poeType: '',
  switchMac: 'c0:c5:20:b2:0e:e9',
  id: 'c0-c5-20-b2-0e-f2_1-2-2',
  neighborName: '',
  venueId: '81e0fac39cee430992e9f770fce3645b',
  ingressAclName: '',
  egressAclName: '',
  vsixIngressAclName: '',
  vsixEgressAclName: '',
  lagName: '',
  switchName: 'ICX7150-C08P Switch - test',
  switchSerial: 'c0:c5:20:b2:0e:e9',
  lagId: '0',
  deviceStatus: 'ONLINE',
  unitStatus: 'Standalone',
  unitState: 'ONLINE',
  switchModel: 'ICX7150-C08P',
  neighborMacAddress: '',
  syncedSwitchConfig: true,
  mediaType: 'MEDIA_TYPE_EMPTY',
  poeUsage: 'off'
}]

export const portSlotsData = [[{
  portCount: 8,
  portNumber: 8,
  portStatus: portList.slice(0, 7),
  portTagged: '',
  slotNumber: 1
}, {
  portCount: 2,
  portNumber: 2,
  portStatus: portList.slice(8, 9),
  portTagged: '',
  slotNumber: 2
}]]