import { BrowserRouter as Router } from '@acx-ui/react-router-dom'
import { render, screen }          from '@acx-ui/test-utils'
import { RolesEnum }               from '@acx-ui/types'

import { EdgeScopes, SwitchScopes, WifiScopes } from './types'
import {
  AuthRoute,
  filterByAccess,
  getShowWithoutRbacCheckKey,
  getUserProfile,
  hasAccess,
  hasRoles,
  hasPermission,
  setUserProfile,
  WrapIfAccessible
} from './userProfile'

function setRole (role: RolesEnum, abacEnabled?: boolean, isCustomRole?:boolean, scopes?:(WifiScopes|SwitchScopes|EdgeScopes)[]) {
  const profile = getUserProfile()
  setUserProfile({
    ...profile,
    profile: {
      ...profile.profile,
      roles: [role]
    },
    allowedOperations: ['GET:/networks', 'GET:/switches'],
    accountTier: '',
    betaEnabled: false,
    abacEnabled: abacEnabled ?? false,
    isCustomRole,
    scopes
  })
}

jest.mock('@acx-ui/react-router-dom', () => ({
  ...jest.requireActual('@acx-ui/react-router-dom'),
  TenantNavigate: () => <div data-testid='no-permissions' />
}))

describe('hasAccess', () => {
  describe('without id', () => {
    it('allow admins', () => {
      setRole(RolesEnum.PRIME_ADMIN)
      expect(hasAccess()).toBe(true)
      setRole(RolesEnum.ADMINISTRATOR)
      expect(hasAccess()).toBe(true)
      setRole(RolesEnum.DPSK_ADMIN)
      expect(hasAccess()).toBe(true)
    })
    it('block guest manager & read-only', () => {
      setRole(RolesEnum.GUEST_MANAGER)
      expect(hasAccess()).toBe(false)
      setRole(RolesEnum.READ_ONLY)
      expect(hasAccess()).toBe(false)
    })
  })

  describe('when id in allowedOperations', () => {
    it('allow when operation in allowedOperations', () => {
      setRole(RolesEnum.READ_ONLY)
      expect(hasAccess('GET:/networks')).toBe(true)
    })

    it('block when operation NOT in allowedOperations', () => {
      setRole(RolesEnum.READ_ONLY)
      expect(hasAccess('GET:/network')).toBe(false)
    })
  })
})

describe('hasRoles', () => {
  beforeEach(() => setRole(RolesEnum.ADMINISTRATOR))

  it('check role', () => {
    expect(hasRoles(RolesEnum.PRIME_ADMIN)).toBe(false)
    expect(hasRoles(RolesEnum.ADMINISTRATOR)).toBe(true)
    expect(hasRoles(RolesEnum.GUEST_MANAGER)).toBe(false)
    expect(hasRoles(RolesEnum.READ_ONLY)).toBe(false)
  })
  it('check roles', () => {
    expect(hasRoles([RolesEnum.PRIME_ADMIN])).toBe(false)
    expect(hasRoles([RolesEnum.ADMINISTRATOR])).toBe(true)
    expect(hasRoles([RolesEnum.GUEST_MANAGER])).toBe(false)
    expect(hasRoles([RolesEnum.READ_ONLY])).toBe(false)

    expect(hasRoles([
      RolesEnum.PRIME_ADMIN,
      RolesEnum.ADMINISTRATOR,
      RolesEnum.DPSK_ADMIN
    ])).toBe(true)
    expect(hasRoles([
      RolesEnum.ADMINISTRATOR,
      RolesEnum.GUEST_MANAGER
    ])).toBe(true)
    expect(hasRoles([
      RolesEnum.GUEST_MANAGER,
      RolesEnum.READ_ONLY
    ])).toBe(false)
  })
})

describe('filterByAccess', () => {
  it('filter based on logic of hasAccess', () => {
    const items = [
      { key: 'random-key' },
      {}
    ]

    setRole(RolesEnum.PRIME_ADMIN)
    expect(filterByAccess(items)).toHaveLength(1)

    setRole(RolesEnum.ADMINISTRATOR)
    expect(filterByAccess(items)).toHaveLength(1)

    setRole(RolesEnum.GUEST_MANAGER)
    expect(filterByAccess(items)).toHaveLength(0)

    setRole(RolesEnum.READ_ONLY)
    expect(filterByAccess(items)).toHaveLength(0)

  })

  it('allow when id is generated by getShowWithoutRbacCheckKey function', () => {
    expect(filterByAccess([
      {
        key: getShowWithoutRbacCheckKey('test')
      }
    ])).toHaveLength(1)
  })
})

describe('hasPermission', () => {
  beforeEach(() => setRole(RolesEnum.ADMINISTRATOR))

  describe('ABAC FF disabled', () => {
    it('check ADMIN user permission', () => {
      expect(hasPermission()).toBe(true)
      expect(hasPermission({ scopes: [], allowedOperations: 'GET:/networks' })).toBe(true)
      expect(hasPermission({ scopes: [], allowedOperations: 'GET:/edges' })).toBe(false)
    })
    it('check READ ONLY user permission', () => {
      setRole(RolesEnum.READ_ONLY)
      expect(hasPermission()).toBe(false)
      expect(hasPermission({ allowedOperations: 'GET:/networks' })).toBe(true)
      expect(hasPermission({ allowedOperations: 'GET:/edges' })).toBe(false)
      expect(
        hasPermission({ scopes: [SwitchScopes.DELETE], allowedOperations: 'GET:/networks' })
      ).toBe(true)
    })
  })

  describe('ABAC FF enabled', () => {
    it('check ADMIN user permission', () => {
      setRole(RolesEnum.ADMINISTRATOR, true)
      expect(hasPermission()).toBe(true)
      expect(hasPermission({ allowedOperations: 'GET:/switches' })).toBe(true)
      expect(hasPermission({ allowedOperations: 'GET:/edges' })).toBe(false)
      expect(hasPermission({ scopes: [], allowedOperations: 'GET:/networks' })).toBe(true)
      expect(hasPermission({ scopes: [], allowedOperations: 'GET:/edges' })).toBe(false)
    })

    it('check CUSTOM user permission', () => {
      setRole('CUSTOM USER' as RolesEnum, true, true,[SwitchScopes.READ])
      expect(hasPermission()).toBe(true)
      expect(hasPermission({ allowedOperations: 'GET:/switches' })).toBe(true)
      expect(hasPermission({ allowedOperations: 'GET:/edges' })).toBe(false)
      expect(hasPermission({ scopes: [], allowedOperations: 'GET:/networks' })).toBe(true)
      expect(hasPermission({ scopes: [], allowedOperations: 'GET:/edges' })).toBe(false)
      expect(
        hasPermission({ scopes: [SwitchScopes.READ], allowedOperations: 'GET:/switches' })
      ).toBe(true)
      expect(
        hasPermission({ scopes: [SwitchScopes.DELETE], allowedOperations: 'GET:/switches' })
      ).toBe(false)
    })
  })
})

describe('WrapIfAccessible', () => {
  it('should wrap if user has access', () => {
    render(
      <WrapIfAccessible wrapper={children =>
        <div data-testid='wrapper'>{children}</div>
      }>
        <div>Test</div>
      </WrapIfAccessible>
    )
    expect(screen.getByTestId('wrapper')).toBeVisible()
  })

  it('should not wrap if user does not have access', () => {
    setRole(RolesEnum.READ_ONLY)
    render(
      <WrapIfAccessible wrapper={children =>
        <div data-testid='wrapper'>{children}</div>
      }>
        <div>Test</div>
      </WrapIfAccessible>
    )
    expect(screen.queryByTestId('wrapper')).toBeNull()
  })
})

describe('AuthRoute', () => {
  it('should go to no permissions page', async () => {
    setRole(RolesEnum.READ_ONLY, true, true, [SwitchScopes.READ])
    render(
      <Router>
        <AuthRoute scopes={[SwitchScopes.UPDATE]}>
          <div>test page</div>
        </AuthRoute>
      </Router>

    )
    expect(await screen.findByTestId('no-permissions')).toBeVisible()
  })

  it('should go to correct page: custom role', async () => {
    setRole(RolesEnum.READ_ONLY, true, true, [SwitchScopes.UPDATE])
    render(
      <Router>
        <AuthRoute scopes={[SwitchScopes.UPDATE]}>
          <div>test page</div>
        </AuthRoute>
      </Router>
    )
    expect(await screen.findByText('test page')).toBeVisible()
  })

  it('should go to correct page: system role', async () => {
    setRole(RolesEnum.PRIME_ADMIN, true, false)
    render(
      <Router>
        <AuthRoute scopes={[SwitchScopes.UPDATE]}>
          <div>test page</div>
        </AuthRoute>
      </Router>
    )
    expect(await screen.findByText('test page')).toBeVisible()
  })
})
