export const venueListResponse = {
  fields: ['name', 'id'],
  totalCount: 5,
  page: 1,
  data: [
    {
      id: '4c778ed630394b76b17bce7fe230cf9f',
      name: 'My-Venue'
    },
    {
      id: '01b1fe5d153d4a2a90455795af6ad877',
      name: 'airport'
    },
    {
      id: 'b2efc20b6d2b426c836d76110f88941b',
      name: 'dsfds'
    },
    {
      id: 'f27f33e0475d4f49af57350fed788c7b',
      name: 'SG office'
    },
    {
      id: 'a678f2e5767746a394a7b10c45235119',
      name: 'sadas'
    }
  ]
}

export const swtichListResponse = {
  totalCount: 2,
  page: 1,
  data: [
    {
      id: 'FEK0000S0A0',
      serialNumber: 'FEK0000S0A0',
      name: '7150stack',
      configReady: true,
      syncDataEndTime: '',
      venueId: 'venue-id'
    },
    {
      serialNumber: 'FEK0010S0A0',
      name: '7150stack',
      configReady: true,
      syncDataEndTime: '',
      venueId: 'venue-id'
    },
    {
      serialNumber: 'FEK0040S0A0',
      configReady: true,
      syncDataEndTime: '',
      venueId: 'venue-id'
    },
    {
      id: 'FEK0030S0A0',
      configReady: true,
      syncDataEndTime: '',
      venueId: 'venue-id'
    }
  ]
}

export const switchListEmptyResponse = {
  data: [],
  fields: ['serialNumber', 'name', 'syncDataStartTime'],
  page: 1,
  totalCount: 0
}

export const vlansByVenueListResponse = [
  {
    id: 'd445b8332be940a6881886a8d9a91306',
    vlanId: 2,
    vlanName: 'vvv',
    ipv4DhcpSnooping: true,
    arpInspection: false,
    igmpSnooping: 'passive',
    multicastVersion: 2,
    spanningTreeProtocol: 'rstp',
    spanningTreePriority: 32768,
    switchFamilyModels: [
      {
        id: 'b6e7fbdfaaa04194b335e95de74d2398',
        model: 'ICX7550-48',
        taggedPorts: '1/1/39,1/3/1',
        slots: [
          {
            slotNumber: 2,
            enable: true,
            option: '2X40G'
          },
          {
            slotNumber: 3,
            enable: true,
            option: '2X40G'
          },
          {
            slotNumber: 1,
            enable: true
          }
        ]
      }
    ]
  }
]

export const vlansByVenueListEmptyResponse = []

export const switchResponse = {
  id: 'dc:ae:eb:2d:ff:8a',
  venueId: '561c8f43714647e2a4aecaba4c4b658b',
  name: 'ICX7150-C12 Router',
  enableStack: false,
  igmpSnooping: 'active',
  jumboMode: false,
  ipAddressInterfaceType: 'VE',
  ipAddressInterface: '1',
  ipAddressType: 'static',
  ipAddress: '192.168.1.73',
  subnetMask: '255.255.255.0',
  firmwareVersion: 'SPR09010e.bin',
  dhcpClientEnabled: false,
  dhcpServerEnabled: false,
  specifiedType: 'AUTO',
  rearModule: 'none'
}

export const switchDetailHeader = {
  type: 'device',
  isStack: false,
  rearModule: 'none',
  switchMac: 'dc:ae:eb:2d:ff:8a',
  switchName: 'ICX7150-C12 Router',
  model: 'ICX7150-C12P',
  id: 'dc:ae:eb:2d:ff:8a',
  syncDataEndTime: 1675058400741,
  firmwareVersion: 'SPR09010e',
  freeMemory: 310996992,
  clientCount: 0,
  floorplanId: '',
  deviceType: 'DVCNWTYPE_SWITCH',
  serialNumber: 'FEK3233R18P',
  yPercent: 0,
  portsStatus: { Down: 15, Up: 1 },
  staticOrDynamic: 'static',
  ipAddress: '192.168.1.73',
  dns: '8.8.8.8',
  cpu: 20,
  stackMember: false,
  cliApplied: false,
  subnetMask: '255.255.255.0',
  unitSerialNumbers: 'FEK3233R18P',
  modules: 'switch',
  venueName: 'My-Venue',
  isIpFullContentParsed: true,
  ipFullContentParsed: true,
  name: 'ICX7150-C12 Router',
  activeSerial: 'FEK3233R18P',
  suspendingDeployTime: '',
  cloudPort: '1/1/1',
  stackMemberOrder: '',
  numOfUnits: 1,
  memory: 69,
  switchType: 'router',
  portModuleIds: 'FEK3233R18P',
  configReady: true,
  deviceStatus: 'ONLINE',
  temperatureGroups:
    // eslint-disable-next-line max-len
    '[{"serialNumber":"FEK3233R18P","stackId":"DC AE EB 2D FF 8A","temperatureSlotList":[{"slotNumber":3,"temperatureValue":54},{"slotNumber":4,"temperatureValue":54.5},{"slotNumber":1,"temperatureValue":71.5},{"slotNumber":2,"temperatureValue":10}]}]',
  sendedHostname: true,
  venueId: '561c8f43714647e2a4aecaba4c4b658b',
  firmware: '',
  timestamp: 1675058400729,
  xPercent: 0,
  syncedSwitchConfig: true,
  defaultGateway: '0.0.0.0',
  stackMembers: [],
  uptime: '20 days, 8:53:43.00',
  poeUsage: { poeFree: 124000, poeTotal: 124000, poeUtilization: 0 },
  totalMemory: 1019744256,
  formStacking: false,
  tenantId: '449455f8e6d749389bb328d2718c85d8',
  family: 'ICX7150-C12P',
  numOfPorts: 16
}

export const switchPortlistResponse = {
  fields: [
    'switchId',
    'switchSerial',
    'portId',
    'inDiscard',
    'authDefaultVlan',
    'crcErr',
    'switchMac',
    'switchName',
    'portSpeed',
    'poeTotal',
    'id',
    'stickyMacAclAllowCount',
    'switchPortProfileType',
    'isPoeScheduleEnabled',
    'vlanIds',
    'outErr',
    'mediaType',
    'multicastOut',
    'ingressAclName',
    'tags',
    'neighborName',
    'switchUnitId',
    'name',
    'switchModel',
    'status',
    'cloudPort',
    'stickyMacAclAllowList',
    'lagForceUpPort',
    'lagName',
    'opticsType',
    'switchMacAcl',
    'switchPortProfileName',
    'poeCapability',
    'deviceStatus',
    'unitStatus',
    'errorDisableStatus',
    'lagId',
    'unTaggedVlan',
    'adminStatus',
    'venueId',
    'usedInFormingStack',
    'egressAclName',
    'stackingNeighborPort',
    'unitState',
    'broadcastOut',
    'syncedSwitchConfig',
    'portIdentifier',
    'broadcastIn',
    'isPoeSupported',
    'neighborMacAddress',
    'poeUsage',
    'vsixEgressAclName',
    'poeEnabled',
    'poeUsed',
    'signalIn',
    'cog',
    'inErr',
    'poeType',
    'vsixIngressAclName',
    'multicastIn',
    'signalOut'
  ],
  totalCount: 16,
  page: 1,
  data: [
    {
      cloudPort: true,
      stack: false,
      name: 'GigabitEthernet1/1/1',
      portId: 'c0-c5-20-aa-35-d9_1-1-1',
      status: 'Up',
      adminStatus: 'Up',
      vlanIds: '1',
      portSpeed: '1 Gb/sec',
      poeUsed: 0,
      poeTotal: 0,
      signalIn: 0,
      signalOut: 0,
      crcErr: '0',
      inErr: '0',
      outErr: '0',
      opticsType: '1 Gbits per second copper',
      switchUnitId: 'FEK3224R0AN',
      poeEnabled: true,
      usedInFormingStack: false,
      portIdentifier: '1/1/1',
      unTaggedVlan: '1',
      inDiscard: '0',
      broadcastIn: '41245582',
      broadcastOut: '99824',
      multicastIn: '85876848',
      multicastOut: '645277',
      poeType: 'n/a',
      switchMac: 'c0:c5:20:aa:35:d9',
      id: 'c0-c5-20-aa-35-d9_1-1-1',
      neighborName: '11F_LAB_R3_UP_10.206.11.2',
      venueId: 'bde45788c8b34706b4c6507f73001540',
      ingressAclName: '',
      egressAclName: '',
      vsixIngressAclName: '',
      vsixEgressAclName: '',
      lagName: '',
      switchName: 'B-ICX7150-C12 Router',
      switchSerial: 'c0:c5:20:aa:35:d9',
      lagId: '0',
      deviceStatus: 'ONLINE',
      unitStatus: 'Standalone',
      unitState: 'ONLINE',
      switchModel: 'ICX7150-C12P',
      neighborMacAddress: 'E8:F7:24:0F:65:40',
      syncedSwitchConfig: true,
      mediaType: 'MEDIA_TYPE_EMPTY',
      poeUsage: '0/0W (0%)',
      errorDisableStatus: '',
      stickyMacAclAllowCount: 0,
      isPoeSupported: 'true',
      lagForceUpPort: false
    },
    {
      cloudPort: false,
      stack: false,
      name: 'GigabitEthernet1/1/2',
      portId: 'c0-c5-20-aa-35-d9_1-1-2',
      status: 'Down',
      adminStatus: 'Down',
      vlanIds: '1',
      portSpeed: 'link down or no traffic',
      poeUsed: 0,
      poeTotal: 0,
      signalIn: 0,
      signalOut: 0,
      crcErr: '0',
      inErr: '0',
      outErr: '0',
      opticsType: '1 Gbits per second copper',
      switchUnitId: 'FEK3224R0AN',
      poeEnabled: true,
      usedInFormingStack: false,
      portIdentifier: '1/1/2',
      unTaggedVlan: '1',
      inDiscard: '0',
      broadcastIn: '0',
      broadcastOut: '0',
      multicastIn: '0',
      multicastOut: '0',
      poeType: 'n/a',
      switchMac: 'c0:c5:20:aa:35:d9',
      id: 'c0-c5-20-aa-35-d9_1-1-2',
      neighborName: '',
      venueId: 'bde45788c8b34706b4c6507f73001540',
      tags: '',
      ingressAclName: '',
      egressAclName: '',
      vsixIngressAclName: '',
      vsixEgressAclName: '',
      lagName: '',
      switchName: 'B-ICX7150-C12 Router',
      switchSerial: 'c0:c5:20:aa:35:d9',
      lagId: '0',
      deviceStatus: 'ONLINE',
      unitStatus: 'Standalone',
      unitState: 'ONLINE',
      switchModel: 'ICX7150-C12P',
      neighborMacAddress: '',
      syncedSwitchConfig: true,
      mediaType: 'MEDIA_TYPE_EMPTY',
      poeUsage: '0/0W (0%)',
      authDefaultVlan: '',
      errorDisableStatus: '',
      stickyMacAclAllowCount: 0,
      isPoeSupported: 'true',
      lagForceUpPort: false
    },
    {
      cloudPort: false,
      stack: false,
      name: 'test',
      portId: 'c0-c5-20-aa-35-d9_1-1-3',
      status: 'Down',
      adminStatus: 'Up',
      vlanIds: '10',
      portSpeed: 'link down or no traffic',
      poeUsed: 0,
      poeTotal: 0,
      signalIn: 0,
      signalOut: 0,
      crcErr: '0',
      inErr: '0',
      outErr: '0',
      opticsType: '1 Gbits per second copper',
      switchUnitId: 'FEK3224R0AN',
      poeEnabled: true,
      usedInFormingStack: false,
      portIdentifier: '1/1/3',
      unTaggedVlan: '',
      inDiscard: '0',
      broadcastIn: '0',
      broadcastOut: '0',
      multicastIn: '0',
      multicastOut: '0',
      poeType: 'n/a',
      switchMac: 'c0:c5:20:aa:35:d9',
      id: 'c0-c5-20-aa-35-d9_1-1-3',
      neighborName: '',
      venueId: 'bde45788c8b34706b4c6507f73001540',
      tags: '',
      ingressAclName: '',
      egressAclName: '',
      vsixIngressAclName: '',
      vsixEgressAclName: '',
      lagName: '',
      switchName: 'B-ICX7150-C12 Router',
      switchSerial: 'c0:c5:20:aa:35:d9',
      lagId: '0',
      deviceStatus: 'ONLINE',
      unitStatus: 'Standalone',
      unitState: 'ONLINE',
      switchModel: 'ICX7150-C12P',
      neighborMacAddress: '',
      syncedSwitchConfig: true,
      mediaType: 'MEDIA_TYPE_EMPTY',
      poeUsage: '0/0W (0%)',
      authDefaultVlan: '10',
      errorDisableStatus: '',
      stickyMacAclAllowCount: 0,
      isPoeSupported: 'true',
      lagForceUpPort: false
    },
    {
      cloudPort: false,
      stack: false,
      name: 'GigabitEthernet1/1/4',
      portId: 'c0-c5-20-aa-35-d9_1-1-4',
      status: 'Down',
      adminStatus: 'Down',
      vlanIds: '19 10 9',
      portSpeed: 'link down or no traffic',
      poeUsed: 0,
      poeTotal: 0,
      signalIn: 0,
      signalOut: 0,
      crcErr: '0',
      inErr: '0',
      outErr: '0',
      opticsType: '1 Gbits per second copper',
      switchUnitId: 'FEK3224R0AN',
      poeEnabled: true,
      usedInFormingStack: false,
      portIdentifier: '1/1/4',
      unTaggedVlan: '',
      inDiscard: '0',
      broadcastIn: '0',
      broadcastOut: '0',
      multicastIn: '0',
      multicastOut: '0',
      poeType: 'n/a',
      switchMac: 'c0:c5:20:aa:35:d9',
      id: 'c0-c5-20-aa-35-d9_1-1-4',
      neighborName: '',
      venueId: 'bde45788c8b34706b4c6507f73001540',
      tags: '',
      ingressAclName: '',
      egressAclName: '',
      vsixIngressAclName: '',
      vsixEgressAclName: '',
      lagName: '',
      switchName: 'B-ICX7150-C12 Router',
      switchSerial: 'c0:c5:20:aa:35:d9',
      lagId: '0',
      deviceStatus: 'ONLINE',
      unitStatus: 'Standalone',
      unitState: 'ONLINE',
      switchModel: 'ICX7150-C12P',
      neighborMacAddress: '',
      syncedSwitchConfig: true,
      mediaType: 'MEDIA_TYPE_EMPTY',
      poeUsage: '0/0W (0%)',
      authDefaultVlan: '10',
      errorDisableStatus: '',
      stickyMacAclAllowCount: 0,
      isPoeSupported: 'true',
      lagForceUpPort: false
    },
    {
      cloudPort: false,
      stack: false,
      name: 'GigabitEthernet1/1/5',
      portId: 'c0-c5-20-aa-35-d9_1-1-5',
      status: 'Down',
      adminStatus: 'Up',
      vlanIds: '10 5',
      portSpeed: 'link down or no traffic',
      poeUsed: 0,
      poeTotal: 0,
      signalIn: 0,
      signalOut: 0,
      crcErr: '0',
      inErr: '0',
      outErr: '0',
      opticsType: '1 Gbits per second copper',
      switchUnitId: 'FEK3224R0AN',
      poeEnabled: true,
      usedInFormingStack: false,
      portIdentifier: '1/1/5',
      unTaggedVlan: '',
      inDiscard: '0',
      broadcastIn: '0',
      broadcastOut: '0',
      multicastIn: '0',
      multicastOut: '0',
      poeType: 'n/a',
      switchMac: 'c0:c5:20:aa:35:d9',
      id: 'c0-c5-20-aa-35-d9_1-1-5',
      neighborName: '',
      venueId: 'bde45788c8b34706b4c6507f73001540',
      tags: '',
      ingressAclName: '',
      egressAclName: '',
      vsixIngressAclName: '',
      vsixEgressAclName: '',
      lagName: '',
      switchName: 'B-ICX7150-C12 Router',
      switchSerial: 'c0:c5:20:aa:35:d9',
      lagId: '0',
      deviceStatus: 'ONLINE',
      unitStatus: 'Standalone',
      unitState: 'ONLINE',
      switchModel: 'ICX7150-C12P',
      neighborMacAddress: '',
      syncedSwitchConfig: true,
      mediaType: 'MEDIA_TYPE_EMPTY',
      poeUsage: '0/0W (0%)',
      authDefaultVlan: '10',
      errorDisableStatus: '',
      stickyMacAclAllowCount: 0,
      isPoeSupported: 'true',
      lagForceUpPort: false
    },
    {
      cloudPort: false,
      stack: false,
      name: 'GigabitEthernet1/1/6',
      portId: 'c0-c5-20-aa-35-d9_1-1-6',
      status: 'Down',
      adminStatus: 'Up',
      vlanIds: '10',
      portSpeed: 'link down or no traffic',
      poeUsed: 0,
      poeTotal: 0,
      signalIn: 0,
      signalOut: 0,
      crcErr: '0',
      inErr: '0',
      outErr: '0',
      opticsType: '1 Gbits per second copper',
      switchUnitId: 'FEK3224R0AN',
      poeEnabled: true,
      usedInFormingStack: false,
      portIdentifier: '1/1/6',
      unTaggedVlan: '',
      inDiscard: '0',
      broadcastIn: '0',
      broadcastOut: '0',
      multicastIn: '0',
      multicastOut: '0',
      poeType: 'n/a',
      switchMac: 'c0:c5:20:aa:35:d9',
      id: 'c0-c5-20-aa-35-d9_1-1-6',
      neighborName: '',
      venueId: 'bde45788c8b34706b4c6507f73001540',
      tags: '',
      ingressAclName: '',
      egressAclName: '',
      vsixIngressAclName: '',
      vsixEgressAclName: '',
      lagName: '',
      switchName: 'B-ICX7150-C12 Router',
      switchSerial: 'c0:c5:20:aa:35:d9',
      lagId: '0',
      deviceStatus: 'ONLINE',
      unitStatus: 'Standalone',
      unitState: 'ONLINE',
      switchModel: 'ICX7150-C12P',
      neighborMacAddress: '',
      syncedSwitchConfig: true,
      mediaType: 'MEDIA_TYPE_EMPTY',
      poeUsage: '0/0W (0%)',
      authDefaultVlan: '10',
      errorDisableStatus: '',
      stickyMacAclAllowCount: 0,
      isPoeSupported: 'true',
      lagForceUpPort: false
    },
    {
      cloudPort: false,
      stack: false,
      name: 'GigabitEthernet1/1/7',
      portId: 'c0-c5-20-aa-35-d9_1-1-7',
      status: 'Down',
      adminStatus: 'Up',
      vlanIds: '5',
      portSpeed: 'link down or no traffic',
      poeUsed: 0,
      poeTotal: 0,
      signalIn: 0,
      signalOut: 0,
      crcErr: '0',
      inErr: '0',
      outErr: '0',
      opticsType: '1 Gbits per second copper',
      switchUnitId: 'FEK3224R0AN',
      poeEnabled: true,
      usedInFormingStack: false,
      portIdentifier: '1/1/7',
      unTaggedVlan: '',
      inDiscard: '0',
      broadcastIn: '0',
      broadcastOut: '0',
      multicastIn: '0',
      multicastOut: '0',
      poeType: 'n/a',
      switchMac: 'c0:c5:20:aa:35:d9',
      id: 'c0-c5-20-aa-35-d9_1-1-7',
      neighborName: '',
      venueId: 'bde45788c8b34706b4c6507f73001540',
      tags: '',
      ingressAclName: '',
      egressAclName: '',
      vsixIngressAclName: '',
      vsixEgressAclName: '',
      lagName: '',
      switchName: 'B-ICX7150-C12 Router',
      switchSerial: 'c0:c5:20:aa:35:d9',
      lagId: '0',
      deviceStatus: 'ONLINE',
      unitStatus: 'Standalone',
      unitState: 'ONLINE',
      switchModel: 'ICX7150-C12P',
      neighborMacAddress: '',
      syncedSwitchConfig: true,
      mediaType: 'MEDIA_TYPE_EMPTY',
      poeUsage: '0/0W (0%)',
      authDefaultVlan: '10',
      errorDisableStatus: '',
      stickyMacAclAllowCount: 0,
      isPoeSupported: 'true',
      lagForceUpPort: false
    },
    {
      cloudPort: false,
      stack: false,
      name: 'GigabitEthernet1/1/8',
      portId: 'c0-c5-20-aa-35-d9_1-1-8',
      status: 'Down',
      adminStatus: 'Up',
      vlanIds: '1',
      portSpeed: 'link down or no traffic',
      poeUsed: 0,
      poeTotal: 0,
      signalIn: 0,
      signalOut: 0,
      crcErr: '0',
      inErr: '0',
      outErr: '0',
      opticsType: '1 Gbits per second copper',
      switchUnitId: 'FEK3224R0AN',
      poeEnabled: true,
      usedInFormingStack: false,
      portIdentifier: '1/1/8',
      unTaggedVlan: '1',
      inDiscard: '0',
      broadcastIn: '0',
      broadcastOut: '0',
      multicastIn: '0',
      multicastOut: '0',
      poeType: 'n/a',
      switchMac: 'c0:c5:20:aa:35:d9',
      id: 'c0-c5-20-aa-35-d9_1-1-8',
      neighborName: '',
      venueId: 'bde45788c8b34706b4c6507f73001540',
      tags: '',
      ingressAclName: '',
      egressAclName: '',
      vsixIngressAclName: '',
      vsixEgressAclName: '',
      lagName: '',
      switchName: 'B-ICX7150-C12 Router',
      switchSerial: 'c0:c5:20:aa:35:d9',
      lagId: '0',
      deviceStatus: 'ONLINE',
      unitStatus: 'Standalone',
      unitState: 'ONLINE',
      switchModel: 'ICX7150-C12P',
      neighborMacAddress: '',
      syncedSwitchConfig: true,
      mediaType: 'MEDIA_TYPE_EMPTY',
      poeUsage: '0/0W (0%)',
      authDefaultVlan: '33',
      errorDisableStatus: '',
      stickyMacAclAllowCount: 0,
      isPoeSupported: 'true',
      lagForceUpPort: false
    },
    {
      cloudPort: false,
      stack: false,
      name: 'GigabitEthernet1/1/9',
      portId: 'c0-c5-20-aa-35-d9_1-1-9',
      status: 'Down',
      adminStatus: 'Up',
      vlanIds: '4',
      portSpeed: 'link down or no traffic',
      poeUsed: 0,
      poeTotal: 0,
      signalIn: 0,
      signalOut: 0,
      crcErr: '0',
      inErr: '0',
      outErr: '0',
      opticsType: '1 Gbits per second copper',
      switchUnitId: 'FEK3224R0AN',
      poeEnabled: true,
      usedInFormingStack: false,
      portIdentifier: '1/1/9',
      unTaggedVlan: '4',
      inDiscard: '0',
      broadcastIn: '0',
      broadcastOut: '0',
      multicastIn: '0',
      multicastOut: '0',
      poeType: 'n/a',
      switchMac: 'c0:c5:20:aa:35:d9',
      id: 'c0-c5-20-aa-35-d9_1-1-9',
      neighborName: '',
      venueId: 'bde45788c8b34706b4c6507f73001540',
      tags: '',
      ingressAclName: '',
      egressAclName: '',
      vsixIngressAclName: '',
      vsixEgressAclName: '',
      lagName: '',
      switchName: 'B-ICX7150-C12 Router',
      switchSerial: 'c0:c5:20:aa:35:d9',
      lagId: '0',
      deviceStatus: 'ONLINE',
      unitStatus: 'Standalone',
      unitState: 'ONLINE',
      switchModel: 'ICX7150-C12P',
      neighborMacAddress: '',
      syncedSwitchConfig: true,
      mediaType: 'MEDIA_TYPE_EMPTY',
      poeUsage: '0/0W (0%)',
      authDefaultVlan: '33',
      errorDisableStatus: '',
      stickyMacAclAllowCount: 0,
      isPoeSupported: 'true',
      lagForceUpPort: false
    },
    {
      cloudPort: false,
      stack: false,
      name: 'GigabitEthernet1/1/10',
      portId: 'c0-c5-20-aa-35-d9_1-1-10',
      status: 'Down',
      adminStatus: 'Up',
      vlanIds: '7',
      portSpeed: 'link down or no traffic',
      poeUsed: 0,
      poeTotal: 0,
      signalIn: 0,
      signalOut: 0,
      crcErr: '0',
      inErr: '0',
      outErr: '0',
      opticsType: '1 Gbits per second copper',
      switchUnitId: 'FEK3224R0AN',
      poeEnabled: true,
      usedInFormingStack: false,
      portIdentifier: '1/1/10',
      unTaggedVlan: '7',
      inDiscard: '0',
      broadcastIn: '0',
      broadcastOut: '0',
      multicastIn: '0',
      multicastOut: '0',
      poeType: 'n/a',
      switchMac: 'c0:c5:20:aa:35:d9',
      id: 'c0-c5-20-aa-35-d9_1-1-10',
      neighborName: '',
      venueId: 'bde45788c8b34706b4c6507f73001540',
      tags: '',
      ingressAclName: '',
      egressAclName: '',
      vsixIngressAclName: '',
      vsixEgressAclName: '',
      lagName: '',
      switchName: 'B-ICX7150-C12 Router',
      switchSerial: 'c0:c5:20:aa:35:d9',
      lagId: '0',
      deviceStatus: 'ONLINE',
      unitStatus: 'Standalone',
      unitState: 'ONLINE',
      switchModel: 'ICX7150-C12P',
      neighborMacAddress: '',
      syncedSwitchConfig: true,
      mediaType: 'MEDIA_TYPE_EMPTY',
      poeUsage: '0/0W (0%)',
      errorDisableStatus: '',
      stickyMacAclAllowCount: 0,
      isPoeSupported: 'true',
      lagForceUpPort: false
    },
    {
      cloudPort: false,
      stack: false,
      name: 'test11-12',
      portId: 'c0-c5-20-aa-35-d9_1-1-11',
      status: 'Down',
      adminStatus: 'Up',
      vlanIds: '1',
      portSpeed: 'link down or no traffic',
      poeUsed: 0,
      poeTotal: 0,
      signalIn: 0,
      signalOut: 0,
      crcErr: '0',
      inErr: '0',
      outErr: '0',
      opticsType: '1 Gbits per second copper',
      switchUnitId: 'FEK3224R0AN',
      poeEnabled: true,
      usedInFormingStack: false,
      portIdentifier: '1/1/11',
      unTaggedVlan: '1',
      inDiscard: '0',
      broadcastIn: '0',
      broadcastOut: '0',
      multicastIn: '0',
      multicastOut: '0',
      poeType: 'n/a',
      switchMac: 'c0:c5:20:aa:35:d9',
      id: 'c0-c5-20-aa-35-d9_1-1-11',
      neighborName: '',
      venueId: 'bde45788c8b34706b4c6507f73001540',
      tags: '',
      ingressAclName: '',
      egressAclName: '',
      vsixIngressAclName: '',
      vsixEgressAclName: '',
      lagName: '',
      switchName: 'B-ICX7150-C12 Router',
      switchSerial: 'c0:c5:20:aa:35:d9',
      lagId: '0',
      deviceStatus: 'ONLINE',
      unitStatus: 'Standalone',
      unitState: 'ONLINE',
      switchModel: 'ICX7150-C12P',
      neighborMacAddress: '',
      syncedSwitchConfig: true,
      mediaType: 'MEDIA_TYPE_EMPTY',
      poeUsage: '0/0W (0%)',
      errorDisableStatus: '',
      stickyMacAclAllowCount: 0,
      isPoeSupported: 'true',
      lagForceUpPort: false
    },
    {
      cloudPort: false,
      stack: false,
      name: 'test11-12',
      portId: 'c0-c5-20-aa-35-d9_1-1-12',
      status: 'Down',
      adminStatus: 'Down',
      vlanIds: '1',
      portSpeed: 'link down or no traffic',
      poeUsed: 0,
      poeTotal: 0,
      signalIn: 0,
      signalOut: 0,
      crcErr: '0',
      inErr: '0',
      outErr: '0',
      opticsType: '1 Gbits per second copper',
      switchUnitId: 'FEK3224R0AN',
      poeEnabled: true,
      usedInFormingStack: false,
      portIdentifier: '1/1/12',
      unTaggedVlan: '1',
      inDiscard: '0',
      broadcastIn: '0',
      broadcastOut: '0',
      multicastIn: '0',
      multicastOut: '0',
      poeType: 'n/a',
      switchMac: 'c0:c5:20:aa:35:d9',
      id: 'c0-c5-20-aa-35-d9_1-1-12',
      neighborName: '',
      venueId: 'bde45788c8b34706b4c6507f73001540',
      tags: '',
      ingressAclName: '',
      egressAclName: '',
      vsixIngressAclName: '',
      vsixEgressAclName: '',
      lagName: '',
      switchName: 'B-ICX7150-C12 Router',
      switchSerial: 'c0:c5:20:aa:35:d9',
      lagId: '0',
      deviceStatus: 'ONLINE',
      unitStatus: 'Standalone',
      unitState: 'ONLINE',
      switchModel: 'ICX7150-C12P',
      neighborMacAddress: '',
      syncedSwitchConfig: true,
      mediaType: 'MEDIA_TYPE_EMPTY',
      poeUsage: '0/0W (0%)',
      errorDisableStatus: '',
      stickyMacAclAllowCount: 0,
      isPoeSupported: 'true',
      lagForceUpPort: false
    },
    {
      cloudPort: false,
      stack: false,
      name: 'GigabitEthernet1/2/1',
      portId: 'c0-c5-20-aa-35-d9_1-2-1',
      status: 'Down',
      adminStatus: 'Up',
      vlanIds: '10',
      portSpeed: 'link down or no traffic',
      poeUsed: 0,
      poeTotal: 0,
      signalIn: 0,
      signalOut: 0,
      crcErr: '0',
      inErr: '0',
      outErr: '0',
      opticsType: '1 Gbits per second copper',
      switchUnitId: 'FEK3224R0AN',
      poeEnabled: false,
      usedInFormingStack: false,
      portIdentifier: '1/2/1',
      unTaggedVlan: '',
      inDiscard: '0',
      broadcastIn: '0',
      broadcastOut: '0',
      multicastIn: '0',
      multicastOut: '0',
      poeType: '',
      switchMac: 'c0:c5:20:aa:35:d9',
      id: 'c0-c5-20-aa-35-d9_1-2-1',
      neighborName: '',
      venueId: 'bde45788c8b34706b4c6507f73001540',
      tags: '',
      ingressAclName: '',
      egressAclName: '',
      vsixIngressAclName: '',
      vsixEgressAclName: '',
      lagName: '',
      switchName: 'B-ICX7150-C12 Router',
      switchSerial: 'c0:c5:20:aa:35:d9',
      lagId: '0',
      deviceStatus: 'ONLINE',
      unitStatus: 'Standalone',
      unitState: 'ONLINE',
      switchModel: 'ICX7150-C12P',
      neighborMacAddress: '',
      syncedSwitchConfig: true,
      mediaType: 'MEDIA_TYPE_EMPTY',
      poeUsage: 'off',
      authDefaultVlan: '10',
      errorDisableStatus: '',
      stickyMacAclAllowCount: 0,
      isPoeSupported: 'false',
      lagForceUpPort: false
    },
    {
      cloudPort: false,
      stack: false,
      name: 'GigabitEthernet1/2/2',
      portId: 'c0-c5-20-aa-35-d9_1-2-2',
      status: 'Down',
      adminStatus: 'Up',
      vlanIds: '1',
      portSpeed: 'link down or no traffic',
      poeUsed: 0,
      poeTotal: 0,
      signalIn: 0,
      signalOut: 0,
      crcErr: '0',
      inErr: '0',
      outErr: '0',
      opticsType: '1 Gbits per second copper',
      switchUnitId: 'FEK3224R0AN',
      poeEnabled: false,
      usedInFormingStack: false,
      portIdentifier: '1/2/2',
      unTaggedVlan: '1',
      inDiscard: '0',
      broadcastIn: '0',
      broadcastOut: '0',
      multicastIn: '0',
      multicastOut: '0',
      poeType: '',
      switchMac: 'c0:c5:20:aa:35:d9',
      id: 'c0-c5-20-aa-35-d9_1-2-2',
      neighborName: '',
      venueId: 'bde45788c8b34706b4c6507f73001540',
      ingressAclName: '',
      egressAclName: '',
      vsixIngressAclName: '',
      vsixEgressAclName: '',
      lagName: '',
      switchName: 'B-ICX7150-C12 Router',
      switchSerial: 'c0:c5:20:aa:35:d9',
      lagId: '0',
      deviceStatus: 'ONLINE',
      unitStatus: 'Standalone',
      unitState: 'ONLINE',
      switchModel: 'ICX7150-C12P',
      neighborMacAddress: '',
      syncedSwitchConfig: true,
      mediaType: 'MEDIA_TYPE_EMPTY',
      poeUsage: 'off',
      errorDisableStatus: '',
      stickyMacAclAllowCount: 0,
      isPoeSupported: 'false',
      lagForceUpPort: false
    },
    {
      cloudPort: false,
      stack: false,
      name: '10GigabitEthernet1/3/1',
      portId: 'c0-c5-20-aa-35-d9_1-3-1',
      status: 'Up',
      adminStatus: 'Up',
      vlanIds: '1',
      portSpeed: '10 Gb/sec',
      poeUsed: 0,
      poeTotal: 0,
      signalIn: 0,
      signalOut: 0,
      crcErr: '0',
      inErr: '0',
      outErr: '0',
      opticsType: '10 Gbits per second fiber',
      switchUnitId: 'FEK3224R0AN',
      poeEnabled: false,
      usedInFormingStack: true,
      portIdentifier: '1/3/1',
      unTaggedVlan: '1',
      inDiscard: '0',
      broadcastIn: '41342314',
      broadcastOut: '0',
      multicastIn: '85553750',
      multicastOut: '645249',
      poeType: '',
      switchMac: 'c0:c5:20:aa:35:d9',
      id: 'c0-c5-20-aa-35-d9_1-3-1',
      neighborName: 'ICX7150-C12 Router',
      venueId: 'bde45788c8b34706b4c6507f73001540',
      tags: '',
      ingressAclName: '',
      egressAclName: '',
      vsixIngressAclName: '',
      vsixEgressAclName: '',
      lagName: '',
      switchName: 'B-ICX7150-C12 Router',
      switchSerial: 'c0:c5:20:aa:35:d9',
      lagId: '0',
      deviceStatus: 'ONLINE',
      unitStatus: 'Standalone',
      unitState: 'ONLINE',
      switchModel: 'ICX7150-C12P',
      neighborMacAddress: '58:FB:96:0E:BC:F8',
      syncedSwitchConfig: true,
      mediaType: 'MEDIA_TYPE_OTHER',
      poeUsage: 'off',
      authDefaultVlan: '20',
      errorDisableStatus: '',
      stickyMacAclAllowCount: 0,
      stackingNeighborPort: '',
      isPoeSupported: 'false',
      lagForceUpPort: false
    },
    {
      cloudPort: false,
      stack: false,
      name: '10GigabitEthernet1/3/2',
      portId: 'c0-c5-20-aa-35-d9_1-3-2',
      status: 'Down',
      adminStatus: 'Up',
      vlanIds: '1',
      portSpeed: 'link down or no traffic',
      poeUsed: 0,
      poeTotal: 0,
      signalIn: 0,
      signalOut: 0,
      crcErr: '0',
      inErr: '0',
      outErr: '0',
      opticsType: '10 Gbits per second fiber',
      switchUnitId: 'FEK3224R0AN',
      poeEnabled: false,
      usedInFormingStack: true,
      portIdentifier: '1/3/2',
      unTaggedVlan: '1',
      inDiscard: '0',
      broadcastIn: '0',
      broadcastOut: '0',
      multicastIn: '0',
      multicastOut: '0',
      poeType: '',
      switchMac: 'c0:c5:20:aa:35:d9',
      id: 'c0-c5-20-aa-35-d9_1-3-2',
      neighborName: '',
      venueId: 'bde45788c8b34706b4c6507f73001540',
      tags: '',
      ingressAclName: '',
      egressAclName: '',
      vsixIngressAclName: '',
      vsixEgressAclName: '',
      lagName: '',
      switchName: 'B-ICX7150-C12 Router',
      switchSerial: 'c0:c5:20:aa:35:d9',
      lagId: '0',
      deviceStatus: 'ONLINE',
      unitStatus: 'Standalone',
      unitState: 'ONLINE',
      switchModel: 'ICX7150-C12P',
      neighborMacAddress: '',
      syncedSwitchConfig: true,
      mediaType: 'MEDIA_TYPE_EMPTY',
      poeUsage: 'off',
      errorDisableStatus: '',
      stickyMacAclAllowCount: 0,
      stackingNeighborPort: '',
      isPoeSupported: 'false',
      lagForceUpPort: false
    }
  ]
}