export * from './commonUrls'
export * from './venueUrls'
export * from './servicesUrls'
export * from './policiesUrls'
export * from './switchUrls'
export * from './apGroupUrls'
export * from './cloneUrls'
export * from './edgeUrls'