import { useState } from 'react'

import {
  Form,
  FormInstance,
  Input,
  InputNumber,
  Radio,
  RadioChangeEvent,
  Space
} from 'antd'
import { FormattedMessage, useIntl } from 'react-intl'

import { Tooltip }                    from '@acx-ui/components'
import { QuestionMarkCircleOutlined } from '@acx-ui/icons'
import { ExpirationDateSelector }     from '@acx-ui/rc/components'
import {
  CreateDpskPassphrasesFormFields,
  ExpirationMode
} from '@acx-ui/rc/utils'

import * as UI from './styledComponents'

enum DeviceNumberType {
  LIMITED,
  UNLIMITED
}

export interface AddDpskPassphrasesFormProps {
  form: FormInstance<CreateDpskPassphrasesFormFields>
}

export default function AddDpskPassphrasesForm (props: AddDpskPassphrasesFormProps) {
  const { $t } = useIntl()
  const { form } = props
  const numberOfDevices = Form.useWatch('numberOfDevices', form)
  const [ deviceNumberType, setDeviceNumberType ] = useState(DeviceNumberType.LIMITED)

  const onDeviceNumberTypeChange = (e: RadioChangeEvent) => {
    setDeviceNumberType(e.target.value)
  }

  return (
    <Form layout='vertical'
      form={form}
    >
      <Form.Item
        label={$t({ defaultMessage: 'Number of Passphrases' })}
        name='numberOfPassphrases'
        rules={[
          { required: true }
        ]}
        children={<InputNumber min={1} />}
      />
      <Form.Item
        label={
          <>
            { $t({ defaultMessage: 'Number of Devices Per Passphrase' }) }
            <Tooltip
              placement='bottom'
              title={<FormattedMessage
                // eslint-disable-next-line max-len
                defaultMessage={'When enabled, multiple devices will be able to use this passphrase'}
              />}
            >
              <QuestionMarkCircleOutlined />
            </Tooltip>
          </>
        }
        children={
          <Radio.Group defaultValue={deviceNumberType} onChange={onDeviceNumberTypeChange}>
            <Space size={'middle'} direction='vertical'>
              <UI.FieldSpace>
                <Radio value={DeviceNumberType.LIMITED}>
                  {$t({ defaultMessage: 'Set number' })}
                </Radio>
                {deviceNumberType === DeviceNumberType.LIMITED &&
                  <Form.Item
                    name='numberOfDevices'
                    rules={[
                      {
                        required: true,
                        message: $t({ defaultMessage: 'Please enter Number of Passphrases' })
                      }
                    ]}
                    children={<InputNumber min={1} />}
                  />
                }
              </UI.FieldSpace>
              <Radio value={DeviceNumberType.UNLIMITED}>
                {$t({ defaultMessage: 'Unlimited' })}
              </Radio>
            </Space>
          </Radio.Group>
        }
      />
      <Form.Item
        label={
          <>
            { $t({ defaultMessage: 'Passphrase' }) }
            <Tooltip
              placement='bottom'
              title={<FormattedMessage
                // eslint-disable-next-line max-len
                defaultMessage={'If empty, passphrase will be generated by the system. Valid range 8-63'}
              />}
            >
              <QuestionMarkCircleOutlined />
            </Tooltip>
          </>
        }
        name='passphrase'
        rules={[
          { min: 8 },
          { max: 63 }
        ]}
        children={<Input.Password />}
      />
      <Form.Item
        label={
          <>
            { $t({ defaultMessage: 'User Name' }) }
            <Tooltip
              placement='bottom'
              title={<FormattedMessage
                // eslint-disable-next-line max-len
                defaultMessage={'The name will be displayed in the DPSK User Table, to help associating devices with names'}
              />}
            >
              <QuestionMarkCircleOutlined />
            </Tooltip>
          </>
        }
        name='username'
        children={<Input />}
      />
      {numberOfDevices === 1 &&
        <Form.Item
          label={
            <>
              { $t({ defaultMessage: 'MAC Address' }) }
              <Tooltip
                placement='bottom'
                title={<FormattedMessage
                  defaultMessage={`
                    Only the device with this MAC address will be allowed into the WiFi network
                    with that passphrase. Leave blank to allow the first device using the
                    passphrase to bond to it
                  `}
                />}
              >
                <QuestionMarkCircleOutlined />
              </Tooltip>
            </>
          }
          name='mac'
          children={<Input />}
        />
      }
      <Form.Item
        label={
          <>
            { $t({ defaultMessage: 'VLAN ID' }) }
            <Tooltip
              placement='bottom'
              title={<FormattedMessage
                defaultMessage={`
                  The device will be placed on this VLAN after authenticating to
                  the WiFi network. If empty, the network's default will be used
                `}
              />}
            >
              <QuestionMarkCircleOutlined />
            </Tooltip>
          </>
        }
        name='vlanId'
        children={
          <Input
            placeholder={$t({ defaultMessage: 'If empty, the network\'s default will be used' })}
          />
        }
      />
      <ExpirationDateSelector
        inputName={'expiration'}
        label={$t({ defaultMessage: 'Passphrase Expiration' })}
        modeLabel={{
          [ExpirationMode.NEVER]: $t({ defaultMessage: 'Same as pool' })
        }}
        modeAvailability={{
          [ExpirationMode.AFTER_TIME]: false
        }}
      />
    </Form>
  )
}
