import { useState } from 'react'

import {
  Form,
  FormInstance,
  Input,
  InputNumber,
  Radio,
  RadioChangeEvent,
  Space
} from 'antd'
import { FormattedMessage, useIntl } from 'react-intl'

import { Tooltip }                from '@acx-ui/components'
import { ExpirationDateSelector } from '@acx-ui/rc/components'
import {
  CreateDpskPassphrasesFormFields,
  ExpirationMode
} from '@acx-ui/rc/utils'
import { validationMessages } from '@acx-ui/utils'

import { unlimitedNumberOfDeviceLabel } from './contentsMap'
import * as UI                          from './styledComponents'

const MAX_PASSPHRASES = 5000
const MAX_DEVICES_PER_PASSPHRASE = 50

enum DeviceNumberType {
  LIMITED,
  UNLIMITED
}

export interface AddDpskPassphrasesFormProps {
  form: FormInstance<CreateDpskPassphrasesFormFields>
}

export default function AddDpskPassphrasesForm (props: AddDpskPassphrasesFormProps) {
  const { $t } = useIntl()
  const { form } = props
  const numberOfDevices = Form.useWatch('numberOfDevices', form)
  const numberOfPassphrases = Form.useWatch('numberOfPassphrases', form)
  const [ deviceNumberType, setDeviceNumberType ] = useState(DeviceNumberType.LIMITED)

  const onDeviceNumberTypeChange = (e: RadioChangeEvent) => {
    setDeviceNumberType(e.target.value)
  }

  const isMacAddressEnabled = () => {
    return numberOfDevices === 1 && numberOfPassphrases === 1
  }

  const isPassphraseEnabled = () => {
    return numberOfPassphrases === 1
  }

  return (
    <Form layout='vertical'
      form={form}
    >
      <Form.Item
        label={$t({
          defaultMessage: 'Number of Passphrases (Up to {maximum} passphrases)'
        }, {
          maximum: MAX_PASSPHRASES
        })}
        name='numberOfPassphrases'
        initialValue={1}
        rules={[
          { required: true },
          {
            type: 'number',
            min: 1,
            max: MAX_PASSPHRASES,
            // eslint-disable-next-line max-len
            message: $t({ defaultMessage: 'Number of Passphrases must be between 1 and {max}' }, { max: MAX_PASSPHRASES })
          }
        ]}
        children={<InputNumber />}
      />
      <Form.Item
        label={
          <>
            { $t({ defaultMessage: 'Number of Devices Per Passphrase' }) }
            <Tooltip.Question
              placement='bottom'
              title={<FormattedMessage
                // eslint-disable-next-line max-len
                defaultMessage={'When enabled, multiple devices will be able to use this passphrase'}
              />}
            />
          </>
        }
        children={
          <Radio.Group defaultValue={deviceNumberType} onChange={onDeviceNumberTypeChange}>
            <Space size={'middle'} direction='vertical'>
              <UI.FieldSpace>
                <Radio value={DeviceNumberType.LIMITED}>
                  {$t(
                    { defaultMessage: 'Set number (1-{max})' },
                    { max: MAX_DEVICES_PER_PASSPHRASE }
                  )}
                </Radio>
                {deviceNumberType === DeviceNumberType.LIMITED &&
                  <Form.Item
                    name='numberOfDevices'
                    initialValue={1}
                    rules={[
                      {
                        required: true,
                        // eslint-disable-next-line max-len
                        message: $t({ defaultMessage: 'Please enter Number of Devices Per Passphrase' })
                      },
                      {
                        type: 'number',
                        min: 1,
                        max: MAX_DEVICES_PER_PASSPHRASE,
                        message: $t(
                          // eslint-disable-next-line max-len
                          { defaultMessage: 'Number of Devices Per Passphrase must be between 1 and {max}' },
                          { max: MAX_DEVICES_PER_PASSPHRASE }
                        )
                      }
                    ]}
                    children={<InputNumber />}
                  />
                }
              </UI.FieldSpace>
              <Radio value={DeviceNumberType.UNLIMITED}>
                {$t(unlimitedNumberOfDeviceLabel)}
              </Radio>
            </Space>
          </Radio.Group>
        }
      />
      {isPassphraseEnabled() &&
        <Form.Item
          label={
            <>
              { $t({ defaultMessage: 'Passphrase' }) }
              <Tooltip.Question
                placement='bottom'
                title={<FormattedMessage
                  // eslint-disable-next-line max-len
                  defaultMessage={'If empty, passphrase will be generated by the system. Valid range 8-63'}
                />}
              />
            </>
          }
          name='passphrase'
          rules={[
            { min: 8 },
            { max: 63 }
          ]}
          children={<Input.Password />}
        />
      }
      <Form.Item
        label={
          <>
            { isPassphraseEnabled()
              ? $t({ defaultMessage: 'User Name' })
              : $t({ defaultMessage: 'User Name Prefix' })
            }
            <Tooltip.Question
              placement='bottom'
              title={<FormattedMessage
                // eslint-disable-next-line max-len
                defaultMessage={'The name will be displayed in the DPSK User Table, to help associating devices with names'}
              />}
            />
          </>
        }
        name='username'
        rules={[
          { max: 190 }
        ]}
        children={<Input />}
      />
      {isMacAddressEnabled() &&
        <Form.Item
          label={
            <>
              { $t({ defaultMessage: 'MAC Address' }) }
              <Tooltip.Question
                placement='bottom'
                title={<FormattedMessage
                  defaultMessage={`
                    Only the device with this MAC address will be allowed into the Wi-Fi network
                    with that passphrase. Leave blank to allow the first device using the
                    passphrase to bond to it
                  `}
                />}
              />
            </>
          }
          name='mac'
          children={<Input />}
        />
      }
      <Form.Item
        label={
          <>
            { $t({ defaultMessage: 'VLAN ID' }) }
            <Tooltip.Question
              placement='bottom'
              title={<FormattedMessage
                defaultMessage={`
                  The device will be placed on this VLAN after authenticating to
                  the Wi-Fi network. If empty, the network's default will be used
                `}
              />}
            />
          </>
        }
        rules={[
          {
            type: 'number',
            min: 1,
            max: 4094,
            message: $t(validationMessages.vlanRange)
          }
        ]}
        name='vlanId'
        children={
          <InputNumber
            placeholder={$t({ defaultMessage: 'If empty, the network\'s default will be used' })}
            style={{ width: '100%' }}
          />
        }
      />
      <ExpirationDateSelector
        inputName={'expiration'}
        label={$t({ defaultMessage: 'Passphrase Expiration' })}
        modeLabel={{
          [ExpirationMode.NEVER]: $t({ defaultMessage: 'Same as pool' })
        }}
        modeAvailability={{
          [ExpirationMode.AFTER_TIME]: false
        }}
      />
    </Form>
  )
}
