import { useState } from 'react'

import { Form }    from 'antd'
import { useIntl } from 'react-intl'

import {
  Drawer
} from '@acx-ui/components'

interface AuthAppProps {
  visible: boolean
  setVisible: (visible: boolean) => void
}

export const AuthApp = (props: AuthAppProps) => {
  const { $t } = useIntl()

  const { visible, setVisible } = props
  const [resetField, setResetField] = useState(false)
  const [form] = Form.useForm()

  const onClose = () => {
    setVisible(false)
    form.resetFields()
  }

  const resetFields = () => {
    setResetField(true)
    onClose()
  }

  const handleSave = () => {
    setVisible(false)
  }

  //   form.setFieldValue('result', recoveryCode)

  const content =
  <Form layout='vertical' form={form} onFinish={onClose}>
    <div/><label >
      { $t({ defaultMessage: 'To enable MFA using an authentication app, follow these steps:' }) }
    </label>
    <div style={{ marginTop: '13px' }}/><label >
      { $t({ defaultMessage: '1. Install an authentication app on your mobile' }) }
    </label>
    <div/><label style={{ marginLeft: '13px' }}>
      { $t({ defaultMessage: 'device' }) }
    </label>
    <div style={{ marginTop: '13px' }} /><label >
      { $t({ defaultMessage: '2. Open the app, then select "Add Account"' }) }
    </label>
    <div style={{ marginTop: '13px' }}/><label >
      { $t({ defaultMessage: '3. Scan the QR code below:' }) }
    </label>

    <div style={{ marginTop: '13px' }}/><label style={{ marginLeft: '13px' }}>
      { $t({ defaultMessage: 'Or enter this key into the app:' }) }
    </label>
    <div /><label style={{ marginLeft: '13px' }} >
      { $t({ defaultMessage: '9DRCEV435RXEG3FD' }) }
    </label>

    <div style={{ marginTop: '13px' }}/><label >
      { $t({ defaultMessage: '4. Enter the verification code generated by your' }) }
    </label>
    <div/><label style={{ marginLeft: '13px' }}>
      { $t({ defaultMessage: 'authentication app:' }) }
    </label>

  </Form>

  const footer = [
    <Drawer.FormFooter
      onCancel={resetFields}
      onSave={async () => handleSave()}
    />
  ]

  return (
    <Drawer
      title={$t({ defaultMessage: 'Manage Authentication App' })}
      visible={visible}
      onClose={onClose}
      children={content}
      footer={footer}
      destroyOnClose={resetField}
      width={'336'}
    />
  )
}
