import { useEffect, useState } from 'react'

import { Form, Input } from 'antd'
import { useIntl }     from 'react-intl'

import {
  Drawer
} from '@acx-ui/components'
import {
  useMfaRegisterPhoneMutation
} from '@acx-ui/rc/services'

interface AuthAppProps {
  visible: boolean
  setVisible: (visible: boolean) => void
  userId: string
}

export const AuthApp = (props: AuthAppProps) => {
  const { $t } = useIntl()

  const { visible, setVisible, userId } = props
  const [resetField, setResetField] = useState(false)
  const [form] = Form.useForm()

  // const { data } = useMfaRegisterPhoneMutation({ params: { userId: userId } })

  const key = 'ASFVZB7MCMYICUNR'
  const url =
  'https://chart.googleapis.com/chart?chs=200x200&chld=M%%7C0&cht=qr&chl=otpauth%3A%2F%2Ftotp%2FRUCKUSCloud%3Anull%3Fsecret%3DASFVZB7MCMYICUNR%26issuer%3DRUCKUSCloud'
  // useEffect(() => {
  //   if (data) {
  //     // setMfaStatus(data.enabled)
  //     // setRecoveryCode(data.recoveryCodes ? data.recoveryCodes : [])
  //   }
  // }, [data])

  const onClose = () => {
    setVisible(false)
    form.resetFields()
  }

  const resetFields = () => {
    setResetField(true)
    onClose()
  }

  const handleSave = () => {
    setVisible(false)
  }

  //   form.setFieldValue('result', recoveryCode)

  const content =
  <Form layout='vertical' form={form} onFinish={onClose}>
    <div/><label >
      { $t({ defaultMessage: 'To enable MFA using an authentication app, follow these steps:' }) }
    </label>
    <div style={{ marginTop: '13px' }}/><label >
      { $t({ defaultMessage: '1. Install an authentication app on your mobile' }) }
    </label>
    <div/><label style={{ marginLeft: '13px' }}>
      { $t({ defaultMessage: 'device' }) }
    </label>
    <div style={{ marginTop: '13px' }} /><label >
      { $t({ defaultMessage: '2. Open the app, then select "Add Account"' }) }
    </label>
    <div style={{ marginTop: '13px' }}/><label >
      { $t({ defaultMessage: '3. Scan the QR code below:' }) }
    </label>
    <div /><img style={{ marginLeft: '13px', marginTop: '10px', width: '135px' }}
      src={url}
      alt={url}
    />

    <div style={{ marginTop: '13px' }}/><label style={{ marginLeft: '13px' }}>
      { $t({ defaultMessage: 'Or enter this key into the app:' }) }
    </label>
    <div /><label style={{ marginLeft: '13px', fontWeight: 'bold' }} >
      { key }
    </label>

    <div style={{ marginTop: '13px' }}/><label >
      { $t({ defaultMessage: '4. Enter the verification code generated by your' }) }
    </label>
    <div/><label style={{ marginLeft: '13px' }}>
      { $t({ defaultMessage: 'authentication app:' }) }
    </label>
    {<Input style={{ marginLeft: '13px', marginTop: '5px', width: '255px' }}/>}

  </Form>

  const footer = [
    <Drawer.FormFooter
      buttonLabel={{ save: $t({ defaultMessage: 'Confirm' }) }}
      onCancel={resetFields}
      onSave={async () => handleSave()}
    />
  ]

  return (
    <Drawer
      title={$t({ defaultMessage: 'Manage Authentication App' })}
      visible={visible}
      onClose={onClose}
      children={content}
      footer={footer}
      destroyOnClose={resetField}
      width={'336'}
    />
  )
}
