import { defineMessage, MessageDescriptor } from 'react-intl'

/* eslint-disable max-len */
export const disconnectReasonCodeMap: Record<string, MessageDescriptor> = {
  0: defineMessage({ defaultMessage: 'Reserved' }),
  1: defineMessage({ defaultMessage: 'Unspecified reason' }),
  2: defineMessage({ defaultMessage: 'Previous authentication no longer valid' }),
  3: defineMessage({ defaultMessage: 'Deauthenticated because sending STA is leaving (or has left) IBSS or ESS' }),
  4: defineMessage({ defaultMessage: 'Disassociated due to inactivity' }),
  5: defineMessage({ defaultMessage: 'Disassociated because AP is unable to handle all currently associated STAs' }),
  6: defineMessage({ defaultMessage: 'Class 2 frame received from nonauthenticated STA' }),
  7: defineMessage({ defaultMessage: 'Class 3 frame received from nonassociated STA' }),
  8: defineMessage({ defaultMessage: 'Disassociated because sending STA is leaving (or has left) BSS' }),
  9: defineMessage({ defaultMessage: 'STA requesting (re)association is not authenticated with responding STA' }),
  10: defineMessage({ defaultMessage: 'Disassociated because the information in the Power Capability element is unacceptable' }),
  11: defineMessage({ defaultMessage: 'Disassociated because the information in the Supported Channels element is unacceptable' }),
  12: defineMessage({ defaultMessage: 'Disassociated due to BSS Transition Management' }),
  13: defineMessage({ defaultMessage: 'Invalid RSN IE' }),
  14: defineMessage({ defaultMessage: 'Message integrity code (MIC) failure' }),
  15: defineMessage({ defaultMessage: '4-Way Handshake timeout' }),
  16: defineMessage({ defaultMessage: 'Group Key Handshake timeout' }),
  17: defineMessage({ defaultMessage: 'Element in 4-Way Handshake different from (Re)Association Request/Probe Response/Beacon frame' }),
  18: defineMessage({ defaultMessage: 'Invalid group cipher' }),
  19: defineMessage({ defaultMessage: 'Invalid pairwise cipher' }),
  20: defineMessage({ defaultMessage: 'Invalid AKMP' }),
  21: defineMessage({ defaultMessage: 'Unsupported RSNE version' }),
  22: defineMessage({ defaultMessage: 'Invalid RSNE capabilities' }),
  23: defineMessage({ defaultMessage: 'IEEE 802.1X authentication failed' }),
  24: defineMessage({ defaultMessage: 'Cipher suite rejected because of the security policy' }),
  25: defineMessage({ defaultMessage: 'TDLS direct-link teardown due to TDLS peer STA unreachable via the TDLS direct link' }),
  26: defineMessage({ defaultMessage: 'TDLS direct-link teardown for unspecified reason' }),
  27: defineMessage({ defaultMessage: 'Disassociated because session terminated by SSP request' }),
  28: defineMessage({ defaultMessage: 'Disassociated because of lack of SSP roaming agreement' }),
  29: defineMessage({ defaultMessage: 'Requested service rejected because of SSP cipher suite or AKM requirement' }),
  30: defineMessage({ defaultMessage: 'Requested service not authorized in this location' }),
  31: defineMessage({ defaultMessage: 'TS deleted because QoS AP lacks sufficient bandwidth for this QoS STA due to change in BSS service characteristics or operational mode (e.g. an HT BSS change from 40 MHz channel to 20 MHz channel' }),
  32: defineMessage({ defaultMessage: 'Disassociated for unspecified, QoS-related reason' }),
  33: defineMessage({ defaultMessage: 'Disassociated because QoS AP lacks sufficient bandwidth for this QoS STA' }),
  34: defineMessage({ defaultMessage: 'Disassociated because excessive number of frames need to be acknowledged, but are not acknowledged due to AP transmissions and/or poor channel conditions' }),
  35: defineMessage({ defaultMessage: 'Disassociated because STA is transmitting outside the limits of TXOPs' }),
  36: defineMessage({ defaultMessage: 'Requested from peer STA as the STA is leaving the BSS (or resetting)' }),
  37: defineMessage({ defaultMessage: 'Requested from peer STA as the STA does not want to use the mechanism' }),
  38: defineMessage({ defaultMessage: 'Requested from peer STA as the STA received frames using the mechanism for which setup is required' }),
  39: defineMessage({ defaultMessage: 'Requested from peer STA due to timeout' }),
  45: defineMessage({ defaultMessage: 'Peer STA does not support the requested cipher suite' }),
  46: defineMessage({ defaultMessage: 'Disassociated because authorized access limit reached' }),
  47: defineMessage({ defaultMessage: 'Disassociated due to external service requirements' }),
  48: defineMessage({ defaultMessage: 'Invalid FT Action frame count' }),
  49: defineMessage({ defaultMessage: 'Invalid pairwise master key identified (PMKI)' }),
  50: defineMessage({ defaultMessage: 'Invalid MDE' }),
  51: defineMessage({ defaultMessage: 'Invalid FTE' }),
  52: defineMessage({ defaultMessage: 'SME cancels the mesh peering instance with the reason other than reaching the maximum number of peer mesh STAs' }),
  53: defineMessage({ defaultMessage: 'The mesh STA has reached the supported maximum number of peer STAs' }),
  54: defineMessage({ defaultMessage: 'The received information violates the Mesh Configuration policy configured in the mesh STA profile' }),
  55: defineMessage({ defaultMessage: 'The mesh STA has received a Mesh Peering Close message requesting to close the mesh peering' }),
  56: defineMessage({ defaultMessage: 'The mesh STA has resent dot11MeshMaxRetries Mesh Peering Open messages, without receiving a Mesh Peering Confirm message' }),
  57: defineMessage({ defaultMessage: 'The confirmTimer for the mesh peering instance times out' }),
  58: defineMessage({ defaultMessage: 'The mesh STA fails to unwrap the GTK or the values in the wrapped contents do not match' }),
  59: defineMessage({ defaultMessage: 'The mesh STA receives inconsistent information about the mesh parameters between Mesh Peering Management frames' }),
  60: defineMessage({ defaultMessage: 'The mesh STA fails the authenticated mesh peering exchange because due to failure in selecting either the pairwise ciphersuite or group ciphersuite' }),
  61: defineMessage({ defaultMessage: 'The mesh STA does not have proxy information for this external destination' }),
  62: defineMessage({ defaultMessage: 'The mesh STA does not have forwarding information for this destination' }),
  63: defineMessage({ defaultMessage: 'The mesh STA determines that the link to the next hop of an active path in its forwarding information is no longer usable' }),
  64: defineMessage({ defaultMessage: 'The Deauthentication frame was sent because the MAC address of the STA already exists in the mesh BSS.' }),
  65: defineMessage({ defaultMessage: 'The mesh STA performs channel switch to meet regulatory requirements' }),
  66: defineMessage({ defaultMessage: 'The mesh STA performs channel switch with unspecified reason' })
}
/* eslint-enable max-len */
