export const vlanList = {
  data: [
    {
      arpInspection: true,
      id: '832157f54e534a6f8f46c228760804b3',
      igmpSnooping: 'passive',
      ipv4DhcpSnooping: true,
      multicastVersion: 3,
      spanningTreeProtocol: 'stp',
      untaggedPorts: '1/1/7',
      switchVlanPortModels: [{
        id: '60bdeef19886490fab191327ccae0b53',
        switchModel: 'ICX7150-C08P',
        untaggedPorts: '1/1/7'
      }],
      vlanId: 666,
      vlanName: 'vlan name'
    },
    {
      arpInspection: false,
      id: '06cb3f62b82943a7baa853f44b5a1e98',
      igmpSnooping: 'none',
      ipv4DhcpSnooping: false,
      spanningTreeProtocol: 'none',
      untaggedPorts: '1/1/5',
      switchVlanPortModels: [{
        id: '60bdeef19886490fab191327ccae0b53',
        switchModel: 'ICX7150-C08P',
        untaggedPorts: '1/1/5'
      }],
      vlanId: 555
    },
    {
      arpInspection: false,
      id: 'ff1b24c7fa8547298fad1ce7068ec6ee',
      igmpSnooping: 'none',
      ipv4DhcpSnooping: false,
      spanningTreeProtocol: 'none',
      untaggedPorts: '1/1/6',
      switchVlanPortModels: [{
        id: '60bdeef19886490fab191327ccae0b53',
        switchModel: 'ICX7150-C08P',
        untaggedPorts: '1/1/6'
      }],
      vlanId: 444
    },
    {
      arpInspection: false,
      id: '5839a723f2314e3d935d78d3ee2dd3ec',
      igmpSnooping: 'none',
      ipv4DhcpSnooping: false,
      spanningTreeProtocol: 'none',
      vlanId: 333
    },
    {
      arpInspection: false,
      id: 'b2c305e36865489482802a22ca8ee853',
      igmpSnooping: 'none',
      ipv4DhcpSnooping: false,
      spanningTreeProtocol: '',
      taggedPorts: '1/1/3',
      vlanId: 222
    },
    {
      arpInspection: false,
      id: 'ef1c79c5959948d594e019719ddd8325',
      igmpSnooping: 'none',
      ipv4DhcpSnooping: false,
      spanningTreeProtocol: 'stp',
      // eslint-disable-next-line max-len
      untaggedPorts: '1/1/1,1/1/2,1/1/3,1/1/4,1/1/5,1/1/6,1/1/7,1/1/8,1/1/9,1/1/10,1/1/11,1/1/12,1/2/1,1/2/2,2/1/1,2/1/2,2/1/3,2/1/4,2/1/5,2/1/6,2/1/7,2/1/8,2/1/9,2/1/10,2/1/11,2/1/12,2/2/1,2/2/2,2/3/2',
      vlanId: 111,
      vlanName: 'DEFAULT-VLAN'
    }
  ],
  page: 1,
  totalCount: 6,
  totalPages: 1
}

export const switchDetails = {
  type: 'device',
  isStack: false,
  rearModule: 'none',
  switchMac: 'c0:c5:20:b2:0e:e9',
  switchName: 'ICX7150-C08P Switch - test',
  model: 'ICX7150-C08P',
  id: 'c0:c5:20:b2:0e:e9',
  syncDataEndTime: 1716791056975,
  firmwareVersion: 'SPS09010j',
  freeMemory: 494800896,
  clientCount: 1,
  floorplanId: '',
  deviceType: 'DVCNWTYPE_SWITCH',
  serialNumber: 'FMF3250Q06R',
  yPercent: 0,
  portsStatus: {
    Down: 9,
    Up: 1
  },
  staticOrDynamic: 'dynamic',
  ipAddress: '10.206.10.44',
  dns: '10.10.10.106',
  cpu: 6,
  stackMember: false,
  cliApplied: false,
  subnetMask: '255.255.254.0',
  unitSerialNumbers: 'FMF3250Q06R',
  modules: 'switch',
  venueName: 'My-Venue',
  name: 'ICX7150-C08P Switch - test',
  activeSerial: 'FMF3250Q06R',
  syncedAdminPassword: false,
  suspendingDeployTime: '',
  cloudPort: 'lg4',
  ipFullContentParsed: true,
  stackMemberOrder: '',
  numOfUnits: 1,
  memory: 51,
  switchType: 'switch',
  crtTime: '1714122179406',
  configReady: true,
  portModuleIds: 'FMF3250Q06R',
  deviceStatus: 'ONLINE',
  // eslint-disable-next-line max-len
  vlanMapping: '{"1":"DEFAULT-VLAN","100":"test<>123${testString}<><ffffff>","34":"34test","101":"test<>123${testString}<><ffffff>","2":"${testString}<AABB>","37":"test37","6":"test66","7":"test","8":"test8","31":"31test","10":"test10","32":"32test"}',
  // eslint-disable-next-line max-len
  temperatureGroups: '[{"serialNumber":"FMF3250Q06R","stackId":"C0:C5:20:B2:0E:E9","temperatureSlotList":[{"slotNumber":3,"temperatureValue":53},{"slotNumber":4,"temperatureValue":53},{"slotNumber":1,"temperatureValue":64.5},{"slotNumber":2,"temperatureValue":46}]}]',
  sendedHostname: true,
  venueId: '81e0fac39cee430992e9f770fce3645b',
  syncDataId: '',
  unitId: 1,
  hasPoECapability: true,
  firmware: 'SPS09010j',
  adminPassword: '',
  timestamp: 1716816234463,
  syncedSwitchConfig: true,
  xPercent: 0,
  defaultGateway: '10.206.11.254',
  stackMembers: [],
  extIp: '210.58.90.254',
  uptime: '3 days, 2:34:34.00',
  poeUsage: {
    poeFree: 62000,
    poeTotal: 62000,
    poeUtilization: 0
  },
  totalMemory: 1019875328,
  tenantId: 'b8713c6fcf5648ad911dfe4bbbfa891d',
  family: 'ICX7150-C08P',
  numOfPorts: 10
}

export const lagList = [{
  id: 'b01edb1f4e5d4306a3e918d76d0e4ac2',
  lagId: 1,
  name: 'LAG1',
  ports: ['1/1/5'],
  type: 'static',
  untaggedVlan: '1'
}]

export const portList = {
  data: [{
    cloudPort: true,
    stack: false,
    name: '1114',
    portId: 'c0-c5-20-b2-0e-e9_1-1-1',
    status: 'Up',
    adminStatus: 'Up',
    vlanIds: '1',
    portSpeed: '1 Gb/sec',
    poeUsed: 0,
    poeTotal: 0,
    signalIn: 0,
    signalOut: 0,
    crcErr: '0',
    inErr: '0',
    outErr: '0',
    opticsType: '1 Gbits per second copper',
    switchUnitId: 'FMF3250Q06R',
    poeEnabled: true,
    usedInFormingStack: false,
    portIdentifier: '1/1/1',
    unTaggedVlan: '1',
    inDiscard: '0',
    broadcastIn: '623822',
    broadcastOut: '4',
    multicastIn: '655248',
    multicastOut: '8931',
    poeType: 'n/a',
    switchMac: 'c0:c5:20:b2:0e:e9',
    id: 'c0-c5-20-b2-0e-e9_1-1-1',
    neighborName: '[11F_LAB_R2_DOWN_10.206.11.5',
    venueId: '81e0fac39cee430992e9f770fce3645b',
    ingressAclName: '',
    egressAclName: '',
    vsixIngressAclName: '',
    vsixEgressAclName: '',
    lagName: 'LAG3',
    switchName: 'ICX7150-C08P Switch - test',
    switchSerial: 'c0:c5:20:b2:0e:e9',
    lagId: '4',
    deviceStatus: 'ONLINE',
    unitStatus: 'Standalone',
    unitState: 'ONLINE',
    switchModel: 'ICX7150-C08P',
    neighborMacAddress: '5C:8A:38:9F:5F:12',
    syncedSwitchConfig: true,
    mediaType: 'MEDIA_TYPE_EMPTY',
    poeUsage: '0/0W (0%)'
  },
  {
    cloudPort: false,
    stack: false,
    name: 'GigabitEthernet1/1/2',
    portId: 'c0-c5-20-b2-0e-ea_1-1-2',
    status: 'Down',
    adminStatus: 'Up',
    vlanIds: '101 100 32 8',
    portSpeed: 'link down or no traffic',
    poeUsed: 0,
    poeTotal: 0,
    signalIn: 0,
    signalOut: 0,
    crcErr: '0',
    inErr: '0',
    outErr: '0',
    opticsType: '1 Gbits per second copper',
    switchUnitId: 'FMF3250Q06R',
    poeEnabled: true,
    usedInFormingStack: false,
    portIdentifier: '1/1/2',
    unTaggedVlan: '32',
    inDiscard: '0',
    broadcastIn: '0',
    broadcastOut: '0',
    multicastIn: '0',
    multicastOut: '0',
    poeType: 'n/a',
    switchMac: 'c0:c5:20:b2:0e:e9',
    id: 'c0-c5-20-b2-0e-ea_1-1-2',
    neighborName: '',
    venueId: '81e0fac39cee430992e9f770fce3645b',
    ingressAclName: '',
    egressAclName: '',
    vsixIngressAclName: '',
    vsixEgressAclName: '',
    lagName: 'LAG2',
    switchName: 'ICX7150-C08P Switch - test',
    switchSerial: 'c0:c5:20:b2:0e:e9',
    lagId: '2',
    deviceStatus: 'ONLINE',
    unitStatus: 'Standalone',
    unitState: 'ONLINE',
    switchModel: 'ICX7150-C08P',
    neighborMacAddress: '',
    syncedSwitchConfig: true,
    mediaType: 'MEDIA_TYPE_EMPTY',
    poeUsage: '0/0W (0%)'
  },
  {
    cloudPort: false,
    stack: false,
    name: 'testtttt${var}<><aaabb>',
    portId: 'c0-c5-20-b2-0e-eb_1-1-3',
    status: 'Down',
    adminStatus: 'Up',
    vlanIds: '1',
    portSpeed: 'link down or no traffic',
    poeUsed: 0,
    poeTotal: 0,
    signalIn: 0,
    signalOut: 0,
    crcErr: '0',
    inErr: '0',
    outErr: '0',
    opticsType: '1 Gbits per second copper',
    switchUnitId: 'FMF3250Q06R',
    poeEnabled: true,
    usedInFormingStack: false,
    portIdentifier: '1/1/3',
    unTaggedVlan: '1',
    inDiscard: '0',
    broadcastIn: '0',
    broadcastOut: '0',
    multicastIn: '0',
    multicastOut: '0',
    poeType: 'n/a',
    switchMac: 'c0:c5:20:b2:0e:e9',
    id: 'c0-c5-20-b2-0e-eb_1-1-3',
    neighborName: '',
    venueId: '81e0fac39cee430992e9f770fce3645b',
    ingressAclName: '',
    egressAclName: '',
    vsixIngressAclName: '',
    vsixEgressAclName: '',
    lagName: '',
    switchName: 'ICX7150-C08P Switch - test',
    switchSerial: 'c0:c5:20:b2:0e:e9',
    lagId: '0',
    deviceStatus: 'ONLINE',
    unitStatus: 'Standalone',
    unitState: 'ONLINE',
    switchModel: 'ICX7150-C08P',
    neighborMacAddress: '',
    syncedSwitchConfig: true,
    mediaType: 'MEDIA_TYPE_EMPTY',
    poeUsage: '0/0W (0%)'
  },
  {
    cloudPort: false,
    stack: false,
    name: 'GigabitEthernet1/1/4',
    portId: 'c0-c5-20-b2-0e-ec_1-1-4',
    status: 'Down',
    adminStatus: 'Up',
    vlanIds: '101 100 32 8',
    portSpeed: 'link down or no traffic',
    poeUsed: 0,
    poeTotal: 0,
    signalIn: 0,
    signalOut: 0,
    crcErr: '0',
    inErr: '0',
    outErr: '0',
    opticsType: '1 Gbits per second copper',
    switchUnitId: 'FMF3250Q06R',
    poeEnabled: true,
    usedInFormingStack: false,
    portIdentifier: '1/1/4',
    unTaggedVlan: '32',
    inDiscard: '0',
    broadcastIn: '0',
    broadcastOut: '0',
    multicastIn: '0',
    multicastOut: '0',
    poeType: 'n/a',
    switchMac: 'c0:c5:20:b2:0e:e9',
    id: 'c0-c5-20-b2-0e-ec_1-1-4',
    neighborName: '',
    venueId: '81e0fac39cee430992e9f770fce3645b',
    ingressAclName: '',
    egressAclName: '',
    vsixIngressAclName: '',
    vsixEgressAclName: '',
    lagName: 'LAG2',
    switchName: 'ICX7150-C08P Switch - test',
    switchSerial: 'c0:c5:20:b2:0e:e9',
    lagId: '2',
    deviceStatus: 'ONLINE',
    unitStatus: 'Standalone',
    unitState: 'ONLINE',
    switchModel: 'ICX7150-C08P',
    neighborMacAddress: '',
    syncedSwitchConfig: true,
    mediaType: 'MEDIA_TYPE_EMPTY',
    poeUsage: '0/0W (0%)'
  },
  {
    cloudPort: false,
    stack: false,
    name: 'GigabitEthernet1/1/5',
    portId: 'c0-c5-20-b2-0e-ed_1-1-5',
    status: 'Down',
    adminStatus: 'Up',
    vlanIds: '7',
    portSpeed: 'link down or no traffic',
    poeUsed: 0,
    poeTotal: 0,
    signalIn: 0,
    signalOut: 0,
    crcErr: '0',
    inErr: '0',
    outErr: '0',
    opticsType: '1 Gbits per second copper',
    switchUnitId: 'FMF3250Q06R',
    poeEnabled: true,
    usedInFormingStack: false,
    portIdentifier: '1/1/5',
    unTaggedVlan: '7',
    inDiscard: '0',
    broadcastIn: '0',
    broadcastOut: '0',
    multicastIn: '0',
    multicastOut: '0',
    poeType: 'n/a',
    switchMac: 'c0:c5:20:b2:0e:e9',
    id: 'c0-c5-20-b2-0e-ed_1-1-5',
    neighborName: '',
    venueId: '81e0fac39cee430992e9f770fce3645b',
    ingressAclName: '11',
    egressAclName: 'ext1',
    vsixIngressAclName: '',
    vsixEgressAclName: '',
    lagName: '',
    switchName: 'ICX7150-C08P Switch - test',
    switchSerial: 'c0:c5:20:b2:0e:e9',
    lagId: '0',
    deviceStatus: 'ONLINE',
    unitStatus: 'Standalone',
    unitState: 'ONLINE',
    switchModel: 'ICX7150-C08P',
    neighborMacAddress: '',
    syncedSwitchConfig: true,
    mediaType: 'MEDIA_TYPE_EMPTY',
    poeUsage: '0/0W (0%)'
  },
  {
    cloudPort: false,
    stack: false,
    name: 'GigabitEthernet1/1/6',
    portId: 'c0-c5-20-b2-0e-ee_1-1-6',
    status: 'Down',
    adminStatus: 'Up',
    vlanIds: '1',
    portSpeed: 'link down or no traffic',
    poeUsed: 0,
    poeTotal: 0,
    signalIn: 0,
    signalOut: 0,
    crcErr: '0',
    inErr: '0',
    outErr: '0',
    opticsType: '1 Gbits per second copper',
    switchUnitId: 'FMF3250Q06R',
    poeEnabled: true,
    usedInFormingStack: false,
    portIdentifier: '1/1/6',
    unTaggedVlan: '1',
    inDiscard: '0',
    broadcastIn: '0',
    broadcastOut: '0',
    multicastIn: '0',
    multicastOut: '0',
    poeType: 'n/a',
    switchMac: 'c0:c5:20:b2:0e:e9',
    id: 'c0-c5-20-b2-0e-ee_1-1-6',
    neighborName: '',
    venueId: '81e0fac39cee430992e9f770fce3645b',
    ingressAclName: '',
    egressAclName: '',
    vsixIngressAclName: '',
    vsixEgressAclName: '',
    lagName: '',
    switchName: 'ICX7150-C08P Switch - test',
    switchSerial: 'c0:c5:20:b2:0e:e9',
    lagId: '0',
    deviceStatus: 'ONLINE',
    unitStatus: 'Standalone',
    unitState: 'ONLINE',
    switchModel: 'ICX7150-C08P',
    neighborMacAddress: '',
    syncedSwitchConfig: true,
    mediaType: 'MEDIA_TYPE_EMPTY',
    poeUsage: '0/0W (0%)'
  },
  {
    cloudPort: false,
    stack: false,
    name: '${testString}<aaabbbccc>',
    portId: 'c0-c5-20-b2-0e-ef_1-1-7',
    status: 'Down',
    adminStatus: 'Up',
    vlanIds: '1',
    portSpeed: 'link down or no traffic',
    poeUsed: 0,
    poeTotal: 0,
    signalIn: 0,
    signalOut: 0,
    crcErr: '0',
    inErr: '0',
    outErr: '0',
    opticsType: '1 Gbits per second copper',
    switchUnitId: 'FMF3250Q06R',
    poeEnabled: true,
    usedInFormingStack: false,
    portIdentifier: '1/1/7',
    unTaggedVlan: '1',
    inDiscard: '0',
    broadcastIn: '0',
    broadcastOut: '0',
    multicastIn: '0',
    multicastOut: '0',
    poeType: 'n/a',
    switchMac: 'c0:c5:20:b2:0e:e9',
    id: 'c0-c5-20-b2-0e-ef_1-1-7',
    neighborName: '',
    venueId: '81e0fac39cee430992e9f770fce3645b',
    ingressAclName: '',
    egressAclName: '',
    vsixIngressAclName: '',
    vsixEgressAclName: '',
    lagName: '',
    switchName: 'ICX7150-C08P Switch - test',
    switchSerial: 'c0:c5:20:b2:0e:e9',
    lagId: '0',
    deviceStatus: 'ONLINE',
    unitStatus: 'Standalone',
    unitState: 'ONLINE',
    switchModel: 'ICX7150-C08P',
    neighborMacAddress: '',
    syncedSwitchConfig: true,
    mediaType: 'MEDIA_TYPE_EMPTY',
    poeUsage: '0/0W (0%)'
  },
  {
    cloudPort: false,
    stack: false,
    name: '${testString}',
    portId: 'c0-c5-20-b2-0e-f0_1-1-8',
    status: 'Down',
    adminStatus: 'Up',
    vlanIds: '4',
    portSpeed: 'link down or no traffic',
    poeUsed: 0,
    poeTotal: 0,
    signalIn: 0,
    signalOut: 0,
    crcErr: '0',
    inErr: '0',
    outErr: '0',
    opticsType: '1 Gbits per second copper',
    switchUnitId: 'FMF3250Q06R',
    poeEnabled: true,
    usedInFormingStack: false,
    portIdentifier: '1/1/8',
    unTaggedVlan: '4',
    inDiscard: '0',
    broadcastIn: '0',
    broadcastOut: '0',
    multicastIn: '0',
    multicastOut: '0',
    poeType: 'n/a',
    switchMac: 'c0:c5:20:b2:0e:e9',
    id: 'c0-c5-20-b2-0e-f0_1-1-8',
    neighborName: '',
    venueId: '81e0fac39cee430992e9f770fce3645b',
    ingressAclName: '',
    egressAclName: '',
    vsixIngressAclName: '',
    vsixEgressAclName: '',
    lagName: '',
    switchName: 'ICX7150-C08P Switch - test',
    switchSerial: 'c0:c5:20:b2:0e:e9',
    lagId: '0',
    deviceStatus: 'ONLINE',
    unitStatus: 'Standalone',
    unitState: 'ONLINE',
    switchModel: 'ICX7150-C08P',
    neighborMacAddress: '',
    syncedSwitchConfig: true,
    mediaType: 'MEDIA_TYPE_EMPTY',
    poeUsage: '0/0W (0%)'
  },
  {
    cloudPort: false,
    stack: false,
    name: 'GigabitEthernet1/2/1',
    portId: 'c0-c5-20-b2-0e-f1_1-2-1',
    status: 'Down',
    adminStatus: 'Up',
    vlanIds: '3',
    portSpeed: 'link down or no traffic',
    poeUsed: 0,
    poeTotal: 0,
    signalIn: 0,
    signalOut: 0,
    crcErr: '0',
    inErr: '0',
    outErr: '0',
    opticsType: '1 Gbits per second fiber',
    switchUnitId: 'FMF3250Q06R',
    poeEnabled: false,
    usedInFormingStack: false,
    portIdentifier: '1/2/1',
    unTaggedVlan: '3',
    inDiscard: '0',
    broadcastIn: '0',
    broadcastOut: '0',
    multicastIn: '0',
    multicastOut: '0',
    poeType: '',
    switchMac: 'c0:c5:20:b2:0e:e9',
    id: 'c0-c5-20-b2-0e-f1_1-2-1',
    neighborName: '',
    venueId: '81e0fac39cee430992e9f770fce3645b',
    ingressAclName: '',
    egressAclName: '',
    vsixIngressAclName: '',
    vsixEgressAclName: '',
    lagName: '',
    switchName: 'ICX7150-C08P Switch - test',
    switchSerial: 'c0:c5:20:b2:0e:e9',
    lagId: '0',
    deviceStatus: 'ONLINE',
    unitStatus: 'Standalone',
    unitState: 'ONLINE',
    switchModel: 'ICX7150-C08P',
    neighborMacAddress: '',
    syncedSwitchConfig: true,
    mediaType: 'MEDIA_TYPE_EMPTY',
    poeUsage: 'off'
  },
  {
    cloudPort: false,
    stack: false,
    name: 'GigabitEthernet1/2/2',
    portId: 'c0-c5-20-b2-0e-f2_1-2-2',
    status: 'Down',
    adminStatus: 'Up',
    vlanIds: '1 7',
    portSpeed: 'link down or no traffic',
    poeUsed: 0,
    poeTotal: 0,
    signalIn: 0,
    signalOut: 0,
    crcErr: '0',
    inErr: '0',
    outErr: '0',
    opticsType: '1 Gbits per second fiber',
    switchUnitId: 'FMF3250Q06R',
    poeEnabled: false,
    usedInFormingStack: false,
    portIdentifier: '1/2/2',
    unTaggedVlan: '1',
    inDiscard: '0',
    broadcastIn: '0',
    broadcastOut: '0',
    multicastIn: '0',
    multicastOut: '0',
    poeType: '',
    switchMac: 'c0:c5:20:b2:0e:e9',
    id: 'c0-c5-20-b2-0e-f2_1-2-2',
    neighborName: '',
    venueId: '81e0fac39cee430992e9f770fce3645b',
    ingressAclName: '',
    egressAclName: '',
    vsixIngressAclName: '',
    vsixEgressAclName: '',
    lagName: '',
    switchName: 'ICX7150-C08P Switch - test',
    switchSerial: 'c0:c5:20:b2:0e:e9',
    lagId: '0',
    deviceStatus: 'ONLINE',
    unitStatus: 'Standalone',
    unitState: 'ONLINE',
    switchModel: 'ICX7150-C08P',
    neighborMacAddress: '',
    syncedSwitchConfig: true,
    mediaType: 'MEDIA_TYPE_EMPTY',
    poeUsage: 'off'
  }]
}