export * from './mdnsProxyUrls'
export * from './networkSegmentationUrls'
export * from './wifiCallingUrls'
export * from './dpskUrls'
export * from './dhcpUrls'
export * from './portalUrls'
export * from './edgeDhcpUrls'
export * from './edgeFirewallUrls'
