export * from 'react-router-dom'
export * from './NewTabLink'
export * from './RootRoutes'
export * from './useTenantLink'
export * from './TenantLink'
export * from './TenantNavLink'
export * from './TenantNavigate'
export * from './useNavigateToPath'

export const MLISA_BASE_PATH = '/ai'
