export const PROFILE_MAX_COUNT_ACCESS_CONTROL = 63

export const PROFILE_MAX_COUNT_DEVICE_POLICY = 1000

export const PROFILE_MAX_COUNT_APPLICATION_POLICY = 63

export const PROFILE_MAX_COUNT_LAYER2_POLICY = 1280

export const PROFILE_MAX_COUNT_LAYER3_POLICY = 1280

