import { defineMessage } from 'react-intl'

/* eslint-disable max-len */
export const apSpecificKeyMap = [
  { id: -1, value: 'initialState.CcmApSpecifics.wlan_groups.wlan_group_6(5)g_id', text: 'NA', textAlto: 'TBD', enumType: '', incidents: {}, kpis: {} },
  { id: 1, value: 'initialState.CcmApSpecifics.id', text: 'NA', textAlto: 'TBD', enumType: '', incidents: {}, kpis: {} },
  { id: 2, value: 'initialState.CcmApSpecifics.ap_tenant_id', text: 'NA', textAlto: 'TBD', enumType: '', incidents: {}, kpis: {} },
  { id: 3, value: 'initialState.CcmApSpecifics.ap_tenant_name', text: 'TBD', textAlto: 'TBD', enumType: '', incidents: {}, kpis: {} },
  { id: 4, value: 'initialState.CcmApSpecifics.domain_id', text: 'NA', textAlto: 'TBD', enumType: '', incidents: {}, kpis: {} },
  { id: 5, value: 'initialState.CcmApSpecifics.domain_name', text: defineMessage({ defaultMessage: 'Domain Name' }), textAlto: 'TBD', enumType: '', incidents: {}, kpis: {} },
  { id: 6, value: 'initialState.CcmApSpecifics.hs20_internal_osu_fqdn', text: 'TBD', textAlto: 'TBD', enumType: '', incidents: {}, kpis: {} },
  { id: 7, value: 'initialState.CcmApSpecifics.lbs_enabled', text: defineMessage({ defaultMessage: 'Location based service : Enabled' }), textAlto: 'TBD', enumType: '', incidents: {}, kpis: {} },
  { id: 8, value: 'initialState.CcmApSpecifics.scg_interface_ip_list', text: 'TBD', textAlto: 'TBD', enumType: '', incidents: {}, kpis: {} },
  { id: 9, value: 'initialState.CcmApSpecifics.scg_portal_fqdn', text: 'TBD', textAlto: 'TBD', enumType: '', incidents: {}, kpis: {} },
  { id: 10, value: 'initialState.CcmApSpecifics.scg_portal_redirection_host', text: 'TBD', textAlto: 'TBD', enumType: '', incidents: {}, kpis: {} },
  { id: 11, value: 'initialState.CcmApSpecifics.scg_nbi_ip', text: 'TBD', textAlto: 'TBD', enumType: '', incidents: {}, kpis: {} },
  { id: 12, value: 'initialState.CcmApSpecifics.scg_nbi_ipv6', text: 'TBD', textAlto: 'TBD', enumType: '', incidents: {}, kpis: {} },
  { id: 13, value: 'initialState.CcmApSpecifics.scg_failover_ip_list', text: 'TBD', textAlto: 'TBD', enumType: '', incidents: {}, kpis: {} },
  { id: 14, value: 'initialState.CcmApSpecifics.scg_control_plane_ip_list', text: 'TBD', textAlto: 'TBD', enumType: '', incidents: {}, kpis: {} },
  { id: 15, value: 'initialState.CcmApSpecifics.currently_connected_control_plane_ip', text: 'TBD', textAlto: 'TBD', enumType: '', incidents: {}, kpis: {} },
  { id: 16, value: 'initialState.CcmApSpecifics.management_ip_of_currently_connected_node', text: 'TBD', textAlto: 'TBD', enumType: '', incidents: {}, kpis: {} },
  { id: 17, value: 'initialState.CcmApSpecifics.zone_id', text: 'NA', textAlto: 'TBD', enumType: '', incidents: {}, kpis: {} },
  { id: 18, value: 'initialState.CcmApSpecifics.cluster_id', text: 'NA', textAlto: 'TBD', enumType: '', incidents: {}, kpis: {} },
  { id: 19, value: 'initialState.CcmApSpecifics.ap_group_id', text: 'NA', textAlto: 'TBD', enumType: '', incidents: {}, kpis: {} },
  { id: 20, value: 'initialState.CcmApSpecifics.wlan_group_24g_id', text: 'NA', textAlto: 'TBD', enumType: '', incidents: {}, kpis: {} },
  { id: 21, value: 'initialState.CcmApSpecifics.wlan_group_50g_id', text: 'NA', textAlto: 'TBD', enumType: '', incidents: {}, kpis: {} },
  { id: 22, value: 'initialState.CcmApSpecifics.ethernet_port_profile_id', text: 'NA', textAlto: 'TBD', enumType: '', incidents: {}, kpis: {} },
  { id: 23, value: 'initialState.CcmApSpecifics.model', text: 'TBD', textAlto: 'TBD', enumType: '', incidents: {}, kpis: {} },
  { id: 24, value: 'initialState.CcmApSpecifics.model_settings.name', text: 'TBD', textAlto: 'TBD', enumType: '', incidents: {}, kpis: {} },
  { id: 25, value: 'initialState.CcmApSpecifics.model_settings.model_specific_ethernet_port_settings.port_number', text: 'TBD', textAlto: 'TBD', enumType: '', incidents: {}, kpis: {} },
  { id: 26, value: 'initialState.CcmApSpecifics.model_settings.model_specific_ethernet_port_settings.ethernet_port_profile_id', text: 'NA', textAlto: 'TBD', enumType: '', incidents: {}, kpis: {} },
  { id: 27, value: 'initialState.CcmApSpecifics.model_settings.model_specific_ethernet_port_settings.untag_id', text: defineMessage({ defaultMessage: 'Untag VLAN ID' }), textAlto: defineMessage({ defaultMessage: 'Untag VLAN ID' }), enumType: '', incidents: {}, kpis: {} },
  { id: 28, value: 'initialState.CcmApSpecifics.model_settings.model_specific_ethernet_port_settings.vlan_members', text: defineMessage({ defaultMessage: 'VLAN Members' }), textAlto: defineMessage({ defaultMessage: 'VLAN Members' }), enumType: '', incidents: { 'i-apserv-high-num-reboots': 1, 'i-apserv-continuous-reboots': 1 }, kpis: {} },
  { id: 29, value: 'initialState.CcmApSpecifics.model_settings.model_specific_ethernet_port_settings.state', text: 'TBD', textAlto: defineMessage({ defaultMessage: 'LAN Port Settings: State' }), enumType: '', incidents: {}, kpis: {} },
  { id: 30, value: 'initialState.CcmApSpecifics.model_settings.model_specific_ethernet_port_settings.override_vlan_enabled', text: defineMessage({ defaultMessage: 'Overwrite VLAN' }), textAlto: 'TBD', enumType: '', incidents: { 'i-apserv-high-num-reboots': 1, 'i-apserv-continuous-reboots': 1 }, kpis: {} },
  { id: 31, value: 'initialState.CcmApSpecifics.model_settings.model_specific_radio_settings.radio_type', text: 'TBD', textAlto: 'TBD', enumType: 'com.ruckuswireless.scg.protobuf.ccm.Zone.CcmModel.CcmModelSpecificRadioSettings.RadioType', incidents: {}, kpis: {} },
  { id: 32, value: 'initialState.CcmApSpecifics.model_settings.model_specific_radio_settings.ext_ant', text: 'TBD', textAlto: 'TBD', enumType: '', incidents: {}, kpis: { clientThroughput: 1, apCapacity: 1, rss: 1 } },
  { id: 33, value: 'initialState.CcmApSpecifics.model_settings.model_specific_radio_settings.ext_ant_chain_mask', text: 'TBD', textAlto: 'TBD', enumType: '', incidents: {}, kpis: { clientThroughput: 1, apCapacity: 1, rss: 1 } },
  { id: 34, value: 'initialState.CcmApSpecifics.model_settings.model_specific_radio_settings.ext_ant_gain', text: 'TBD', textAlto: 'TBD', enumType: '', incidents: {}, kpis: { clientThroughput: 1, apCapacity: 1, rss: 1 } },
  { id: 35, value: 'initialState.CcmApSpecifics.model_settings.model_specific_radio_settings.ani_ofdm_level', text: 'TBD', textAlto: 'TBD', enumType: '', incidents: {}, kpis: { clientThroughput: 1, apCapacity: 1, rss: 1 } },
  { id: 36, value: 'initialState.CcmApSpecifics.model_settings.model_specific_lldp_settings.lldp_enabled', text: defineMessage({ defaultMessage: 'LLDP :Enabled ' }), textAlto: 'TBD', enumType: '', incidents: {}, kpis: {} },
  { id: 37, value: 'initialState.CcmApSpecifics.model_settings.model_specific_lldp_settings.lldp_mgmt_enabled', text: defineMessage({ defaultMessage: 'LLDP Management IP TLV Enabled' }), textAlto: 'TBD', enumType: '', incidents: {}, kpis: {} },
  { id: 38, value: 'initialState.CcmApSpecifics.model_settings.model_specific_lldp_settings.lldp_ad_interval', text: defineMessage({ defaultMessage: 'LLDP Advertise Interval' }), textAlto: 'TBD', enumType: '', incidents: {}, kpis: {} },
  { id: 39, value: 'initialState.CcmApSpecifics.model_settings.model_specific_lldp_settings.lldp_hold_time', text: defineMessage({ defaultMessage: 'LLDP Hold Time' }), textAlto: 'TBD', enumType: '', incidents: {}, kpis: {} },
  { id: 40, value: 'initialState.CcmApSpecifics.model_settings.cm_led_mode', text: 'TBD', textAlto: 'TBD', enumType: '', incidents: {}, kpis: {} },
  { id: 41, value: 'initialState.CcmApSpecifics.model_settings.led_status', text: 'TBD', textAlto: 'TBD', enumType: '', incidents: {}, kpis: {} },
  { id: 42, value: 'initialState.CcmApSpecifics.model_settings.poe_mode_setting', text: defineMessage({ defaultMessage: 'PoE Operating Mode' }), textAlto: 'TBD', enumType: '', incidents: {}, kpis: {} },
  { id: 43, value: 'initialState.CcmApSpecifics.model_settings.poe_out_port', text: defineMessage({ defaultMessage: 'PoE out port' }), textAlto: 'TBD', enumType: '', incidents: {}, kpis: {} },
  { id: 44, value: 'initialState.CcmApSpecifics.model_settings.poe_tx_chain', text: 'TBD', textAlto: 'TBD', enumType: '', incidents: {}, kpis: {} },
  { id: 45, value: 'initialState.CcmApSpecifics.model_settings.usb_power_enabled', text: defineMessage({ defaultMessage: 'USB Port' }), textAlto: 'TBD', enumType: '', incidents: {}, kpis: {} },
  { id: 46, value: 'initialState.CcmApSpecifics.model_settings.model_specific_poe_mode_settings.poe_mode_setting', text: 'TBD', textAlto: 'TBD', enumType: 'com.ruckuswireless.scg.protobuf.ccm.Zone.CcmModel.CcmModelSpecificPoeModeSettings.PoeOperatingMode', incidents: {}, kpis: {} },
  { id: 47, value: 'initialState.CcmApSpecifics.model_settings.model_specific_poe_mode_settings.poe_tx_chain', text: 'TBD', textAlto: 'TBD', enumType: '', incidents: {}, kpis: {} },
  { id: 48, value: 'initialState.CcmApSpecifics.model_settings.led_mode', text: 'TBD', textAlto: 'TBD', enumType: 'com.ruckuswireless.scg.protobuf.ccm.Zone.CcmModel.LedMode', incidents: {}, kpis: {} },
  { id: 49, value: 'initialState.CcmApSpecifics.model_settings.led_status_enabled', text: defineMessage({ defaultMessage: 'Status LEDs : Enabled' }), textAlto: 'TBD', enumType: '', incidents: {}, kpis: {} },
  { id: 50, value: 'initialState.CcmApSpecifics.model_settings.poe_out_port_enabled', text: 'TBD', textAlto: 'TBD', enumType: '', incidents: {}, kpis: {} },
  { id: 51, value: 'initialState.CcmApSpecifics.model_settings.model_specific_cellular_settings.mobile_ap_name', text: defineMessage({ defaultMessage: 'Cellular Radio Settings : APN for Primary SIM' }), textAlto: 'TBD', enumType: '', incidents: {}, kpis: {} },
  { id: 52, value: 'initialState.CcmApSpecifics.model_settings.model_specific_cellular_settings.mobile_ap_name2', text: defineMessage({ defaultMessage: 'Cellular Radio Settings : APN for Secondary SIM' }), textAlto: 'TBD', enumType: '', incidents: {}, kpis: {} },
  { id: 53, value: 'initialState.CcmApSpecifics.model_settings.model_specific_cellular_settings.sim_card_usage', text: defineMessage({ defaultMessage: 'Cellular Radio Settings : Simcard Usage' }), textAlto: 'TBD', enumType: 'com.ruckuswireless.scg.protobuf.ccm.Zone.CcmModel.CcmModelSpecificCellularSettings.SIMCardUsage', incidents: {}, kpis: {} },
  { id: 54, value: 'initialState.CcmApSpecifics.model_settings.model_specific_cellular_settings.select_3g_4g', text: defineMessage({ defaultMessage: 'Cellular Radio Settings : 3g/4g selection primary' }), textAlto: 'TBD', enumType: 'com.ruckuswireless.scg.protobuf.ccm.Zone.CcmModel.CcmModelSpecificCellularSettings.Select3G4G', incidents: {}, kpis: {} },
  { id: 55, value: 'initialState.CcmApSpecifics.model_settings.model_specific_cellular_settings.data_roaming', text: defineMessage({ defaultMessage: 'Cellular Radio Settings : Data Roaming Primary SIM' }), textAlto: 'TBD', enumType: 'com.ruckuswireless.scg.protobuf.ccm.Zone.CcmModel.CcmModelSpecificCellularSettings.DataRoaming', incidents: {}, kpis: {} },
  { id: 56, value: 'initialState.CcmApSpecifics.model_settings.model_specific_cellular_settings.wan_connection', text: defineMessage({ defaultMessage: 'Cellular Radio Settings : WAN connection' }), textAlto: 'TBD', enumType: 'com.ruckuswireless.scg.protobuf.ccm.Zone.CcmModel.CcmModelSpecificCellularSettings.WANConnection', incidents: {}, kpis: {} },
  { id: 57, value: 'initialState.CcmApSpecifics.model_settings.model_specific_cellular_settings.wan_recovery_timer', text: defineMessage({ defaultMessage: 'Cellular Radio Settings : Primary WAN Recovery Timer' }), textAlto: 'TBD', enumType: '', incidents: {}, kpis: {} },
  { id: 58, value: 'initialState.CcmApSpecifics.model_settings.model_specific_cellular_settings.select_3g_4g2', text: defineMessage({ defaultMessage: 'Cellular Radio Settings : 3g/4g selection Secondary' }), textAlto: 'TBD', enumType: 'com.ruckuswireless.scg.protobuf.ccm.Zone.CcmModel.CcmModelSpecificCellularSettings.Select3G4G', incidents: {}, kpis: {} },
  { id: 59, value: 'initialState.CcmApSpecifics.model_settings.model_specific_cellular_settings.data_roaming2', text: defineMessage({ defaultMessage: 'Cellular Radio Settings : Data Roaming Secondary SIM' }), textAlto: 'TBD', enumType: 'com.ruckuswireless.scg.protobuf.ccm.Zone.CcmModel.CcmModelSpecificCellularSettings.DataRoaming', incidents: {}, kpis: {} },
  { id: 60, value: 'initialState.CcmApSpecifics.model_settings.model_specific_cellular_settings.geofence_profile_id', text: 'NA', textAlto: 'TBD', enumType: '', incidents: {}, kpis: {} },
  { id: 61, value: 'initialState.CcmApSpecifics.model_settings.model_specific_lacp_settings.lacp_enabled', text: defineMessage({ defaultMessage: 'LACP/LAG' }), textAlto: 'TBD', enumType: '', incidents: {}, kpis: {} },
  { id: 62, value: 'initialState.CcmApSpecifics.model_settings.model_specific_lacp_settings.lacp_keep_ap_setting', text: 'TBD', textAlto: 'TBD', enumType: '', incidents: {}, kpis: {} },
  { id: 63, value: 'initialState.CcmApSpecifics.model_settings.model_specific_lacp_settings.bond_port_profile_id', text: 'NA', textAlto: 'TBD', enumType: '', incidents: {}, kpis: {} },
  { id: 64, value: 'initialState.CcmApSpecifics.tunnel.type', text: defineMessage({ defaultMessage: 'Tunnel Type' }), textAlto: 'TBD', enumType: 'com.ruckuswireless.scg.protobuf.ccm.ApSpecifics.CcmApSpecifics.CcmTunnel.Type', incidents: {}, kpis: {} },
  { id: 65, value: 'initialState.CcmApSpecifics.tunnel.dp_ip_list', text: 'NA', textAlto: 'TBD', enumType: '', incidents: {}, kpis: {} },
  { id: 66, value: 'initialState.CcmApSpecifics.tunnel.compute_ip_strategy', text: 'TBD', textAlto: 'TBD', enumType: 'com.ruckuswireless.scg.protobuf.ccm.ApSpecifics.CcmApSpecifics.ComputeIpStrategy', incidents: {}, kpis: {} },
  { id: 67, value: 'initialState.CcmApSpecifics.tunnel.dp_ip_group_sequence', text: 'TBD', textAlto: 'TBD', enumType: '', incidents: {}, kpis: {} },
  { id: 68, value: 'initialState.CcmApSpecifics.tunnel.rebalance_timestamp', text: 'TBD', textAlto: 'TBD', enumType: '', incidents: {}, kpis: {} },
  { id: 69, value: 'initialState.CcmApSpecifics.tunnel.dp_connect_resource.id', text: 'NA', textAlto: 'TBD', enumType: '', incidents: {}, kpis: {} },
  { id: 70, value: 'initialState.CcmApSpecifics.tunnel.dp_connect_resource.ipv4', text: 'TBD', textAlto: 'TBD', enumType: '', incidents: {}, kpis: {} },
  { id: 71, value: 'initialState.CcmApSpecifics.tunnel.dp_connect_resource.ipv4_port', text: 'TBD', textAlto: 'TBD', enumType: '', incidents: {}, kpis: {} },
  { id: 72, value: 'initialState.CcmApSpecifics.tunnel.dp_connect_resource.ipv4_exteranl', text: 'TBD', textAlto: 'TBD', enumType: '', incidents: {}, kpis: {} },
  { id: 73, value: 'initialState.CcmApSpecifics.tunnel.dp_connect_resource.ipv4_exteranl_port', text: 'TBD', textAlto: 'TBD', enumType: '', incidents: {}, kpis: {} },
  { id: 74, value: 'initialState.CcmApSpecifics.tunnel.dp_connect_resource.ipv6', text: 'TBD', textAlto: 'TBD', enumType: '', incidents: {}, kpis: {} },
  { id: 75, value: 'initialState.CcmApSpecifics.tunnel.dp_connect_resource.ipv6_port', text: 'TBD', textAlto: 'TBD', enumType: '', incidents: {}, kpis: {} },
  { id: 76, value: 'initialState.CcmApSpecifics.tunnel.dp_connect_resource.tunnel_cert_subject.c', text: 'TBD', textAlto: 'TBD', enumType: '', incidents: {}, kpis: {} },
  { id: 77, value: 'initialState.CcmApSpecifics.tunnel.dp_connect_resource.tunnel_cert_subject.st', text: 'TBD', textAlto: 'TBD', enumType: '', incidents: {}, kpis: {} },
  { id: 78, value: 'initialState.CcmApSpecifics.tunnel.dp_connect_resource.tunnel_cert_subject.l', text: 'TBD', textAlto: 'TBD', enumType: '', incidents: {}, kpis: {} },
  { id: 79, value: 'initialState.CcmApSpecifics.tunnel.dp_connect_resource.tunnel_cert_subject.o', text: 'TBD', textAlto: 'TBD', enumType: '', incidents: {}, kpis: {} },
  { id: 80, value: 'initialState.CcmApSpecifics.tunnel.dp_connect_resource.tunnel_cert_subject.cn', text: 'TBD', textAlto: 'TBD', enumType: '', incidents: {}, kpis: {} },
  { id: 81, value: 'initialState.CcmApSpecifics.tunnel.dp_connect_resource.tunnel_cert_subject.email_address', text: 'TBD', textAlto: 'TBD', enumType: '', incidents: {}, kpis: {} },
  { id: 82, value: 'initialState.CcmApSpecifics.tunnel.dp_connect_resource.group_id', text: 'NA', textAlto: 'TBD', enumType: '', incidents: {}, kpis: {} },
  { id: 83, value: 'initialState.CcmApSpecifics.tunnel.action', text: 'TBD', textAlto: 'TBD', enumType: 'com.ruckuswireless.scg.protobuf.ccm.ApSpecifics.CcmApSpecifics.Action', incidents: {}, kpis: {} },
  { id: 84, value: 'initialState.CcmApSpecifics.radio24g.radio.adj_threshold', text: 'TBD', textAlto: 'TBD', enumType: '', incidents: {}, kpis: { clientThroughput: 1, apCapacity: 1, rss: 1 } },
  { id: 85, value: 'initialState.CcmApSpecifics.radio24g.radio.bg_scan', text: defineMessage({ defaultMessage: 'Background Scan (2.4 GHz)' }), textAlto: 'TBD', enumType: '', incidents: {}, kpis: { clientThroughput: 1, apCapacity: 1, rss: 1 } },
  { id: 86, value: 'initialState.CcmApSpecifics.radio24g.radio.bg_scan_timer', text: defineMessage({ defaultMessage: 'Background Scan Timer (2.4 GHz)' }), textAlto: 'TBD', enumType: '', incidents: {}, kpis: { clientThroughput: 1, apCapacity: 1, rss: 1 } },
  { id: 87, value: 'initialState.CcmApSpecifics.radio24g.radio.channel', text: defineMessage({ defaultMessage: 'Channel (2.4 GHz)' }), textAlto: defineMessage({ defaultMessage: 'Channel (2.4 GHz)' }), enumType: '', incidents: {}, kpis: { clientThroughput: 1, apCapacity: 1, rss: 1 } },
  { id: 88, value: 'initialState.CcmApSpecifics.radio24g.radio.channel_range', text: defineMessage({ defaultMessage: 'Channel Range (2.4 GHz)' }), textAlto: defineMessage({ defaultMessage: 'Channel Range (2.4 GHz)' }), enumType: '', incidents: {}, kpis: { clientThroughput: 1, apCapacity: 1, rss: 1 } },
  { id: 89, value: 'initialState.CcmApSpecifics.radio24g.radio.channel_select_mode', text: defineMessage({ defaultMessage: 'Auto Channel Selection: Mode (2.4 GHz)' }), textAlto: 'TBD', enumType: 'com.ruckuswireless.scg.protobuf.ccm.Zone.CcmRadio.ChannelSelectMode', incidents: {}, kpis: { clientThroughput: 1, apCapacity: 1, rss: 1 } },
  { id: 90, value: 'initialState.CcmApSpecifics.radio24g.radio.channel_width', text: defineMessage({ defaultMessage: 'Channelization: Channel Width (2.4 GHz)' }), textAlto: 'TBD', enumType: 'com.ruckuswireless.scg.protobuf.ccm.Zone.CcmRadio.ChannelWidth', incidents: {}, kpis: { clientThroughput: 1, apCapacity: 1, rss: 1 } },
  { id: 91, value: 'initialState.CcmApSpecifics.radio24g.radio.channel_fly_mtbc', text: 'TBD', textAlto: 'TBD', enumType: '', incidents: {}, kpis: { clientThroughput: 1, apCapacity: 1, rss: 1 } },
  { id: 92, value: 'initialState.CcmApSpecifics.radio24g.radio.clb_enabled', text: 'TBD', textAlto: 'TBD', enumType: '', incidents: {}, kpis: { clientThroughput: 1, apCapacity: 1, rss: 1 } },
  { id: 93, value: 'initialState.CcmApSpecifics.radio24g.radio.indoor_channel_block', text: 'TBD', textAlto: 'TBD', enumType: 'com.ruckuswireless.scg.protobuf.ccm.Zone.CcmRadio.AllowIndoorChannel', incidents: {}, kpis: { clientThroughput: 1, apCapacity: 1, rss: 1 } },
  { id: 94, value: 'initialState.CcmApSpecifics.radio24g.radio.roam_enabled', text: 'TBD', textAlto: 'TBD', enumType: '', incidents: {}, kpis: { clientThroughput: 1, apCapacity: 1, rss: 1 } },
  { id: 95, value: 'initialState.CcmApSpecifics.radio24g.radio.tax_power', text: defineMessage({ defaultMessage: 'TX Power Adjustment (2.4 GHz)' }), textAlto: 'TBD', enumType: 'com.ruckuswireless.scg.protobuf.ccm.Zone.CcmRadio.TaxPower', incidents: {}, kpis: { clientThroughput: 1, apCapacity: 1, rss: 1 } },
  { id: 96, value: 'initialState.CcmApSpecifics.radio24g.radio.client_admission.minimum_client_count', text: defineMessage({ defaultMessage: 'Client Admission Control : Min Client Count (2.4 GHz)' }), textAlto: 'TBD', enumType: '', incidents: {}, kpis: { clientThroughput: 1, apCapacity: 1, rss: 1 } },
  { id: 97, value: 'initialState.CcmApSpecifics.radio24g.radio.client_admission.maxiumum_radio_load', text: defineMessage({ defaultMessage: 'Client Admission Control: Max Radio Load (2.4 GHz)' }), textAlto: 'TBD', enumType: '', incidents: {}, kpis: { clientThroughput: 1, apCapacity: 1, rss: 1 } },
  { id: 98, value: 'initialState.CcmApSpecifics.radio24g.radio.client_admission.minimum_client_throughput', text: defineMessage({ defaultMessage: 'Client Admission Control: Min Client Throughput (2.4 GHz)' }), textAlto: 'TBD', enumType: '', incidents: {}, kpis: { clientThroughput: 1, apCapacity: 1, rss: 1 } },
  { id: 99, value: 'initialState.CcmApSpecifics.radio24g.radio.client_admission.enabled', text: defineMessage({ defaultMessage: 'Client Admission Control : Enabled (2.4 GHz)' }), textAlto: 'TBD', enumType: '', incidents: {}, kpis: { clientThroughput: 1, apCapacity: 1, rss: 1 } },
  { id: 100, value: 'initialState.CcmApSpecifics.radio24g.radio.protection_mode', text: defineMessage({ defaultMessage: 'Protection Mode (2.4 GHz)' }), textAlto: 'TBD', enumType: 'com.ruckuswireless.scg.protobuf.ccm.Zone.CcmRadio.ProtectionMode', incidents: {}, kpis: { clientThroughput: 1, apCapacity: 1, rss: 1 } },
  { id: 101, value: 'initialState.CcmApSpecifics.radio24g.radio.wlan_service_enabled', text: defineMessage({ defaultMessage: 'Wlan Service (2.4 GHz)' }), textAlto: 'TBD', enumType: '', incidents: {}, kpis: { clientThroughput: 1, apCapacity: 1, rss: 1 } },
  { id: 102, value: 'initialState.CcmApSpecifics.radio24g.radio.bg_scanner.enabled', text: defineMessage({ defaultMessage: 'Background scan : Enabled (2.4 GHz)' }), textAlto: 'TBD', enumType: '', incidents: {}, kpis: { clientThroughput: 1, apCapacity: 1, rss: 1 } },
  { id: 103, value: 'initialState.CcmApSpecifics.radio24g.radio.bg_scanner.timer', text: defineMessage({ defaultMessage: 'Background scan Timer (2.4 GHz)' }), textAlto: 'TBD', enumType: '', incidents: {}, kpis: { clientThroughput: 1, apCapacity: 1, rss: 1 } },
  { id: 104, value: 'initialState.CcmApSpecifics.radio24g.radio.auto_cell_sizing', text: defineMessage({ defaultMessage: 'Auto Cell Sizing (2.4 GHz)' }), textAlto: defineMessage({ defaultMessage: 'Auto Cell Sizing (2.4 GHz)' }), enumType: '', incidents: {}, kpis: { clientThroughput: 1, apCapacity: 1, rss: 1 } },
  { id: 105, value: 'initialState.CcmApSpecifics.radio24g.radio.weak_bypass', text: 'TBD', textAlto: 'TBD', enumType: '', incidents: {}, kpis: { clientThroughput: 1, apCapacity: 1, rss: 1 } },
  { id: 106, value: 'initialState.CcmApSpecifics.radio24g.radio.head_room', text: 'TBD', textAlto: 'TBD', enumType: '', incidents: {}, kpis: { clientThroughput: 1, apCapacity: 1, rss: 1 } },
  { id: 107, value: 'initialState.CcmApSpecifics.radio24g.radio.roam_macfilt_time', text: 'TBD', textAlto: 'TBD', enumType: '', incidents: {}, kpis: { clientThroughput: 1, apCapacity: 1, rss: 1 } },
  { id: 108, value: 'initialState.CcmApSpecifics.radio24g.radio.channel_fly_config.channel_change_frequency', text: defineMessage({ defaultMessage: 'Channel Change Frequency (2.4 GHz)' }), textAlto: 'TBD', enumType: '', incidents: {}, kpis: { clientThroughput: 1, apCapacity: 1, rss: 1 } },
  { id: 109, value: 'initialState.CcmApSpecifics.radio24g.radio.channel_fly_config.optimization_time_period', text: defineMessage({ defaultMessage: 'Full Optimization Period (2.4 GHz)' }), textAlto: 'TBD', enumType: '', incidents: {}, kpis: { clientThroughput: 1, apCapacity: 1, rss: 1 } },
  { id: 110, value: 'initialState.CcmApSpecifics.radio5g.radio.adj_threshold', text: 'TBD', textAlto: 'TBD', enumType: '', incidents: {}, kpis: { clientThroughput: 1, apCapacity: 1, rss: 1 } },
  { id: 111, value: 'initialState.CcmApSpecifics.radio5g.radio.bg_scan', text: defineMessage({ defaultMessage: 'Background Scan (5 GHz)' }), textAlto: 'TBD', enumType: '', incidents: {}, kpis: { clientThroughput: 1, apCapacity: 1, rss: 1 } },
  { id: 112, value: 'initialState.CcmApSpecifics.radio5g.radio.bg_scan_timer', text: defineMessage({ defaultMessage: 'Background Scan  Timer (5 GHz)' }), textAlto: 'TBD', enumType: '', incidents: {}, kpis: { clientThroughput: 1, apCapacity: 1, rss: 1 } },
  { id: 113, value: 'initialState.CcmApSpecifics.radio5g.radio.channel', text: defineMessage({ defaultMessage: 'Channel (5 GHz)' }), textAlto: defineMessage({ defaultMessage: 'Channel (5 GHz)' }), enumType: '', incidents: {}, kpis: { clientThroughput: 1, apCapacity: 1, rss: 1 } },
  { id: 114, value: 'initialState.CcmApSpecifics.radio5g.radio.channel_range', text: defineMessage({ defaultMessage: 'Channel Range (5 GHz)' }), textAlto: defineMessage({ defaultMessage: 'Channel Range (5 GHz)' }), enumType: '', incidents: {}, kpis: { clientThroughput: 1, apCapacity: 1, rss: 1 } },
  { id: 115, value: 'initialState.CcmApSpecifics.radio5g.radio.channel_select_mode', text: 'TBD', textAlto: 'TBD', enumType: 'com.ruckuswireless.scg.protobuf.ccm.Zone.CcmRadio.ChannelSelectMode', incidents: {}, kpis: { clientThroughput: 1, apCapacity: 1, rss: 1 } },
  { id: 116, value: 'initialState.CcmApSpecifics.radio5g.radio.channel_width', text: defineMessage({ defaultMessage: 'Channelization: Channel Width (5 GHz)' }), textAlto: 'TBD', enumType: 'com.ruckuswireless.scg.protobuf.ccm.Zone.CcmRadio.ChannelWidth', incidents: {}, kpis: { clientThroughput: 1, apCapacity: 1, rss: 1 } },
  { id: 117, value: 'initialState.CcmApSpecifics.radio5g.radio.channel_fly_mtbc', text: 'TBD', textAlto: 'TBD', enumType: '', incidents: {}, kpis: { clientThroughput: 1, apCapacity: 1, rss: 1 } },
  { id: 118, value: 'initialState.CcmApSpecifics.radio5g.radio.clb_enabled', text: 'TBD', textAlto: 'TBD', enumType: '', incidents: {}, kpis: { clientThroughput: 1, apCapacity: 1, rss: 1 } },
  { id: 119, value: 'initialState.CcmApSpecifics.radio5g.radio.indoor_channel_block', text: 'TBD', textAlto: 'TBD', enumType: 'com.ruckuswireless.scg.protobuf.ccm.Zone.CcmRadio.AllowIndoorChannel', incidents: {}, kpis: { clientThroughput: 1, apCapacity: 1, rss: 1 } },
  { id: 120, value: 'initialState.CcmApSpecifics.radio5g.radio.roam_enabled', text: 'TBD', textAlto: 'TBD', enumType: '', incidents: {}, kpis: { clientThroughput: 1, apCapacity: 1, rss: 1 } },
  { id: 121, value: 'initialState.CcmApSpecifics.radio5g.radio.tax_power', text: defineMessage({ defaultMessage: 'TX Power Adjustment (5 GHz)' }), textAlto: 'TBD', enumType: 'com.ruckuswireless.scg.protobuf.ccm.Zone.CcmRadio.TaxPower', incidents: {}, kpis: { clientThroughput: 1, apCapacity: 1, rss: 1 } },
  { id: 122, value: 'initialState.CcmApSpecifics.radio5g.radio.client_admission.minimum_client_count', text: defineMessage({ defaultMessage: 'Client Admission Control: Min Client Count (5 GHz)' }), textAlto: 'TBD', enumType: '', incidents: {}, kpis: { clientThroughput: 1, apCapacity: 1, rss: 1 } },
  { id: 123, value: 'initialState.CcmApSpecifics.radio5g.radio.client_admission.maxiumum_radio_load', text: defineMessage({ defaultMessage: 'Client Admission Control: Max Radio Load (5 GHz)' }), textAlto: 'TBD', enumType: '', incidents: {}, kpis: { clientThroughput: 1, apCapacity: 1, rss: 1 } },
  { id: 124, value: 'initialState.CcmApSpecifics.radio5g.radio.client_admission.minimum_client_throughput', text: defineMessage({ defaultMessage: 'Client Admission Control: Min Client Throughput (5 GHz)' }), textAlto: 'TBD', enumType: '', incidents: {}, kpis: { clientThroughput: 1, apCapacity: 1, rss: 1 } },
  { id: 125, value: 'initialState.CcmApSpecifics.radio5g.radio.client_admission.enabled', text: defineMessage({ defaultMessage: 'Client Admission control : Enabled (5 GHz)' }), textAlto: 'TBD', enumType: '', incidents: {}, kpis: { clientThroughput: 1, apCapacity: 1, rss: 1 } },
  { id: 126, value: 'initialState.CcmApSpecifics.radio5g.radio.protection_mode', text: defineMessage({ defaultMessage: 'Protection Mode (5 GHz)' }), textAlto: 'TBD', enumType: 'com.ruckuswireless.scg.protobuf.ccm.Zone.CcmRadio.ProtectionMode', incidents: {}, kpis: { clientThroughput: 1, apCapacity: 1, rss: 1 } },
  { id: 127, value: 'initialState.CcmApSpecifics.radio5g.radio.wlan_service_enabled', text: defineMessage({ defaultMessage: 'Wlan Service (5 GHz)' }), textAlto: 'TBD', enumType: '', incidents: {}, kpis: { clientThroughput: 1, apCapacity: 1, rss: 1 } },
  { id: 128, value: 'initialState.CcmApSpecifics.radio5g.radio.bg_scanner.enabled', text: defineMessage({ defaultMessage: 'Background scan : Enabled (5 GHz)' }), textAlto: 'TBD', enumType: '', incidents: {}, kpis: { clientThroughput: 1, apCapacity: 1, rss: 1 } },
  { id: 129, value: 'initialState.CcmApSpecifics.radio5g.radio.bg_scanner.timer', text: defineMessage({ defaultMessage: 'Background scan timer (5 GHz)' }), textAlto: 'TBD', enumType: '', incidents: {}, kpis: { clientThroughput: 1, apCapacity: 1, rss: 1 } },
  { id: 130, value: 'initialState.CcmApSpecifics.radio5g.radio.auto_cell_sizing', text: defineMessage({ defaultMessage: 'Auto Cell Sizing (5 GHz)' }), textAlto: defineMessage({ defaultMessage: 'Auto Cell Sizing (5 GHz)' }), enumType: '', incidents: {}, kpis: { clientThroughput: 1, apCapacity: 1, rss: 1 } },
  { id: 131, value: 'initialState.CcmApSpecifics.radio5g.radio.weak_bypass', text: 'TBD', textAlto: 'TBD', enumType: '', incidents: {}, kpis: { clientThroughput: 1, apCapacity: 1, rss: 1 } },
  { id: 132, value: 'initialState.CcmApSpecifics.radio5g.radio.head_room', text: 'TBD', textAlto: 'TBD', enumType: '', incidents: {}, kpis: { clientThroughput: 1, apCapacity: 1, rss: 1 } },
  { id: 133, value: 'initialState.CcmApSpecifics.radio5g.radio.roam_macfilt_time', text: 'TBD', textAlto: 'TBD', enumType: '', incidents: {}, kpis: { clientThroughput: 1, apCapacity: 1, rss: 1 } },
  { id: 134, value: 'initialState.CcmApSpecifics.radio5g.radio.channel_fly_config.channel_change_frequency', text: defineMessage({ defaultMessage: 'Channel Change Frequency (5 GHz)' }), textAlto: 'TBD', enumType: '', incidents: {}, kpis: { clientThroughput: 1, apCapacity: 1, rss: 1 } },
  { id: 135, value: 'initialState.CcmApSpecifics.radio5g.radio.channel_fly_config.optimization_time_period', text: defineMessage({ defaultMessage: 'Full Optimization Period (5 GHz)' }), textAlto: 'TBD', enumType: '', incidents: {}, kpis: { clientThroughput: 1, apCapacity: 1, rss: 1 } },
  { id: 136, value: 'initialState.CcmApSpecifics.radio5g.secondary_channel', text: 'TBD', textAlto: 'TBD', enumType: '', incidents: {}, kpis: { clientThroughput: 1, apCapacity: 1, rss: 1 } },
  { id: 137, value: 'initialState.CcmApSpecifics.radio5g.indoor_secondary_channel', text: 'TBD', textAlto: 'TBD', enumType: '', incidents: {}, kpis: { clientThroughput: 1, apCapacity: 1, rss: 1 } },
  { id: 138, value: 'initialState.CcmApSpecifics.radio5g.indoor_channel_range', text: defineMessage({ defaultMessage: 'Channel Range (5 GHz) Indoor' }), textAlto: 'TBD', enumType: '', incidents: {}, kpis: { clientThroughput: 1, apCapacity: 1, rss: 1 } },
  { id: 139, value: 'initialState.CcmApSpecifics.radio5g.indoor_channel', text: defineMessage({ defaultMessage: 'Channel (5 GHz) Indoor' }), textAlto: 'TBD', enumType: '', incidents: {}, kpis: { clientThroughput: 1, apCapacity: 1, rss: 1 } },
  { id: 140, value: 'initialState.CcmApSpecifics.capabilities.is_outdoor', text: 'TBD', textAlto: 'TBD', enumType: '', incidents: {}, kpis: {} },
  { id: 141, value: 'initialState.CcmApSpecifics.capabilities.is_dual_radio', text: 'TBD', textAlto: 'TBD', enumType: '', incidents: {}, kpis: {} },
  { id: 142, value: 'initialState.CcmApSpecifics.capabilities.has_cable_modem', text: 'TBD', textAlto: 'TBD', enumType: '', incidents: {}, kpis: {} },
  { id: 143, value: 'initialState.CcmApSpecifics.capabilities.support_reset_cable_modem', text: 'TBD', textAlto: 'TBD', enumType: '', incidents: {}, kpis: {} },
  { id: 144, value: 'initialState.CcmApSpecifics.capabilities.support_bonjour', text: 'TBD', textAlto: 'TBD', enumType: '', incidents: {}, kpis: {} },
  { id: 145, value: 'initialState.CcmApSpecifics.capabilities.support_lbs', text: 'TBD', textAlto: 'TBD', enumType: '', incidents: {}, kpis: {} },
  { id: 146, value: 'initialState.CcmApSpecifics.capabilities.support_bandswitch', text: 'TBD', textAlto: 'TBD', enumType: '', incidents: {}, kpis: {} },
  { id: 147, value: 'initialState.CcmApSpecifics.capabilities.support_ipsec', text: 'TBD', textAlto: 'TBD', enumType: '', incidents: {}, kpis: {} },
  { id: 148, value: 'initialState.CcmApSpecifics.capabilities.support_ap_usb_software_package', text: 'TBD', textAlto: 'TBD', enumType: '', incidents: {}, kpis: {} },
  { id: 149, value: 'initialState.CcmApSpecifics.capabilities.is_usb_power_enabled', text: 'TBD', textAlto: 'TBD', enumType: '', incidents: {}, kpis: {} },
  { id: 150, value: 'initialState.CcmApSpecifics.capabilities.has_gps', text: 'TBD', textAlto: 'TBD', enumType: '', incidents: {}, kpis: {} },
  { id: 151, value: 'initialState.CcmApSpecifics.capabilities.maximum_wlan_size_for_2_4_g', text: 'TBD', textAlto: 'TBD', enumType: '', incidents: {}, kpis: {} },
  { id: 152, value: 'initialState.CcmApSpecifics.capabilities.maximum_wlan_size_for_5_g', text: 'TBD', textAlto: 'TBD', enumType: '', incidents: {}, kpis: {} },
  { id: 153, value: 'initialState.CcmApSpecifics.capabilities.maximum_channel_width_for_2_4_g', text: 'TBD', textAlto: 'TBD', enumType: 'com.ruckuswireless.scg.protobuf.ccm.Zone.CcmRadio.ChannelWidth', incidents: {}, kpis: {} },
  { id: 154, value: 'initialState.CcmApSpecifics.capabilities.maximum_channel_width_for_5_g', text: 'TBD', textAlto: 'TBD', enumType: 'com.ruckuswireless.scg.protobuf.ccm.Zone.CcmRadio.ChannelWidth', incidents: {}, kpis: {} },
  { id: 155, value: 'initialState.CcmApSpecifics.capabilities.default_channel_width_for_5_g', text: 'TBD', textAlto: 'TBD', enumType: 'com.ruckuswireless.scg.protobuf.ccm.Zone.CcmRadio.ChannelWidth', incidents: {}, kpis: {} },
  { id: 156, value: 'initialState.CcmApSpecifics.capabilities.default_channel_width_for_2_4_g', text: 'TBD', textAlto: 'TBD', enumType: 'com.ruckuswireless.scg.protobuf.ccm.Zone.CcmRadio.ChannelWidth', incidents: {}, kpis: {} },
  { id: 157, value: 'initialState.CcmApSpecifics.capabilities.number_of_wlan_reserved_for_mesh_support_in_5_g', text: 'TBD', textAlto: 'TBD', enumType: '', incidents: {}, kpis: {} },
  { id: 158, value: 'initialState.CcmApSpecifics.capabilities.support_11_ac', text: 'TBD', textAlto: 'TBD', enumType: '', incidents: {}, kpis: {} },
  { id: 159, value: 'initialState.CcmApSpecifics.capabilities.support_channel_width_160', text: 'TBD', textAlto: 'TBD', enumType: '', incidents: {}, kpis: {} },
  { id: 160, value: 'initialState.CcmApSpecifics.capabilities.has_scan_radio', text: 'TBD', textAlto: 'TBD', enumType: '', incidents: {}, kpis: {} },
  { id: 161, value: 'initialState.CcmApSpecifics.capabilities.countries_that_allows_dynamic_frequencies', text: 'TBD', textAlto: 'TBD', enumType: '', incidents: {}, kpis: {} },
  { id: 162, value: 'initialState.CcmApSpecifics.capabilities.support_mesh', text: 'TBD', textAlto: 'TBD', enumType: '', incidents: {}, kpis: {} },
  { id: 163, value: 'initialState.CcmApSpecifics.capabilities.support_cellular', text: 'TBD', textAlto: 'TBD', enumType: '', incidents: {}, kpis: {} },
  { id: 164, value: 'initialState.CcmApSpecifics.capabilities.lacp_enable', text: 'TBD', textAlto: 'TBD', enumType: '', incidents: {}, kpis: {} },
  { id: 165, value: 'initialState.CcmApSpecifics.capabilities.mesh_radio_caps', text: 'TBD', textAlto: 'TBD', enumType: '', incidents: {}, kpis: {} },
  { id: 166, value: 'initialState.CcmApSpecifics.ccmLbs.enabled', text: 'TBD', textAlto: 'TBD', enumType: '', incidents: {}, kpis: {} },
  { id: 167, value: 'initialState.CcmApSpecifics.ccmLbs.profile_id', text: 'NA', textAlto: 'TBD', enumType: '', incidents: {}, kpis: {} },
  { id: 168, value: 'initialState.CcmApSpecifics.rehome_timestamp', text: 'TBD', textAlto: 'TBD', enumType: '', incidents: {}, kpis: {} },
  { id: 169, value: 'initialState.CcmApSpecifics.rebalance_timestamp', text: 'TBD', textAlto: 'TBD', enumType: '', incidents: {}, kpis: {} },
  { id: 170, value: 'initialState.CcmApSpecifics.indoor_map.id', text: 'NA', textAlto: 'TBD', enumType: '', incidents: {}, kpis: {} },
  { id: 171, value: 'initialState.CcmApSpecifics.indoor_map.name', text: defineMessage({ defaultMessage: 'Name' }), textAlto: 'TBD', enumType: '', incidents: {}, kpis: {} },
  { id: 172, value: 'initialState.CcmApSpecifics.ideal_event_required', text: 'TBD', textAlto: 'TBD', enumType: '', incidents: {}, kpis: {} },
  { id: 173, value: 'initialState.CcmApSpecifics.node_affinity_trigger_timestamp', text: 'TBD', textAlto: 'TBD', enumType: '', incidents: {}, kpis: {} },
  { id: 175, value: 'initialState.CcmApSpecifics.model_settings.model_specific_ethernet_port_settings.vni', text: 'TBD', textAlto: 'TBD', enumType: '', incidents: {}, kpis: {} },
  { id: 176, value: 'initialState.CcmApSpecifics.radio24g.radio.radio_enabled', text: 'TBD', textAlto: 'TBD', enumType: '', incidents: {}, kpis: {} },
  { id: 177, value: 'initialState.CcmApSpecifics.radio5g.cband_channel_enable', text: 'TBD', textAlto: 'TBD', enumType: '', incidents: {}, kpis: {} },
  { id: 178, value: 'initialState.CcmApSpecifics.radio5g.cband_channel_license', text: 'TBD', textAlto: 'TBD', enumType: '', incidents: {}, kpis: {} },
  { id: 179, value: 'initialState.CcmApSpecifics.radio5g.channel_144_enable', text: 'TBD', textAlto: 'TBD', enumType: '', incidents: {}, kpis: {} },
  { id: 180, value: 'initialState.CcmApSpecifics.radio5g.radio.radio_enabled', text: 'TBD', textAlto: 'TBD', enumType: '', incidents: {}, kpis: {} },
  { id: 181, value: 'initialState.CcmApSpecifics.radio_configs.dual_5g_enable', text: defineMessage({ defaultMessage: 'Dual 5G : Enabled' }), textAlto: 'TBD', enumType: '', incidents: {}, kpis: {} },
  { id: 182, value: 'initialState.CcmApSpecifics.radio_configs.radio24g.radio.adj_threshold', text: 'TBD', textAlto: 'TBD', enumType: '', incidents: {}, kpis: {} },
  { id: 183, value: 'initialState.CcmApSpecifics.radio_configs.radio24g.radio.auto_cell_sizing', text: 'TBD', textAlto: 'TBD', enumType: '', incidents: {}, kpis: {} },
  { id: 184, value: 'initialState.CcmApSpecifics.radio_configs.radio24g.radio.bg_scan', text: 'TBD', textAlto: 'TBD', enumType: '', incidents: {}, kpis: {} },
  { id: 185, value: 'initialState.CcmApSpecifics.radio_configs.radio24g.radio.bg_scan_timer', text: 'TBD', textAlto: 'TBD', enumType: '', incidents: {}, kpis: {} },
  { id: 186, value: 'initialState.CcmApSpecifics.radio_configs.radio24g.radio.bg_scanner.enabled', text: 'TBD', textAlto: 'TBD', enumType: '', incidents: {}, kpis: {} },
  { id: 187, value: 'initialState.CcmApSpecifics.radio_configs.radio24g.radio.bg_scanner.timer', text: 'TBD', textAlto: 'TBD', enumType: '', incidents: {}, kpis: {} },
  { id: 188, value: 'initialState.CcmApSpecifics.radio_configs.radio24g.radio.channel', text: 'TBD', textAlto: 'TBD', enumType: '', incidents: {}, kpis: {} },
  { id: 189, value: 'initialState.CcmApSpecifics.radio_configs.radio24g.radio.channel_fly_config.channel_change_frequency', text: 'TBD', textAlto: 'TBD', enumType: '', incidents: {}, kpis: {} },
  { id: 190, value: 'initialState.CcmApSpecifics.radio_configs.radio24g.radio.channel_fly_config.optimization_time_period', text: 'TBD', textAlto: 'TBD', enumType: '', incidents: {}, kpis: {} },
  { id: 191, value: 'initialState.CcmApSpecifics.radio_configs.radio24g.radio.channel_fly_mtbc', text: 'TBD', textAlto: 'TBD', enumType: '', incidents: {}, kpis: {} },
  { id: 192, value: 'initialState.CcmApSpecifics.radio_configs.radio24g.radio.channel_range', text: 'TBD', textAlto: 'TBD', enumType: '', incidents: {}, kpis: {} },
  { id: 193, value: 'initialState.CcmApSpecifics.radio_configs.radio24g.radio.channel_select_mode', text: 'TBD', textAlto: 'TBD', enumType: 'com.ruckuswireless.scg.protobuf.ccm.Zone.CcmRadio.ChannelSelectMode', incidents: {}, kpis: {} },
  { id: 194, value: 'initialState.CcmApSpecifics.radio_configs.radio24g.radio.channel_width', text: 'TBD', textAlto: 'TBD', enumType: 'com.ruckuswireless.scg.protobuf.ccm.Zone.CcmRadio.ChannelWidth', incidents: {}, kpis: {} },
  { id: 195, value: 'initialState.CcmApSpecifics.radio_configs.radio24g.radio.clb_enabled', text: 'TBD', textAlto: 'TBD', enumType: '', incidents: {}, kpis: {} },
  { id: 196, value: 'initialState.CcmApSpecifics.radio_configs.radio24g.radio.client_admission.enabled', text: 'TBD', textAlto: 'TBD', enumType: '', incidents: {}, kpis: {} },
  { id: 197, value: 'initialState.CcmApSpecifics.radio_configs.radio24g.radio.client_admission.maxiumum_radio_load', text: 'TBD', textAlto: 'TBD', enumType: '', incidents: {}, kpis: {} },
  { id: 198, value: 'initialState.CcmApSpecifics.radio_configs.radio24g.radio.client_admission.minimum_client_count', text: 'TBD', textAlto: 'TBD', enumType: '', incidents: {}, kpis: {} },
  { id: 199, value: 'initialState.CcmApSpecifics.radio_configs.radio24g.radio.client_admission.minimum_client_throughput', text: 'TBD', textAlto: 'TBD', enumType: '', incidents: {}, kpis: {} },
  { id: 200, value: 'initialState.CcmApSpecifics.radio_configs.radio24g.radio.head_room', text: 'TBD', textAlto: 'TBD', enumType: '', incidents: {}, kpis: {} },
  { id: 201, value: 'initialState.CcmApSpecifics.radio_configs.radio24g.radio.indoor_channel_block', text: 'TBD', textAlto: 'TBD', enumType: 'com.ruckuswireless.scg.protobuf.ccm.Zone.CcmRadio.AllowIndoorChannel', incidents: {}, kpis: {} },
  { id: 202, value: 'initialState.CcmApSpecifics.radio_configs.radio24g.radio.protection_mode', text: 'TBD', textAlto: 'TBD', enumType: 'com.ruckuswireless.scg.protobuf.ccm.Zone.CcmRadio.ProtectionMode', incidents: {}, kpis: {} },
  { id: 203, value: 'initialState.CcmApSpecifics.radio_configs.radio24g.radio.radio_enabled', text: 'TBD', textAlto: 'TBD', enumType: '', incidents: {}, kpis: {} },
  { id: 204, value: 'initialState.CcmApSpecifics.radio_configs.radio24g.radio.roam_enabled', text: 'TBD', textAlto: 'TBD', enumType: '', incidents: {}, kpis: {} },
  { id: 205, value: 'initialState.CcmApSpecifics.radio_configs.radio24g.radio.roam_macfilt_time', text: 'TBD', textAlto: 'TBD', enumType: '', incidents: {}, kpis: {} },
  { id: 206, value: 'initialState.CcmApSpecifics.radio_configs.radio24g.radio.tax_power', text: 'TBD', textAlto: 'TBD', enumType: 'com.ruckuswireless.scg.protobuf.ccm.Zone.CcmRadio.TaxPower', incidents: {}, kpis: {} },
  { id: 207, value: 'initialState.CcmApSpecifics.radio_configs.radio24g.radio.weak_bypass', text: 'TBD', textAlto: 'TBD', enumType: '', incidents: {}, kpis: {} },
  { id: 208, value: 'initialState.CcmApSpecifics.radio_configs.radio24g.radio.wlan_service_enabled', text: 'TBD', textAlto: 'TBD', enumType: '', incidents: {}, kpis: {} },
  { id: 209, value: 'initialState.CcmApSpecifics.radio_configs.radio5g.cband_channel_enable', text: 'TBD', textAlto: 'TBD', enumType: '', incidents: {}, kpis: {} },
  { id: 210, value: 'initialState.CcmApSpecifics.radio_configs.radio5g.cband_channel_license', text: 'TBD', textAlto: 'TBD', enumType: '', incidents: {}, kpis: {} },
  { id: 211, value: 'initialState.CcmApSpecifics.radio_configs.radio5g.channel_144_enable', text: 'TBD', textAlto: 'TBD', enumType: '', incidents: {}, kpis: {} },
  { id: 212, value: 'initialState.CcmApSpecifics.radio_configs.radio5g.indoor_channel', text: 'TBD', textAlto: 'TBD', enumType: '', incidents: {}, kpis: {} },
  { id: 213, value: 'initialState.CcmApSpecifics.radio_configs.radio5g.indoor_channel_range', text: 'TBD', textAlto: 'TBD', enumType: '', incidents: {}, kpis: {} },
  { id: 214, value: 'initialState.CcmApSpecifics.radio_configs.radio5g.indoor_secondary_channel', text: 'TBD', textAlto: 'TBD', enumType: '', incidents: {}, kpis: {} },
  { id: 215, value: 'initialState.CcmApSpecifics.radio_configs.radio5g.radio.adj_threshold', text: 'TBD', textAlto: 'TBD', enumType: '', incidents: {}, kpis: {} },
  { id: 216, value: 'initialState.CcmApSpecifics.radio_configs.radio5g.radio.auto_cell_sizing', text: 'TBD', textAlto: 'TBD', enumType: '', incidents: {}, kpis: {} },
  { id: 217, value: 'initialState.CcmApSpecifics.radio_configs.radio5g.radio.bg_scan', text: 'TBD', textAlto: 'TBD', enumType: '', incidents: {}, kpis: {} },
  { id: 218, value: 'initialState.CcmApSpecifics.radio_configs.radio5g.radio.bg_scan_timer', text: 'TBD', textAlto: 'TBD', enumType: '', incidents: {}, kpis: {} },
  { id: 219, value: 'initialState.CcmApSpecifics.radio_configs.radio5g.radio.bg_scanner.enabled', text: 'TBD', textAlto: 'TBD', enumType: '', incidents: {}, kpis: {} },
  { id: 220, value: 'initialState.CcmApSpecifics.radio_configs.radio5g.radio.bg_scanner.timer', text: 'TBD', textAlto: 'TBD', enumType: '', incidents: {}, kpis: {} },
  { id: 221, value: 'initialState.CcmApSpecifics.radio_configs.radio5g.radio.channel', text: 'TBD', textAlto: 'TBD', enumType: '', incidents: {}, kpis: {} },
  { id: 222, value: 'initialState.CcmApSpecifics.radio_configs.radio5g.radio.channel_fly_config.channel_change_frequency', text: 'TBD', textAlto: 'TBD', enumType: '', incidents: {}, kpis: {} },
  { id: 223, value: 'initialState.CcmApSpecifics.radio_configs.radio5g.radio.channel_fly_config.optimization_time_period', text: 'TBD', textAlto: 'TBD', enumType: '', incidents: {}, kpis: {} },
  { id: 224, value: 'initialState.CcmApSpecifics.radio_configs.radio5g.radio.channel_fly_mtbc', text: 'TBD', textAlto: 'TBD', enumType: '', incidents: {}, kpis: {} },
  { id: 225, value: 'initialState.CcmApSpecifics.radio_configs.radio5g.radio.channel_range', text: 'TBD', textAlto: 'TBD', enumType: '', incidents: {}, kpis: {} },
  { id: 226, value: 'initialState.CcmApSpecifics.radio_configs.radio5g.radio.channel_select_mode', text: 'TBD', textAlto: 'TBD', enumType: 'com.ruckuswireless.scg.protobuf.ccm.Zone.CcmRadio.ChannelSelectMode', incidents: {}, kpis: {} },
  { id: 227, value: 'initialState.CcmApSpecifics.radio_configs.radio5g.radio.channel_width', text: 'TBD', textAlto: 'TBD', enumType: 'com.ruckuswireless.scg.protobuf.ccm.Zone.CcmRadio.ChannelWidth', incidents: {}, kpis: {} },
  { id: 228, value: 'initialState.CcmApSpecifics.radio_configs.radio5g.radio.clb_enabled', text: 'TBD', textAlto: 'TBD', enumType: '', incidents: {}, kpis: {} },
  { id: 229, value: 'initialState.CcmApSpecifics.radio_configs.radio5g.radio.client_admission.enabled', text: 'TBD', textAlto: 'TBD', enumType: '', incidents: {}, kpis: {} },
  { id: 230, value: 'initialState.CcmApSpecifics.radio_configs.radio5g.radio.client_admission.maxiumum_radio_load', text: 'TBD', textAlto: 'TBD', enumType: '', incidents: {}, kpis: {} },
  { id: 231, value: 'initialState.CcmApSpecifics.radio_configs.radio5g.radio.client_admission.minimum_client_count', text: 'TBD', textAlto: 'TBD', enumType: '', incidents: {}, kpis: {} },
  { id: 232, value: 'initialState.CcmApSpecifics.radio_configs.radio5g.radio.client_admission.minimum_client_throughput', text: 'TBD', textAlto: 'TBD', enumType: '', incidents: {}, kpis: {} },
  { id: 233, value: 'initialState.CcmApSpecifics.radio_configs.radio5g.radio.head_room', text: 'TBD', textAlto: 'TBD', enumType: '', incidents: {}, kpis: {} },
  { id: 234, value: 'initialState.CcmApSpecifics.radio_configs.radio5g.radio.indoor_channel_block', text: 'TBD', textAlto: 'TBD', enumType: 'com.ruckuswireless.scg.protobuf.ccm.Zone.CcmRadio.AllowIndoorChannel', incidents: {}, kpis: {} },
  { id: 235, value: 'initialState.CcmApSpecifics.radio_configs.radio5g.radio.protection_mode', text: 'TBD', textAlto: 'TBD', enumType: 'com.ruckuswireless.scg.protobuf.ccm.Zone.CcmRadio.ProtectionMode', incidents: {}, kpis: {} },
  { id: 236, value: 'initialState.CcmApSpecifics.radio_configs.radio5g.radio.radio_enabled', text: 'TBD', textAlto: 'TBD', enumType: '', incidents: {}, kpis: {} },
  { id: 237, value: 'initialState.CcmApSpecifics.radio_configs.radio5g.radio.roam_enabled', text: 'TBD', textAlto: 'TBD', enumType: '', incidents: {}, kpis: {} },
  { id: 238, value: 'initialState.CcmApSpecifics.radio_configs.radio5g.radio.roam_macfilt_time', text: 'TBD', textAlto: 'TBD', enumType: '', incidents: {}, kpis: {} },
  { id: 239, value: 'initialState.CcmApSpecifics.radio_configs.radio5g.radio.tax_power', text: 'TBD', textAlto: 'TBD', enumType: 'com.ruckuswireless.scg.protobuf.ccm.Zone.CcmRadio.TaxPower', incidents: {}, kpis: {} },
  { id: 240, value: 'initialState.CcmApSpecifics.radio_configs.radio5g.radio.weak_bypass', text: 'TBD', textAlto: 'TBD', enumType: '', incidents: {}, kpis: {} },
  { id: 241, value: 'initialState.CcmApSpecifics.radio_configs.radio5g.radio.wlan_service_enabled', text: 'TBD', textAlto: 'TBD', enumType: '', incidents: {}, kpis: {} },
  { id: 242, value: 'initialState.CcmApSpecifics.radio_configs.radio5g.secondary_channel', text: 'TBD', textAlto: 'TBD', enumType: '', incidents: {}, kpis: {} },
  { id: 243, value: 'initialState.CcmApSpecifics.radio_configs.radio5gLower.cband_channel_enable', text: 'TBD', textAlto: 'TBD', enumType: '', incidents: {}, kpis: {} },
  { id: 244, value: 'initialState.CcmApSpecifics.radio_configs.radio5gLower.cband_channel_license', text: 'TBD', textAlto: 'TBD', enumType: '', incidents: {}, kpis: {} },
  { id: 245, value: 'initialState.CcmApSpecifics.radio_configs.radio5gLower.channel_144_enable', text: 'TBD', textAlto: 'TBD', enumType: '', incidents: {}, kpis: {} },
  { id: 246, value: 'initialState.CcmApSpecifics.radio_configs.radio5gLower.indoor_channel', text: 'TBD', textAlto: 'TBD', enumType: '', incidents: {}, kpis: {} },
  { id: 247, value: 'initialState.CcmApSpecifics.radio_configs.radio5gLower.indoor_channel_range', text: 'TBD', textAlto: 'TBD', enumType: '', incidents: {}, kpis: {} },
  { id: 248, value: 'initialState.CcmApSpecifics.radio_configs.radio5gLower.indoor_secondary_channel', text: 'TBD', textAlto: 'TBD', enumType: '', incidents: {}, kpis: {} },
  { id: 249, value: 'initialState.CcmApSpecifics.radio_configs.radio5gLower.radio.adj_threshold', text: 'TBD', textAlto: 'TBD', enumType: '', incidents: {}, kpis: {} },
  { id: 250, value: 'initialState.CcmApSpecifics.radio_configs.radio5gLower.radio.auto_cell_sizing', text: 'TBD', textAlto: 'TBD', enumType: '', incidents: {}, kpis: {} },
  { id: 251, value: 'initialState.CcmApSpecifics.radio_configs.radio5gLower.radio.bg_scan', text: 'TBD', textAlto: 'TBD', enumType: '', incidents: {}, kpis: {} },
  { id: 252, value: 'initialState.CcmApSpecifics.radio_configs.radio5gLower.radio.bg_scan_timer', text: 'TBD', textAlto: 'TBD', enumType: '', incidents: {}, kpis: {} },
  { id: 253, value: 'initialState.CcmApSpecifics.radio_configs.radio5gLower.radio.bg_scanner.enabled', text: 'TBD', textAlto: 'TBD', enumType: '', incidents: {}, kpis: {} },
  { id: 254, value: 'initialState.CcmApSpecifics.radio_configs.radio5gLower.radio.bg_scanner.timer', text: 'TBD', textAlto: 'TBD', enumType: '', incidents: {}, kpis: {} },
  { id: 255, value: 'initialState.CcmApSpecifics.radio_configs.radio5gLower.radio.channel', text: defineMessage({ defaultMessage: 'Channel (Lower 5 GHz)' }), textAlto: 'TBD', enumType: '', incidents: {}, kpis: {} },
  { id: 256, value: 'initialState.CcmApSpecifics.radio_configs.radio5gLower.radio.channel_fly_config.channel_change_frequency', text: 'TBD', textAlto: 'TBD', enumType: '', incidents: {}, kpis: {} },
  { id: 257, value: 'initialState.CcmApSpecifics.radio_configs.radio5gLower.radio.channel_fly_config.optimization_time_period', text: 'TBD', textAlto: 'TBD', enumType: '', incidents: {}, kpis: {} },
  { id: 258, value: 'initialState.CcmApSpecifics.radio_configs.radio5gLower.radio.channel_fly_mtbc', text: 'TBD', textAlto: 'TBD', enumType: '', incidents: {}, kpis: {} },
  { id: 259, value: 'initialState.CcmApSpecifics.radio_configs.radio5gLower.radio.channel_range', text: defineMessage({ defaultMessage: 'Channel Range (Lower 5 GHz)' }), textAlto: 'TBD', enumType: '', incidents: {}, kpis: {} },
  { id: 260, value: 'initialState.CcmApSpecifics.radio_configs.radio5gLower.radio.channel_select_mode', text: 'TBD', textAlto: 'TBD', enumType: 'com.ruckuswireless.scg.protobuf.ccm.Zone.CcmRadio.ChannelSelectMode', incidents: {}, kpis: {} },
  { id: 261, value: 'initialState.CcmApSpecifics.radio_configs.radio5gLower.radio.channel_width', text: defineMessage({ defaultMessage: 'Channel Width(Lower 5 GHz)' }), textAlto: 'TBD', enumType: 'com.ruckuswireless.scg.protobuf.ccm.Zone.CcmRadio.ChannelWidth', incidents: {}, kpis: {} },
  { id: 262, value: 'initialState.CcmApSpecifics.radio_configs.radio5gLower.radio.clb_enabled', text: 'TBD', textAlto: 'TBD', enumType: '', incidents: {}, kpis: {} },
  { id: 263, value: 'initialState.CcmApSpecifics.radio_configs.radio5gLower.radio.client_admission.enabled', text: 'TBD', textAlto: 'TBD', enumType: '', incidents: {}, kpis: {} },
  { id: 264, value: 'initialState.CcmApSpecifics.radio_configs.radio5gLower.radio.client_admission.maxiumum_radio_load', text: 'TBD', textAlto: 'TBD', enumType: '', incidents: {}, kpis: {} },
  { id: 265, value: 'initialState.CcmApSpecifics.radio_configs.radio5gLower.radio.client_admission.minimum_client_count', text: 'TBD', textAlto: 'TBD', enumType: '', incidents: {}, kpis: {} },
  { id: 266, value: 'initialState.CcmApSpecifics.radio_configs.radio5gLower.radio.client_admission.minimum_client_throughput', text: 'TBD', textAlto: 'TBD', enumType: '', incidents: {}, kpis: {} },
  { id: 267, value: 'initialState.CcmApSpecifics.radio_configs.radio5gLower.radio.head_room', text: 'TBD', textAlto: 'TBD', enumType: '', incidents: {}, kpis: {} },
  { id: 268, value: 'initialState.CcmApSpecifics.radio_configs.radio5gLower.radio.indoor_channel_block', text: 'TBD', textAlto: 'TBD', enumType: 'com.ruckuswireless.scg.protobuf.ccm.Zone.CcmRadio.AllowIndoorChannel', incidents: {}, kpis: {} },
  { id: 269, value: 'initialState.CcmApSpecifics.radio_configs.radio5gLower.radio.protection_mode', text: 'TBD', textAlto: 'TBD', enumType: 'com.ruckuswireless.scg.protobuf.ccm.Zone.CcmRadio.ProtectionMode', incidents: {}, kpis: {} },
  { id: 270, value: 'initialState.CcmApSpecifics.radio_configs.radio5gLower.radio.radio_enabled', text: 'TBD', textAlto: 'TBD', enumType: '', incidents: {}, kpis: {} },
  { id: 271, value: 'initialState.CcmApSpecifics.radio_configs.radio5gLower.radio.roam_enabled', text: 'TBD', textAlto: 'TBD', enumType: '', incidents: {}, kpis: {} },
  { id: 272, value: 'initialState.CcmApSpecifics.radio_configs.radio5gLower.radio.roam_macfilt_time', text: 'TBD', textAlto: 'TBD', enumType: '', incidents: {}, kpis: {} },
  { id: 273, value: 'initialState.CcmApSpecifics.radio_configs.radio5gLower.radio.tax_power', text: 'TBD', textAlto: 'TBD', enumType: 'com.ruckuswireless.scg.protobuf.ccm.Zone.CcmRadio.TaxPower', incidents: {}, kpis: {} },
  { id: 274, value: 'initialState.CcmApSpecifics.radio_configs.radio5gLower.radio.weak_bypass', text: 'TBD', textAlto: 'TBD', enumType: '', incidents: {}, kpis: {} },
  { id: 275, value: 'initialState.CcmApSpecifics.radio_configs.radio5gLower.radio.wlan_service_enabled', text: 'TBD', textAlto: 'TBD', enumType: '', incidents: {}, kpis: {} },
  { id: 276, value: 'initialState.CcmApSpecifics.radio_configs.radio5gLower.secondary_channel', text: 'TBD', textAlto: 'TBD', enumType: '', incidents: {}, kpis: {} },
  { id: 277, value: 'initialState.CcmApSpecifics.radio_configs.radio5gUpper.cband_channel_enable', text: 'TBD', textAlto: 'TBD', enumType: '', incidents: {}, kpis: {} },
  { id: 278, value: 'initialState.CcmApSpecifics.radio_configs.radio5gUpper.cband_channel_license', text: 'TBD', textAlto: 'TBD', enumType: '', incidents: {}, kpis: {} },
  { id: 279, value: 'initialState.CcmApSpecifics.radio_configs.radio5gUpper.channel_144_enable', text: 'TBD', textAlto: 'TBD', enumType: '', incidents: {}, kpis: {} },
  { id: 280, value: 'initialState.CcmApSpecifics.radio_configs.radio5gUpper.indoor_channel', text: 'TBD', textAlto: 'TBD', enumType: '', incidents: {}, kpis: {} },
  { id: 281, value: 'initialState.CcmApSpecifics.radio_configs.radio5gUpper.indoor_channel_range', text: 'TBD', textAlto: 'TBD', enumType: '', incidents: {}, kpis: {} },
  { id: 282, value: 'initialState.CcmApSpecifics.radio_configs.radio5gUpper.indoor_secondary_channel', text: 'TBD', textAlto: 'TBD', enumType: '', incidents: {}, kpis: {} },
  { id: 283, value: 'initialState.CcmApSpecifics.radio_configs.radio5gUpper.radio.adj_threshold', text: 'TBD', textAlto: 'TBD', enumType: '', incidents: {}, kpis: {} },
  { id: 284, value: 'initialState.CcmApSpecifics.radio_configs.radio5gUpper.radio.auto_cell_sizing', text: 'TBD', textAlto: 'TBD', enumType: '', incidents: {}, kpis: {} },
  { id: 285, value: 'initialState.CcmApSpecifics.radio_configs.radio5gUpper.radio.bg_scan', text: 'TBD', textAlto: 'TBD', enumType: '', incidents: {}, kpis: {} },
  { id: 286, value: 'initialState.CcmApSpecifics.radio_configs.radio5gUpper.radio.bg_scan_timer', text: 'TBD', textAlto: 'TBD', enumType: '', incidents: {}, kpis: {} },
  { id: 287, value: 'initialState.CcmApSpecifics.radio_configs.radio5gUpper.radio.bg_scanner.enabled', text: 'TBD', textAlto: 'TBD', enumType: '', incidents: {}, kpis: {} },
  { id: 288, value: 'initialState.CcmApSpecifics.radio_configs.radio5gUpper.radio.bg_scanner.timer', text: 'TBD', textAlto: 'TBD', enumType: '', incidents: {}, kpis: {} },
  { id: 289, value: 'initialState.CcmApSpecifics.radio_configs.radio5gUpper.radio.channel', text: defineMessage({ defaultMessage: 'Channel (Upper 5 GHz)' }), textAlto: 'TBD', enumType: '', incidents: {}, kpis: {} },
  { id: 290, value: 'initialState.CcmApSpecifics.radio_configs.radio5gUpper.radio.channel_fly_config.channel_change_frequency', text: 'TBD', textAlto: 'TBD', enumType: '', incidents: {}, kpis: {} },
  { id: 291, value: 'initialState.CcmApSpecifics.radio_configs.radio5gUpper.radio.channel_fly_config.optimization_time_period', text: 'TBD', textAlto: 'TBD', enumType: '', incidents: {}, kpis: {} },
  { id: 292, value: 'initialState.CcmApSpecifics.radio_configs.radio5gUpper.radio.channel_fly_mtbc', text: 'TBD', textAlto: 'TBD', enumType: '', incidents: {}, kpis: {} },
  { id: 293, value: 'initialState.CcmApSpecifics.radio_configs.radio5gUpper.radio.channel_range', text: defineMessage({ defaultMessage: 'Channel Range(Upper 5 GHz)' }), textAlto: 'TBD', enumType: '', incidents: {}, kpis: {} },
  { id: 294, value: 'initialState.CcmApSpecifics.radio_configs.radio5gUpper.radio.channel_select_mode', text: 'TBD', textAlto: 'TBD', enumType: 'com.ruckuswireless.scg.protobuf.ccm.Zone.CcmRadio.ChannelSelectMode', incidents: {}, kpis: {} },
  { id: 295, value: 'initialState.CcmApSpecifics.radio_configs.radio5gUpper.radio.channel_width', text: defineMessage({ defaultMessage: 'Channel Width(Upper 5 GHz)' }), textAlto: 'TBD', enumType: 'com.ruckuswireless.scg.protobuf.ccm.Zone.CcmRadio.ChannelWidth', incidents: {}, kpis: {} },
  { id: 296, value: 'initialState.CcmApSpecifics.radio_configs.radio5gUpper.radio.clb_enabled', text: 'TBD', textAlto: 'TBD', enumType: '', incidents: {}, kpis: {} },
  { id: 297, value: 'initialState.CcmApSpecifics.radio_configs.radio5gUpper.radio.client_admission.enabled', text: 'TBD', textAlto: 'TBD', enumType: '', incidents: {}, kpis: {} },
  { id: 298, value: 'initialState.CcmApSpecifics.radio_configs.radio5gUpper.radio.client_admission.maxiumum_radio_load', text: 'TBD', textAlto: 'TBD', enumType: '', incidents: {}, kpis: {} },
  { id: 299, value: 'initialState.CcmApSpecifics.radio_configs.radio5gUpper.radio.client_admission.minimum_client_count', text: 'TBD', textAlto: 'TBD', enumType: '', incidents: {}, kpis: {} },
  { id: 300, value: 'initialState.CcmApSpecifics.radio_configs.radio5gUpper.radio.client_admission.minimum_client_throughput', text: 'TBD', textAlto: 'TBD', enumType: '', incidents: {}, kpis: {} },
  { id: 301, value: 'initialState.CcmApSpecifics.radio_configs.radio5gUpper.radio.head_room', text: 'TBD', textAlto: 'TBD', enumType: '', incidents: {}, kpis: {} },
  { id: 302, value: 'initialState.CcmApSpecifics.radio_configs.radio5gUpper.radio.indoor_channel_block', text: 'TBD', textAlto: 'TBD', enumType: 'com.ruckuswireless.scg.protobuf.ccm.Zone.CcmRadio.AllowIndoorChannel', incidents: {}, kpis: {} },
  { id: 303, value: 'initialState.CcmApSpecifics.radio_configs.radio5gUpper.radio.protection_mode', text: 'TBD', textAlto: 'TBD', enumType: 'com.ruckuswireless.scg.protobuf.ccm.Zone.CcmRadio.ProtectionMode', incidents: {}, kpis: {} },
  { id: 304, value: 'initialState.CcmApSpecifics.radio_configs.radio5gUpper.radio.radio_enabled', text: 'TBD', textAlto: 'TBD', enumType: '', incidents: {}, kpis: {} },
  { id: 305, value: 'initialState.CcmApSpecifics.radio_configs.radio5gUpper.radio.roam_enabled', text: 'TBD', textAlto: 'TBD', enumType: '', incidents: {}, kpis: {} },
  { id: 306, value: 'initialState.CcmApSpecifics.radio_configs.radio5gUpper.radio.roam_macfilt_time', text: 'TBD', textAlto: 'TBD', enumType: '', incidents: {}, kpis: {} },
  { id: 307, value: 'initialState.CcmApSpecifics.radio_configs.radio5gUpper.radio.tax_power', text: 'TBD', textAlto: 'TBD', enumType: 'com.ruckuswireless.scg.protobuf.ccm.Zone.CcmRadio.TaxPower', incidents: {}, kpis: {} },
  { id: 308, value: 'initialState.CcmApSpecifics.radio_configs.radio5gUpper.radio.weak_bypass', text: 'TBD', textAlto: 'TBD', enumType: '', incidents: {}, kpis: {} },
  { id: 309, value: 'initialState.CcmApSpecifics.radio_configs.radio5gUpper.radio.wlan_service_enabled', text: 'TBD', textAlto: 'TBD', enumType: '', incidents: {}, kpis: {} },
  { id: 310, value: 'initialState.CcmApSpecifics.radio_configs.radio5gUpper.secondary_channel', text: 'TBD', textAlto: 'TBD', enumType: '', incidents: {}, kpis: {} },
  { id: 311, value: 'initialState.CcmApSpecifics.radio_configs.radio6g.channel2_enable', text: 'TBD', textAlto: 'TBD', enumType: '', incidents: {}, kpis: {} },
  { id: 312, value: 'initialState.CcmApSpecifics.radio_configs.radio6g.low_power_indoor_mode_enable', text: 'TBD', textAlto: 'TBD', enumType: '', incidents: {}, kpis: {} },
  { id: 313, value: 'initialState.CcmApSpecifics.radio_configs.radio6g.radio.adj_threshold', text: 'TBD', textAlto: 'TBD', enumType: '', incidents: {}, kpis: {} },
  { id: 314, value: 'initialState.CcmApSpecifics.radio_configs.radio6g.radio.auto_cell_sizing', text: 'TBD', textAlto: 'TBD', enumType: '', incidents: {}, kpis: {} },
  { id: 315, value: 'initialState.CcmApSpecifics.radio_configs.radio6g.radio.bg_scan', text: 'TBD', textAlto: 'TBD', enumType: '', incidents: {}, kpis: {} },
  { id: 316, value: 'initialState.CcmApSpecifics.radio_configs.radio6g.radio.bg_scan_timer', text: 'TBD', textAlto: 'TBD', enumType: '', incidents: {}, kpis: {} },
  { id: 317, value: 'initialState.CcmApSpecifics.radio_configs.radio6g.radio.bg_scanner.enabled', text: 'TBD', textAlto: 'TBD', enumType: '', incidents: {}, kpis: {} },
  { id: 318, value: 'initialState.CcmApSpecifics.radio_configs.radio6g.radio.bg_scanner.timer', text: 'TBD', textAlto: 'TBD', enumType: '', incidents: {}, kpis: {} },
  { id: 319, value: 'initialState.CcmApSpecifics.radio_configs.radio6g.radio.channel', text: defineMessage({ defaultMessage: 'Channel (6 GHz)' }), textAlto: 'TBD', enumType: '', incidents: {}, kpis: {} },
  { id: 320, value: 'initialState.CcmApSpecifics.radio_configs.radio6g.radio.channel_fly_config.channel_change_frequency', text: 'TBD', textAlto: 'TBD', enumType: '', incidents: {}, kpis: {} },
  { id: 321, value: 'initialState.CcmApSpecifics.radio_configs.radio6g.radio.channel_fly_config.optimization_time_period', text: 'TBD', textAlto: 'TBD', enumType: '', incidents: {}, kpis: {} },
  { id: 322, value: 'initialState.CcmApSpecifics.radio_configs.radio6g.radio.channel_fly_mtbc', text: 'TBD', textAlto: 'TBD', enumType: '', incidents: {}, kpis: {} },
  { id: 323, value: 'initialState.CcmApSpecifics.radio_configs.radio6g.radio.channel_range', text: defineMessage({ defaultMessage: 'Channel Range (6 GHz)' }), textAlto: 'TBD', enumType: '', incidents: {}, kpis: {} },
  { id: 324, value: 'initialState.CcmApSpecifics.radio_configs.radio6g.radio.channel_select_mode', text: 'TBD', textAlto: 'TBD', enumType: 'com.ruckuswireless.scg.protobuf.ccm.Zone.CcmRadio.ChannelSelectMode', incidents: {}, kpis: {} },
  { id: 325, value: 'initialState.CcmApSpecifics.radio_configs.radio6g.radio.channel_width', text: 'TBD', textAlto: 'TBD', enumType: 'com.ruckuswireless.scg.protobuf.ccm.Zone.CcmRadio.ChannelWidth', incidents: {}, kpis: {} },
  { id: 326, value: 'initialState.CcmApSpecifics.radio_configs.radio6g.radio.clb_enabled', text: 'TBD', textAlto: 'TBD', enumType: '', incidents: {}, kpis: {} },
  { id: 327, value: 'initialState.CcmApSpecifics.radio_configs.radio6g.radio.client_admission.enabled', text: 'TBD', textAlto: 'TBD', enumType: '', incidents: {}, kpis: {} },
  { id: 328, value: 'initialState.CcmApSpecifics.radio_configs.radio6g.radio.client_admission.maxiumum_radio_load', text: 'TBD', textAlto: 'TBD', enumType: '', incidents: {}, kpis: {} },
  { id: 329, value: 'initialState.CcmApSpecifics.radio_configs.radio6g.radio.client_admission.minimum_client_count', text: 'TBD', textAlto: 'TBD', enumType: '', incidents: {}, kpis: {} },
  { id: 330, value: 'initialState.CcmApSpecifics.radio_configs.radio6g.radio.client_admission.minimum_client_throughput', text: 'TBD', textAlto: 'TBD', enumType: '', incidents: {}, kpis: {} },
  { id: 331, value: 'initialState.CcmApSpecifics.radio_configs.radio6g.radio.head_room', text: 'TBD', textAlto: 'TBD', enumType: '', incidents: {}, kpis: {} },
  { id: 332, value: 'initialState.CcmApSpecifics.radio_configs.radio6g.radio.indoor_channel_block', text: 'TBD', textAlto: 'TBD', enumType: 'com.ruckuswireless.scg.protobuf.ccm.Zone.CcmRadio.AllowIndoorChannel', incidents: {}, kpis: {} },
  { id: 333, value: 'initialState.CcmApSpecifics.radio_configs.radio6g.radio.protection_mode', text: 'TBD', textAlto: 'TBD', enumType: 'com.ruckuswireless.scg.protobuf.ccm.Zone.CcmRadio.ProtectionMode', incidents: {}, kpis: {} },
  { id: 334, value: 'initialState.CcmApSpecifics.radio_configs.radio6g.radio.radio_enabled', text: 'TBD', textAlto: 'TBD', enumType: '', incidents: {}, kpis: {} },
  { id: 335, value: 'initialState.CcmApSpecifics.radio_configs.radio6g.radio.roam_enabled', text: 'TBD', textAlto: 'TBD', enumType: '', incidents: {}, kpis: {} },
  { id: 336, value: 'initialState.CcmApSpecifics.radio_configs.radio6g.radio.roam_macfilt_time', text: 'TBD', textAlto: 'TBD', enumType: '', incidents: {}, kpis: {} },
  { id: 337, value: 'initialState.CcmApSpecifics.radio_configs.radio6g.radio.tax_power', text: 'TBD', textAlto: 'TBD', enumType: 'com.ruckuswireless.scg.protobuf.ccm.Zone.CcmRadio.TaxPower', incidents: {}, kpis: {} },
  { id: 338, value: 'initialState.CcmApSpecifics.radio_configs.radio6g.radio.weak_bypass', text: 'TBD', textAlto: 'TBD', enumType: '', incidents: {}, kpis: {} },
  { id: 339, value: 'initialState.CcmApSpecifics.radio_configs.radio6g.radio.wlan_service_enabled', text: 'TBD', textAlto: 'TBD', enumType: '', incidents: {}, kpis: {} },
  { id: 340, value: 'initialState.CcmApSpecifics.wlan_groups.radio_id', text: 'TBD', textAlto: 'TBD', enumType: '', incidents: {}, kpis: {} },
  { id: 341, value: 'initialState.CcmApSpecifics.wlan_groups.wlan_group_id', text: 'TBD', textAlto: 'TBD', enumType: '', incidents: {}, kpis: {} }
]
