import { defineMessage } from 'react-intl'

/* eslint-disable max-len */
export const ethernetPortProfileKeyMap = [
  { id: 1, value: 'initialState.CcmEthernetPortProfile.id', text: 'NA', textAlto: 'NA', enumType: '', incidents: {}, kpis: {} },
  { id: 2, value: 'initialState.CcmEthernetPortProfile.name', text: defineMessage({ defaultMessage: 'Name' }), textAlto: 'TBD', enumType: '', incidents: {}, kpis: {} },
  { id: 3, value: 'initialState.CcmEthernetPortProfile.role', text: defineMessage({ defaultMessage: '802.1x Role' }), textAlto: defineMessage({ defaultMessage: '802.1x Role' }), enumType: 'com.ruckuswireless.scg.protobuf.ccm.EthernetPortProfile.CcmEthernetPortProfile.Role', incidents: {}, kpis: {} },
  { id: 4, value: 'initialState.CcmEthernetPortProfile.type', text: defineMessage({ defaultMessage: 'Ethernet Port Type' }), textAlto: defineMessage({ defaultMessage: 'Ethernet Port Type' }), enumType: 'com.ruckuswireless.scg.protobuf.ccm.EthernetPortProfile.CcmEthernetPortProfile.Type', incidents: {}, kpis: {} },
  { id: 5, value: 'initialState.CcmEthernetPortProfile.untag_id', text: defineMessage({ defaultMessage: 'VLAN Untag ID' }), textAlto: defineMessage({ defaultMessage: 'VLAN Untag ID' }), enumType: '', incidents: {}, kpis: {} },
  { id: 6, value: 'initialState.CcmEthernetPortProfile.vlan_members', text: defineMessage({ defaultMessage: 'Vlan Members' }), textAlto: defineMessage({ defaultMessage: 'Vlan Members' }), enumType: '', incidents: { 'i-apserv-high-num-reboots': 1, 'i-apserv-continuous-reboots': 1 }, kpis: {} },
  { id: 7, value: 'initialState.CcmEthernetPortProfile.dVlan_enabled', text: defineMessage({ defaultMessage: 'Dynamic vlan' }), textAlto: defineMessage({ defaultMessage: 'Dynamic vlan' }), enumType: '', incidents: { 'i-apserv-high-num-reboots': 1, 'i-apserv-continuous-reboots': 1 }, kpis: {} },
  { id: 8, value: 'initialState.CcmEthernetPortProfile.role_supplicant.type', text: defineMessage({ defaultMessage: 'Supplicant Type' }), textAlto: 'TBD', enumType: 'com.ruckuswireless.scg.protobuf.ccm.EthernetPortProfile.CcmEthernetPortProfile.CcmRoleSupplicant.Type', incidents: {}, kpis: {} },
  { id: 9, value: 'initialState.CcmEthernetPortProfile.role_supplicant.user', text: defineMessage({ defaultMessage: 'Username' }), textAlto: 'TBD', enumType: '', incidents: {}, kpis: {} },
  { id: 10, value: 'initialState.CcmEthernetPortProfile.role_supplicant.password', text: defineMessage({ defaultMessage: 'Password' }), textAlto: 'TBD', enumType: '', incidents: {}, kpis: {} },
  { id: 11, value: 'initialState.CcmEthernetPortProfile.role_authenticator.authentication_server_proxy_enabled', text: defineMessage({ defaultMessage: 'Proxy authentication server Enabled' }), textAlto: 'TBD', enumType: '', incidents: {}, kpis: {} },
  { id: 12, value: 'initialState.CcmEthernetPortProfile.role_authenticator.accounting_server_proxy_enabled', text: defineMessage({ defaultMessage: 'Proxy Accounting server Enabled' }), textAlto: 'TBD', enumType: '', incidents: {}, kpis: {} },
  { id: 13, value: 'initialState.CcmEthernetPortProfile.role_authenticator.authentication_server_id', text: 'NA', textAlto: 'TBD', enumType: '', incidents: {}, kpis: {} },
  { id: 14, value: 'initialState.CcmEthernetPortProfile.role_authenticator.accounting_server_id', text: 'NA', textAlto: 'TBD', enumType: '', incidents: {}, kpis: {} },
  { id: 15, value: 'initialState.CcmEthernetPortProfile.role_authenticator.mac_by_pass_enabled', text: defineMessage({ defaultMessage: 'By pass mac' }), textAlto: 'TBD', enumType: '', incidents: {}, kpis: {} },
  { id: 16, value: 'initialState.CcmEthernetPortProfile.role_open.accounting_server_proxy_enabled', text: 'TBD', textAlto: 'TBD', enumType: '', incidents: {}, kpis: {} },
  { id: 17, value: 'initialState.CcmEthernetPortProfile.role_open.accounting_server_id', text: 'NA', textAlto: 'TBD', enumType: '', incidents: {}, kpis: {} },
  { id: 18, value: 'initialState.CcmEthernetPortProfile.nas_id_type', text: defineMessage({ defaultMessage: 'NAS ID' }), textAlto: 'TBD', enumType: 'com.ruckuswireless.scg.protobuf.ccm.EthernetPortProfile.CcmEthernetPortProfile.NasIdType', incidents: {}, kpis: {} },
  { id: 19, value: 'initialState.CcmEthernetPortProfile.nas_id_delimiter', text: defineMessage({ defaultMessage: 'NAS ID Delimiter' }), textAlto: 'TBD', enumType: 'com.ruckuswireless.scg.protobuf.ccm.EthernetPortProfile.CcmEthernetPortProfile.NasIdDelimiter', incidents: {}, kpis: {} },
  { id: 20, value: 'initialState.CcmEthernetPortProfile.user_defined_nas_id', text: defineMessage({ defaultMessage: 'User defined NAS ID' }), textAlto: 'TBD', enumType: '', incidents: {}, kpis: {} },
  { id: 21, value: 'initialState.CcmEthernetPortProfile.zone_id', text: 'NA', textAlto: 'TBD', enumType: '', incidents: {}, kpis: {} },
  { id: 22, value: 'initialState.CcmEthernetPortProfile.tenant_id', text: 'NA', textAlto: 'TBD', enumType: '', incidents: {}, kpis: {} },
  { id: 23, value: 'initialState.CcmEthernetPortProfile.factory_default', text: 'TBD', textAlto: 'TBD', enumType: '', incidents: {}, kpis: {} },
  { id: 24, value: 'initialState.CcmEthernetPortProfile.guest_vlan', text: defineMessage({ defaultMessage: 'Guest Vlan' }), textAlto: 'TBD', enumType: '', incidents: {}, kpis: {} },
  { id: 25, value: 'initialState.CcmEthernetPortProfile.tunnel_enabled', text: 'TBD', textAlto: 'TBD', enumType: '', incidents: {}, kpis: {} },
  { id: 26, value: 'initialState.CcmEthernetPortProfile.tunnel_profile.profile_id', text: 'NA', textAlto: 'TBD', enumType: '', incidents: {}, kpis: {} },
  { id: 27, value: 'initialState.CcmEthernetPortProfile.ipsec_profile.profile_id', text: 'NA', textAlto: 'TBD', enumType: '', incidents: {}, kpis: {} },
  { id: 28, value: 'initialState.CcmEthernetPortProfile.access_network_type', text: defineMessage({ defaultMessage: 'Access network Type' }), textAlto: 'TBD', enumType: 'com.ruckuswireless.scg.protobuf.ccm.EthernetPortProfile.CcmEthernetPortProfile.CcmAccessNetworkType', incidents: {}, kpis: {} },
  { id: 29, value: 'initialState.CcmEthernetPortProfile.anti_spoofing.enabled', text: defineMessage({ defaultMessage: 'Anti Spoofing Enabled' }), textAlto: 'TBD', enumType: '', incidents: {}, kpis: {} },
  { id: 30, value: 'initialState.CcmEthernetPortProfile.anti_spoofing.arp_request_rate_limit', text: defineMessage({ defaultMessage: 'ARP Request Rate' }), textAlto: 'TBD', enumType: '', incidents: {}, kpis: {} },
  { id: 31, value: 'initialState.CcmEthernetPortProfile.anti_spoofing.dhcp_request_rate_limit', text: defineMessage({ defaultMessage: 'DHCP Request Rate' }), textAlto: 'TBD', enumType: '', incidents: {}, kpis: {} },
  { id: 32, value: 'initialState.CcmEthernetPortProfile.qinq.cvlan_id', text: defineMessage({ defaultMessage: 'CVLAN' }), textAlto: 'TBD', enumType: '', incidents: { 'i-apserv-high-num-reboots': 1, 'i-apserv-continuous-reboots': 1 }, kpis: {} },
  { id: 33, value: 'initialState.CcmEthernetPortProfile.qinq.svlan_id', text: defineMessage({ defaultMessage: 'SVLAN' }), textAlto: 'TBD', enumType: '', incidents: { 'i-apserv-high-num-reboots': 1, 'i-apserv-continuous-reboots': 1 }, kpis: {} },
  { id: 34, value: 'initialState.CcmEthernetPortProfile.user_side_port.user_side_port_enabled', text: defineMessage({ defaultMessage: 'User side Port enabled' }), textAlto: 'TBD', enumType: '', incidents: {}, kpis: {} },
  { id: 35, value: 'initialState.CcmEthernetPortProfile.user_side_port.user_side_port_max_client', text: defineMessage({ defaultMessage: 'User Side port Max clients' }), textAlto: 'TBD', enumType: '', incidents: {}, kpis: {} },
  { id: 36, value: 'initialState.CcmEthernetPortProfile.firewall_profile_id', text: 'NA', textAlto: 'TBD', enumType: '', incidents: {}, kpis: {} },
  { id: 37, value: 'initialState.CcmEthernetPortProfile.l2_access_control_policy_id', text: 'NA', textAlto: 'TBD', enumType: '', incidents: {}, kpis: {} },
  { id: 38, value: 'initialState.CcmEthernetPortProfile.firewall_application_visibility_control_enabled', text: defineMessage({ defaultMessage: 'Application Recognition & Control Enabled' }), textAlto: 'TBD', enumType: '', incidents: {}, kpis: {} },
  { id: 39, value: 'initialState.CcmEthernetPortProfile.firewall_url_filtering_enabled', text: defineMessage({ defaultMessage: 'URL filtering enabled' }), textAlto: 'TBD', enumType: '', incidents: {}, kpis: {} },
  { id: 40, value: 'initialState.CcmEthernetPortProfile.dp_tunnel_dhcp_enabled', text: defineMessage({ defaultMessage: 'DP Tunnel DHCP enabled' }), textAlto: 'TBD', enumType: '', incidents: {}, kpis: {} },
  { id: 41, value: 'initialState.CcmEthernetPortProfile.dp_tunnel_nat_enabled', text: defineMessage({ defaultMessage: 'DP Tunnel NAT enabled' }), textAlto: 'TBD', enumType: '', incidents: {}, kpis: {} },
  { id: 42, value: 'initialState.CcmEthernetPortProfile.mdu_profile_id', text: 'TBD', textAlto: 'TBD', enumType: '', incidents: {}, kpis: {} },
  { id: 43, value: 'initialState.CcmEthernetPortProfile.user_side_port.user_side_port_downlink_limit', text: 'TBD', textAlto: 'TBD', enumType: '', incidents: {}, kpis: {} },
  { id: 44, value: 'initialState.CcmEthernetPortProfile.user_side_port.user_side_port_uplink_limit', text: 'TBD', textAlto: 'TBD', enumType: '', incidents: {}, kpis: {} }
]
