import { defineMessage } from 'react-intl'

/* eslint-disable max-len */
export const intentAIKeyMap = [
  { id: 1, value: 'intentAi.c-bgscan24g-enable', text: defineMessage({ defaultMessage: 'AI Operations: Dynamic vs Static Channel capability on 2.4 GHz radio' }), textAlto: defineMessage({ defaultMessage: 'AI Operations: Dynamic vs Static Channel capability on 2.4 GHz radio' }), enumType: '', incidents: {}, kpis: {} },
  { id: 2, value: 'intentAi.c-bgscan5g-enable', text: defineMessage({ defaultMessage: 'AI Operations: Dynamic vs Static Channel capability on 5 GHz radio' }), textAlto: defineMessage({ defaultMessage: 'AI Operations: Dynamic vs Static Channel capability on 5 GHz radio' }), enumType: '', incidents: {}, kpis: {} },
  { id: 3, value: 'intentAi.c-bgscan24g-timer', text: defineMessage({ defaultMessage: 'AI Operations: Network Efficiency vs Stability on 2.4 GHz radio' }), textAlto: defineMessage({ defaultMessage: 'AI Operations: Network Efficiency vs Stability on 2.4 GHz radio' }), enumType: '', incidents: {}, kpis: {} },
  { id: 4, value: 'intentAi.c-bgscan5g-timer', text: defineMessage({ defaultMessage: 'AI Operations: Network Efficiency vs Stability on 5 GHz radio' }), textAlto: defineMessage({ defaultMessage: 'AI Operations: Network Efficiency vs Stability on 5 GHz radio' }), enumType: '', incidents: {}, kpis: {} },
  { id: 5, value: 'intentAi.c-bgscan6g-timer', text: defineMessage({ defaultMessage: 'AI Operations: Network Efficiency vs Stability on 6 GHz radio' }), textAlto: defineMessage({ defaultMessage: 'AI Operations: Network Efficiency vs Stability on 6 GHz radio' }), enumType: '', incidents: {}, kpis: {} },
  { id: 6, value: 'intentAi.c-dfschannels-enable', text: defineMessage({ defaultMessage: 'AI Operations: Expanded Radar channels vs Limited Channel options' }), textAlto: defineMessage({ defaultMessage: 'AI Operations: Expanded Radar channels vs Limited Channel options' }), enumType: '', incidents: {}, kpis: {} },
  { id: 7, value: 'intentAi.c-dfschannels-disable', text: defineMessage({ defaultMessage: 'AI Operations: Radar Interference vs Optimal Channel availability' }), textAlto: defineMessage({ defaultMessage: 'AI Operations: Radar Interference vs Optimal Channel availability' }), enumType: '', incidents: {}, kpis: {} },
  { id: 8, value: 'intentAi.c-bandbalancing-enable', text: defineMessage({ defaultMessage: 'AI Operations: Client Performance vs Compatibility' }), textAlto: defineMessage({ defaultMessage: 'AI Operations: Client Performance vs Compatibility' }), enumType: '', incidents: {}, kpis: {} },
  { id: 9, value: 'intentAi.c-bandbalancing-enable-below-61', text: defineMessage({ defaultMessage: 'AI Operations: Client Performance vs Compatibility' }), textAlto: defineMessage({ defaultMessage: 'AI Operations: Client Performance vs Compatibility' }), enumType: '', incidents: {}, kpis: {} },
  { id: 10, value: 'intentAi.c-bandbalancing-proactive', text: defineMessage({ defaultMessage: 'AI Operations: Client Distribution vs Compatibility' }), textAlto: defineMessage({ defaultMessage: 'AI Operations: Client Distribution vs Compatibility' }), enumType: '', incidents: {}, kpis: {} },
  { id: 11, value: 'intentAi.c-aclb-enable', text: defineMessage({ defaultMessage: 'AI Operations: Distributed Wi-Fi Load vs Client Stability' }), textAlto: defineMessage({ defaultMessage: 'AI Operations: Distributed Wi-Fi Load vs Client Stability' }), enumType: '', incidents: {}, kpis: {} },
  { id: 12, value: 'intentAi.i-zonefirmware-upgrade', text: defineMessage({ defaultMessage: 'AI Operations: Secure AP firmware vs Client Device Compatibility' }), textAlto: defineMessage({ defaultMessage: 'AI Operations: Secure AP firmware vs Client Device Compatibility' }), enumType: '', incidents: {}, kpis: {} },
  { id: 13, value: 'intentAi.c-txpower-same', text: defineMessage({ defaultMessage: 'AI Operations: Optimize for 5 GHz Radio vs Longer range with 2.4 GHz' }), textAlto: defineMessage({ defaultMessage: 'AI Operations: Optimize for 5 GHz Radio vs Longer range with 2.4 GHz' }), enumType: '', incidents: {}, kpis: {} },
  { id: 14, value: 'intentAi.c-crrm-channel24g-auto', text: defineMessage({ defaultMessage: 'AI-Driven RRM: Client Density vs Throughput for 2.4 GHz radio' }), textAlto: defineMessage({ defaultMessage: 'AI-Driven RRM: Client Density vs Throughput for 2.4 GHz radio' }), enumType: '', incidents: {}, kpis: {} },
  { id: 15, value: 'intentAi.c-crrm-channel5g-auto', text: defineMessage({ defaultMessage: 'AI-Driven RRM: Client Density vs Throughput for 5 GHz radio' }), textAlto: defineMessage({ defaultMessage: 'AI-Driven RRM: Client Density vs Throughput for 5 GHz radio' }), enumType: '', incidents: {}, kpis: {} },
  { id: 16, value: 'intentAi.c-crrm-channel6g-auto', text: defineMessage({ defaultMessage: 'AI-Driven RRM: Client Density vs Throughput for 6 GHz radio' }), textAlto: defineMessage({ defaultMessage: 'AI-Driven RRM: Client Density vs Throughput for 6 GHz radio' }), enumType: '', incidents: {}, kpis: {} },
  { id: 17, value: 'intentAi.c-probeflex-24g', text: defineMessage({ defaultMessage: 'EquiFlex: Time to Connect vs Client Density for 2.4 GHz' }), textAlto: defineMessage({ defaultMessage: 'EquiFlex: Time to Connect vs Client Density for 2.4 GHz' }), enumType: '', incidents: {}, kpis: {} },
  { id: 18, value: 'intentAi.c-probeflex-5g', text: defineMessage({ defaultMessage: 'EquiFlex: Time to Connect vs Client Density for 5 GHz' }), textAlto: defineMessage({ defaultMessage: 'EquiFlex: Time to Connect vs Client Density for 5 GHz' }), enumType: '', incidents: {}, kpis: {} },
  { id: 19, value: 'intentAi.c-probeflex-6g', text: defineMessage({ defaultMessage: 'EquiFlex: Time to Connect vs Client Density for 6 GHz' }), textAlto: defineMessage({ defaultMessage: 'EquiFlex: Time to Connect vs Client Density for 6 GHz' }), enumType: '', incidents: {}, kpis: {} },
  { id: 20, value: 'intentAi.i-ecoflex', text: defineMessage({ defaultMessage: 'EcoFlex: Energy Footprint vs Mission Criticality' }), textAlto: defineMessage({ defaultMessage: 'EcoFlex: Energy Footprint vs Mission Criticality' }), enumType: '', incidents: {}, kpis: {} }
]

