export { ReactComponent as AccessPointOutlined } from './icons/AccessPointOutlined.svg'
export { ReactComponent as AccessPointSolid } from './icons/AccessPointSolid.svg'
export { ReactComponent as AccessPointWiFiOutlined } from './icons/AccessPointWiFiOutlined.svg'
export { ReactComponent as AccessPointWiFiSolid } from './icons/AccessPointWiFiSolid.svg'
export { ReactComponent as AccountCircleOutlined } from './icons/AccountCircleOutlined.svg'
export { ReactComponent as AccountCircleSolid } from './icons/AccountCircleSolid.svg'
export { ReactComponent as AccountCircleSolidSmall } from './icons/AccountCircleSolidSmall.svg'
export { ReactComponent as AI } from './icons/AI.svg'
export { ReactComponent as AndroidOutlined } from './icons/AndroidOutlined.svg'
export { ReactComponent as AndroidSolid } from './icons/AndroidSolid.svg'
export { ReactComponent as AppleOutlined } from './icons/AppleOutlined.svg'
export { ReactComponent as AppleSolid } from './icons/AppleSolid.svg'
export { ReactComponent as ApplicationsOutlined } from './icons/ApplicationsOutlined.svg'
export { ReactComponent as ApplicationsSolid } from './icons/ApplicationsSolid.svg'
export { ReactComponent as ArrowBack } from './icons/ArrowBack.svg'
export { ReactComponent as ArrowChevronLeft } from './icons/ArrowChevronLeft.svg'
export { ReactComponent as ArrowChevronRight } from './icons/ArrowChevronRight.svg'
export { ReactComponent as ArrowExpand } from './icons/ArrowExpand.svg'
export { ReactComponent as ArrowsOut } from './icons/ArrowsOut.svg'
export { ReactComponent as BarChartOutlined } from './icons/BarChartOutlined.svg'
export { ReactComponent as BarChartSolid } from './icons/BarChartSolid.svg'
export { ReactComponent as BookmarkOutlined } from './icons/BookmarkOutlined.svg'
export { ReactComponent as BookmarkSolid } from './icons/BookmarkSolid.svg'
export { ReactComponent as BooksOutlined } from './icons/BooksOutlined.svg'
export { ReactComponent as BuildingsOutlined } from './icons/BuildingsOutlined.svg'
export { ReactComponent as BuildingsSolid } from './icons/BuildingsSolid.svg'
export { ReactComponent as BulbOutlined } from './icons/BulbOutlined.svg'
export { ReactComponent as BulbSolid } from './icons/BulbSolid.svg'
export { ReactComponent as CalendarDateOutlined } from './icons/CalendarDateOutlined.svg'
export { ReactComponent as CalendarDateSolid } from './icons/CalendarDateSolid.svg'
export { ReactComponent as CalendarOutlined } from './icons/CalendarOutlined.svg'
export { ReactComponent as CalendarSolid } from './icons/CalendarSolid.svg'
export { ReactComponent as CancelCircle } from './icons/CancelCircle.svg'
export { ReactComponent as CancelCircleOutlined } from './icons/CancelCircleOutlined.svg'
export { ReactComponent as CancelCircleSolid } from './icons/CancelCircleSolid.svg'
export { ReactComponent as CaretDoubleDownOutlined } from './icons/CaretDoubleDownOutlined.svg'
export { ReactComponent as CaretDoubleDownSolid } from './icons/CaretDoubleDownSolid.svg'
export { ReactComponent as CaretDoubleLeftCircleOutlined }
  from './icons/CaretDoubleLeftCircleOutlined.svg'
export { ReactComponent as CaretDoubleLeftCircleSolid }
  from './icons/CaretDoubleLeftCircleSolid.svg'
export { ReactComponent as CaretDoubleLeftOutlined } from './icons/CaretDoubleLeftOutlined.svg'
export { ReactComponent as CaretDoubleLeftSolid } from './icons/CaretDoubleLeftSolid.svg'
export { ReactComponent as CaretDoubleRightCircleOutlined }
  from './icons/CaretDoubleRightCircleOutlined.svg'
export { ReactComponent as CaretDoubleRightCircleSolid }
  from './icons/CaretDoubleRightCircleSolid.svg'
export { ReactComponent as CaretDoubleRightOutlined } from './icons/CaretDoubleRightOutlined.svg'
export { ReactComponent as CaretDoubleRightSolid } from './icons/CaretDoubleRightSolid.svg'
export { ReactComponent as CaretDoubleUpOutlined } from './icons/CaretDoubleUpOutlined.svg'
export { ReactComponent as CaretDoubleUpSolid } from './icons/CaretDoubleUpSolid.svg'
export { ReactComponent as CaretDownOutlined } from './icons/CaretDownOutlined.svg'
export { ReactComponent as CaretDownSolid } from './icons/CaretDownSolid.svg'
export { ReactComponent as CaretLeftOutlined } from './icons/CaretLeftOutlined.svg'
export { ReactComponent as CaretLeftSolid } from './icons/CaretLeftSolid.svg'
export { ReactComponent as CaretRightOutlined } from './icons/CaretRightOutlined.svg'
export { ReactComponent as CaretRightSolid } from './icons/CaretRightSolid.svg'
export { ReactComponent as CaretUpOutlined } from './icons/CaretUpOutlined.svg'
export { ReactComponent as CaretUpSolid } from './icons/CaretUpSolid.svg'
export { ReactComponent as CheckMarkCircleOutline } from './icons/CheckMarkCircleOutline.svg'
export { ReactComponent as CheckMarkCircleSolid } from './icons/CheckMarkCircleSolid.svg'
export { ReactComponent as ChevronLeftCircleOutlined } from './icons/ChevronLeftCircleOutlined.svg'
export { ReactComponent as ChevronLeftCircleSolid } from './icons/ChevronLeftCircleSolid.svg'
export { ReactComponent as ChevronLeftSquareOutlined } from './icons/ChevronLeftSquareOutlined.svg'
export { ReactComponent as ChevronLeftSquareSolid } from './icons/ChevronLeftSquareSolid.svg'
export { ReactComponent as ChevronRightCircleOutlined }
  from './icons/ChevronRightCircleOutlined.svg'
export { ReactComponent as ChevronRightCircleSolid } from './icons/ChevronRightCircleSolid.svg'
export { ReactComponent as ChevronRightSquareArrowsChevronRightSquareOutlined }
  from './icons/ChevronRightSquareArrowsChevronRightSquareOutlined.svg'
export { ReactComponent as ChevronRightSquareArrowsChevronRightSquareSolid }
  from './icons/ChevronRightSquareArrowsChevronRightSquareSolid.svg'
export { ReactComponent as CloseSymbol } from './icons/CloseSymbol.svg'
export { ReactComponent as Close } from './icons/Close.svg'
export { ReactComponent as ClockOutlined } from './icons/ClockOutlined.svg'
export { ReactComponent as ClockSolid } from './icons/ClockSolid.svg'
export { ReactComponent as CollapseAllCircleArrowsCollapseAllCircleOutlined }
  from './icons/CollapseAllCircleArrowsCollapseAllCircleOutlined.svg'
export { ReactComponent as CollapseAllCircleArrowsCollapseAllCircleSolid }
  from './icons/CollapseAllCircleArrowsCollapseAllCircleSolid.svg'
export { ReactComponent as CollapseCircleOutlined } from './icons/CollapseCircleOutlined.svg'
export { ReactComponent as CollapseCircleSolid } from './icons/CollapseCircleSolid.svg'
export { ReactComponent as CollapseSquareOutlined } from './icons/CollapseSquareOutlined.svg'
export { ReactComponent as CollapseSquareSolid } from './icons/CollapseSquareSolid.svg'
export { ReactComponent as ConfigurationOutlined } from './icons/ConfigurationOutlined.svg'
export { ReactComponent as ConfigurationSolid } from './icons/ConfigurationSolid.svg'
export { ReactComponent as CopyOutlined } from './icons/CopyOutlined.svg'
export { ReactComponent as CopySolid } from './icons/CopySolid.svg'
export { ReactComponent as CrownOutlined } from './icons/CrownOutlined.svg'
export { ReactComponent as CrownSolid } from './icons/CrownSolid.svg'
export { ReactComponent as DashboardOutlined } from './icons/DashboardOutlined.svg'
export { ReactComponent as DashboardSolid } from './icons/DashboardSolid.svg'
export { ReactComponent as DeleteOutlined } from './icons/DeleteOutlined.svg'
export { ReactComponent as DeleteSolid } from './icons/DeleteSolid.svg'
export { ReactComponent as DeviceOutlined } from './icons/DeviceOutlined.svg'
export { ReactComponent as DeviceSolid } from './icons/DeviceSolid.svg'
export { ReactComponent as DevicesOutlined } from './icons/DevicesOutlined.svg'
export { ReactComponent as DevicesSolid } from './icons/DevicesSolid.svg'
export { ReactComponent as DownloadOutlined } from './icons/DownloadOutlined.svg'
export { ReactComponent as EnvelopClosedOutlined } from './icons/EnvelopClosedOutlined.svg'
export { ReactComponent as EnvelopClosedSolid } from './icons/EnvelopClosedSolid.svg'
export { ReactComponent as EnvelopOpenOutlined } from './icons/EnvelopOpenOutlined.svg'
export { ReactComponent as EnvelopOpenSolid } from './icons/EnvelopOpenSolid.svg'
export { ReactComponent as ExpandAllCircleOutlined } from './icons/ExpandAllCircleOutlined.svg'
export { ReactComponent as ExpandAllCircleSolid } from './icons/ExpandAllCircleSolid.svg'
export { ReactComponent as ExpandSquareOutlined } from './icons/ExpandSquareOutlined.svg'
export { ReactComponent as ExpandSquareSolid } from './icons/ExpandSquareSolid.svg'
export { ReactComponent as ExpandSquareDown } from './icons/ExpandSquareDown.svg'
export { ReactComponent as ExpandSquareUp } from './icons/ExpandSquareUp.svg'
export { ReactComponent as EyeOpenOutlined } from './icons/EyeOpenOutlined.svg'
export { ReactComponent as EyeOpenSolid } from './icons/EyeOpenSolid.svg'
export { ReactComponent as EyeSlashOutlined } from './icons/EyeSlashOutlined.svg'
export { ReactComponent as EyeSlashSolid } from './icons/EyeSlashSolid.svg'
export { ReactComponent as FailedOutline } from './icons/FailedOutline.svg'
export { ReactComponent as FailedSolid } from './icons/FailedSolid.svg'
export { ReactComponent as FilterOutlined } from './icons/FilterOutlined.svg'
export { ReactComponent as FilterSolid } from './icons/FilterSolid.svg'
export { ReactComponent as GlobeOutlined } from './icons/GlobeOutlined.svg'
export { ReactComponent as GlobeSolid } from './icons/GlobeSolid.svg'
export { ReactComponent as HealthOutline } from './icons/HealthOutline.svg'
export { ReactComponent as HealthSolid } from './icons/HealthSolid.svg'
export { ReactComponent as HelpOutlined } from './icons/HelpOutlined.svg'
export { ReactComponent as HelpSolid } from './icons/HelpSolid.svg'
export { ReactComponent as HomeOutlined } from './icons/HomeOutlined.svg'
export { ReactComponent as HomeSolid } from './icons/HomeSolid.svg'
export { ReactComponent as InformationSolid } from './icons/InformationSolid.svg'
export { ReactComponent as InformationOutlined } from './icons/InformationOutlined.svg'
export { ReactComponent as KeyOutline } from './icons/KeyOutline.svg'
export { ReactComponent as KeySolid } from './icons/KeySolid.svg'
export { ReactComponent as LicenceOutlined } from './icons/LicenceOutlined.svg'
export { ReactComponent as LicenceSolid } from './icons/LicenceSolid.svg'
export { ReactComponent as LightningOutlined } from './icons/LightningOutlined.svg'
export { ReactComponent as LightningSolid } from './icons/LightningSolid.svg'
export { ReactComponent as LineChartOutline } from './icons/LineChartOutline.svg'
export { ReactComponent as LineChartSolid } from './icons/LineChartSolid.svg'
export { ReactComponent as LoadingSolid } from './icons/LoadingSolid.svg'
export { ReactComponent as LocationOutline } from './icons/LocationOutline.svg'
export { ReactComponent as LocationOutlined } from './icons/LocationOutlined.svg'
export { ReactComponent as LocationSolid } from './icons/LocationSolid.svg'
export { ReactComponent as Logo } from './icons/Logo.svg'
export { ReactComponent as MagnifyingGlassMinusOutlined }
  from './icons/MagnifyingGlassMinusOutlined.svg'
export { ReactComponent as MagnifyingGlassMinusSolid } from './icons/MagnifyingGlassMinusSolid.svg'
export { ReactComponent as MagnifyingGlassPlusOutlined }
  from './icons/MagnifyingGlassPlusOutlined.svg'
export { ReactComponent as MagnifyingGlassPlusSolid } from './icons/MagnifyingGlassPlusSolid.svg'
export { ReactComponent as MapOutlined } from './icons/MapOutlined.svg'
export { ReactComponent as MapSolid } from './icons/MapSolid.svg'
export { ReactComponent as MicrophoneOutlined } from './icons/MicrophoneOutlined.svg'
export { ReactComponent as MicrophoneSolid } from './icons/MicrophoneSolid.svg'
export { ReactComponent as MinusCircleOutlined } from './icons/MinusCircleOutlined.svg'
export { ReactComponent as MinusCircleSolid } from './icons/MinusCircleSolid.svg'
export { ReactComponent as MinusSquareOutlined } from './icons/MinusSquareOutlined.svg'
export { ReactComponent as MinusSquareSolid } from './icons/MinusSquareSolid.svg'
export { ReactComponent as MobilePhoneOutlined } from './icons/MobilePhoneOutlined.svg'
export { ReactComponent as MobilePhoneSolid } from './icons/MobilePhoneSolid.svg'
export { ReactComponent as MoreVertical } from './icons/MoreVertical.svg'
export { ReactComponent as NetworksOutlined } from './icons/NetworksOutlined.svg'
export { ReactComponent as NetworksSolid } from './icons/NetworksSolid.svg'
export { ReactComponent as NotificationOutlined } from './icons/NotificationOutlined.svg'
export { ReactComponent as NotificationSolid } from './icons/NotificationSolid.svg'
export { ReactComponent as PhoneOutlined } from './icons/PhoneOutlined.svg'
export { ReactComponent as PhoneSolid } from './icons/PhoneSolid.svg'
export { ReactComponent as PhotoOutlined } from './icons/PhotoOutlined.svg'
export { ReactComponent as PhotoSolid } from './icons/PhotoSolid.svg'
export { ReactComponent as PieChartOutlined } from './icons/PieChartOutlined.svg'
export { ReactComponent as PieChartSolid } from './icons/PieChartSolid.svg'
export { ReactComponent as PlayOutlined } from './icons/PlayOutlined.svg'
export { ReactComponent as PlaySolid } from './icons/PlaySolid.svg'
export { ReactComponent as PlusCircleOutlined } from './icons/PlusCircleOutlined.svg'
export { ReactComponent as PlusCircleSolid } from './icons/PlusCircleSolid.svg'
export { ReactComponent as PlusSquareOutlined } from './icons/PlusSquareOutlined.svg'
export { ReactComponent as PlusSquareSolid } from './icons/PlusSquareSolid.svg'
export { ReactComponent as QuestionMarkCircleOutlined }
  from './icons/QuestionMarkCircleOutlined.svg'
export { ReactComponent as QuestionMarkCircleSolid } from './icons/QuestionMarkCircleSolid.svg'
export { ReactComponent as ReportsOutlined } from './icons/ReportsOutlined.svg'
export { ReactComponent as ReportsSolid } from './icons/ReportsSolid.svg'
export { ReactComponent as RocketOutlined } from './icons/RocketOutlined.svg'
export { ReactComponent as RocketSolid } from './icons/RocketSolid.svg'
export { ReactComponent as SearchFitOutlined } from './icons/SearchFitOutlined.svg'
export { ReactComponent as SearchFullOutlined } from './icons/SearchFullOutlined.svg'
export { ReactComponent as SearchOutlined } from './icons/SearchOutlined.svg'
export { ReactComponent as SendMessageOutlined } from './icons/SendMessageOutlined.svg'
export { ReactComponent as SendMessageSolid } from './icons/SendMessageSolid.svg'
export { ReactComponent as ServicesOutlined } from './icons/ServicesOutlined.svg'
export { ReactComponent as ServicesSolid } from './icons/ServicesSolid.svg'
export { ReactComponent as SettingsOutlined } from './icons/SettingsOutlined.svg'
export { ReactComponent as SettingsSolid } from './icons/SettingsSolid.svg'
export { ReactComponent as ShareOutlined } from './icons/ShareOutlined.svg'
export { ReactComponent as ShareSolid } from './icons/ShareSolid.svg'
export { ReactComponent as SpeedIndicatorOutlined } from './icons/SpeedIndicatorOutlined.svg'
export { ReactComponent as SpeedIndicatorSolid } from './icons/SpeedIndicatorSolid.svg'
export { ReactComponent as StarOutline } from './icons/StarOutline.svg'
export { ReactComponent as StarSolid } from './icons/StarSolid.svg'
export { ReactComponent as SuccessOutline } from './icons/SuccessOutline.svg'
export { ReactComponent as SuccessSolid } from './icons/SuccessSolid.svg'
export { ReactComponent as TagsOutline } from './icons/TagsOutline.svg'
export { ReactComponent as TagsSolid } from './icons/TagsSolid.svg'
export { ReactComponent as UsersThreeOutlined } from './icons/UsersThreeOutlined.svg'
export { ReactComponent as UsersThreeSolid } from './icons/UsersThreeSolid.svg'
export { ReactComponent as UsersTwoOutlined } from './icons/UsersTwoOutlined.svg'
export { ReactComponent as UsersTwoSolid } from './icons/UsersTwoSolid.svg'
export { ReactComponent as WarningCircleOutlined } from './icons/WarningCircleOutlined.svg'
export { ReactComponent as WarningCircleSolid } from './icons/WarningCircleSolid.svg'
export { ReactComponent as WarningTriangleOutlined } from './icons/WarningTriangleOutlined.svg'
export { ReactComponent as WarningTriangleSolid } from './icons/WarningTriangleSolid.svg'
export { ReactComponent as WavinghandWawingHandOutlined }
  from './icons/WavinghandWawingHandOutlined.svg'
export { ReactComponent as WindowsOutlined } from './icons/WindowsOutlined.svg'
export { ReactComponent as WindowsSolid } from './icons/WindowsSolid.svg'
export { ReactComponent as WorldOutlined } from './icons/WorldOutlined.svg'
export { ReactComponent as WorldSolid } from './icons/WorldSolid.svg'
