import { defineMessage, MessageDescriptor } from 'react-intl'

/* eslint-disable max-len */
export enum Features {
  ADDITIONAL_REGULATORY_DOMAINS_TOGGLE = 'wifi-eda-additional-regulatory-domains-toggle',
  AI_CRRM = 'acx-ui-ai-crrm-toggle',
  AI_RECOMMENDATIONS = 'acx-ui-ai-recommendations-toggle',
  ALLOW_INDOOR_CHANNEL_TOGGLE = 'wifi-consumer-allow-indoor-channel-toggle',
  ANY_3RDPARTY_INVITE_TOGGLE = 'ptenant-any-3rdparty-invite-toggle',
  AP_AFC_TOGGLE = 'ap-afc-toggle',
  AP_GPS = 'ap-gps-toggle',
  AP_GROUP_TOGGLE = 'wifi-eda-ap-group-table-toggle',
  AP_MANAGEMENT_VLAN_AP_LEVEL_TOGGLE = 'wifi-ap-mgmt-vlan-ap-level-toggle',
  AP_MESH_TOPOLOGY = 'acx-ui-ap-mesh-topology',
  AP_SNMP = 'wifi-consumer-ap-snmp-toggle',
  AP_STATIC_IP = 'wifi-consumer-ap-static-ip-toggle',
  AP_UPTIME_TOGGLE = 'ap-uptime-toggle',
  APP_INSIGHTS = 'acx-ui-app-insights-toggle',
  ASSIGN_MULTI_EC_TO_MSP_ADMINS = 'mspservice-assign-multi-ec-to-multi-msp-admin',
  BETA_BUTTON = 'acx-ui-beta-button-toggle',
  BETA_FLAG = 'acx-ui-beta-flag-toggle',
  CCD_TOGGLE = 'ap-ops-client-connection-diagnosis-toggle',
  CLOUDMOTE_SERVICE = 'cloudmote-service-enabled',
  CLOUDPATH_ASYNC_API_TOGGLE = 'acx-ui-cloudpath-async-api-toggle',
  CLOUDPATH_BETA = 'BETA-CP',
  CONFIG_CHANGE = 'acx-ui-config-change-toggle',
  CONFIG_TEMPLATE = 'acx-ui-config-template',
  CONNECTION_METERING = 'connection-metering-enabled',
  CRRM_PARTIAL = 'acx-ui-recommendations-crrm-partial-toggle',
  DATA_PLANE = 'dataPlane',
  DELEGATION_TIERING = 'acx-ui-delegation-tiering-toggle',
  DELETE_SOLO = 'ap-delete-with-solo-image-toggle',
  DEVICE_AGNOSTIC = 'entitlement-device-agnostic-sku-toggle',
  DIRECTED_MULTICAST = 'wifi-consumer-directed-multicast-toggle',
  DPSK_PER_BOUND_PASSPHRASE_ALLOWED_DEVICE_INCREASED_LIMIT = 'dpsk-per-bound-passphrase-allowed-device-increased-limit',
  EDGE_LAG = 'acx-ui-edges-lag-toggle',
  EDGES_DHCP_CSV_TOGGLE = 'acx-ui-edges-dhcp-csv-toggle',
  EDGES_PING_TRACEROUTE_TOGGLE = 'acx-ui-edges-ping-traceroute-toggle',
  EDGES_SCHEDULE_UPGRADE_TOGGLE = 'acx-ui-edges-schedule-upgrade-toggle',
  EDGES_SD_LAN_PHASE2_TOGGLE = 'acx-ui-edges-sdlan-phase2-toggle',
  EDGES_SD_LAN_TOGGLE = 'acx-ui-edges-centralized-forwarding-toggle',
  EDGES_SD_LAN_HA_TOGGLE = 'edge-sdlan-ha-toggle',
  EDGES_SUB_INTERFACE_CSV_TOGGLE = 'acx-ui-edges-sub-interface-csv-toggle',
  EDGES_TOGGLE = 'acx-ui-edges-toggle',
  EDGE_HA_TOGGLE = 'edge-ha-toggle',
  EDGE_DHCP_HA_TOGGLE = 'edge-dhcp-ha-toggle',
  EDGE_FIREWALL_HA_TOGGLE = 'edge-firewall-ha-toggle',
  EDGE_PIN_HA_TOGGLE = 'edge-pin-ha-toggle',
  EOL_AP_2022_12_PHASE_2_TOGGLE = 'eol-ap-2022-12-phase-2-toggle',
  EXPORT_DEVICE = 'viewmodel-export-device-inventory',
  EXPORT_EVENTS_TOGGLE = 'acx-ui-scheduled-events-export-toggle',
  G_MAP = 'acx-ui-maps-api-toggle',
  GOOGLE_WORKSPACE_SSO_TOGGLE = 'google-workspace-sso-toggle',
  GROUP_BASED_LOGIN_TOGGLE = 'group-based-login-toggle',
  HEALTH_DRILLDOWN = 'acx-ui-health-drilldown-toggle',
  HELP_SUPPORT = 'acx-ui-help-support',
  HOST_APPROVAL_EMAIL_LIST_TOGGLE = 'guest-host-approval-email-list-toggle',
  I18N_DATA_STUDIO_TOGGLE = 'acx-ui-i18n-data-studio-toggle',
  I18N_DE_ZH_TOGGLE = 'acx-ui-i18n-de-zh-toggle',
  I18N_PHASE2_TOGGLE = 'acx-ui-i18n-phase2-toggle',
  I18N_TOGGLE = 'acx-ui-i18n-toggle',
  IDM_APPLICATION_KEY_TOGGLE = 'ptenant-application-key-toggle',
  IDM_DECOUPLING = 'ptenant-admin-authentication-enabled',
  INCIDENTS_EMAIL_NOTIFICATION_TOGGLE = 'acx-ui-incidents-notification-toggle',
  INCIDENTS_AIRTIME_TOGGLE = 'acx-ui-incidents-airtime-toggle',
  LICENSE_BANNER = 'acx-ui-license-banner',
  LINKEDIN_OIDC_TOGGLE = 'guest-linkedin-openid-connect-toggle',
  LIST_OF_CLIENTS_PER_WLAN = 'acx-ui-list-of-clients-per-wlan-toggle',
  LOAD_BALANCING = 'wifi-consumer-load-balancing-toggle',
  MDNS_FENCING = 'wifi-consumer-bonjour-fencing-toggle',
  MESH_ENHANCEMENTS = 'wifi-eda-mesh-enhancements-toggle',
  MSP_AGGREGATE_NOTIFICATION_TOGGLE = 'aggregate-notification-toggle',
  MSP_BRAND_360 = 'acx-ui-msp-brand360-toggle',
  MSP_EC_CREATE_WITH_TIER = 'mspservice-mspec-create-pass-tier-info',
  MSP_HSP_SUPPORT = 'mspservice-hsp-01',
  MSP_HSP_PLM_FF = 'LOC-HSP',
  MSP_SELF_ASSIGNMENT = 'entitlement-msp-own-license-assignment-toggle',
  MSP_UPGRADE_MULTI_EC_FIRMWARE = 'mspservice-multi-ec-to-upgrade-ap-firmware',
  MSPEC_ALARM_COUNT_SUPPORT_TOGGLE = 'acx-ui-mspec-alarm-count-toggle',
  MSPEC_ALLOW_DELETE_ADMIN = 'mspservice-allow-last-ec-admin-deletion',
  MSPEC_OPTIONAL_ADMIN = 'mspservice-mspec-adminoptional',
  MULTICAST_RATE_LIMIT_TOGGLE = 'wifi-eda-multicast-rate-limiting-toggle',
  MULTIPLE_VAR_INVITATION_TOGGLE = 'ptenant-multiple-var-support-toggle',
  NETWORK_SEGMENTATION = 'acx-ui-network-segmentation-toggle',
  NETWORK_SEGMENTATION_SWITCH = 'switch-consumer-nsg-toggle',
  NEW_OS_VENDOR_IN_DEVICE_POLICY = 'acx-ui-new-os-vendor-in-device-policy-toggle',
  PLM_FF = 'ACX-PLM-FF',
  POLICIES = 'acx-ui-policies',
  PTENANT_RBAC_DPSK_ROLE_INTRODUCTION = 'ptenant-rbac-dpsk-role-introduction',
  RADIO6G_RATE_CONTROL = 'radio6g-rate-control-toggle',
  RADIUS_CLIENT_CONFIG = 'radius-client-config-api-enabled',
  RADIUS_OPTIONS = 'wifi-eda-wlan-radius-options-toggle',
  RECOMMENDATION_EMAIL_NOTIFICIATION_TOGGLE = 'acx-ui-recommendation-notification-toggle',
  ROGUE_EVENTS_FILTER = 'rogue-events-filter-enabled',
  RUCKUS_AI_CHATBOT_TOGGLE = 'ruckus-ai-chatbot-toggle',
  RUCKUS_AI_CRRM_PARTIAL = 'ruckus-ai-recommendations-crrm-partial-toggle',
  RUCKUS_AI_INCIDENT_SUMMARY_TOGGLE = 'ruckus-ai-incident-summary-toggle',
  RUCKUS_AI_INCIDENTS_AIRTIME_TOGGLE = 'ruckus-ai-incidents-airtime-toggle',
  RUCKUS_AI_ZONES_LIST = 'ruckus-ai-zones-toggle',
  RUCKUS_WAN_GATEWAY_UI_SHOW = 'ruckus-wan-gateway-ui-show',
  SERVICES = 'acx-ui-services',
  SIGPACK_UPGRADE = 'acx-ui-sigpack-upgrade',
  SSO = 'ADMN-SSO',
  STICKY_CLIENT_STEERING = 'wifi-eda-sticky-client-steering-toggle',
  SUPPORT_DELEGATE_MSP_DASHBOARD_TOGGLE = 'acx-ui-support-to-msp-dashboard-toggle',
  SUPPORT_SWITCH_TWO_VERSION_UPGRADE = 'switch-consumer-support-two-fw-upgrade-toggle',
  SWITCH_ADMIN_PASSWORD = 'switch-consumer-admin-password-toggle',
  SWITCH_DHCP_CLIENTS = 'switch-dhcp-clients',
  SWITCH_EDIT_PORTS_FROM_PANEL = 'acx-ui-edit-ports-from-panel',
  SWITCH_FIRMWARE_RELATED_TSB_BLOCKING_TOGGLE = 'switch-firmware-related-tsb-blocking-toggle',
  SWITCH_RBAC_API = 'acx-ui-rbac-api-switch-toggle',
  SWITCH_STACK_NAME_DISPLAY_TOGGLE = 'switch-stack-name-display-toggle',
  SWITCH_STACK_UNIT_LIMITATION = 'switch-stack-unit-limitation',
  SWITCH_UPGRADE_BY_SWITCH = 'switch-consumer-upgrade-by-switch-toggle',
  TECH_PARTNER_ASSIGN_ECS = 'mspservice-techpartner-assign-ecs',
  TECH_PARTNER_GET_MSP_CUSTOMERS_TOGGLE = 'viewmodel-techpartner-getmspcustomers',
  TRI_RADIO = 'tri-band-radio-toggle',
  VENUE_AP_MANAGEMENT_VLAN_TOGGLE = 'wifi-venue-ap-mgmt-vlan-toggle',
  VIDEO_CALL_QOE = 'acx-ui-video-call-qoe-toggle',
  WIFI_AMB_TOGGLE = 'wifi-amb-toggle',
  WIFI_AP_BSS_COLORING_TOGGLE = 'wifi-ap-bss-coloring-toggle',
  WIFI_COMPATIBILITY_CHECK_TOGGLE = 'wifi-compatibility-check-toggle',
  WIFI_DHCP_OPT_82_TOGGLE = 'wifi-dhcp-opt-82-toggle',
  WIFI_DOWNGRADE_VENUE_ABF_TOGGLE = 'wifi-downgrade-venue-abf-toggle',
  WIFI_DTIM_TOGGLE = 'wifi-dtim-toggle',
  WIFI_DYNAMIC_VLAN_TOGGLE = 'wifi-dynamic-vlan-toggle',
  WIFI_EDA_BSS_PRIORITY_TOGGLE = 'wifi-eda-bss-priority-toggle',
  WIFI_EDA_BYPASS_CNA_TOGGLE = 'wifi-eda-bypass-cna-toggle',
  WIFI_EDA_CLIENT_REVOKE_TOGGLE = 'wifi-eda-client-revoke-toggle',
  WIFI_EDA_GATEWAY = 'wifi-api-gateway-eda-toggle',
  WIFI_EDA_MULTICAST_FILTER_TOGGLE = 'wifi-eda-multicast-filter-toggle',
  WIFI_EDA_NEIGHBORS_TOGGLE = 'wifi-eda-neighbors-toggle',
  WIFI_EDA_NON_PROXY_DPSK_TOGGLE = 'wifi-eda-non-proxy-dpsk-toggle',
  WIFI_EDA_OWE_TOGGLE = 'wifi-eda-owe-toggle',
  WIFI_EDA_OWE_TRANSITION_TOGGLE = 'wifi-eda-owe-transition-toggle',
  WIFI_EDA_PER_AP_RADIO_CUSTOMIZATION_TOGGLE = 'wifi-eda-per-ap-radio-customization-toggle',
  WIFI_EDA_QOS_MAP_SET_TOGGLE = 'wifi-eda-qos-map-set-toggle',
  WIFI_EDA_QOS_MIRRORING_TOGGLE = 'wifi-eda-qos-mirroring-toggle',
  WIFI_EDA_READY_TOGGLE = 'wifi-eda-ready-toggle',
  WIFI_EDA_SECURE_BOOT_TOGGLE = 'wifi-eda-secure-boot-toggle',
  WIFI_EDA_WIFI6_AND_WIFI7_FLAG_TOGGLE = 'wifi-eda-wifi6-and-wifi7-flag-toggle',
  WIFI_EDA_WIFI7_320MHZ = 'wifi-eda-wifi7-320mhz-toggle',
  WIFI_EDA_WIFI7_MLO_TOGGLE = 'wifi-eda-wifi7-mlo-toggle',
  WIFI_EDA_WISPR_ALWAYS_ACCEPT_TOGGLE = 'wifi-eda-wispr-always-accept-toggle',
  WIFI_EDA_WPA3_DSAE_TOGGLE = 'wifi-eda-wpa3-dsae-toggle',
  WIFI_FR_6029_FG1_TOGGLE = 'wifi-fr-6029-fg1-toggle',
  WIFI_FR_6029_FG3_2_TOGGLE = 'wifi-fr-6029-fg3-2-toggle',
  WIFI_FR_6029_FG5_TOGGLE = 'wifi-fr-6029-fg5-toggle',
  WIFI_FR_6029_FG6_1_TOGGLE = 'wifi-fr-6029-fg6-1-toggle',
  WIFI_FR_6029_FG6_2_TOGGLE = 'wifi-fr-6029-fg6-2-toggle',
  WIFI_FR_HOTSPOT20_R1_TOGGLE = 'wifi-fr-hotspot20-r1-toggle',
  WIFI_SWITCHABLE_RF_TOGGLE = 'wifi-switchable-rf-toggle',
  WIFI_ANTENNA_TYPE_TOGGLE = 'wifi-antenna-type-selection-toggle',
  WIFI_TRUNK_PORT_UNTAGGED_VLAN_TOGGLE = 'wifi-trunk-port-untagged-vlan-toggle',
  WIFI_VENUE_BSS_COLORING_TOGGLE = 'wifi-fr-6029-fg1-toggle',
  WIFI_API_V2_TOGGLE = 'wifi-api-network-activations-by-query-v2-toggle',
  WISPR_ENCRYPT_MAC_IP = 'acx-ui-wispr-encrypt-mac-ip-toggle',
  WPA3_80211R = 'wifi-eda-wpa3-80211r-toggle',
  ZERO_TOUCH_MESH = 'wifi-eda-zero-touch-mesh-toggle',
  WIFI_EDA_BRANCH_LEVEL_SUPPORTED_MODELS_TOGGLE = 'wifi-eda-branch-level-supported-models-toggle',
  RUCKUS_AI_USERS_TOGGLE = 'ruckus-ai-sso-toggle',
  SWITCH_EXTERNAL_IP_TOGGLE = 'acx-ui-display-external-ip-address-for-switches-toggle',
  WIFI_8021X_MAC_AUTH_TOGGLE = 'wifi-fr-8021x-mac-toggle',
  RUCKUS_AI_NEW_ROLES_TOGGLE = 'ruckus-ai-users-new-roles-toggle'
}

export enum TierFeatures { // for Tier (ex: Beta) feature flag
  AP_70 = 'AP-70',
  BETA_DPSK3 = 'BETA-DPSK3',
  SMART_EDGES = 'PLCY-EDGE'
}

interface BetaList {
  key: TierFeatures
  description: MessageDescriptor
  status: boolean
}

// This is Mandatory for Beta features list...
// When every we add a TierFeatures enum value above we need it's related
// description details and status value - true/false to show/hide
// from displaying in UI drawer component BetaFeaturesDrawer.
// If we don't have a description blurb and
// don't want it to be displayed then add status = false
export const BetaListDetails:BetaList[] = [
  { key: TierFeatures.BETA_DPSK3, description: defineMessage({ defaultMessage: 'DPSK3: Dynamic Preshared Keys working with WPA3-DSAE. Users connect their devices to a WPA2/WPA3 network with DPSK and are automatically moved to the WPA3 WLAN, allowing DPSK operation with WiFi 6e or WiFi7. DPSK3 allows the customer to take advantage of the flexibility of DPSK with the security of WPA3.' }), status: true },
  { key: TierFeatures.AP_70, description: defineMessage({ defaultMessage: 'AP-70: Wi-Fi 7 - Wi-Fi 7 UI configuration available for early adopters and customers provided with advance units of the R770. Contact your reseller for more information on availability of the new R770!' }), status: true },
  { key: TierFeatures.SMART_EDGES, description: defineMessage({ defaultMessage: 'SmartEdge: RUCKUS SmartEdge is a platfrom to run RUCKUS services on. Network administrators can utilize SD-LAN service or Personal Identity Networking service on a SmartEdge. SD-LAN provides WLAN tunnelling using VXLAN. This will provide end users a seamless roaming experience across a network. The Personal Identity Networking service provides individual networks for users which is typically used in a multi-dwelling facility.' }), status: true }
]
