export const trafficByApplicationFixture = {
  uploadAppTraffic: 5789742796,
  downloadAppTraffic: 13706202165,
  topNAppByUpload: [
    {
      name: 'ipsec',
      applicationTraffic: 5775521028,
      clientCount: 1,
      timeSeries: {
        applicationTraffic: [
          3431156014,
          3898202840,
          693221544,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null
        ]
      }
    },
    {
      name: 'safebrowsing.googleapis.com',
      applicationTraffic: 2731785,
      clientCount: 2,
      timeSeries: {
        applicationTraffic: [
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          2701488,
          9244,
          21053,
          null
        ]
      }
    },
    {
      name: 'outlook',
      applicationTraffic: 1878505,
      clientCount: 5,
      timeSeries: {
        applicationTraffic: [
          801267,
          82494,
          155672,
          68,
          null,
          6787,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          1034,
          856292,
          20245,
          1150
        ]
      }
    },
    {
      name: 'apple',
      applicationTraffic: 1714154,
      clientCount: 5,
      timeSeries: {
        applicationTraffic: [
          5871,
          4819,
          9100,
          17242,
          17566,
          2035,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          1833,
          2133,
          11903,
          1595250,
          16608,
          2635,
          31288
        ]
      }
    },
    {
      name: 'google',
      applicationTraffic: 965038,
      clientCount: 3,
      timeSeries: {
        applicationTraffic: [
          null,
          null,
          null,
          null,
          null,
          3050,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          177134,
          784854,
          null
        ]
      }
    }
  ],
  topNAppByDownload: [
    {
      name: 'ipsec',
      applicationTraffic: 13400029596,
      clientCount: 1,
      timeSeries: {
        applicationTraffic: [
          7921185566,
          9027440808,
          1557117452,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null
        ]
      }
    },
    {
      name: 'apple',
      applicationTraffic: 160701505,
      clientCount: 5,
      timeSeries: {
        applicationTraffic: [
          16953,
          82332,
          25432,
          104599,
          57965,
          13338,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          6228,
          6317,
          370527,
          159218019,
          214899,
          17084,
          577938
        ]
      }
    },
    {
      name: 'outlook',
      applicationTraffic: 24161004,
      clientCount: 5,
      timeSeries: {
        applicationTraffic: [
          1834004,
          67916,
          478485,
          120,
          null,
          109741,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          2642,
          21720859,
          25645,
          2895
        ]
      }
    },
    {
      name: 'intellij.tips',
      applicationTraffic: 18429540,
      clientCount: 1,
      timeSeries: {
        applicationTraffic: [
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          18429540,
          null
        ]
      }
    },
    {
      name: 'youtube.com',
      applicationTraffic: 13940858,
      clientCount: 2,
      timeSeries: {
        applicationTraffic: [
          null,
          null,
          5986,
          13917326,
          17546,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null
        ]
      }
    }
  ]
}
