export enum ApPacketCaptureStateEnum {
  IDLE = 'IDLE',
  OPERATION_TIMEOUT = 'OPERATION_TIMEOUT',
  STARTING = 'STARTING',
  STARTING_TIMEOUT = 'STARTING_TIMEOUT',
  STARTING_ERROR = 'STARTING_ERROR',
  CAPTURING = 'CAPTURING',
  STOPPING = 'STOPPING',
  STOPPING_TIMEOUT = 'STOPPING_TIMEOUT',
  STOPPING_ERROR = 'STOPPING_ERROR',
  READY = 'READY',
}

export enum CaptureInterfaceEnum {
  RADIO24 = 'RADIO24',
  RADIO50 = 'RADIO50',
  RADIO50UPPER = 'RADIO50UPPER',
  RADIO50LOWER = 'RADIO50LOWER',
  RADIO60 = 'RADIO60',
  ETH0 = 'ETH0',
  ETH1 = 'ETH1',
  ETH2 = 'ETH2',
  ETH3 = 'ETH3',
  ETH4 = 'ETH4',
  ETH5 = 'ETH5',
  ETH6 = 'ETH6',
  ETH7 = 'ETH7',
}

export enum FrameTypeFilterEnum {
  MANAGEMENT = 'MANAGEMENT',
  CONTROL = 'CONTROL',
  DATA = 'DATA',
}
