import { defineMessage } from 'react-intl'

/* eslint-disable max-len */
export const apKeyMap = [
  { id: 1, value: 'initialState.ccmAp.id', text: 'NA', textAlto: 'TBD', enumType: '', incidents: {}, kpis: {} },
  { id: 2, value: 'initialState.ccmAp.device_name', text: defineMessage({ defaultMessage: 'AP Name' }), textAlto: defineMessage({ defaultMessage: 'AP Name' }), enumType: '', incidents: {}, kpis: {} },
  { id: 3, value: 'initialState.ccmAp.common.sci_enabled', text: 'TBD', textAlto: 'TBD', enumType: '', incidents: {}, kpis: {} },
  { id: 4, value: 'initialState.ccmAp.common.ap_login', text: defineMessage({ defaultMessage: 'AP Admin Logon : Username' }), textAlto: 'TBD', enumType: '', incidents: {}, kpis: {} },
  { id: 5, value: 'initialState.ccmAp.common.ap_management_vlan_id', text: defineMessage({ defaultMessage: 'AP Management VLAN' }), textAlto: 'TBD', enumType: '', incidents: { 'i-apserv-high-num-reboots': 1, 'i-apserv-continuous-reboots': 1 }, kpis: {} },
  { id: 6, value: 'initialState.ccmAp.common.ap_management_vlan_mode', text: defineMessage({ defaultMessage: 'AP Management VLAN Mode' }), textAlto: 'TBD', enumType: '', incidents: { 'i-apserv-high-num-reboots': 1, 'i-apserv-continuous-reboots': 1 }, kpis: { apToSZLatency: 1 } },
  { id: 7, value: 'initialState.ccmAp.common.ap_pass', text: defineMessage({ defaultMessage: 'AP Admin Logon : Password' }), textAlto: 'TBD', enumType: '', incidents: {}, kpis: {} },
  { id: 8, value: 'initialState.ccmAp.common.ap_rogue_enabled', text: defineMessage({ defaultMessage: 'Rogue AP Detection' }), textAlto: 'TBD', enumType: '', incidents: {}, kpis: {} },
  { id: 9, value: 'initialState.ccmAp.common.ap_rogue_report_all', text: 'TBD', textAlto: 'TBD', enumType: '', incidents: {}, kpis: {} },
  { id: 10, value: 'initialState.ccmAp.common.ap_rogue_report_mac_spoofing', text: 'TBD', textAlto: 'TBD', enumType: '', incidents: {}, kpis: {} },
  { id: 11, value: 'initialState.ccmAp.common.ap_rogue_report_protect', text: defineMessage({ defaultMessage: 'Rogue Protection' }), textAlto: 'TBD', enumType: '', incidents: {}, kpis: {} },
  { id: 12, value: 'initialState.ccmAp.common.ap_rogue_report_same_network', text: 'TBD', textAlto: 'TBD', enumType: '', incidents: {}, kpis: {} },
  { id: 13, value: 'initialState.ccmAp.common.ap_rogue_report_ssid_spoofing', text: 'TBD', textAlto: 'TBD', enumType: '', incidents: {}, kpis: {} },
  { id: 14, value: 'initialState.ccmAp.common.ap_rogue_report_user_blocked', text: 'TBD', textAlto: 'TBD', enumType: '', incidents: {}, kpis: {} },
  { id: 15, value: 'initialState.ccmAp.common.aws_venue', text: 'TBD', textAlto: 'TBD', enumType: '', incidents: {}, kpis: {} },
  { id: 16, value: 'initialState.ccmAp.common.bonjour_gateway_enabled', text: defineMessage({ defaultMessage: 'Bonjour Fencing' }), textAlto: 'TBD', enumType: '', incidents: {}, kpis: {} },
  { id: 17, value: 'initialState.ccmAp.common.channel_evaluation_interval', text: 'TBD', textAlto: 'TBD', enumType: '', incidents: {}, kpis: {} },
  { id: 18, value: 'initialState.ccmAp.common.control_tos', text: 'TBD', textAlto: 'TBD', enumType: '', incidents: {}, kpis: {} },
  { id: 19, value: 'initialState.ccmAp.common.country_code', text: defineMessage({ defaultMessage: 'Country Code' }), textAlto: 'TBD', enumType: '', incidents: {}, kpis: {} },
  { id: 20, value: 'initialState.ccmAp.common.device_ip_mode', text: defineMessage({ defaultMessage: 'AP IP Mode' }), textAlto: 'TBD', enumType: 'com.ruckuswireless.scg.protobuf.ccm.Zone.CcmCommon.IpMode', incidents: {}, kpis: {} },
  { id: 21, value: 'initialState.ccmAp.common.dos_barring_enabled', text: defineMessage({ defaultMessage: 'Dos Protection' }), textAlto: 'TBD', enumType: '', incidents: {}, kpis: {} },
  { id: 22, value: 'initialState.ccmAp.common.gw_loss_timeout', text: defineMessage({ defaultMessage: 'AP Reboot Timeout : Default gateway not reachable' }), textAlto: 'TBD', enumType: '', incidents: {}, kpis: {} },
  { id: 23, value: 'initialState.ccmAp.common.lbs_enabled', text: defineMessage({ defaultMessage: 'Location Based service' }), textAlto: 'TBD', enumType: '', incidents: {}, kpis: {} },
  { id: 24, value: 'initialState.ccmAp.common.location', text: defineMessage({ defaultMessage: 'Location' }), textAlto: 'TBD', enumType: '', incidents: {}, kpis: {} },
  { id: 25, value: 'initialState.ccmAp.common.location_additional_info', text: defineMessage({ defaultMessage: 'Location Additional Information' }), textAlto: 'TBD', enumType: '', incidents: {}, kpis: {} },
  { id: 26, value: 'initialState.ccmAp.common.mesh_enabled', text: defineMessage({ defaultMessage: 'Mesh Networking' }), textAlto: 'TBD', enumType: '', incidents: { 'i-apserv-high-num-reboots': 1, 'i-apserv-continuous-reboots': 1 }, kpis: { connectionSuccess: 1, timeToConnect: 1, apCapacity: 1 } },
  { id: 27, value: 'initialState.ccmAp.common.recovery_ssid_enabled', text: defineMessage({ defaultMessage: 'Recovery SSID: Enable Broadcast' }), textAlto: 'TBD', enumType: '', incidents: {}, kpis: {} },
  { id: 28, value: 'initialState.ccmAp.common.recovery_ssid_psk_key', text: defineMessage({ defaultMessage: 'Recovery SSID: Custom Passphrase' }), textAlto: 'TBD', enumType: '', incidents: {}, kpis: {} },
  { id: 29, value: 'initialState.ccmAp.common.server_loss_timeout', text: defineMessage({ defaultMessage: 'AP Reboot Timeout : Controller not reachable' }), textAlto: 'TBD', enumType: '', incidents: {}, kpis: {} },
  { id: 30, value: 'initialState.ccmAp.common.smart_mon_enabled', text: defineMessage({ defaultMessage: 'Smart Monitor' }), textAlto: 'TBD', enumType: '', incidents: {}, kpis: {} },
  { id: 31, value: 'initialState.ccmAp.common.smart_mon_interval', text: defineMessage({ defaultMessage: 'Smart Monitor: Health Check Interval' }), textAlto: 'TBD', enumType: '', incidents: {}, kpis: {} },
  { id: 32, value: 'initialState.ccmAp.common.smart_mon_threshold', text: defineMessage({ defaultMessage: 'Smart Monitor: Health Check Retry Threshold' }), textAlto: 'TBD', enumType: '', incidents: {}, kpis: {} },
  { id: 33, value: 'initialState.ccmAp.common.smart_roam_disconnect', text: 'TBD', textAlto: 'TBD', enumType: '', incidents: {}, kpis: {} },
  { id: 34, value: 'initialState.ccmAp.common.syslog_facility', text: defineMessage({ defaultMessage: 'Syslog Event Facility' }), textAlto: 'TBD', enumType: '', incidents: {}, kpis: {} },
  { id: 35, value: 'initialState.ccmAp.common.syslog_ip', text: defineMessage({ defaultMessage: 'Syslog : IP' }), textAlto: 'TBD', enumType: '', incidents: {}, kpis: {} },
  { id: 36, value: 'initialState.ccmAp.common.syslog_port', text: defineMessage({ defaultMessage: 'Syslog : Port' }), textAlto: 'TBD', enumType: '', incidents: {}, kpis: {} },
  { id: 37, value: 'initialState.ccmAp.common.syslog_r_level', text: 'TBD', textAlto: 'TBD', enumType: '', incidents: {}, kpis: {} },
  { id: 38, value: 'initialState.ccmAp.common.time_zone', text: defineMessage({ defaultMessage: 'AP Time Zone' }), textAlto: 'TBD', enumType: '', incidents: {}, kpis: {} },
  { id: 39, value: 'initialState.ccmAp.common.vlan_overlapping_enabled', text: 'TBD', textAlto: 'TBD', enumType: '', incidents: { 'i-apserv-high-num-reboots': 1, 'i-apserv-continuous-reboots': 1 }, kpis: {} },
  { id: 40, value: 'initialState.ccmAp.common.tunnel_profile_id', text: 'NA', textAlto: 'TBD', enumType: '', incidents: {}, kpis: {} },
  { id: 41, value: 'initialState.ccmAp.common.ap_latency_interval_ping_enabled', text: defineMessage({ defaultMessage: 'AP Ping Latency Interval' }), textAlto: 'TBD', enumType: '', incidents: {}, kpis: {} },
  { id: 42, value: 'initialState.ccmAp.common.directed_multicast_from_wired', text: defineMessage({ defaultMessage: 'Directed Multicast Traffic From Wired Client' }), textAlto: 'TBD', enumType: '', incidents: {}, kpis: {} },
  { id: 43, value: 'initialState.ccmAp.common.directed_multicast_from_wireless', text: defineMessage({ defaultMessage: 'Directed Multicast Traffic From Wireless Client' }), textAlto: 'TBD', enumType: '', incidents: {}, kpis: {} },
  { id: 44, value: 'initialState.ccmAp.common.directed_multicast_from_network', text: defineMessage({ defaultMessage: 'Directed Multicast Traffic From Network' }), textAlto: 'TBD', enumType: '', incidents: {}, kpis: {} },
  { id: 45, value: 'initialState.ccmAp.common.venue_profile_id', text: 'NA', textAlto: 'TBD', enumType: '', incidents: {}, kpis: {} },
  { id: 46, value: 'initialState.ccmAp.common.ssh_tunnel_encryption', text: defineMessage({ defaultMessage: 'SSH Tunnel Encryption' }), textAlto: 'TBD', enumType: 'com.ruckuswireless.scg.protobuf.ccm.Zone.CcmCommon.SshTunnelEncryption', incidents: { 'i-apserv-high-num-reboots': 1, 'i-apserv-continuous-reboots': 1 }, kpis: {} },
  { id: 47, value: 'initialState.ccmAp.common.contact_apr', text: 'TBD', textAlto: 'TBD', enumType: '', incidents: {}, kpis: {} },
  { id: 48, value: 'initialState.ccmAp.common.ap_hccd_enabled', text: defineMessage({ defaultMessage: 'Client Diagnostic' }), textAlto: 'TBD', enumType: '', incidents: {}, kpis: {} },
  { id: 49, value: 'initialState.ccmAp.common.ipv6_traffic_filter_enabled', text: 'TBD', textAlto: 'TBD', enumType: '', incidents: {}, kpis: {} },
  { id: 50, value: 'initialState.ccmAp.common.cband_channel_enable', text: defineMessage({ defaultMessage: 'Based on country : 5.8 GHz Channel' }), textAlto: 'TBD', enumType: '', incidents: {}, kpis: {} },
  { id: 51, value: 'initialState.ccmAp.common.cband_channel_license', text: defineMessage({ defaultMessage: 'Based on country : 5.8 GHz Channel License' }), textAlto: 'TBD', enumType: '', incidents: {}, kpis: {} },
  { id: 52, value: 'initialState.ccmAp.common.altitude_unit', text: defineMessage({ defaultMessage: 'GPS Coordinates: Altitude Unit' }), textAlto: 'TBD', enumType: '', incidents: {}, kpis: {} },
  { id: 53, value: 'initialState.ccmAp.common.altitude_value', text: defineMessage({ defaultMessage: 'GPS Coordinates: Altitude' }), textAlto: 'TBD', enumType: '', incidents: {}, kpis: {} },
  { id: 54, value: 'initialState.ccmAp.common.device_gps', text: defineMessage({ defaultMessage: 'GPS Coordinates : Latitude Longitude' }), textAlto: 'TBD', enumType: '', incidents: {}, kpis: {} },
  { id: 55, value: 'initialState.ccmAp.common.gps_source', text: 'TBD', textAlto: 'TBD', enumType: 'com.ruckuswireless.scg.protobuf.ccm.Zone.CcmCommon.GpsMode', incidents: {}, kpis: {} },
  { id: 56, value: 'initialState.ccmAp.common.rtls_profile_id', text: 'NA', textAlto: 'TBD', enumType: '', incidents: {}, kpis: {} },
  { id: 57, value: 'initialState.ccmAp.common.ap_rogue_report_snr_threshold', text: defineMessage({ defaultMessage: 'Rogue: Report RSSI Threshold' }), textAlto: 'TBD', enumType: '', incidents: {}, kpis: {} },
  { id: 58, value: 'initialState.ccmAp.common.rogue_contain_mode', text: defineMessage({ defaultMessage: 'Rogue: Rogue Protection Aggressiveness' }), textAlto: 'TBD', enumType: 'com.ruckuswireless.scg.protobuf.ccm.Zone.CcmCommon.RogueContainmentMode', incidents: {}, kpis: {} },
  { id: 59, value: 'initialState.ccmAp.common.ap_rogue_jamming_detection', text: defineMessage({ defaultMessage: 'Rogue: Radio Jamming Detection' }), textAlto: 'TBD', enumType: '', incidents: {}, kpis: {} },
  { id: 60, value: 'initialState.ccmAp.common.ap_rogue_jamming_threshold', text: defineMessage({ defaultMessage: 'Rogue: Radio Jamming Threshold' }), textAlto: 'TBD', enumType: '', incidents: {}, kpis: {} },
  { id: 61, value: 'initialState.ccmAp.common.load_balancing.loadBalancingMethod', text: defineMessage({ defaultMessage: 'Load Balancing' }), textAlto: 'TBD', enumType: 'com.ruckuswireless.scg.protobuf.ccm.Zone.CcmLoadBalancing.LoadBalancingMethod', incidents: {}, kpis: {} },
  { id: 62, value: 'initialState.ccmAp.common.load_balancing.band_balancing_mode', text: defineMessage({ defaultMessage: 'Load Balancing: Band Balancing Mode' }), textAlto: 'TBD', enumType: 'com.ruckuswireless.scg.protobuf.ccm.Zone.CcmLoadBalancing.BandBalancingMode', incidents: {}, kpis: {} },
  { id: 63, value: 'initialState.ccmAp.common.load_balancing.bb_client_percent_24g', text: defineMessage({ defaultMessage: 'Load Balancing: Band Balancing: Percentage of client load on 2.4G Band' }), textAlto: 'TBD', enumType: '', incidents: {}, kpis: {} },
  { id: 64, value: 'initialState.ccmAp.common.load_balancing.bb_client_percent_5g', text: defineMessage({ defaultMessage: 'Load Balancing: Band Balancing: Percentage of client load on 5G Band' }), textAlto: 'TBD', enumType: '', incidents: {}, kpis: {} },
  { id: 65, value: 'initialState.ccmAp.common.load_balancing.band_balancing_enabled', text: defineMessage({ defaultMessage: 'Load Balancing: Band Balancing' }), textAlto: 'TBD', enumType: '', incidents: {}, kpis: {} },
  { id: 66, value: 'initialState.ccmAp.common.load_balancing.steering_mode', text: defineMessage({ defaultMessage: 'Load Balancing: Band Balancing Steering Mode' }), textAlto: 'TBD', enumType: 'com.ruckuswireless.scg.protobuf.ccm.Zone.CcmLoadBalancing.SteeringMode', incidents: {}, kpis: {} },
  { id: 67, value: 'initialState.ccmAp.common.lte_firmware_upgrade_timestamp', text: 'TBD', textAlto: 'TBD', enumType: '', incidents: {}, kpis: {} },
  { id: 68, value: 'initialState.ccmAp.common.health_check_sites', text: defineMessage({ defaultMessage: 'Health Check Sites' }), textAlto: 'TBD', enumType: '', incidents: {}, kpis: {} },
  { id: 69, value: 'initialState.ccmAp.common.lte_band_lock_channel.sim_card_id', text: 'NA', textAlto: 'TBD', enumType: '', incidents: {}, kpis: {} },
  { id: 70, value: 'initialState.ccmAp.common.lte_band_lock_channel.type', text: 'TBD', textAlto: 'TBD', enumType: '', incidents: {}, kpis: {} },
  { id: 71, value: 'initialState.ccmAp.common.lte_band_lock_channel.channel4g', text: defineMessage({ defaultMessage: 'LTE Band Lock : 4G' }), textAlto: 'TBD', enumType: '', incidents: {}, kpis: {} },
  { id: 72, value: 'initialState.ccmAp.common.lte_band_lock_channel.channel3g', text: defineMessage({ defaultMessage: 'LTE Band Lock : 3G' }), textAlto: 'TBD', enumType: '', incidents: {}, kpis: {} },
  { id: 73, value: 'initialState.ccmAp.common.channel_144_enable', text: defineMessage({ defaultMessage: 'Enable DFS channel : Channel 144' }), textAlto: 'TBD', enumType: '', incidents: {}, kpis: {} },
  { id: 74, value: 'initialState.ccmAp.common.monitoring_enabled', text: defineMessage({ defaultMessage: 'Monitoring AP' }), textAlto: 'TBD', enumType: '', incidents: {}, kpis: {} },
  { id: 75, value: 'initialState.ccmAp.common.rogue_scan_freq', text: 'TBD', textAlto: 'TBD', enumType: 'com.ruckuswireless.scg.protobuf.ccm.Zone.CcmCommon.RogueScanFrequency', incidents: {}, kpis: {} },
  { id: 76, value: 'initialState.ccmAp.common.multiple_tunnel.rks_gre_setting.profile_id', text: 'NA', textAlto: 'TBD', enumType: '', incidents: {}, kpis: {} },
  { id: 77, value: 'initialState.ccmAp.common.multiple_tunnel.rks_gre_setting.aaa_affinity_enabled', text: defineMessage({ defaultMessage: 'Ruckus GRE : AAA Affinity enabled' }), textAlto: 'TBD', enumType: '', incidents: {}, kpis: {} },
  { id: 78, value: 'initialState.ccmAp.common.multiple_tunnel.soft_gre_setting.profile_id', text: 'NA', textAlto: 'TBD', enumType: '', incidents: {}, kpis: {} },
  { id: 79, value: 'initialState.ccmAp.common.multiple_tunnel.soft_gre_setting.aaa_affinity_enabled', text: defineMessage({ defaultMessage: 'Soft GRE : AAA Affinity enabled' }), textAlto: 'TBD', enumType: '', incidents: {}, kpis: {} },
  { id: 80, value: 'initialState.ccmAp.common.multiple_tunnel.ipsec_setting.profile_id', text: 'NA', textAlto: 'TBD', enumType: '', incidents: {}, kpis: {} },
  { id: 81, value: 'initialState.ccmAp.common.multiple_tunnel.ipsec_setting.aaa_affinity_enabled', text: defineMessage({ defaultMessage: 'IPsec Tunnel : AAA affinity enabled' }), textAlto: 'TBD', enumType: '', incidents: {}, kpis: {} },
  { id: 82, value: 'initialState.ccmAp.common.multiple_tunnel.rks_gre_forward_broadcast', text: defineMessage({ defaultMessage: 'Ruckus GRE Forwarding Broadcast' }), textAlto: 'TBD', enumType: '', incidents: {}, kpis: {} },
  { id: 83, value: 'initialState.ccmAp.common.restricted_ap_access.enabled', text: defineMessage({ defaultMessage: 'Restricted AP Access Profile Enabled ' }), textAlto: 'TBD', enumType: '', incidents: {}, kpis: {} },
  { id: 84, value: 'initialState.ccmAp.common.restricted_ap_access.id', text: 'NA', textAlto: 'TBD', enumType: '', incidents: {}, kpis: {} },
  { id: 85, value: 'initialState.ccmAp.common.my_ruckus.acl_for_tunnel_wlan_and_vlan_enabled', text: defineMessage({ defaultMessage: 'My.Ruckus support for Tunnel-WLAN/VLAN' }), textAlto: 'TBD', enumType: '', incidents: { 'i-apserv-high-num-reboots': 1, 'i-apserv-continuous-reboots': 1 }, kpis: {} },
  { id: 86, value: 'initialState.ccmAp.common.zapd_enabled', text: 'TBD', textAlto: 'TBD', enumType: '', incidents: {}, kpis: {} },
  { id: 87, value: 'initialState.ccmAp.common.ap_http2_cert_chk_enable', text: 'TBD', textAlto: 'TBD', enumType: '', incidents: {}, kpis: {} },
  { id: 88, value: 'initialState.ccmAp.common.subscription_report.enable', text: 'TBD', textAlto: 'TBD', enumType: '', incidents: {}, kpis: {} },
  { id: 89, value: 'initialState.ccmAp.common.subscription_report.subscriber_id', text: 'NA', textAlto: 'TBD', enumType: '', incidents: {}, kpis: {} },
  { id: 90, value: 'initialState.ccmAp.common.subscription_report.stats_type', text: 'TBD', textAlto: 'TBD', enumType: '', incidents: {}, kpis: {} },
  { id: 91, value: 'initialState.ccmAp.common.subscription_report.report_interval', text: 'TBD', textAlto: 'TBD', enumType: '', incidents: {}, kpis: {} },
  { id: 92, value: 'initialState.ccmAp.common.subscription_report.dest_module', text: 'TBD', textAlto: 'TBD', enumType: '', incidents: {}, kpis: {} },
  { id: 93, value: 'initialState.ccmAp.common.bss_coloring.bss_coloring_enabled', text: defineMessage({ defaultMessage: 'BSS Coloring' }), textAlto: 'TBD', enumType: '', incidents: {}, kpis: {} },
  { id: 94, value: 'initialState.ccmAp.radio24g.radio.adj_threshold', text: 'TBD', textAlto: 'TBD', enumType: '', incidents: {}, kpis: {} },
  { id: 95, value: 'initialState.ccmAp.radio24g.radio.bg_scan', text: defineMessage({ defaultMessage: 'Background Scan (2.4 GHz)' }), textAlto: 'TBD', enumType: '', incidents: {}, kpis: {} },
  { id: 96, value: 'initialState.ccmAp.radio24g.radio.bg_scan_timer', text: defineMessage({ defaultMessage: 'Background Scan Timer ( 2.4 GHz )' }), textAlto: 'TBD', enumType: '', incidents: {}, kpis: {} },
  { id: 97, value: 'initialState.ccmAp.radio24g.radio.channel', text: 'TBD', textAlto: 'TBD', enumType: '', incidents: {}, kpis: {} },
  { id: 98, value: 'initialState.ccmAp.radio24g.radio.channel_range', text: 'TBD', textAlto: 'TBD', enumType: '', incidents: {}, kpis: {} },
  { id: 99, value: 'initialState.ccmAp.radio24g.radio.channel_select_mode', text: defineMessage({ defaultMessage: 'Auto Channel Selection: Mode (2.4 GHz)' }), textAlto: defineMessage({ defaultMessage: 'Auto Channel Selection: Mode (2.4 GHz)' }), enumType: 'com.ruckuswireless.scg.protobuf.ccm.Zone.CcmRadio.ChannelSelectMode', incidents: {}, kpis: {} },
  { id: 100, value: 'initialState.ccmAp.radio24g.radio.channel_width', text: 'TBD', textAlto: defineMessage({ defaultMessage: 'Channelization: bandwidth (2.4 GHz)' }), enumType: 'com.ruckuswireless.scg.protobuf.ccm.Zone.CcmRadio.ChannelWidth', incidents: {}, kpis: {} },
  { id: 101, value: 'initialState.ccmAp.radio24g.radio.channel_fly_mtbc', text: 'TBD', textAlto: defineMessage({ defaultMessage: 'Reselect channel Frequency  (2.4 GHz)' }), enumType: '', incidents: {}, kpis: {} },
  { id: 102, value: 'initialState.ccmAp.radio24g.radio.clb_enabled', text: 'TBD', textAlto: 'TBD', enumType: '', incidents: {}, kpis: {} },
  { id: 103, value: 'initialState.ccmAp.radio24g.radio.indoor_channel_block', text: 'TBD', textAlto: 'TBD', enumType: 'com.ruckuswireless.scg.protobuf.ccm.Zone.CcmRadio.AllowIndoorChannel', incidents: {}, kpis: {} },
  { id: 104, value: 'initialState.ccmAp.radio24g.radio.roam_enabled', text: 'TBD', textAlto: 'TBD', enumType: '', incidents: {}, kpis: {} },
  { id: 105, value: 'initialState.ccmAp.radio24g.radio.tax_power', text: defineMessage({ defaultMessage: 'TX Power Adjustment (2.4 GHz)' }), textAlto: defineMessage({ defaultMessage: 'TX Power Adjustment (2.4 GHz)' }), enumType: 'com.ruckuswireless.scg.protobuf.ccm.Zone.CcmRadio.TaxPower', incidents: {}, kpis: {} },
  { id: 106, value: 'initialState.ccmAp.radio24g.radio.client_admission.minimum_client_count', text: defineMessage({ defaultMessage: 'Client Admission Control : Min Client Count (2.4 GHz)' }), textAlto: 'TBD', enumType: '', incidents: {}, kpis: {} },
  { id: 107, value: 'initialState.ccmAp.radio24g.radio.client_admission.maxiumum_radio_load', text: defineMessage({ defaultMessage: 'Client Admission Control: Max Radio Load (2.4 GHz)' }), textAlto: 'TBD', enumType: '', incidents: {}, kpis: {} },
  { id: 108, value: 'initialState.ccmAp.radio24g.radio.client_admission.minimum_client_throughput', text: defineMessage({ defaultMessage: 'Client Admission Control: Min Client Throughput (2.4 GHz)' }), textAlto: 'TBD', enumType: '', incidents: {}, kpis: {} },
  { id: 109, value: 'initialState.ccmAp.radio24g.radio.client_admission.enabled', text: defineMessage({ defaultMessage: 'Client Admission Control : Enabled (2.4 GHz)' }), textAlto: 'TBD', enumType: '', incidents: {}, kpis: {} },
  { id: 110, value: 'initialState.ccmAp.radio24g.radio.protection_mode', text: defineMessage({ defaultMessage: 'Protection Mode (2.4 GHz)' }), textAlto: 'TBD', enumType: 'com.ruckuswireless.scg.protobuf.ccm.Zone.CcmRadio.ProtectionMode', incidents: {}, kpis: {} },
  { id: 111, value: 'initialState.ccmAp.radio24g.radio.wlan_service_enabled', text: defineMessage({ defaultMessage: 'Wlan Service (2.4 GHz)' }), textAlto: defineMessage({ defaultMessage: 'Wlan Service (2.4 GHz)' }), enumType: '', incidents: {}, kpis: {} },
  { id: 112, value: 'initialState.ccmAp.radio24g.radio.bg_scanner.enabled', text: defineMessage({ defaultMessage: 'Background scan : Enabled (2.4 GHz)' }), textAlto: 'TBD', enumType: '', incidents: {}, kpis: {} },
  { id: 113, value: 'initialState.ccmAp.radio24g.radio.bg_scanner.timer', text: defineMessage({ defaultMessage: 'Background Scan Timer ( 2.4 GHz )' }), textAlto: 'TBD', enumType: '', incidents: {}, kpis: {} },
  { id: 114, value: 'initialState.ccmAp.radio24g.radio.auto_cell_sizing', text: defineMessage({ defaultMessage: 'Auto Cell Sizing (2.4 GHz)' }), textAlto: 'TBD', enumType: '', incidents: {}, kpis: {} },
  { id: 115, value: 'initialState.ccmAp.radio24g.radio.weak_bypass', text: 'TBD', textAlto: 'TBD', enumType: '', incidents: {}, kpis: {} },
  { id: 116, value: 'initialState.ccmAp.radio24g.radio.head_room', text: 'TBD', textAlto: 'TBD', enumType: '', incidents: {}, kpis: {} },
  { id: 117, value: 'initialState.ccmAp.radio24g.radio.roam_macfilt_time', text: 'TBD', textAlto: 'TBD', enumType: '', incidents: {}, kpis: {} },
  { id: 118, value: 'initialState.ccmAp.radio24g.radio.channel_fly_config.channel_change_frequency', text: defineMessage({ defaultMessage: 'Channel Change Frequency (2.4 GHz)' }), textAlto: 'TBD', enumType: '', incidents: {}, kpis: {} },
  { id: 119, value: 'initialState.ccmAp.radio24g.radio.channel_fly_config.optimization_time_period', text: defineMessage({ defaultMessage: 'Channelfly: Full Optimization Period (2.4 GHz)' }), textAlto: 'TBD', enumType: '', incidents: {}, kpis: {} },
  { id: 120, value: 'initialState.ccmAp.radio5g.radio.adj_threshold', text: 'TBD', textAlto: 'TBD', enumType: '', incidents: {}, kpis: {} },
  { id: 121, value: 'initialState.ccmAp.radio5g.radio.bg_scan', text: defineMessage({ defaultMessage: 'Background Scan (5 GHz)' }), textAlto: 'TBD', enumType: '', incidents: {}, kpis: {} },
  { id: 122, value: 'initialState.ccmAp.radio5g.radio.bg_scan_timer', text: defineMessage({ defaultMessage: 'Background Scan  Timer (5 GHz)' }), textAlto: 'TBD', enumType: '', incidents: {}, kpis: {} },
  { id: 123, value: 'initialState.ccmAp.radio5g.radio.channel', text: 'TBD', textAlto: 'TBD', enumType: '', incidents: {}, kpis: {} },
  { id: 124, value: 'initialState.ccmAp.radio5g.radio.channel_range', text: 'TBD', textAlto: 'TBD', enumType: '', incidents: {}, kpis: {} },
  { id: 125, value: 'initialState.ccmAp.radio5g.radio.channel_select_mode', text: defineMessage({ defaultMessage: 'Auto Channel Selection: Mode (5 GHz)' }), textAlto: defineMessage({ defaultMessage: 'Auto Channel Selection: Mode (5 GHz)' }), enumType: 'com.ruckuswireless.scg.protobuf.ccm.Zone.CcmRadio.ChannelSelectMode', incidents: {}, kpis: {} },
  { id: 126, value: 'initialState.ccmAp.radio5g.radio.channel_width', text: 'TBD', textAlto: defineMessage({ defaultMessage: 'Channelization: Bandwidth (5 GHz)' }), enumType: 'com.ruckuswireless.scg.protobuf.ccm.Zone.CcmRadio.ChannelWidth', incidents: {}, kpis: {} },
  { id: 127, value: 'initialState.ccmAp.radio5g.radio.channel_fly_mtbc', text: 'TBD', textAlto: defineMessage({ defaultMessage: 'Reselect channel Frequency  (5 GHz)' }), enumType: '', incidents: {}, kpis: {} },
  { id: 128, value: 'initialState.ccmAp.radio5g.radio.clb_enabled', text: 'TBD', textAlto: 'TBD', enumType: '', incidents: {}, kpis: {} },
  { id: 129, value: 'initialState.ccmAp.radio5g.radio.indoor_channel_block', text: 'TBD', textAlto: 'TBD', enumType: 'com.ruckuswireless.scg.protobuf.ccm.Zone.CcmRadio.AllowIndoorChannel', incidents: {}, kpis: {} },
  { id: 130, value: 'initialState.ccmAp.radio5g.radio.roam_enabled', text: 'TBD', textAlto: 'TBD', enumType: '', incidents: {}, kpis: {} },
  { id: 131, value: 'initialState.ccmAp.radio5g.radio.tax_power', text: defineMessage({ defaultMessage: 'TX Power Adjustment (5 GHz)' }), textAlto: defineMessage({ defaultMessage: 'TX Power Adjustment (5 GHz)' }), enumType: 'com.ruckuswireless.scg.protobuf.ccm.Zone.CcmRadio.TaxPower', incidents: {}, kpis: {} },
  { id: 132, value: 'initialState.ccmAp.radio5g.radio.client_admission.minimum_client_count', text: defineMessage({ defaultMessage: 'Client Admission Control: Min Client Count (5 GHz)' }), textAlto: 'TBD', enumType: '', incidents: {}, kpis: {} },
  { id: 133, value: 'initialState.ccmAp.radio5g.radio.client_admission.maxiumum_radio_load', text: defineMessage({ defaultMessage: 'Client Admission Control: Max Radio Load (5 GHz)' }), textAlto: 'TBD', enumType: '', incidents: {}, kpis: {} },
  { id: 134, value: 'initialState.ccmAp.radio5g.radio.client_admission.minimum_client_throughput', text: defineMessage({ defaultMessage: 'Client Admission Control: Min Client Throughput (5 GHz)' }), textAlto: 'TBD', enumType: '', incidents: {}, kpis: {} },
  { id: 135, value: 'initialState.ccmAp.radio5g.radio.client_admission.enabled', text: defineMessage({ defaultMessage: 'Client Admission control : Enabled (5 GHz)' }), textAlto: 'TBD', enumType: '', incidents: {}, kpis: {} },
  { id: 136, value: 'initialState.ccmAp.radio5g.radio.protection_mode', text: defineMessage({ defaultMessage: 'Protection Mode (5 GHz)' }), textAlto: 'TBD', enumType: 'com.ruckuswireless.scg.protobuf.ccm.Zone.CcmRadio.ProtectionMode', incidents: {}, kpis: {} },
  { id: 137, value: 'initialState.ccmAp.radio5g.radio.wlan_service_enabled', text: defineMessage({ defaultMessage: 'Wlan Service (5 GHz)' }), textAlto: defineMessage({ defaultMessage: 'Wlan Service (5 GHz)' }), enumType: '', incidents: {}, kpis: {} },
  { id: 138, value: 'initialState.ccmAp.radio5g.radio.bg_scanner.enabled', text: defineMessage({ defaultMessage: 'Background scan : Enabled (5 GHz)' }), textAlto: 'TBD', enumType: '', incidents: {}, kpis: {} },
  { id: 139, value: 'initialState.ccmAp.radio5g.radio.bg_scanner.timer', text: defineMessage({ defaultMessage: 'Background scan timer (5 GHz)' }), textAlto: 'TBD', enumType: '', incidents: {}, kpis: {} },
  { id: 140, value: 'initialState.ccmAp.radio5g.radio.auto_cell_sizing', text: defineMessage({ defaultMessage: 'Auto Cell Sizing (5 GHz)' }), textAlto: 'TBD', enumType: '', incidents: {}, kpis: {} },
  { id: 141, value: 'initialState.ccmAp.radio5g.radio.weak_bypass', text: 'TBD', textAlto: 'TBD', enumType: '', incidents: {}, kpis: {} },
  { id: 142, value: 'initialState.ccmAp.radio5g.radio.head_room', text: 'TBD', textAlto: 'TBD', enumType: '', incidents: {}, kpis: {} },
  { id: 143, value: 'initialState.ccmAp.radio5g.radio.roam_macfilt_time', text: 'TBD', textAlto: 'TBD', enumType: '', incidents: {}, kpis: {} },
  { id: 144, value: 'initialState.ccmAp.radio5g.radio.channel_fly_config.channel_change_frequency', text: defineMessage({ defaultMessage: 'Channel Change Frequency (5 GHz)' }), textAlto: 'TBD', enumType: '', incidents: {}, kpis: {} },
  { id: 145, value: 'initialState.ccmAp.radio5g.radio.channel_fly_config.optimization_time_period', text: defineMessage({ defaultMessage: 'Channelfly: Full Optimization Period (5 GHz)' }), textAlto: 'TBD', enumType: '', incidents: {}, kpis: {} },
  { id: 146, value: 'initialState.ccmAp.radio5g.secondary_channel', text: 'TBD', textAlto: 'TBD', enumType: '', incidents: {}, kpis: {} },
  { id: 147, value: 'initialState.ccmAp.radio5g.indoor_secondary_channel', text: 'TBD', textAlto: 'TBD', enumType: '', incidents: {}, kpis: {} },
  { id: 148, value: 'initialState.ccmAp.radio5g.indoor_channel_range', text: defineMessage({ defaultMessage: 'Channel Range (5 GHz) Indoor' }), textAlto: 'TBD', enumType: '', incidents: {}, kpis: {} },
  { id: 149, value: 'initialState.ccmAp.radio5g.indoor_channel', text: defineMessage({ defaultMessage: 'Channel (5 GHz) Indoor' }), textAlto: 'TBD', enumType: '', incidents: {}, kpis: {} },
  { id: 150, value: 'initialState.ccmAp.model.name', text: defineMessage({ defaultMessage: 'AP Model' }), textAlto: 'TBD', enumType: '', incidents: {}, kpis: {} },
  { id: 151, value: 'initialState.ccmAp.model.model_specific_ethernet_port_settings.port_number', text: defineMessage({ defaultMessage: 'Ethernet Port settings : Port number' }), textAlto: 'TBD', enumType: '', incidents: {}, kpis: {} },
  { id: 152, value: 'initialState.ccmAp.model.model_specific_ethernet_port_settings.ethernet_port_profile_id', text: 'NA', textAlto: 'TBD', enumType: '', incidents: {}, kpis: {} },
  { id: 153, value: 'initialState.ccmAp.model.model_specific_ethernet_port_settings.untag_id', text: defineMessage({ defaultMessage: 'Ethernet Port settings : Untag VLAN' }), textAlto: 'TBD', enumType: '', incidents: {}, kpis: {} },
  { id: 154, value: 'initialState.ccmAp.model.model_specific_ethernet_port_settings.vlan_members', text: defineMessage({ defaultMessage: 'Ethernet Port settings : VLAN Members' }), textAlto: 'TBD', enumType: '', incidents: { 'i-apserv-high-num-reboots': 1, 'i-apserv-continuous-reboots': 1 }, kpis: {} },
  { id: 155, value: 'initialState.ccmAp.model.model_specific_ethernet_port_settings.state', text: defineMessage({ defaultMessage: 'Ethernet Port Settings: State' }), textAlto: defineMessage({ defaultMessage: 'Ethernet Port Settings: State' }), enumType: '', incidents: {}, kpis: {} },
  { id: 156, value: 'initialState.ccmAp.model.model_specific_ethernet_port_settings.override_vlan_enabled', text: defineMessage({ defaultMessage: 'Ethernet Port settings: Overwrite VLAN' }), textAlto: 'TBD', enumType: '', incidents: { 'i-apserv-high-num-reboots': 1, 'i-apserv-continuous-reboots': 1 }, kpis: {} },
  { id: 157, value: 'initialState.ccmAp.model.model_specific_radio_settings.radio_type', text: 'TBD', textAlto: 'TBD', enumType: 'com.ruckuswireless.scg.protobuf.ccm.Zone.CcmModel.CcmModelSpecificRadioSettings.RadioType', incidents: {}, kpis: {} },
  { id: 158, value: 'initialState.ccmAp.model.model_specific_radio_settings.ext_ant', text: 'TBD', textAlto: 'TBD', enumType: '', incidents: {}, kpis: {} },
  { id: 159, value: 'initialState.ccmAp.model.model_specific_radio_settings.ext_ant_chain_mask', text: 'TBD', textAlto: 'TBD', enumType: '', incidents: {}, kpis: {} },
  { id: 160, value: 'initialState.ccmAp.model.model_specific_radio_settings.ext_ant_gain', text: 'TBD', textAlto: 'TBD', enumType: '', incidents: {}, kpis: {} },
  { id: 161, value: 'initialState.ccmAp.model.model_specific_radio_settings.ani_ofdm_level', text: 'TBD', textAlto: 'TBD', enumType: '', incidents: {}, kpis: {} },
  { id: 162, value: 'initialState.ccmAp.model.model_specific_lldp_settings.lldp_enabled', text: defineMessage({ defaultMessage: 'LLDP Enabled' }), textAlto: 'TBD', enumType: '', incidents: {}, kpis: {} },
  { id: 163, value: 'initialState.ccmAp.model.model_specific_lldp_settings.lldp_mgmt_enabled', text: defineMessage({ defaultMessage: 'LLDP Management IP TLV Enabled' }), textAlto: 'TBD', enumType: '', incidents: {}, kpis: {} },
  { id: 164, value: 'initialState.ccmAp.model.model_specific_lldp_settings.lldp_ad_interval', text: defineMessage({ defaultMessage: 'LLDP Advertise Interval' }), textAlto: 'TBD', enumType: '', incidents: {}, kpis: {} },
  { id: 165, value: 'initialState.ccmAp.model.model_specific_lldp_settings.lldp_hold_time', text: defineMessage({ defaultMessage: 'LLDP Hold Time' }), textAlto: 'TBD', enumType: '', incidents: {}, kpis: {} },
  { id: 166, value: 'initialState.ccmAp.model.cm_led_mode', text: 'TBD', textAlto: 'TBD', enumType: '', incidents: {}, kpis: {} },
  { id: 167, value: 'initialState.ccmAp.model.led_status', text: defineMessage({ defaultMessage: 'Status LEDs' }), textAlto: 'TBD', enumType: '', incidents: {}, kpis: {} },
  { id: 168, value: 'initialState.ccmAp.model.poe_mode_setting', text: defineMessage({ defaultMessage: 'PoE Operating Mode' }), textAlto: 'TBD', enumType: '', incidents: {}, kpis: {} },
  { id: 169, value: 'initialState.ccmAp.model.poe_out_port', text: defineMessage({ defaultMessage: 'PoE out port' }), textAlto: 'TBD', enumType: '', incidents: {}, kpis: {} },
  { id: 170, value: 'initialState.ccmAp.model.poe_tx_chain', text: 'TBD', textAlto: 'TBD', enumType: '', incidents: {}, kpis: {} },
  { id: 171, value: 'initialState.ccmAp.model.usb_power_enabled', text: defineMessage({ defaultMessage: 'USB Port' }), textAlto: 'TBD', enumType: '', incidents: {}, kpis: {} },
  { id: 172, value: 'initialState.ccmAp.model.model_specific_poe_mode_settings.poe_mode_setting', text: defineMessage({ defaultMessage: 'PoE Operating Mode' }), textAlto: 'TBD', enumType: 'com.ruckuswireless.scg.protobuf.ccm.Zone.CcmModel.CcmModelSpecificPoeModeSettings.PoeOperatingMode', incidents: {}, kpis: {} },
  { id: 173, value: 'initialState.ccmAp.model.model_specific_poe_mode_settings.poe_tx_chain', text: 'TBD', textAlto: 'TBD', enumType: '', incidents: {}, kpis: {} },
  { id: 174, value: 'initialState.ccmAp.model.led_mode', text: 'TBD', textAlto: 'TBD', enumType: 'com.ruckuswireless.scg.protobuf.ccm.Zone.CcmModel.LedMode', incidents: {}, kpis: {} },
  { id: 175, value: 'initialState.ccmAp.model.led_status_enabled', text: defineMessage({ defaultMessage: 'Status LEDs' }), textAlto: 'TBD', enumType: '', incidents: {}, kpis: {} },
  { id: 176, value: 'initialState.ccmAp.model.poe_out_port_enabled', text: defineMessage({ defaultMessage: 'PoE out port' }), textAlto: 'TBD', enumType: '', incidents: {}, kpis: {} },
  { id: 177, value: 'initialState.ccmAp.model.model_specific_cellular_settings.mobile_ap_name', text: defineMessage({ defaultMessage: 'Cellular Radio Settings : APN for Primary SIM' }), textAlto: 'TBD', enumType: '', incidents: {}, kpis: {} },
  { id: 178, value: 'initialState.ccmAp.model.model_specific_cellular_settings.mobile_ap_name2', text: defineMessage({ defaultMessage: 'Cellular Radio Settings : APN for Secondary SIM' }), textAlto: 'TBD', enumType: '', incidents: {}, kpis: {} },
  { id: 179, value: 'initialState.ccmAp.model.model_specific_cellular_settings.sim_card_usage', text: defineMessage({ defaultMessage: 'Cellular Radio Settings : Simcard Usage' }), textAlto: 'TBD', enumType: 'com.ruckuswireless.scg.protobuf.ccm.Zone.CcmModel.CcmModelSpecificCellularSettings.SIMCardUsage', incidents: {}, kpis: {} },
  { id: 180, value: 'initialState.ccmAp.model.model_specific_cellular_settings.select_3g_4g', text: defineMessage({ defaultMessage: 'Cellular Radio Settings : 3g/4g selection primary' }), textAlto: 'TBD', enumType: 'com.ruckuswireless.scg.protobuf.ccm.Zone.CcmModel.CcmModelSpecificCellularSettings.Select3G4G', incidents: {}, kpis: {} },
  { id: 181, value: 'initialState.ccmAp.model.model_specific_cellular_settings.data_roaming', text: defineMessage({ defaultMessage: 'Cellular Radio Settings : Data Roaming Primary SIM' }), textAlto: 'TBD', enumType: 'com.ruckuswireless.scg.protobuf.ccm.Zone.CcmModel.CcmModelSpecificCellularSettings.DataRoaming', incidents: {}, kpis: {} },
  { id: 182, value: 'initialState.ccmAp.model.model_specific_cellular_settings.wan_connection', text: defineMessage({ defaultMessage: 'Cellular Radio Settings : WAN connection' }), textAlto: 'TBD', enumType: 'com.ruckuswireless.scg.protobuf.ccm.Zone.CcmModel.CcmModelSpecificCellularSettings.WANConnection', incidents: {}, kpis: {} },
  { id: 183, value: 'initialState.ccmAp.model.model_specific_cellular_settings.wan_recovery_timer', text: defineMessage({ defaultMessage: 'Cellular Radio Settings : Primary WAN Recovery Timer' }), textAlto: 'TBD', enumType: '', incidents: {}, kpis: {} },
  { id: 184, value: 'initialState.ccmAp.model.model_specific_cellular_settings.select_3g_4g2', text: defineMessage({ defaultMessage: 'Cellular Radio Settings : 3g/4g selection Secondary' }), textAlto: 'TBD', enumType: 'com.ruckuswireless.scg.protobuf.ccm.Zone.CcmModel.CcmModelSpecificCellularSettings.Select3G4G', incidents: {}, kpis: {} },
  { id: 185, value: 'initialState.ccmAp.model.model_specific_cellular_settings.data_roaming2', text: defineMessage({ defaultMessage: 'Cellular Radio Settings : Data Roaming Secondary SIM' }), textAlto: 'TBD', enumType: 'com.ruckuswireless.scg.protobuf.ccm.Zone.CcmModel.CcmModelSpecificCellularSettings.DataRoaming', incidents: {}, kpis: {} },
  { id: 186, value: 'initialState.ccmAp.model.model_specific_cellular_settings.geofence_profile_id', text: 'NA', textAlto: 'TBD', enumType: '', incidents: {}, kpis: {} },
  { id: 187, value: 'initialState.ccmAp.model.model_specific_lacp_settings.lacp_enabled', text: 'TBD', textAlto: 'TBD', enumType: '', incidents: {}, kpis: {} },
  { id: 188, value: 'initialState.ccmAp.model.model_specific_lacp_settings.lacp_keep_ap_setting', text: defineMessage({ defaultMessage: 'LACP/LAG: Keep Ap Settings' }), textAlto: 'TBD', enumType: '', incidents: {}, kpis: {} },
  { id: 189, value: 'initialState.ccmAp.model.model_specific_lacp_settings.bond_port_profile_id', text: 'NA', textAlto: 'TBD', enumType: '', incidents: {}, kpis: {} },
  { id: 190, value: 'initialState.ccmAp.syslog.enabled', text: defineMessage({ defaultMessage: 'External Syslog server' }), textAlto: 'TBD', enumType: '', incidents: {}, kpis: {} },
  { id: 191, value: 'initialState.ccmAp.syslog.primary_server_ip', text: defineMessage({ defaultMessage: 'Syslog: Primary Server address' }), textAlto: 'TBD', enumType: '', incidents: {}, kpis: {} },
  { id: 192, value: 'initialState.ccmAp.syslog.primary_port', text: defineMessage({ defaultMessage: 'Syslog: Primary Server Port' }), textAlto: 'TBD', enumType: '', incidents: {}, kpis: {} },
  { id: 193, value: 'initialState.ccmAp.syslog.primary_protocol', text: defineMessage({ defaultMessage: 'Syslog: Primary Server Protocol' }), textAlto: 'TBD', enumType: 'com.ruckuswireless.scg.protobuf.ccm.Zone.CcmSyslog.Protocol', incidents: {}, kpis: {} },
  { id: 194, value: 'initialState.ccmAp.syslog.redundancy_mode', text: defineMessage({ defaultMessage: 'Syslog: Redundancy Mode' }), textAlto: 'TBD', enumType: 'com.ruckuswireless.scg.protobuf.ccm.Zone.CcmSyslog.Redundancy', incidents: {}, kpis: {} },
  { id: 195, value: 'initialState.ccmAp.syslog.secondary_server_ip', text: defineMessage({ defaultMessage: 'Syslog: Secondary Server address' }), textAlto: 'TBD', enumType: '', incidents: {}, kpis: {} },
  { id: 196, value: 'initialState.ccmAp.syslog.secondary_port', text: defineMessage({ defaultMessage: 'Syslog: Secondary Server Port' }), textAlto: 'TBD', enumType: '', incidents: {}, kpis: {} },
  { id: 197, value: 'initialState.ccmAp.syslog.secondary_protocol', text: defineMessage({ defaultMessage: 'Syslog: Secondary Server Protocol' }), textAlto: 'TBD', enumType: 'com.ruckuswireless.scg.protobuf.ccm.Zone.CcmSyslog.Protocol', incidents: {}, kpis: {} },
  { id: 198, value: 'initialState.ccmAp.syslog.flow_level', text: defineMessage({ defaultMessage: 'Syslog: Send Logs' }), textAlto: 'TBD', enumType: 'com.ruckuswireless.scg.protobuf.ccm.Zone.CcmSyslog.FlowLevel', incidents: {}, kpis: {} },
  { id: 199, value: 'initialState.ccmAp.syslog.event_facility', text: defineMessage({ defaultMessage: 'Syslog: Event Facility' }), textAlto: 'TBD', enumType: 'com.ruckuswireless.scg.protobuf.ccm.Zone.CcmSyslog.EventFacility', incidents: {}, kpis: {} },
  { id: 200, value: 'initialState.ccmAp.syslog.priority', text: defineMessage({ defaultMessage: 'Syslog: Priority' }), textAlto: 'TBD', enumType: 'com.ruckuswireless.scg.protobuf.ccm.Zone.CcmSyslog.Priority', incidents: {}, kpis: {} },
  { id: 201, value: 'initialState.ccmAp.snmp.enabled', text: defineMessage({ defaultMessage: 'AP SNMP' }), textAlto: 'TBD', enumType: '', incidents: {}, kpis: {} },
  { id: 202, value: 'initialState.ccmAp.snmp.snmp_v2_agent.name', text: defineMessage({ defaultMessage: 'SNMPv2 Agent' }), textAlto: 'TBD', enumType: '', incidents: {}, kpis: {} },
  { id: 203, value: 'initialState.ccmAp.snmp.snmp_v2_agent.is_allowed_to_read', text: defineMessage({ defaultMessage: 'SNMPv2 Privilege : Read-only ' }), textAlto: 'TBD', enumType: '', incidents: {}, kpis: {} },
  { id: 204, value: 'initialState.ccmAp.snmp.snmp_v2_agent.is_allowed_to_write', text: defineMessage({ defaultMessage: 'SNMPv2 Privilege : Read-Write' }), textAlto: 'TBD', enumType: '', incidents: {}, kpis: {} },
  { id: 205, value: 'initialState.ccmAp.snmp.snmp_v2_agent.is_allowed_to_notify', text: defineMessage({ defaultMessage: 'SNMPv2 Privilege : Notification' }), textAlto: 'TBD', enumType: '', incidents: {}, kpis: {} },
  { id: 206, value: 'initialState.ccmAp.snmp.snmp_v2_agent.notification_target.notification_type', text: defineMessage({ defaultMessage: 'SNMPv2 Privilege : Notification Type' }), textAlto: 'TBD', enumType: 'com.ruckuswireless.scg.protobuf.ccm.Zone.CcmSnmp.CcmNotificationTarget.Type', incidents: {}, kpis: {} },
  { id: 207, value: 'initialState.ccmAp.snmp.snmp_v2_agent.notification_target.ip', text: defineMessage({ defaultMessage: 'SNMPv2 Privilege : Notification : IP address' }), textAlto: 'TBD', enumType: '', incidents: {}, kpis: {} },
  { id: 208, value: 'initialState.ccmAp.snmp.snmp_v2_agent.notification_target.port', text: defineMessage({ defaultMessage: 'SNMPv2 Privilege : Notification : Port' }), textAlto: 'TBD', enumType: '', incidents: {}, kpis: {} },
  { id: 209, value: 'initialState.ccmAp.snmp.snmp_v3_agent.name', text: defineMessage({ defaultMessage: 'SNMPv3 Agent' }), textAlto: 'TBD', enumType: '', incidents: {}, kpis: {} },
  { id: 210, value: 'initialState.ccmAp.snmp.snmp_v3_agent.is_allowed_to_read', text: defineMessage({ defaultMessage: 'SNMPv3 Privilege : Read-only ' }), textAlto: 'TBD', enumType: '', incidents: {}, kpis: {} },
  { id: 211, value: 'initialState.ccmAp.snmp.snmp_v3_agent.is_allowed_to_write', text: defineMessage({ defaultMessage: 'SNMPv3 Privilege : Read-Write' }), textAlto: 'TBD', enumType: '', incidents: {}, kpis: {} },
  { id: 212, value: 'initialState.ccmAp.snmp.snmp_v3_agent.is_allowed_to_notify', text: defineMessage({ defaultMessage: 'SNMPv3 Privilege : Notification' }), textAlto: 'TBD', enumType: '', incidents: {}, kpis: {} },
  { id: 213, value: 'initialState.ccmAp.snmp.snmp_v3_agent.authentication_type', text: defineMessage({ defaultMessage: 'SNMPv3: Authentication ' }), textAlto: 'TBD', enumType: 'com.ruckuswireless.scg.protobuf.ccm.Zone.CcmSnmp.CcmUser.AuthenticationType', incidents: {}, kpis: {} },
  { id: 214, value: 'initialState.ccmAp.snmp.snmp_v3_agent.authentication_passphrase', text: defineMessage({ defaultMessage: 'SNMPv3 : Authentication pass phrase' }), textAlto: 'TBD', enumType: '', incidents: {}, kpis: {} },
  { id: 215, value: 'initialState.ccmAp.snmp.snmp_v3_agent.privacy_type', text: defineMessage({ defaultMessage: 'SNMPv3 : Privacy types' }), textAlto: 'TBD', enumType: 'com.ruckuswireless.scg.protobuf.ccm.Zone.CcmSnmp.CcmUser.PrivacyType', incidents: {}, kpis: {} },
  { id: 216, value: 'initialState.ccmAp.snmp.snmp_v3_agent.privacy_passphrase', text: defineMessage({ defaultMessage: 'SNMPv3 : Privacy passphrase for DES & AES' }), textAlto: 'TBD', enumType: '', incidents: {}, kpis: {} },
  { id: 217, value: 'initialState.ccmAp.snmp.snmp_v3_agent.notification_target.notification_type', text: defineMessage({ defaultMessage: 'SNMPv3 Privilege : Notification' }), textAlto: 'TBD', enumType: 'com.ruckuswireless.scg.protobuf.ccm.Zone.CcmSnmp.CcmNotificationTarget.Type', incidents: {}, kpis: {} },
  { id: 218, value: 'initialState.ccmAp.snmp.snmp_v3_agent.notification_target.ip', text: defineMessage({ defaultMessage: 'SNMPv3 Privilege : Notification : Target IP' }), textAlto: 'TBD', enumType: '', incidents: {}, kpis: {} },
  { id: 219, value: 'initialState.ccmAp.snmp.snmp_v3_agent.notification_target.port', text: defineMessage({ defaultMessage: 'SNMPv3 Privilege : Notification : Target Port' }), textAlto: 'TBD', enumType: '', incidents: {}, kpis: {} },
  { id: 220, value: 'initialState.ccmAp.mesh.mesh_mode', text: defineMessage({ defaultMessage: 'Mesh Networking' }), textAlto: 'TBD', enumType: 'com.ruckuswireless.scg.protobuf.ccm.Zone.CcmMesh.CcmMeshApSettings.MeshMode', incidents: { 'i-apserv-high-num-reboots': 1, 'i-apserv-continuous-reboots': 1 }, kpis: {} },
  { id: 221, value: 'initialState.ccmAp.mesh.uplink_mode', text: 'TBD', textAlto: 'TBD', enumType: 'com.ruckuswireless.scg.protobuf.ccm.Zone.CcmMesh.CcmMeshApSettings.UplinkMode', incidents: { 'i-apserv-high-num-reboots': 1, 'i-apserv-continuous-reboots': 1 }, kpis: {} },
  { id: 222, value: 'initialState.ccmAp.mesh.uplink_entry_list', text: 'TBD', textAlto: 'TBD', enumType: '', incidents: { 'i-apserv-high-num-reboots': 1, 'i-apserv-continuous-reboots': 1 }, kpis: {} },
  { id: 223, value: 'initialState.ccmAp.mesh.mesh_downlink_enabled', text: 'TBD', textAlto: 'TBD', enumType: '', incidents: { 'i-apserv-high-num-reboots': 1, 'i-apserv-continuous-reboots': 1 }, kpis: {} },
  { id: 224, value: 'initialState.ccmAp.ipv4_settings.method', text: defineMessage({ defaultMessage: 'IPv4 Address Method' }), textAlto: 'TBD', enumType: 'com.ruckuswireless.scg.protobuf.ccm.Ap.CcmApNetworkSettings.ConfigureMethod', incidents: { 'i-apserv-high-num-reboots': 1, 'i-apserv-continuous-reboots': 1 }, kpis: {} },
  { id: 225, value: 'initialState.ccmAp.ipv4_settings.ip_address', text: defineMessage({ defaultMessage: 'IPv4 Address' }), textAlto: 'TBD', enumType: '', incidents: { 'i-apserv-high-num-reboots': 1, 'i-apserv-continuous-reboots': 1 }, kpis: {} },
  { id: 226, value: 'initialState.ccmAp.ipv4_settings.gateway', text: defineMessage({ defaultMessage: 'IPv4 Gateway' }), textAlto: 'TBD', enumType: '', incidents: { 'i-apserv-high-num-reboots': 1, 'i-apserv-continuous-reboots': 1 }, kpis: {} },
  { id: 227, value: 'initialState.ccmAp.ipv4_settings.network_mask', text: defineMessage({ defaultMessage: 'IPv4 Subnet Mask' }), textAlto: 'TBD', enumType: '', incidents: { 'i-apserv-high-num-reboots': 1, 'i-apserv-continuous-reboots': 1 }, kpis: {} },
  { id: 228, value: 'initialState.ccmAp.ipv4_settings.primary_dns', text: defineMessage({ defaultMessage: 'IPv4 Primary DNS' }), textAlto: 'TBD', enumType: '', incidents: { 'i-apserv-high-num-reboots': 1, 'i-apserv-continuous-reboots': 1 }, kpis: {} },
  { id: 229, value: 'initialState.ccmAp.ipv4_settings.secondary_dns', text: defineMessage({ defaultMessage: 'IPv4 Secondary DNS' }), textAlto: 'TBD', enumType: '', incidents: { 'i-apserv-high-num-reboots': 1, 'i-apserv-continuous-reboots': 1 }, kpis: {} },
  { id: 230, value: 'initialState.ccmAp.ipv6_settings.method', text: defineMessage({ defaultMessage: 'IPv6 Address Method' }), textAlto: 'TBD', enumType: 'com.ruckuswireless.scg.protobuf.ccm.Ap.CcmApNetworkSettings.ConfigureMethod', incidents: { 'i-apserv-high-num-reboots': 1, 'i-apserv-continuous-reboots': 1 }, kpis: {} },
  { id: 231, value: 'initialState.ccmAp.ipv6_settings.ip_address', text: defineMessage({ defaultMessage: 'IPv6 Address' }), textAlto: 'TBD', enumType: '', incidents: { 'i-apserv-high-num-reboots': 1, 'i-apserv-continuous-reboots': 1 }, kpis: {} },
  { id: 232, value: 'initialState.ccmAp.ipv6_settings.gateway', text: defineMessage({ defaultMessage: 'IPv6 Gateway' }), textAlto: 'TBD', enumType: '', incidents: { 'i-apserv-high-num-reboots': 1, 'i-apserv-continuous-reboots': 1 }, kpis: {} },
  { id: 233, value: 'initialState.ccmAp.ipv6_settings.network_mask', text: defineMessage({ defaultMessage: 'IPv6 Subnet Mask' }), textAlto: 'TBD', enumType: '', incidents: { 'i-apserv-high-num-reboots': 1, 'i-apserv-continuous-reboots': 1 }, kpis: {} },
  { id: 234, value: 'initialState.ccmAp.ipv6_settings.primary_dns', text: defineMessage({ defaultMessage: 'IPv6 Primary DNS' }), textAlto: 'TBD', enumType: '', incidents: { 'i-apserv-high-num-reboots': 1, 'i-apserv-continuous-reboots': 1 }, kpis: {} },
  { id: 235, value: 'initialState.ccmAp.ipv6_settings.secondary_dns', text: defineMessage({ defaultMessage: 'IPv6 Secondary DNS' }), textAlto: 'TBD', enumType: '', incidents: { 'i-apserv-high-num-reboots': 1, 'i-apserv-continuous-reboots': 1 }, kpis: {} },
  { id: 236, value: 'initialState.ccmAp.ap_certificate.certificate_state', text: 'TBD', textAlto: 'TBD', enumType: 'com.ruckuswireless.scg.protobuf.ccm.Ap.CcmApCertificate.CertificateState', incidents: {}, kpis: {} },
  { id: 237, value: 'initialState.ccmAp.ap_certificate.reload_url', text: 'TBD', textAlto: 'TBD', enumType: '', incidents: {}, kpis: {} },
  { id: 238, value: 'initialState.ccmAp.bonjour_gateway.enabled', text: defineMessage({ defaultMessage: 'Bonjour gateway' }), textAlto: defineMessage({ defaultMessage: 'Bonjour gateway' }), enumType: '', incidents: {}, kpis: {} },
  { id: 239, value: 'initialState.ccmAp.bonjour_gateway.policy_id', text: 'NA', textAlto: 'TBD', enumType: '', incidents: {}, kpis: {} },
  { id: 240, value: 'initialState.ccmAp.status.external_ip', text: 'TBD', textAlto: 'TBD', enumType: '', incidents: {}, kpis: {} },
  { id: 241, value: 'initialState.ccmAp.device_ap.id', text: 'NA', textAlto: 'TBD', enumType: '', incidents: {}, kpis: {} },
  { id: 242, value: 'initialState.ccmAp.device_ap.mobility_zone_uuid', text: 'TBD', textAlto: 'TBD', enumType: '', incidents: {}, kpis: {} },
  { id: 243, value: 'initialState.ccmAp.device_ap.registration_state', text: 'TBD', textAlto: 'TBD', enumType: 'com.ruckuswireless.scg.protobuf.ccm.DeviceAp.CcmDeviceAp.RegistrationState', incidents: {}, kpis: {} },
  { id: 244, value: 'initialState.ccmAp.device_ap.provision_method', text: 'TBD', textAlto: 'TBD', enumType: 'com.ruckuswireless.scg.protobuf.ccm.DeviceAp.CcmDeviceAp.ProvisionMethod', incidents: {}, kpis: {} },
  { id: 245, value: 'initialState.ccmAp.device_ap.ext_ip', text: 'TBD', textAlto: 'TBD', enumType: '', incidents: {}, kpis: {} },
  { id: 246, value: 'initialState.ccmAp.device_ap.switchover_destination', text: 'TBD', textAlto: 'TBD', enumType: '', incidents: {}, kpis: {} },
  { id: 247, value: 'initialState.ccmAp.device_ap.switchover_ap_deletion', text: 'TBD', textAlto: 'TBD', enumType: '', incidents: {}, kpis: {} },
  { id: 248, value: 'initialState.ccmAp.device_ap.switchover_expiration_time', text: 'TBD', textAlto: 'TBD', enumType: '', incidents: {}, kpis: {} },
  { id: 249, value: 'initialState.ccmAp.common.communicator_server_cert_changed_time', text: 'TBD', textAlto: 'TBD', enumType: '', incidents: {}, kpis: {} },
  { id: 250, value: 'initialState.ccmAp.common.device_trusted_cert_chain_setting_enable', text: 'TBD', textAlto: 'TBD', enumType: '', incidents: {}, kpis: {} },
  { id: 251, value: 'initialState.ccmAp.model.model_specific_ethernet_port_settings.vni', text: 'TBD', textAlto: 'TBD', enumType: '', incidents: {}, kpis: {} },
  { id: 252, value: 'initialState.ccmAp.radio24g.radio.radio_enabled', text: 'TBD', textAlto: 'TBD', enumType: '', incidents: {}, kpis: {} },
  { id: 253, value: 'initialState.ccmAp.radio5g.cband_channel_enable', text: defineMessage({ defaultMessage: 'Based on country : 5.8 GHz Channel' }), textAlto: 'TBD', enumType: '', incidents: {}, kpis: {} },
  { id: 254, value: 'initialState.ccmAp.radio5g.cband_channel_license', text: defineMessage({ defaultMessage: 'Based on country : 5.8 GHz Channel License' }), textAlto: 'TBD', enumType: '', incidents: {}, kpis: {} },
  { id: 255, value: 'initialState.ccmAp.radio5g.channel_144_enable', text: 'TBD', textAlto: 'TBD', enumType: '', incidents: {}, kpis: {} },
  { id: 256, value: 'initialState.ccmAp.radio5g.radio.radio_enabled', text: 'TBD', textAlto: 'TBD', enumType: '', incidents: {}, kpis: {} },
  { id: 257, value: 'initialState.ccmAp.radio_configs.dual_5g_enable', text: defineMessage({ defaultMessage: 'Dual 5G : Enabled' }), textAlto: 'TBD', enumType: '', incidents: {}, kpis: {} },
  { id: 258, value: 'initialState.ccmAp.radio_configs.radio24g.radio.adj_threshold', text: 'TBD', textAlto: 'TBD', enumType: '', incidents: {}, kpis: {} },
  { id: 259, value: 'initialState.ccmAp.radio_configs.radio24g.radio.auto_cell_sizing', text: 'TBD', textAlto: 'TBD', enumType: '', incidents: {}, kpis: {} },
  { id: 260, value: 'initialState.ccmAp.radio_configs.radio24g.radio.bg_scan', text: 'TBD', textAlto: 'TBD', enumType: '', incidents: {}, kpis: {} },
  { id: 261, value: 'initialState.ccmAp.radio_configs.radio24g.radio.bg_scan_timer', text: 'TBD', textAlto: 'TBD', enumType: '', incidents: {}, kpis: {} },
  { id: 262, value: 'initialState.ccmAp.radio_configs.radio24g.radio.bg_scanner.enabled', text: 'TBD', textAlto: 'TBD', enumType: '', incidents: {}, kpis: {} },
  { id: 263, value: 'initialState.ccmAp.radio_configs.radio24g.radio.bg_scanner.timer', text: 'TBD', textAlto: 'TBD', enumType: '', incidents: {}, kpis: {} },
  { id: 264, value: 'initialState.ccmAp.radio_configs.radio24g.radio.channel', text: 'TBD', textAlto: 'TBD', enumType: '', incidents: {}, kpis: {} },
  { id: 265, value: 'initialState.ccmAp.radio_configs.radio24g.radio.channel_fly_config.channel_change_frequency', text: 'TBD', textAlto: 'TBD', enumType: '', incidents: {}, kpis: {} },
  { id: 266, value: 'initialState.ccmAp.radio_configs.radio24g.radio.channel_fly_config.optimization_time_period', text: 'TBD', textAlto: 'TBD', enumType: '', incidents: {}, kpis: {} },
  { id: 267, value: 'initialState.ccmAp.radio_configs.radio24g.radio.channel_fly_mtbc', text: 'TBD', textAlto: 'TBD', enumType: '', incidents: {}, kpis: {} },
  { id: 268, value: 'initialState.ccmAp.radio_configs.radio24g.radio.channel_range', text: 'TBD', textAlto: 'TBD', enumType: '', incidents: {}, kpis: {} },
  { id: 269, value: 'initialState.ccmAp.radio_configs.radio24g.radio.channel_select_mode', text: 'TBD', textAlto: 'TBD', enumType: 'com.ruckuswireless.scg.protobuf.ccm.Zone.CcmRadio.ChannelSelectMode', incidents: {}, kpis: {} },
  { id: 270, value: 'initialState.ccmAp.radio_configs.radio24g.radio.channel_width', text: 'TBD', textAlto: 'TBD', enumType: 'com.ruckuswireless.scg.protobuf.ccm.Zone.CcmRadio.ChannelWidth', incidents: {}, kpis: {} },
  { id: 271, value: 'initialState.ccmAp.radio_configs.radio24g.radio.clb_enabled', text: 'TBD', textAlto: 'TBD', enumType: '', incidents: {}, kpis: {} },
  { id: 272, value: 'initialState.ccmAp.radio_configs.radio24g.radio.client_admission.enabled', text: 'TBD', textAlto: 'TBD', enumType: '', incidents: {}, kpis: {} },
  { id: 273, value: 'initialState.ccmAp.radio_configs.radio24g.radio.client_admission.maxiumum_radio_load', text: 'TBD', textAlto: 'TBD', enumType: '', incidents: {}, kpis: {} },
  { id: 274, value: 'initialState.ccmAp.radio_configs.radio24g.radio.client_admission.minimum_client_count', text: 'TBD', textAlto: 'TBD', enumType: '', incidents: {}, kpis: {} },
  { id: 275, value: 'initialState.ccmAp.radio_configs.radio24g.radio.client_admission.minimum_client_throughput', text: 'TBD', textAlto: 'TBD', enumType: '', incidents: {}, kpis: {} },
  { id: 276, value: 'initialState.ccmAp.radio_configs.radio24g.radio.head_room', text: 'TBD', textAlto: 'TBD', enumType: '', incidents: {}, kpis: {} },
  { id: 277, value: 'initialState.ccmAp.radio_configs.radio24g.radio.indoor_channel_block', text: 'TBD', textAlto: 'TBD', enumType: 'com.ruckuswireless.scg.protobuf.ccm.Zone.CcmRadio.AllowIndoorChannel', incidents: {}, kpis: {} },
  { id: 278, value: 'initialState.ccmAp.radio_configs.radio24g.radio.protection_mode', text: 'TBD', textAlto: 'TBD', enumType: 'com.ruckuswireless.scg.protobuf.ccm.Zone.CcmRadio.ProtectionMode', incidents: {}, kpis: {} },
  { id: 279, value: 'initialState.ccmAp.radio_configs.radio24g.radio.radio_enabled', text: 'TBD', textAlto: 'TBD', enumType: '', incidents: {}, kpis: {} },
  { id: 280, value: 'initialState.ccmAp.radio_configs.radio24g.radio.roam_enabled', text: 'TBD', textAlto: 'TBD', enumType: '', incidents: {}, kpis: {} },
  { id: 281, value: 'initialState.ccmAp.radio_configs.radio24g.radio.roam_macfilt_time', text: 'TBD', textAlto: 'TBD', enumType: '', incidents: {}, kpis: {} },
  { id: 282, value: 'initialState.ccmAp.radio_configs.radio24g.radio.tax_power', text: 'TBD', textAlto: 'TBD', enumType: 'com.ruckuswireless.scg.protobuf.ccm.Zone.CcmRadio.TaxPower', incidents: {}, kpis: {} },
  { id: 283, value: 'initialState.ccmAp.radio_configs.radio24g.radio.weak_bypass', text: 'TBD', textAlto: 'TBD', enumType: '', incidents: {}, kpis: {} },
  { id: 284, value: 'initialState.ccmAp.radio_configs.radio24g.radio.wlan_service_enabled', text: 'TBD', textAlto: 'TBD', enumType: '', incidents: {}, kpis: {} },
  { id: 285, value: 'initialState.ccmAp.radio_configs.radio5g.cband_channel_enable', text: 'TBD', textAlto: 'TBD', enumType: '', incidents: {}, kpis: {} },
  { id: 286, value: 'initialState.ccmAp.radio_configs.radio5g.cband_channel_license', text: 'TBD', textAlto: 'TBD', enumType: '', incidents: {}, kpis: {} },
  { id: 287, value: 'initialState.ccmAp.radio_configs.radio5g.channel_144_enable', text: 'TBD', textAlto: 'TBD', enumType: '', incidents: {}, kpis: {} },
  { id: 288, value: 'initialState.ccmAp.radio_configs.radio5g.indoor_channel', text: 'TBD', textAlto: 'TBD', enumType: '', incidents: {}, kpis: {} },
  { id: 289, value: 'initialState.ccmAp.radio_configs.radio5g.indoor_channel_range', text: 'TBD', textAlto: 'TBD', enumType: '', incidents: {}, kpis: {} },
  { id: 290, value: 'initialState.ccmAp.radio_configs.radio5g.indoor_secondary_channel', text: 'TBD', textAlto: 'TBD', enumType: '', incidents: {}, kpis: {} },
  { id: 291, value: 'initialState.ccmAp.radio_configs.radio5g.radio.adj_threshold', text: 'TBD', textAlto: 'TBD', enumType: '', incidents: {}, kpis: {} },
  { id: 292, value: 'initialState.ccmAp.radio_configs.radio5g.radio.auto_cell_sizing', text: 'TBD', textAlto: 'TBD', enumType: '', incidents: {}, kpis: {} },
  { id: 293, value: 'initialState.ccmAp.radio_configs.radio5g.radio.bg_scan', text: 'TBD', textAlto: 'TBD', enumType: '', incidents: {}, kpis: {} },
  { id: 294, value: 'initialState.ccmAp.radio_configs.radio5g.radio.bg_scan_timer', text: 'TBD', textAlto: 'TBD', enumType: '', incidents: {}, kpis: {} },
  { id: 295, value: 'initialState.ccmAp.radio_configs.radio5g.radio.bg_scanner.enabled', text: 'TBD', textAlto: 'TBD', enumType: '', incidents: {}, kpis: {} },
  { id: 296, value: 'initialState.ccmAp.radio_configs.radio5g.radio.bg_scanner.timer', text: 'TBD', textAlto: 'TBD', enumType: '', incidents: {}, kpis: {} },
  { id: 297, value: 'initialState.ccmAp.radio_configs.radio5g.radio.channel', text: 'TBD', textAlto: 'TBD', enumType: '', incidents: {}, kpis: {} },
  { id: 298, value: 'initialState.ccmAp.radio_configs.radio5g.radio.channel_fly_config.channel_change_frequency', text: 'TBD', textAlto: 'TBD', enumType: '', incidents: {}, kpis: {} },
  { id: 299, value: 'initialState.ccmAp.radio_configs.radio5g.radio.channel_fly_config.optimization_time_period', text: 'TBD', textAlto: 'TBD', enumType: '', incidents: {}, kpis: {} },
  { id: 300, value: 'initialState.ccmAp.radio_configs.radio5g.radio.channel_fly_mtbc', text: 'TBD', textAlto: 'TBD', enumType: '', incidents: {}, kpis: {} },
  { id: 301, value: 'initialState.ccmAp.radio_configs.radio5g.radio.channel_range', text: 'TBD', textAlto: 'TBD', enumType: '', incidents: {}, kpis: {} },
  { id: 302, value: 'initialState.ccmAp.radio_configs.radio5g.radio.channel_select_mode', text: 'TBD', textAlto: 'TBD', enumType: 'com.ruckuswireless.scg.protobuf.ccm.Zone.CcmRadio.ChannelSelectMode', incidents: {}, kpis: {} },
  { id: 303, value: 'initialState.ccmAp.radio_configs.radio5g.radio.channel_width', text: 'TBD', textAlto: 'TBD', enumType: 'com.ruckuswireless.scg.protobuf.ccm.Zone.CcmRadio.ChannelWidth', incidents: {}, kpis: {} },
  { id: 304, value: 'initialState.ccmAp.radio_configs.radio5g.radio.clb_enabled', text: 'TBD', textAlto: 'TBD', enumType: '', incidents: {}, kpis: {} },
  { id: 305, value: 'initialState.ccmAp.radio_configs.radio5g.radio.client_admission.enabled', text: 'TBD', textAlto: 'TBD', enumType: '', incidents: {}, kpis: {} },
  { id: 306, value: 'initialState.ccmAp.radio_configs.radio5g.radio.client_admission.maxiumum_radio_load', text: 'TBD', textAlto: 'TBD', enumType: '', incidents: {}, kpis: {} },
  { id: 307, value: 'initialState.ccmAp.radio_configs.radio5g.radio.client_admission.minimum_client_count', text: 'TBD', textAlto: 'TBD', enumType: '', incidents: {}, kpis: {} },
  { id: 308, value: 'initialState.ccmAp.radio_configs.radio5g.radio.client_admission.minimum_client_throughput', text: 'TBD', textAlto: 'TBD', enumType: '', incidents: {}, kpis: {} },
  { id: 309, value: 'initialState.ccmAp.radio_configs.radio5g.radio.head_room', text: 'TBD', textAlto: 'TBD', enumType: '', incidents: {}, kpis: {} },
  { id: 310, value: 'initialState.ccmAp.radio_configs.radio5g.radio.indoor_channel_block', text: 'TBD', textAlto: 'TBD', enumType: 'com.ruckuswireless.scg.protobuf.ccm.Zone.CcmRadio.AllowIndoorChannel', incidents: {}, kpis: {} },
  { id: 311, value: 'initialState.ccmAp.radio_configs.radio5g.radio.protection_mode', text: 'TBD', textAlto: 'TBD', enumType: 'com.ruckuswireless.scg.protobuf.ccm.Zone.CcmRadio.ProtectionMode', incidents: {}, kpis: {} },
  { id: 312, value: 'initialState.ccmAp.radio_configs.radio5g.radio.radio_enabled', text: 'TBD', textAlto: 'TBD', enumType: '', incidents: {}, kpis: {} },
  { id: 313, value: 'initialState.ccmAp.radio_configs.radio5g.radio.roam_enabled', text: 'TBD', textAlto: 'TBD', enumType: '', incidents: {}, kpis: {} },
  { id: 314, value: 'initialState.ccmAp.radio_configs.radio5g.radio.roam_macfilt_time', text: 'TBD', textAlto: 'TBD', enumType: '', incidents: {}, kpis: {} },
  { id: 315, value: 'initialState.ccmAp.radio_configs.radio5g.radio.tax_power', text: 'TBD', textAlto: 'TBD', enumType: 'com.ruckuswireless.scg.protobuf.ccm.Zone.CcmRadio.TaxPower', incidents: {}, kpis: {} },
  { id: 316, value: 'initialState.ccmAp.radio_configs.radio5g.radio.weak_bypass', text: 'TBD', textAlto: 'TBD', enumType: '', incidents: {}, kpis: {} },
  { id: 317, value: 'initialState.ccmAp.radio_configs.radio5g.radio.wlan_service_enabled', text: 'TBD', textAlto: 'TBD', enumType: '', incidents: {}, kpis: {} },
  { id: 318, value: 'initialState.ccmAp.radio_configs.radio5g.secondary_channel', text: 'TBD', textAlto: 'TBD', enumType: '', incidents: {}, kpis: {} },
  { id: 319, value: 'initialState.ccmAp.radio_configs.radio5gLower.cband_channel_enable', text: 'TBD', textAlto: 'TBD', enumType: '', incidents: {}, kpis: {} },
  { id: 320, value: 'initialState.ccmAp.radio_configs.radio5gLower.cband_channel_license', text: 'TBD', textAlto: 'TBD', enumType: '', incidents: {}, kpis: {} },
  { id: 321, value: 'initialState.ccmAp.radio_configs.radio5gLower.channel_144_enable', text: 'TBD', textAlto: 'TBD', enumType: '', incidents: {}, kpis: {} },
  { id: 322, value: 'initialState.ccmAp.radio_configs.radio5gLower.indoor_channel', text: 'TBD', textAlto: 'TBD', enumType: '', incidents: {}, kpis: {} },
  { id: 323, value: 'initialState.ccmAp.radio_configs.radio5gLower.indoor_channel_range', text: 'TBD', textAlto: 'TBD', enumType: '', incidents: {}, kpis: {} },
  { id: 324, value: 'initialState.ccmAp.radio_configs.radio5gLower.indoor_secondary_channel', text: 'TBD', textAlto: 'TBD', enumType: '', incidents: {}, kpis: {} },
  { id: 325, value: 'initialState.ccmAp.radio_configs.radio5gLower.radio.adj_threshold', text: 'TBD', textAlto: 'TBD', enumType: '', incidents: {}, kpis: {} },
  { id: 326, value: 'initialState.ccmAp.radio_configs.radio5gLower.radio.auto_cell_sizing', text: defineMessage({ defaultMessage: 'Auto Cell Sizing (Lower 5 GHz)' }), textAlto: 'TBD', enumType: '', incidents: {}, kpis: {} },
  { id: 327, value: 'initialState.ccmAp.radio_configs.radio5gLower.radio.bg_scan', text: 'TBD', textAlto: 'TBD', enumType: '', incidents: {}, kpis: {} },
  { id: 328, value: 'initialState.ccmAp.radio_configs.radio5gLower.radio.bg_scan_timer', text: 'TBD', textAlto: 'TBD', enumType: '', incidents: {}, kpis: {} },
  { id: 329, value: 'initialState.ccmAp.radio_configs.radio5gLower.radio.bg_scanner.enabled', text: 'TBD', textAlto: 'TBD', enumType: '', incidents: {}, kpis: {} },
  { id: 330, value: 'initialState.ccmAp.radio_configs.radio5gLower.radio.bg_scanner.timer', text: 'TBD', textAlto: 'TBD', enumType: '', incidents: {}, kpis: {} },
  { id: 331, value: 'initialState.ccmAp.radio_configs.radio5gLower.radio.channel', text: defineMessage({ defaultMessage: 'Channel (Lower 5 GHz)' }), textAlto: 'TBD', enumType: '', incidents: {}, kpis: {} },
  { id: 332, value: 'initialState.ccmAp.radio_configs.radio5gLower.radio.channel_fly_config.channel_change_frequency', text: defineMessage({ defaultMessage: 'Channel Change Frequency (Lower 5 GHz)' }), textAlto: 'TBD', enumType: '', incidents: {}, kpis: {} },
  { id: 333, value: 'initialState.ccmAp.radio_configs.radio5gLower.radio.channel_fly_config.optimization_time_period', text: defineMessage({ defaultMessage: 'Channelfly: Full Optimization Period (Lower 5 GHz)' }), textAlto: 'TBD', enumType: '', incidents: {}, kpis: {} },
  { id: 334, value: 'initialState.ccmAp.radio_configs.radio5gLower.radio.channel_fly_mtbc', text: 'TBD', textAlto: 'TBD', enumType: '', incidents: {}, kpis: {} },
  { id: 335, value: 'initialState.ccmAp.radio_configs.radio5gLower.radio.channel_range', text: defineMessage({ defaultMessage: 'Channel Range (Lower 5 GHz)' }), textAlto: 'TBD', enumType: '', incidents: {}, kpis: {} },
  { id: 336, value: 'initialState.ccmAp.radio_configs.radio5gLower.radio.channel_select_mode', text: 'TBD', textAlto: 'TBD', enumType: 'com.ruckuswireless.scg.protobuf.ccm.Zone.CcmRadio.ChannelSelectMode', incidents: {}, kpis: {} },
  { id: 337, value: 'initialState.ccmAp.radio_configs.radio5gLower.radio.channel_width', text: 'TBD', textAlto: 'TBD', enumType: 'com.ruckuswireless.scg.protobuf.ccm.Zone.CcmRadio.ChannelWidth', incidents: {}, kpis: {} },
  { id: 338, value: 'initialState.ccmAp.radio_configs.radio5gLower.radio.clb_enabled', text: 'TBD', textAlto: 'TBD', enumType: '', incidents: {}, kpis: {} },
  { id: 339, value: 'initialState.ccmAp.radio_configs.radio5gLower.radio.client_admission.enabled', text: defineMessage({ defaultMessage: 'Client Admission control : Enabled (Lower 5 GHz)' }), textAlto: 'TBD', enumType: '', incidents: {}, kpis: {} },
  { id: 340, value: 'initialState.ccmAp.radio_configs.radio5gLower.radio.client_admission.maxiumum_radio_load', text: defineMessage({ defaultMessage: 'Client Admission Control: Max Radio Load (Lower 5 GHz)' }), textAlto: 'TBD', enumType: '', incidents: {}, kpis: {} },
  { id: 341, value: 'initialState.ccmAp.radio_configs.radio5gLower.radio.client_admission.minimum_client_count', text: defineMessage({ defaultMessage: 'Client Admission Control: Min Client Count (Lower 5 GHz)' }), textAlto: 'TBD', enumType: '', incidents: {}, kpis: {} },
  { id: 342, value: 'initialState.ccmAp.radio_configs.radio5gLower.radio.client_admission.minimum_client_throughput', text: defineMessage({ defaultMessage: 'Client Admission Control: Min Client Throughput (Lower 5 GHz)' }), textAlto: 'TBD', enumType: '', incidents: {}, kpis: {} },
  { id: 343, value: 'initialState.ccmAp.radio_configs.radio5gLower.radio.head_room', text: 'TBD', textAlto: 'TBD', enumType: '', incidents: {}, kpis: {} },
  { id: 344, value: 'initialState.ccmAp.radio_configs.radio5gLower.radio.indoor_channel_block', text: 'TBD', textAlto: 'TBD', enumType: 'com.ruckuswireless.scg.protobuf.ccm.Zone.CcmRadio.AllowIndoorChannel', incidents: {}, kpis: {} },
  { id: 345, value: 'initialState.ccmAp.radio_configs.radio5gLower.radio.protection_mode', text: 'TBD', textAlto: 'TBD', enumType: 'com.ruckuswireless.scg.protobuf.ccm.Zone.CcmRadio.ProtectionMode', incidents: {}, kpis: {} },
  { id: 346, value: 'initialState.ccmAp.radio_configs.radio5gLower.radio.radio_enabled', text: 'TBD', textAlto: 'TBD', enumType: '', incidents: {}, kpis: {} },
  { id: 347, value: 'initialState.ccmAp.radio_configs.radio5gLower.radio.roam_enabled', text: 'TBD', textAlto: 'TBD', enumType: '', incidents: {}, kpis: {} },
  { id: 348, value: 'initialState.ccmAp.radio_configs.radio5gLower.radio.roam_macfilt_time', text: 'TBD', textAlto: 'TBD', enumType: '', incidents: {}, kpis: {} },
  { id: 349, value: 'initialState.ccmAp.radio_configs.radio5gLower.radio.tax_power', text: defineMessage({ defaultMessage: 'TX Power Adjustment (Lower 5 GHz)' }), textAlto: 'TBD', enumType: 'com.ruckuswireless.scg.protobuf.ccm.Zone.CcmRadio.TaxPower', incidents: {}, kpis: {} },
  { id: 350, value: 'initialState.ccmAp.radio_configs.radio5gLower.radio.weak_bypass', text: 'TBD', textAlto: 'TBD', enumType: '', incidents: {}, kpis: {} },
  { id: 351, value: 'initialState.ccmAp.radio_configs.radio5gLower.radio.wlan_service_enabled', text: defineMessage({ defaultMessage: 'Wlan Service (Lower 5 GHz)' }), textAlto: 'TBD', enumType: '', incidents: {}, kpis: {} },
  { id: 352, value: 'initialState.ccmAp.radio_configs.radio5gLower.secondary_channel', text: 'TBD', textAlto: 'TBD', enumType: '', incidents: {}, kpis: {} },
  { id: 353, value: 'initialState.ccmAp.radio_configs.radio5gUpper.cband_channel_enable', text: 'TBD', textAlto: 'TBD', enumType: '', incidents: {}, kpis: {} },
  { id: 354, value: 'initialState.ccmAp.radio_configs.radio5gUpper.cband_channel_license', text: 'TBD', textAlto: 'TBD', enumType: '', incidents: {}, kpis: {} },
  { id: 355, value: 'initialState.ccmAp.radio_configs.radio5gUpper.channel_144_enable', text: 'TBD', textAlto: 'TBD', enumType: '', incidents: {}, kpis: {} },
  { id: 356, value: 'initialState.ccmAp.radio_configs.radio5gUpper.indoor_channel', text: 'TBD', textAlto: 'TBD', enumType: '', incidents: {}, kpis: {} },
  { id: 357, value: 'initialState.ccmAp.radio_configs.radio5gUpper.indoor_channel_range', text: 'TBD', textAlto: 'TBD', enumType: '', incidents: {}, kpis: {} },
  { id: 358, value: 'initialState.ccmAp.radio_configs.radio5gUpper.indoor_secondary_channel', text: 'TBD', textAlto: 'TBD', enumType: '', incidents: {}, kpis: {} },
  { id: 359, value: 'initialState.ccmAp.radio_configs.radio5gUpper.radio.adj_threshold', text: 'TBD', textAlto: 'TBD', enumType: '', incidents: {}, kpis: {} },
  { id: 360, value: 'initialState.ccmAp.radio_configs.radio5gUpper.radio.auto_cell_sizing', text: defineMessage({ defaultMessage: 'Auto Cell Sizing (Upper 5 GHz)' }), textAlto: 'TBD', enumType: '', incidents: {}, kpis: {} },
  { id: 361, value: 'initialState.ccmAp.radio_configs.radio5gUpper.radio.bg_scan', text: 'TBD', textAlto: 'TBD', enumType: '', incidents: {}, kpis: {} },
  { id: 362, value: 'initialState.ccmAp.radio_configs.radio5gUpper.radio.bg_scan_timer', text: 'TBD', textAlto: 'TBD', enumType: '', incidents: {}, kpis: {} },
  { id: 363, value: 'initialState.ccmAp.radio_configs.radio5gUpper.radio.bg_scanner.enabled', text: 'TBD', textAlto: 'TBD', enumType: '', incidents: {}, kpis: {} },
  { id: 364, value: 'initialState.ccmAp.radio_configs.radio5gUpper.radio.bg_scanner.timer', text: 'TBD', textAlto: 'TBD', enumType: '', incidents: {}, kpis: {} },
  { id: 365, value: 'initialState.ccmAp.radio_configs.radio5gUpper.radio.channel', text: defineMessage({ defaultMessage: 'Channel (Upper 5 GHz)' }), textAlto: 'TBD', enumType: '', incidents: {}, kpis: {} },
  { id: 366, value: 'initialState.ccmAp.radio_configs.radio5gUpper.radio.channel_fly_config.channel_change_frequency', text: defineMessage({ defaultMessage: 'Channel Change Frequency (Upper 5 GHz)' }), textAlto: 'TBD', enumType: '', incidents: {}, kpis: {} },
  { id: 367, value: 'initialState.ccmAp.radio_configs.radio5gUpper.radio.channel_fly_config.optimization_time_period', text: defineMessage({ defaultMessage: 'Channelfly: Full Optimization Period (Upper 5 GHz)' }), textAlto: 'TBD', enumType: '', incidents: {}, kpis: {} },
  { id: 368, value: 'initialState.ccmAp.radio_configs.radio5gUpper.radio.channel_fly_mtbc', text: defineMessage({ defaultMessage: 'ChannelFly MTBC (Upper 5 GHz)' }), textAlto: 'TBD', enumType: '', incidents: {}, kpis: {} },
  { id: 369, value: 'initialState.ccmAp.radio_configs.radio5gUpper.radio.channel_range', text: defineMessage({ defaultMessage: 'Channel Range (Upper 5 GHz)' }), textAlto: 'TBD', enumType: '', incidents: {}, kpis: {} },
  { id: 370, value: 'initialState.ccmAp.radio_configs.radio5gUpper.radio.channel_select_mode', text: 'TBD', textAlto: 'TBD', enumType: 'com.ruckuswireless.scg.protobuf.ccm.Zone.CcmRadio.ChannelSelectMode', incidents: {}, kpis: {} },
  { id: 371, value: 'initialState.ccmAp.radio_configs.radio5gUpper.radio.channel_width', text: 'TBD', textAlto: 'TBD', enumType: 'com.ruckuswireless.scg.protobuf.ccm.Zone.CcmRadio.ChannelWidth', incidents: {}, kpis: {} },
  { id: 372, value: 'initialState.ccmAp.radio_configs.radio5gUpper.radio.clb_enabled', text: 'TBD', textAlto: 'TBD', enumType: '', incidents: {}, kpis: {} },
  { id: 373, value: 'initialState.ccmAp.radio_configs.radio5gUpper.radio.client_admission.enabled', text: defineMessage({ defaultMessage: 'Client Admission control : Enabled (Upper 5 GHz)' }), textAlto: 'TBD', enumType: '', incidents: {}, kpis: {} },
  { id: 374, value: 'initialState.ccmAp.radio_configs.radio5gUpper.radio.client_admission.maxiumum_radio_load', text: defineMessage({ defaultMessage: 'Client Admission Control: Max Radio Load (Upper 5 GHz)' }), textAlto: 'TBD', enumType: '', incidents: {}, kpis: {} },
  { id: 375, value: 'initialState.ccmAp.radio_configs.radio5gUpper.radio.client_admission.minimum_client_count', text: defineMessage({ defaultMessage: 'Client Admission Control: Min Client Count (Upper 5 GHz)' }), textAlto: 'TBD', enumType: '', incidents: {}, kpis: {} },
  { id: 376, value: 'initialState.ccmAp.radio_configs.radio5gUpper.radio.client_admission.minimum_client_throughput', text: defineMessage({ defaultMessage: 'Client Admission Control: Min Client Throughput (Upper 5 GHz)' }), textAlto: 'TBD', enumType: '', incidents: {}, kpis: {} },
  { id: 377, value: 'initialState.ccmAp.radio_configs.radio5gUpper.radio.head_room', text: 'TBD', textAlto: 'TBD', enumType: '', incidents: {}, kpis: {} },
  { id: 378, value: 'initialState.ccmAp.radio_configs.radio5gUpper.radio.indoor_channel_block', text: 'TBD', textAlto: 'TBD', enumType: 'com.ruckuswireless.scg.protobuf.ccm.Zone.CcmRadio.AllowIndoorChannel', incidents: {}, kpis: {} },
  { id: 379, value: 'initialState.ccmAp.radio_configs.radio5gUpper.radio.protection_mode', text: 'TBD', textAlto: 'TBD', enumType: 'com.ruckuswireless.scg.protobuf.ccm.Zone.CcmRadio.ProtectionMode', incidents: {}, kpis: {} },
  { id: 380, value: 'initialState.ccmAp.radio_configs.radio5gUpper.radio.radio_enabled', text: 'TBD', textAlto: 'TBD', enumType: '', incidents: {}, kpis: {} },
  { id: 381, value: 'initialState.ccmAp.radio_configs.radio5gUpper.radio.roam_enabled', text: 'TBD', textAlto: 'TBD', enumType: '', incidents: {}, kpis: {} },
  { id: 382, value: 'initialState.ccmAp.radio_configs.radio5gUpper.radio.roam_macfilt_time', text: 'TBD', textAlto: 'TBD', enumType: '', incidents: {}, kpis: {} },
  { id: 383, value: 'initialState.ccmAp.radio_configs.radio5gUpper.radio.tax_power', text: defineMessage({ defaultMessage: 'TX Power Adjustment (Upper 5 GHz)' }), textAlto: 'TBD', enumType: 'com.ruckuswireless.scg.protobuf.ccm.Zone.CcmRadio.TaxPower', incidents: {}, kpis: {} },
  { id: 384, value: 'initialState.ccmAp.radio_configs.radio5gUpper.radio.weak_bypass', text: 'TBD', textAlto: 'TBD', enumType: '', incidents: {}, kpis: {} },
  { id: 385, value: 'initialState.ccmAp.radio_configs.radio5gUpper.radio.wlan_service_enabled', text: defineMessage({ defaultMessage: 'Wlan Service (Upper 5 GHz)' }), textAlto: 'TBD', enumType: '', incidents: {}, kpis: {} },
  { id: 386, value: 'initialState.ccmAp.radio_configs.radio5gUpper.secondary_channel', text: 'TBD', textAlto: 'TBD', enumType: '', incidents: {}, kpis: {} },
  { id: 387, value: 'initialState.ccmAp.radio_configs.radio6g.channel2_enable', text: 'TBD', textAlto: 'TBD', enumType: '', incidents: {}, kpis: {} },
  { id: 388, value: 'initialState.ccmAp.radio_configs.radio6g.low_power_indoor_mode_enable', text: 'TBD', textAlto: 'TBD', enumType: '', incidents: {}, kpis: {} },
  { id: 389, value: 'initialState.ccmAp.radio_configs.radio6g.radio.adj_threshold', text: 'TBD', textAlto: 'TBD', enumType: '', incidents: {}, kpis: {} },
  { id: 390, value: 'initialState.ccmAp.radio_configs.radio6g.radio.auto_cell_sizing', text: defineMessage({ defaultMessage: 'Auto Cell Sizing (6 GHz)' }), textAlto: 'TBD', enumType: '', incidents: {}, kpis: {} },
  { id: 391, value: 'initialState.ccmAp.radio_configs.radio6g.radio.bg_scan', text: 'TBD', textAlto: 'TBD', enumType: '', incidents: {}, kpis: {} },
  { id: 392, value: 'initialState.ccmAp.radio_configs.radio6g.radio.bg_scan_timer', text: 'TBD', textAlto: 'TBD', enumType: '', incidents: {}, kpis: {} },
  { id: 393, value: 'initialState.ccmAp.radio_configs.radio6g.radio.bg_scanner.enabled', text: 'TBD', textAlto: 'TBD', enumType: '', incidents: {}, kpis: {} },
  { id: 394, value: 'initialState.ccmAp.radio_configs.radio6g.radio.bg_scanner.timer', text: 'TBD', textAlto: 'TBD', enumType: '', incidents: {}, kpis: {} },
  { id: 395, value: 'initialState.ccmAp.radio_configs.radio6g.radio.channel', text: defineMessage({ defaultMessage: 'Channel (6 GHz)' }), textAlto: 'TBD', enumType: '', incidents: {}, kpis: {} },
  { id: 396, value: 'initialState.ccmAp.radio_configs.radio6g.radio.channel_fly_config.channel_change_frequency', text: defineMessage({ defaultMessage: 'Channel Change Frequency (6 GHz)' }), textAlto: 'TBD', enumType: '', incidents: {}, kpis: {} },
  { id: 397, value: 'initialState.ccmAp.radio_configs.radio6g.radio.channel_fly_config.optimization_time_period', text: defineMessage({ defaultMessage: 'Channelfly: Full Optimization Period (6 GHz)' }), textAlto: 'TBD', enumType: '', incidents: {}, kpis: {} },
  { id: 398, value: 'initialState.ccmAp.radio_configs.radio6g.radio.channel_fly_mtbc', text: 'TBD', textAlto: 'TBD', enumType: '', incidents: {}, kpis: {} },
  { id: 399, value: 'initialState.ccmAp.radio_configs.radio6g.radio.channel_range', text: defineMessage({ defaultMessage: 'Channel Range (6 GHz) ' }), textAlto: 'TBD', enumType: '', incidents: {}, kpis: {} },
  { id: 400, value: 'initialState.ccmAp.radio_configs.radio6g.radio.channel_select_mode', text: 'TBD', textAlto: 'TBD', enumType: 'com.ruckuswireless.scg.protobuf.ccm.Zone.CcmRadio.ChannelSelectMode', incidents: {}, kpis: {} },
  { id: 401, value: 'initialState.ccmAp.radio_configs.radio6g.radio.channel_width', text: 'TBD', textAlto: 'TBD', enumType: 'com.ruckuswireless.scg.protobuf.ccm.Zone.CcmRadio.ChannelWidth', incidents: {}, kpis: {} },
  { id: 402, value: 'initialState.ccmAp.radio_configs.radio6g.radio.clb_enabled', text: 'TBD', textAlto: 'TBD', enumType: '', incidents: {}, kpis: {} },
  { id: 403, value: 'initialState.ccmAp.radio_configs.radio6g.radio.client_admission.enabled', text: 'TBD', textAlto: 'TBD', enumType: '', incidents: {}, kpis: {} },
  { id: 404, value: 'initialState.ccmAp.radio_configs.radio6g.radio.client_admission.maxiumum_radio_load', text: 'TBD', textAlto: 'TBD', enumType: '', incidents: {}, kpis: {} },
  { id: 405, value: 'initialState.ccmAp.radio_configs.radio6g.radio.client_admission.minimum_client_count', text: 'TBD', textAlto: 'TBD', enumType: '', incidents: {}, kpis: {} },
  { id: 406, value: 'initialState.ccmAp.radio_configs.radio6g.radio.client_admission.minimum_client_throughput', text: 'TBD', textAlto: 'TBD', enumType: '', incidents: {}, kpis: {} },
  { id: 407, value: 'initialState.ccmAp.radio_configs.radio6g.radio.head_room', text: 'TBD', textAlto: 'TBD', enumType: '', incidents: {}, kpis: {} },
  { id: 408, value: 'initialState.ccmAp.radio_configs.radio6g.radio.indoor_channel_block', text: 'TBD', textAlto: 'TBD', enumType: 'com.ruckuswireless.scg.protobuf.ccm.Zone.CcmRadio.AllowIndoorChannel', incidents: {}, kpis: {} },
  { id: 409, value: 'initialState.ccmAp.radio_configs.radio6g.radio.protection_mode', text: 'TBD', textAlto: 'TBD', enumType: 'com.ruckuswireless.scg.protobuf.ccm.Zone.CcmRadio.ProtectionMode', incidents: {}, kpis: {} },
  { id: 410, value: 'initialState.ccmAp.radio_configs.radio6g.radio.radio_enabled', text: 'TBD', textAlto: 'TBD', enumType: '', incidents: {}, kpis: {} },
  { id: 411, value: 'initialState.ccmAp.radio_configs.radio6g.radio.roam_enabled', text: 'TBD', textAlto: 'TBD', enumType: '', incidents: {}, kpis: {} },
  { id: 412, value: 'initialState.ccmAp.radio_configs.radio6g.radio.roam_macfilt_time', text: 'TBD', textAlto: 'TBD', enumType: '', incidents: {}, kpis: {} },
  { id: 413, value: 'initialState.ccmAp.radio_configs.radio6g.radio.tax_power', text: defineMessage({ defaultMessage: 'TX Power Adjustment (6 GHz)' }), textAlto: 'TBD', enumType: 'com.ruckuswireless.scg.protobuf.ccm.Zone.CcmRadio.TaxPower', incidents: {}, kpis: {} },
  { id: 414, value: 'initialState.ccmAp.radio_configs.radio6g.radio.weak_bypass', text: 'TBD', textAlto: 'TBD', enumType: '', incidents: {}, kpis: {} },
  { id: 415, value: 'initialState.ccmAp.radio_configs.radio6g.radio.wlan_service_enabled', text: defineMessage({ defaultMessage: 'Wlan Service (6 GHz)' }), textAlto: 'TBD', enumType: '', incidents: {}, kpis: {} },
  { id: 416, value: 'initialState.ccmAp.snmp.ap_snmp_agent_profile_id', text: 'TBD', textAlto: 'TBD', enumType: '', incidents: {}, kpis: {} },
  { id: 417, value: 'initialState.ccmAp.snmp.config_type', text: 'TBD', textAlto: 'TBD', enumType: 'com.ruckuswireless.scg.protobuf.ccm.Zone.CcmSnmp.SnmpConfigType', incidents: {}, kpis: {} },
  { id: 418, value: 'initialState.ccmAp.snmp.custom_ap_snmp_agent.description', text: 'TBD', textAlto: 'TBD', enumType: '', incidents: {}, kpis: {} },
  { id: 419, value: 'initialState.ccmAp.snmp.custom_ap_snmp_agent.id', text: 'TBD', textAlto: 'TBD', enumType: '', incidents: {}, kpis: {} },
  { id: 420, value: 'initialState.ccmAp.snmp.custom_ap_snmp_agent.name', text: 'TBD', textAlto: 'TBD', enumType: '', incidents: {}, kpis: {} },
  { id: 421, value: 'initialState.ccmAp.snmp.custom_ap_snmp_agent.snmp_v2_agent.is_allowed_to_notify', text: 'TBD', textAlto: 'TBD', enumType: '', incidents: {}, kpis: {} },
  { id: 422, value: 'initialState.ccmAp.snmp.custom_ap_snmp_agent.snmp_v2_agent.is_allowed_to_read', text: 'TBD', textAlto: 'TBD', enumType: '', incidents: {}, kpis: {} },
  { id: 423, value: 'initialState.ccmAp.snmp.custom_ap_snmp_agent.snmp_v2_agent.is_allowed_to_write', text: 'TBD', textAlto: 'TBD', enumType: '', incidents: {}, kpis: {} },
  { id: 424, value: 'initialState.ccmAp.snmp.custom_ap_snmp_agent.snmp_v2_agent.name', text: 'TBD', textAlto: 'TBD', enumType: '', incidents: {}, kpis: {} },
  { id: 425, value: 'initialState.ccmAp.snmp.custom_ap_snmp_agent.snmp_v2_agent.notification_target.ip', text: 'TBD', textAlto: 'TBD', enumType: '', incidents: {}, kpis: {} },
  { id: 426, value: 'initialState.ccmAp.snmp.custom_ap_snmp_agent.snmp_v2_agent.notification_target.notification_type', text: 'TBD', textAlto: 'TBD', enumType: 'com.ruckuswireless.scg.protobuf.ccm.Domain.CcmDomain.Type', incidents: {}, kpis: {} },
  { id: 427, value: 'initialState.ccmAp.snmp.custom_ap_snmp_agent.snmp_v2_agent.notification_target.port', text: 'TBD', textAlto: 'TBD', enumType: '', incidents: {}, kpis: {} },
  { id: 428, value: 'initialState.ccmAp.snmp.custom_ap_snmp_agent.snmp_v3_agent.authentication_passphrase', text: 'TBD', textAlto: 'TBD', enumType: '', incidents: {}, kpis: {} },
  { id: 429, value: 'initialState.ccmAp.snmp.custom_ap_snmp_agent.snmp_v3_agent.authentication_type', text: 'TBD', textAlto: 'TBD', enumType: 'com.ruckuswireless.scg.protobuf.ccm.Zone.CcmSnmp.CcmUser.AuthenticationType', incidents: {}, kpis: {} },
  { id: 430, value: 'initialState.ccmAp.snmp.custom_ap_snmp_agent.snmp_v3_agent.is_allowed_to_notify', text: 'TBD', textAlto: 'TBD', enumType: '', incidents: {}, kpis: {} },
  { id: 431, value: 'initialState.ccmAp.snmp.custom_ap_snmp_agent.snmp_v3_agent.is_allowed_to_read', text: 'TBD', textAlto: 'TBD', enumType: '', incidents: {}, kpis: {} },
  { id: 432, value: 'initialState.ccmAp.snmp.custom_ap_snmp_agent.snmp_v3_agent.is_allowed_to_write', text: 'TBD', textAlto: 'TBD', enumType: '', incidents: {}, kpis: {} },
  { id: 433, value: 'initialState.ccmAp.snmp.custom_ap_snmp_agent.snmp_v3_agent.name', text: 'TBD', textAlto: 'TBD', enumType: '', incidents: {}, kpis: {} },
  { id: 434, value: 'initialState.ccmAp.snmp.custom_ap_snmp_agent.snmp_v3_agent.notification_target.ip', text: 'TBD', textAlto: 'TBD', enumType: '', incidents: {}, kpis: {} },
  { id: 435, value: 'initialState.ccmAp.snmp.custom_ap_snmp_agent.snmp_v3_agent.notification_target.notification_type', text: 'TBD', textAlto: 'TBD', enumType: 'com.ruckuswireless.scg.protobuf.ccm.Domain.CcmDomain.Type', incidents: {}, kpis: {} },
  { id: 436, value: 'initialState.ccmAp.snmp.custom_ap_snmp_agent.snmp_v3_agent.notification_target.port', text: 'TBD', textAlto: 'TBD', enumType: '', incidents: {}, kpis: {} },
  { id: 437, value: 'initialState.ccmAp.snmp.custom_ap_snmp_agent.snmp_v3_agent.privacy_passphrase', text: 'TBD', textAlto: 'TBD', enumType: '', incidents: {}, kpis: {} },
  { id: 438, value: 'initialState.ccmAp.snmp.custom_ap_snmp_agent.snmp_v3_agent.privacy_type', text: 'TBD', textAlto: 'TBD', enumType: 'com.ruckuswireless.scg.protobuf.ccm.Zone.CcmSnmp.CcmUser.PrivacyType', incidents: {}, kpis: {} },
  { id: 439, value: 'initialState.ccmAp.syslog.ap_syslog_server_profile_id', text: defineMessage({ defaultMessage: 'ap syslog server profile id' }), textAlto: 'TBD', enumType: '', incidents: {}, kpis: {} },
  { id: 440, value: 'initialState.ccmAp.syslog.config_type', text: 'TBD', textAlto: 'TBD', enumType: 'com.ruckuswireless.scg.protobuf.ccm.Zone.CcmSyslog.SyslogConfigType', incidents: {}, kpis: {} },
  { id: 441, value: 'initialState.ccmAp.syslog.custom_ap_syslog_server.description', text: 'TBD', textAlto: 'TBD', enumType: '', incidents: {}, kpis: {} },
  { id: 442, value: 'initialState.ccmAp.syslog.custom_ap_syslog_server.event_facility', text: 'TBD', textAlto: 'TBD', enumType: 'com.ruckuswireless.scg.protobuf.ccm.Zone.CcmSyslog.EventFacility', incidents: {}, kpis: {} },
  { id: 443, value: 'initialState.ccmAp.syslog.custom_ap_syslog_server.flow_level', text: 'TBD', textAlto: 'TBD', enumType: 'com.ruckuswireless.scg.protobuf.ccm.Zone.CcmSyslog.FlowLevel', incidents: {}, kpis: {} },
  { id: 444, value: 'initialState.ccmAp.syslog.custom_ap_syslog_server.id', text: 'TBD', textAlto: 'TBD', enumType: '', incidents: {}, kpis: {} },
  { id: 445, value: 'initialState.ccmAp.syslog.custom_ap_syslog_server.name', text: 'TBD', textAlto: 'TBD', enumType: '', incidents: {}, kpis: {} },
  { id: 446, value: 'initialState.ccmAp.syslog.custom_ap_syslog_server.primary_port', text: 'TBD', textAlto: 'TBD', enumType: '', incidents: {}, kpis: {} },
  { id: 447, value: 'initialState.ccmAp.syslog.custom_ap_syslog_server.primary_protocol', text: 'TBD', textAlto: 'TBD', enumType: 'com.ruckuswireless.scg.protobuf.ccm.Zone.CcmSyslog.Protocol', incidents: {}, kpis: {} },
  { id: 448, value: 'initialState.ccmAp.syslog.custom_ap_syslog_server.primary_server_ip', text: 'TBD', textAlto: 'TBD', enumType: '', incidents: {}, kpis: {} },
  { id: 449, value: 'initialState.ccmAp.syslog.custom_ap_syslog_server.priority', text: 'TBD', textAlto: 'TBD', enumType: 'com.ruckuswireless.scg.protobuf.ccm.Zone.CcmSyslog.Priority', incidents: {}, kpis: {} },
  { id: 450, value: 'initialState.ccmAp.syslog.custom_ap_syslog_server.redundancy_mode', text: 'TBD', textAlto: 'TBD', enumType: 'com.ruckuswireless.scg.protobuf.ccm.Zone.CcmSyslog.Redundancy', incidents: {}, kpis: {} },
  { id: 451, value: 'initialState.ccmAp.syslog.custom_ap_syslog_server.secondary_port', text: 'TBD', textAlto: 'TBD', enumType: '', incidents: {}, kpis: {} },
  { id: 452, value: 'initialState.ccmAp.syslog.custom_ap_syslog_server.secondary_protocol', text: 'TBD', textAlto: 'TBD', enumType: 'com.ruckuswireless.scg.protobuf.ccm.Zone.CcmSyslog.Protocol', incidents: {}, kpis: {} },
  { id: 453, value: 'initialState.ccmAp.syslog.custom_ap_syslog_server.secondary_server_ip', text: 'TBD', textAlto: 'TBD', enumType: '', incidents: {}, kpis: {} }
]
